### ISSUE TITLE
use TSN to train HMDB51, then errors happen

### ISSUE THREAD

**Issue by zjykzj** [open-mmlab/mmaction2#101]
hi mmaction2, First of all, thank you for your contribution. i want to train hmdb51 dataset using TSN, following tutorials, i do something as:

1. data processing: following `preparing_hmdb51.md`

```
$ cd mmaction2/tools/data/hmdb51

# process data and annotation
$ bash download_annotations.sh
$ bash download_videos.sh

# extract data
$ bash extract_rgb_frames.sh

# generate label
$ bash  generate_rawframes_filelist.sh
$ bash generate_videos_filelist.sh
```

when doing this, the log shows some .avi doesn't work

```
...
...
rgb 6568 talk/The_Matrix_3_talk_h_nm_np1_fr_goo_13.avi None done       <------------- here
"../../data/hmdb51/videos/talk/Hamlet_(1996)_Fencing_Scenes_talk_u_cm_np1_fr_med_0.avi", frames ≈ 96
extracted frames of video "../../data/hmdb51/videos/talk/Hamlet_(1996)_Fencing_Scenes_talk_u_cm_np1_fr_med_0.avi", 95 frames
1 videos (95 frames, 0 tvl1 flows) processed, using 0.276s, decoding speed 344.203fps, flow speed 0fps
rgb 6569 talk/Hamlet_(1996)_Fencing_Scenes_talk_u_cm_np1_fr_med_0.avi None done              <-------------------here
"../../data/hmdb51/videos/talk/Fellowship_6_talk_h_cm_np1_fr_goo_14.avi", frames ≈ 59
extracted frames of video "../../data/hmdb51/videos/talk/Fellowship_6_talk_h_cm_np1_fr_goo_14.avi", 58 frames
1 videos (58 frames, 0 tvl1 flows) processed, using 0.327s, decoding speed 177.37fps, flow speed 0fps
rgb 6570 talk/Fellowship_6_talk_h_cm_np1_fr_goo_14.avi None done
"../../data/hmdb51/videos/talk/Fellowship_6_talk_h_cm_np1_fr_goo_13.avi", frames ≈ 73
extracted frames of video "../../data/hmdb51/videos/talk/Fellowship_6_talk_h_cm_np1_fr_goo_13.avi", 72 frames
1 videos (72 frames, 0 tvl1 flows) processed, using 0.502s, decoding speed 143.426fps, flow speed 0fps
rgb 6571 talk/Fellowship_6_talk_h_cm_np1_fr_goo_13.avi None done
Genearte raw frames (RGB only)
```

2. prepare config

i copy `mmaction2/configs/recognition/tsn/tsn_r50_1x1x3_80e_ucf101_rgb.py` to `tsn_hmdb51_config.py` and modified some place

```
# model settings
model = dict(
    type='Recognizer2D',
    backbone=dict(
        type='ResNet',
        pretrained='torchvision://resnet50',
        depth=50,
        norm_eval=False),
    cls_head=dict(
        type='TSNHead',
        # num_classes=101,
        # 修改类别
        num_classes=51,                 <--------------- here
        in_channels=2048,
        spatial_type='avg',
        consensus=dict(type='AvgConsensus', dim=1),
        dropout_ratio=0.8,
        init_std=0.001))
# model training and testing settings
train_cfg = None
test_cfg = dict(average_clips=None)
# dataset settings
dataset_type = 'RawframeDataset'
data_root = 'data/hmdb51/rawframes/'                                    <--- here
data_root_val = 'data/hmdb51/rawframes/'
ann_file_train = 'data/hmdb51/hmdb51_train_split_{1,2,3}_rawframes.txt'
ann_file_val = 'data/hmdb51/hmdb51_val_split_{1,2,3}_rawframes.txt'
ann_file_test = 'data/hmdb51/hmdb51_val_split_{1,2,3}_rawframes.txt'       <----- here
img_norm_cfg = dict(mean=[104, 117, 128], std=[1, 1, 1], to_bgr=False)
train_pipeline = [
    dict(type='SampleFrames', clip_len=1, frame_interval=1, num_clips=3),
    dict(type='FrameSelector'),
    dict(type='Resize', scale=(-1, 256)),
    dict(
        type='MultiScaleCrop',
        input_size=224,
        scales=(1, 0.875, 0.75, 0.66),
        random_crop=False,
        max_wh_scale_gap=1),
    dict(type='Resize', scale=(224, 224), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]
val_pipeline = [
    dict(
        type='SampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=3,
        test_mode=True),
    dict(type='FrameSelector'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='Flip', flip_ratio=0),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
test_pipeline = [
    dict(
        type='SampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=25,
        test_mode=True),
    dict(type='FrameSelector'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='TenCrop', crop_size=224),
    dict(type='Flip', flip_ratio=0),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
data = dict(
    videos_per_gpu=32,
    workers_per_gpu=4,
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix=data_root,
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix=data_root_val,
        pipeline=val_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=ann_file_test,
        data_prefix=data_root_val,
        pipeline=test_pipeline))
# optimizer
optimizer = dict(
    type='SGD', lr=0.001, momentum=0.9,
    weight_decay=0.0005)  # this lr is used for 8 gpus
optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))
# learning policy
lr_config = dict(policy='step', step=[30, 60])
total_epochs = 80
checkpoint_config = dict(interval=5)
evaluation = dict(
    interval=5, metrics=['top_k_accuracy', 'mean_class_accuracy'], topk=(1, 5))
log_config = dict(
    interval=20,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook'),
    ])
# runtime settings
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/tsn_r50_1x1x3_80e_hmdb51_rgb/'
# 使用预训练模型
load_from = './checkpoints/tsn_r50_1x1x3_80e_ucf101_rgb_20200613-d6ad9c48.pth'           <- here
# load_from = None
resume_from = None
workflow = [('train', 1)]
```

3. begin train. using following statement

```
$ CUDA_VISIBLE_DEVICES=3 python tools/train.py configs/recognition/tsn/tsn_hmdb51_config.py 
2020-08-11 15:19:47,841 - mmaction - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.7 (default, Mar 26 2020, 15:48:22) [GCC 7.3.0]
CUDA available: True
...
...
...
# load_from = None
resume_from = None
workflow = [('train', 1)]

2020-08-11 15:19:49,517 - mmaction - INFO - These parameters in pretrained checkpoint are not loaded: {'fc.weight', 'fc.bias'}
Traceback (most recent call last):
  File "tools/train.py", line 146, in <module>
    main()
  File "tools/train.py", line 125, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/zj/zhonglian/mmaction2/mmaction/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/zj/zhonglian/mmcv/mmcv/utils/registry.py", line 167, in build_from_cfg
    return obj_cls(**args)
  File "/home/zj/zhonglian/mmaction2/mmaction/datasets/rawframe_dataset.py", line 92, in __init__
    multi_class, num_classes, modality)
  File "/home/zj/zhonglian/mmaction2/mmaction/datasets/base.py", line 57, in __init__
    self.video_infos = self.load_annotations()
  File "/home/zj/zhonglian/mmaction2/mmaction/datasets/rawframe_dataset.py", line 97, in load_annotations
    with open(self.ann_file, 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'data/hmdb51/hmdb51_train_split_{1,2,3}_rawframes.txt'
```

ok, i modified the path to `ann_file_train = 'data/hmdb51/hmdb51_train_split_1_rawframes.txt'`, then another error happens

```
...
...
2020-08-11 15:36:29,645 - mmaction - INFO - These parameters in pretrained checkpoint are not loaded: {'fc.bias', 'fc.weight'}
2020-08-11 15:36:41,862 - mmaction - INFO - load checkpoint from ./checkpoints/tsn_r50_1x1x3_80e_ucf101_rgb_20200613-d6ad9c48.pth
2020-08-11 15:36:44,408 - mmaction - WARNING - The model and loaded state dict do not match exactly

size mismatch for cls_head.fc_cls.weight: copying a param with shape torch.Size([101, 2048]) from checkpoint, the shape in current model is torch.Size([51, 2048]).
size mismatch for cls_head.fc_cls.bias: copying a param with shape torch.Size([101]) from checkpoint, the shape in current model is torch.Size([51]).
2020-08-11 15:36:44,409 - mmaction - INFO - Start running, host: zj@user-SYS-7049GP-TRT, work_dir: /home/zj/zhonglian/mmaction2/work_dirs/tsn_r50_1x1x3_80e_hmdb51_rgb
2020-08-11 15:36:44,409 - mmaction - INFO - workflow: [('train', 1)], max: 80 epochs
Traceback (most recent call last):
  File "tools/train.py", line 146, in <module>
    main()
  File "tools/train.py", line 142, in main
    meta=meta)
  File "/home/zj/zhonglian/mmaction2/mmaction/apis/train.py", line 111, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/zj/zhonglian/mmcv/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zj/zhonglian/mmcv/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/zj/anaconda3/envs/zhonglian/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/zj/anaconda3/envs/zhonglian/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/home/zj/anaconda3/envs/zhonglian/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/zj/anaconda3/envs/zhonglian/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/zj/anaconda3/envs/zhonglian/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zj/anaconda3/envs/zhonglian/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zj/anaconda3/envs/zhonglian/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zj/zhonglian/mmaction2/mmaction/datasets/base.py", line 103, in __getitem__
    return self.prepare_train_frames(idx)
  File "/home/zj/zhonglian/mmaction2/mmaction/datasets/rawframe_dataset.py", line 137, in prepare_train_frames
    return self.pipeline(results)
  File "/home/zj/zhonglian/mmaction2/mmaction/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/zj/zhonglian/mmaction2/mmaction/datasets/pipelines/loading.py", line 848, in __call__
    img_bytes = self.file_client.get(filepath)
  File "/home/zj/zhonglian/mmcv/mmcv/fileio/file_client.py", line 294, in get
    return self.client.get(filepath)
  File "/home/zj/zhonglian/mmcv/mmcv/fileio/file_client.py", line 185, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/zj/zhonglian/mmaction2/data/hmdb51/rawframes/shake_hands/Concourse_d_elegance_Sofia_2009___PRICE_GIVING_CEREMONY_shake_hands_f_cm_np2_le_med_0/img_00066.jpg'
```

i check the img dir

```
$ ls
img_00000.jpg  img_00006.jpg  img_00012.jpg  img_00018.jpg  img_00024.jpg  img_00030.jpg  img_00036.jpg  img_00042.jpg  img_00048.jpg  img_00054.jpg  img_00060.jpg
img_00001.jpg  img_00007.jpg  img_00013.jpg  img_00019.jpg  img_00025.jpg  img_00031.jpg  img_00037.jpg  img_00043.jpg  img_00049.jpg  img_00055.jpg  img_00061.jpg
img_00002.jpg  img_00008.jpg  img_00014.jpg  img_00020.jpg  img_00026.jpg  img_00032.jpg  img_00038.jpg  img_00044.jpg  img_00050.jpg  img_00056.jpg  img_00062.jpg
img_00003.jpg  img_00009.jpg  img_00015.jpg  img_00021.jpg  img_00027.jpg  img_00033.jpg  img_00039.jpg  img_00045.jpg  img_00051.jpg  img_00057.jpg  img_00063.jpg
img_00004.jpg  img_00010.jpg  img_00016.jpg  img_00022.jpg  img_00028.jpg  img_00034.jpg  img_00040.jpg  img_00046.jpg  img_00052.jpg  img_00058.jpg  img_00064.jpg
img_00005.jpg  img_00011.jpg  img_00017.jpg  img_00023.jpg  img_00029.jpg  img_00035.jpg  img_00041.jpg  img_00047.jpg  img_00053.jpg  img_00059.jpg  img_00065.jpg
```

there is no img_00066.jpg happens, why this will happen and how to solve it ? Looking forward to your help

**Comment by innerlee** [comment]
need to set `start_index=0`

**Comment by zjykzj** [comment]
> need to set `start_index=0`

thank you for your reply. i pull the newest code, in `base.py` it appears `start_index`

```
    def __init__(self,
                 ann_file,
                 pipeline,
                 data_prefix=None,
                 test_mode=False,
                 multi_class=False,
                 num_classes=None,
                 start_index=1,
                 modality='RGB'):
```

i modified the config file as 

```
data = dict(
    videos_per_gpu=32,
    workers_per_gpu=4,
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix=data_root,
        pipeline=train_pipeline,
        start_index=0),                          <--- here
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix=data_root_val,
        pipeline=val_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=ann_file_test,
        data_prefix=data_root_val,
        pipeline=test_pipeline))
```

it works 

```
2020-08-11 16:02:47,581 - mmaction - INFO - Start running, host: zj@user-SYS-7049GP-TRT, work_dir: /home/zj/zhonglian/mmaction2/work_dirs/tsn_r50_1x1x3_80e_hmdb51_rgb
2020-08-11 16:02:47,581 - mmaction - INFO - workflow: [('train', 1)], max: 80 epochs
2020-08-11 16:03:12,362 - mmaction - INFO - Epoch [1][20/112]	lr: 1.000e-03, eta: 3:04:24, time: 1.238, data_time: 0.790, memory: 8235, top1_acc: 0.0500, top5_acc: 0.1422, loss_cls: 3.8857, loss: 3.8857, grad_norm: 11.2011
2020-08-11 16:03:33,752 - mmaction - INFO - Epoch [1][40/112]	lr: 1.000e-03, eta: 2:51:34, time: 1.071, data_time: 0.672, memory: 8235, top1_acc: 0.1000, top5_acc: 0.3078, loss_cls: 3.7143, loss: 3.7143, grad_norm: 11.2360
2020-08-11 16:03:55,510 - mmaction - INFO - Epoch [1][60/112]	lr: 1.000e-03, eta: 2:47:55, time: 1.088, data_time: 0.690, memory: 8235, top1_acc: 0.1453, top5_acc: 0.4484, loss_cls: 3.4622, loss: 3.4622, grad_norm: 11.1968
```

**Comment by dreamerlin** [comment]
`rgb 6569 talk/Hamlet_(1996)_Fencing_Scenes_talk_u_cm_np1_fr_med_0.avi None done`. It is correct.
