### ISSUE TITLE
TypeError: Object of type ndarray is not JSON serializable

### ISSUE THREAD

**Issue by zjykzj** [open-mmlab/mmaction2#108]
hi mmation2 , i trained a model for ucf101 using config file `configs/recognition/tsn/tsn_r50_1x1x3_80e_ucf101_rgb.py`

now i want to test the power of it, using following code:

```
$ CUDA_VISIBLE_DEVICES=1 python tools/test.py configs/recognition/tsn/tsn_r50_1x1x3_80e_ucf101_rgb.py work_dirs/tsn_r50_1x1x3_80e_ucf101_rgb/latest.pth --eval top_k_accuracy mean_class_accuracy     --out result.json
```

it works fine, but when save result into json file, error happes

```
$ CUDA_VISIBLE_DEVICES=1 python tools/test.py configs/recognition/tsn/tsn_r50_1x1x3_80e_ucf101_rgb.py work_dirs/tsn_r50_1x1x3_80e_ucf101_rgb/latest.pth --eval top_k_accuracy mean_class_accuracy     --out result.json
2020-08-12 14:40:58,082 - mmaction - INFO - These parameters in pretrained checkpoint are not loaded: {'fc.bias', 'fc.weight'}
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 4/4, 1.6 task/s, elapsed: 3s, ETA:     0s
writing results to result.json
Traceback (most recent call last):
  File "tools/test.py", line 139, in <module>
    main()
  File "tools/test.py", line 131, in main
    dataset.dump_results(outputs, **output_config)
  File "/home/zj/zhonglian/mmaction2/mmaction/datasets/base.py", line 86, in dump_results
    return mmcv.dump(results, out)
  File "/home/zj/zhonglian/mmcv/mmcv/fileio/io.py", line 80, in dump
    handler.dump_to_path(obj, file, **kwargs)
  File "/home/zj/zhonglian/mmcv/mmcv/fileio/handlers/base.py", line 25, in dump_to_path
    self.dump_to_fileobj(obj, f, **kwargs)
  File "/home/zj/zhonglian/mmcv/mmcv/fileio/handlers/json_handler.py", line 13, in dump_to_fileobj
    json.dump(obj, file, **kwargs)
  File "/home/zj/anaconda3/envs/zhonglian/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/zj/anaconda3/envs/zhonglian/lib/python3.7/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/home/zj/anaconda3/envs/zhonglian/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home/zj/anaconda3/envs/zhonglian/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/zj/anaconda3/envs/zhonglian/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
```

in `tools/test.py`, the correlative code is 

```
    if rank == 0:
        if output_config:
            out = output_config['out']
            print(f'\nwriting results to {out}')
            dataset.dump_results(outputs, **output_config)
```

i printed the `output_config` and `out`, the info is:

```
{'out': 'result.json'}

[array([ 1.9529229 ,  2.923142  ,  0.26469332, -0.12839134, -2.1167572 ,
       -0.7340729 , -1.3261667 ,  0.4541236 ,  0.94828093,  1.155941  ,
        0.23628543, -0.78831387,  2.2801087 ,  1.0793906 ,  0.31419927,
        0.30997226,  0.5425246 , -0.70942116, -1.1134925 ,  2.236816  ,
        3.9390984 , -2.1505275 , -1.085769  , -2.8008654 , -1.3788043 ,
       -0.35550973,  0.6128084 ,  0.97523236, -1.4105709 , -1.2038826 ,
       -2.1797624 , -1.4052689 , -0.67973197,  1.7024329 , -0.7162529 ,
       -1.2531643 , -1.405829  , -1.7755532 , -0.9127121 , -0.52495575,
        0.5702051 , -0.54499656,  0.9248879 , -1.0198474 ,  1.8331637 ,
       -0.5963148 , -1.2978854 ,  1.1907437 , -1.4260625 ,  0.20374985,
        1.7188393 ,  0.9811421 , -1.6228783 ,  0.58338284, -0.7557665 ,
       -1.0928499 , -0.7617161 , -0.65688896,  4.0263968 , -0.09345046,
        0.07987386,  0.73330057, 13.416785  , -0.31503808,  3.6180706 ,
        1.4577851 ,  1.4350643 ,  0.21168658, -0.19559935, -1.103691  ,
        0.7532946 ,  1.5955294 , -1.1590674 , -1.2700799 , -0.32934734,
       -0.52962774, -0.747167  ,  0.18337195, -0.2666077 ,  0.717041  ,
       -0.6293016 , -0.6326269 , -0.17059498, -2.4983056 ,  0.0488462 ,
       -1.161425  ,  0.13799725, -1.8053738 , -1.6930958 ,  1.2327036 ,
       -1.2348598 , -0.18195666,  1.3208578 , -3.0858784 ,  1.1431783 ,
       -0.9411551 , -0.7087368 , -1.15071   , -3.0066304 , -1.8325434 ,
        2.1851883 ], dtype=float32), array([-3.1554081 , -1.8086557 , -1.2189873 , -1.3863541 , -3.4624038 ,
       -3.7378008 ,  7.6724052 ,  5.97018   , -4.2795534 , -2.5561104 ,
        2.2037597 ,  1.2032832 , -5.6521015 , -3.200562  ,  0.06564808,
       -3.1106699 , -0.22693926, -4.557994  , -0.9784015 , -2.8301358 ,
       -0.26256648, -1.9581242 , -0.75423837,  3.251859  , -3.7698638 ,
        2.8235092 , -2.9476943 ,  0.75258267, 10.651768  ,  1.6277269 ,
       -0.08898169, -1.1676219 ,  4.3143296 , -4.4079895 , -4.0753226 ,
        2.1783433 , -4.154809  , -1.7371117 , -2.4756253 ,  6.97458   ,
       -1.4465613 ,  3.5330255 , -1.9635652 , -1.0765982 ,  3.4709496 ,
       -0.44178772, -0.5041221 ,  2.493868  , -0.25774002, -2.910048  ,
        1.3306173 ,  3.3166916 , -1.9219271 , -1.5394036 , -1.2261659 ,
       -1.2541034 , -0.9439164 , -0.20131937, -2.7909422 , -1.7844346 ,
       -0.31215718, -2.2882266 , -1.4200875 , -2.3059387 , -1.2107593 ,
       -2.174218  , -3.193241  ,  2.251296  , -2.9217339 ,  2.1830683 ,
        0.09082523,  0.70335275, -3.5495253 , -5.4326572 , -2.9788358 ,
        0.7502857 , -2.0108578 , -3.704027  ,  2.679557  , -0.8924122 ,
        0.39617965,  2.2738085 , -3.2832923 ,  7.1167126 ,  3.3312867 ,
       -0.20836425, -3.8255863 , -0.7380201 ,  2.5008836 ,  5.836446  ,
        3.9049966 , 16.540073  ,  9.489449  ,  6.8317823 , -2.6105278 ,
        0.0635196 , -0.18466364,  2.4365137 , -0.29589617, -0.49789888,
        2.5412517 ], dtype=float32), array([-3.40932107e+00, -1.06936395e-02, -1.73499656e+00, -1.59915805e+00,
        5.71720302e-02, -1.26235354e+00,  1.75313354e+00,  1.82909936e-01,
       -2.73504066e+00, -8.32203209e-01,  1.33741820e+00,  1.22894943e+00,
       -3.33747673e+00, -2.82331657e+00, -6.27151072e-01, -5.35833001e-01,
        7.28152394e-02, -3.50825024e+00,  2.36635065e+00,  1.20436706e-01,
        1.99636745e+00,  1.94954121e+00,  1.54881507e-01,  3.04111511e-01,
       -2.20299864e+00,  4.68201256e+00, -3.32769918e+00,  1.58799827e+00,
        2.00522804e+00,  4.28090960e-01,  1.21267533e+00, -3.45705330e-01,
        2.38831758e+00, -2.96614265e+00, -1.35263073e+00,  1.28939712e+00,
       -1.74022067e+00, -1.94155240e+00, -3.36226821e+00,  7.63379526e+00,
        4.00016403e+00,  4.05345821e+00, -4.05784190e-01,  1.22065210e+00,
        3.96605849e-01, -3.39757466e+00,  1.67164028e+00,  6.65977716e-01,
        3.89114916e-01, -1.13685560e+00,  1.78429723e+00,  1.66959250e+00,
        8.51574957e-01, -1.33695388e+00, -3.62328577e+00, -2.20936608e+00,
       -4.98263955e-01, -1.52075148e+00, -1.68073058e+00, -3.47000551e+00,
       -4.68902290e-03,  9.44112360e-01, -2.32742310e+00, -7.69852519e-01,
       -2.74959385e-01, -1.03926265e+00, -1.83813047e+00,  3.34748793e+00,
       -3.22042465e-01, -4.92838115e-01,  2.63888419e-01,  3.05683446e+00,
        1.63758367e-01, -4.02872753e+00, -2.33594084e+00,  1.09016666e+01,
       -2.16153765e+00, -2.93059349e+00,  3.17019510e+00,  1.59995222e+00,
       -7.56023049e-01,  7.05853367e+00, -1.75534749e+00, -9.27645862e-02,
       -7.87818313e-01, -1.31494510e+00, -5.49836457e-02,  7.27982521e-01,
       -9.21023250e-01,  2.67443925e-01,  1.25793505e+00,  1.52883315e+00,
        2.56475949e+00,  9.29922283e-01, -1.78127527e+00, -6.23938262e-01,
       -6.67548358e-01,  1.15025485e+00, -2.27030230e+00,  2.42970988e-01,
       -1.11846581e-01], dtype=float32), array([ 9.7881667e-02,  6.3227153e-01, -1.8561482e+00, -2.1571205e+00,
        1.4059830e+01,  4.8399657e-01, -1.8275721e+00, -2.1536226e+00,
        2.0527697e+00, -2.3162837e+00, -3.0728564e+00,  4.5147705e-01,
       -2.2566085e+00,  9.0172809e-01,  9.2773736e-01,  3.4005036e+00,
       -2.4779036e+00, -1.9556541e+00, -4.0643939e-01, -1.2113328e+00,
        1.0615828e+00,  1.8980796e+00,  8.0910289e-01, -3.4260190e+00,
        1.6985834e-02,  1.8681365e+00, -1.6745995e+00,  3.1297741e+00,
        4.9533206e-01,  7.7088308e+00, -9.4858694e-01,  1.6952250e+00,
       -3.3255212e+00, -9.6397811e-01,  2.0618695e-01,  3.0011529e-01,
        1.3867394e+00,  2.7509351e+00, -1.8679692e+00,  1.8175439e+00,
       -1.7074220e+00, -3.3053722e+00,  4.2096773e-01,  3.0590990e+00,
       -3.0134280e+00, -4.1446114e+00,  1.4162828e+00, -1.3907127e+00,
       -2.8771629e+00,  9.5357203e-01,  1.0698979e+00, -3.5089359e+00,
       -4.6066377e-01, -2.0315270e+00, -2.4641752e+00, -1.7112375e+00,
        7.7639780e+00, -7.3515660e-01, -1.6210897e+00, -1.6490629e+00,
       -1.4550496e+00,  8.2967222e-01, -2.4997182e+00, -3.0694556e-01,
        7.3129952e-01, -7.7849364e-01, -8.0653977e-01, -2.7814975e-01,
        6.9563894e+00, -2.2368103e-02,  1.2655897e+00,  1.0192424e-02,
        1.6345310e+00, -2.7512756e-01, -1.4516522e+00, -1.3889271e-01,
       -7.7020127e-01, -1.5020751e+00,  1.9333646e+00, -4.9428000e+00,
       -1.9338553e+00, -2.5300448e+00,  4.6418971e-01, -5.1236825e+00,
        2.4116956e-01,  7.5193768e+00,  5.8947573e+00, -5.9647286e-01,
       -3.0245688e+00,  1.1701695e+00, -2.1766311e-01, -2.4784267e+00,
       -2.7892220e+00,  1.5604091e-01,  2.2785933e+00,  7.8045473e+00,
       -1.1207641e+00, -2.6828754e+00,  1.1542189e+00,  3.2799768e-01,
       -9.7450703e-01], dtype=float32)]
```

I hope you can help me solve this problem

**Comment by dreamerlin** [comment]
You should dump to a pickle file according to [this](https://github.com/open-mmlab/mmaction2/blob/master/tools/test.py#L20)

**Comment by zjykzj** [comment]
> You should dump to a pickle file according to [this](https://github.com/open-mmlab/mmaction2/blob/master/tools/test.py#L20)

thank you @dreamerlin . it works 

```
CUDA_VISIBLE_DEVICES=1 python tools/test.py configs/recognition/tsn/tsn_r50_1x1x3_80e_ucf101_rgb.py work_dirs/tsn_r50_1x1x3_80e_ucf101_rgb/latest.pth --eval top_k_accuracy mean_class_accuracy --out results.pkl
```

*Although I don't know the meaning of this array yet*

**Comment by dreamerlin** [comment]
> > You should dump to a pickle file according to [this](https://github.com/open-mmlab/mmaction2/blob/master/tools/test.py#L20)
> 
> thank you @dreamerlin . it works
> 
> ```
> CUDA_VISIBLE_DEVICES=1 python tools/test.py configs/recognition/tsn/tsn_r50_1x1x3_80e_ucf101_rgb.py work_dirs/tsn_r50_1x1x3_80e_ucf101_rgb/latest.pth --eval top_k_accuracy mean_class_accuracy --out results.pkl
> ```
> 
> _Although I don't know the meaning of this array yet_

The array is the score of each class. you can find that an array is of shape [101, ] same to your dataset UCF101 class. and 4 is the batch size

**Comment by dreamerlin** [comment]
@zjykzj The latest version of `mmcv` now will convert ``set``, ``range`` and ``np.ndarray`` data types to list to make it JSON serializable. [Details](https://github.com/open-mmlab/mmcv/pull/485/files).
