### ISSUE TITLE
Error with multi-class (VideoDataset) validation

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmaction2#1106]
I am having a problem with a multi-class VideoDataset. 

While evaluating the `top_k_accuracy` during training I get 0.0% accuracy due to the error which comes up while calculating `mean_class_accuracy`  (mmaction/core/evaluation/[accuracy.py](https://github.com/open-mmlab/mmaction2/blob/acce52d21a2545d9351b1060853c3bcd171b7158/mmaction/core/evaluation/accuracy.py#L33)). 

```
mmaction - INFO - Evaluating top_k_accuracy ...
/mmaction2/mmaction/core/evaluation/accuracy.py:141: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  labels = np.array(labels)[:, np.newaxis]

top1_acc        0.0000
top2_acc        0.0000
top3_acc        0.0000
top4_acc        0.0000
top5_acc        0.0000

mmaction - INFO - Evaluating mean_class_accuracy ...
/mmaction2/mmaction/core/evaluation/accuracy.py:35: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  y_real = np.array(y_real)
Traceback (most recent call last):
  File "/mmaction2/tools/train.py", line 200, in <module>
    main()
  File "/mmaction2/tools/train.py", line 188, in main
    train_model(
  File "/mmaction2/mmaction/apis/train.py", line 165, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 237, in after_train_epoch
    self._do_evaluate(runner)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 447, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 324, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "/mmaction2/mmaction/datasets/base.py", line 218, in evaluate
    mean_acc = mean_class_accuracy(results, gt_labels)
  File "/mmaction2/mmaction/core/evaluation/accuracy.py", line 82, in mean_class_accuracy
    cf_mat = confusion_matrix(pred, labels).astype(float)
  File "/mmaction2/mmaction/core/evaluation/accuracy.py", line 40, in confusion_matrix
    raise TypeError(
TypeError: y_real dtype must be np.int64, but got object
```

The values of  `y_real` are like so: [[3], [23], ... [33, 39, 41], [31, 26]]
And of `y_pred` like so:  [21 23 .... 36  9]

Any ideas? My config file is pretty standard.

**Comment by kennymckormick** [comment]
To use `mean_average_precision`, for each video, `y_pred` should be a vector (the length is `num_classes`), `y_real` should also be a vector of length `num_classes` (1 if belongs to that category, else 0)

**Comment by gaoyingjai** [comment]
I also encountered the same problem as you, how did you solve it?Thanks

**Comment by athos1981** [comment]
val_evaluator = dict(type='AccMetric',metric_list='mmit_mean_average_precision')  # Config of validation evaluator
test_evaluator = val_evaluator  # Config of testing evaluator
