### ISSUE TITLE
get_flops script doesn't work for 2D models

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmaction2#1132]
**Describe the bug**

The `get_flops.py` script doesn't seem to work for 2D models.

**Reproduction**

`python tools/analysis/get_flops.py configs/recognition/tsm/tsm_r50_video_1x1x8_50e_kinetics400_rgb.py `

**Error traceback**

```
Traceback (most recent call last):
  File "tools/analysis/get_flops.py", line 73, in <module>
    main()
  File "tools/analysis/get_flops.py", line 63, in main
    flops, params = get_model_complexity_info(model, input_shape)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/utils/flops_counter.py", line 104, in get_model_complexity_info
    _ = flops_model(batch)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mmaction2/mmaction/models/recognizers/recognizer2d.py", line 166, in forward_dummy
    x = self.extract_feat(imgs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/mmaction2/mmaction/models/recognizers/base.py", line 158, in extract_feat
    x = self.backbone(imgs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mmaction2/mmaction/models/backbones/resnet.py", line 546, in forward
    x = res_layer(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mmaction2/mmaction/models/backbones/resnet.py", line 215, in forward
    out = _inner_forward(x)
  File "/mmaction2/mmaction/models/backbones/resnet.py", line 201, in _inner_forward
    out = self.conv1(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 199, in forward
    x = self.conv(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mmaction2/mmaction/models/backbones/resnet_tsm.py", line 69, in forward
    x = self.shift(x, self.num_segments, shift_div=self.shift_div)
  File "/mmaction2/mmaction/models/backbones/resnet_tsm.py", line 89, in shift
    x = x.view(-1, num_segments, c, h * w)
RuntimeError: shape '[-1, 8, 64, 5440]' is invalid for input of size 348160
```

**Comment by kennymckormick** [comment]
You need to specify the input shape explicitly, for example:
```
python tools/analysis/get_flops.py configs/recognition/tsm/tsm_r50_video_1x1x8_50e_kinetics400_rgb.py --shape 8 3 256 256
```

**Comment by kennymckormick** [comment]
The current default value of `get_flops` is not reasonable. We may need some change (maybe read it from the config file?) @gengenkai

**Comment by gengenkai** [comment]
> The current default value of `get_flops` is not reasonable. We may need some change (maybe read it from the config file?) @gengenkai

Will fix it as soon as possible.
