### ISSUE TITLE
Error about the training and testing of the SSN using my own dataset

### ISSUE THREAD

**Issue by 1Awei** [open-mmlab/mmaction2#1146]
hello! when I using my own datasets to training the SSN model ,something wrong happened. My datasets has six classes, the proposal documents have been prepared in the required format.

Training error: [
 configs: 
 ssn=dict(
        assigner=dict(
            positive_iou_threshold=0.7,
            background_iou_threshold=0.01,
            incomplete_iou_threshold=0.3,
            background_coverage_threshold=0.02,
            incomplete_overlap_threshold=0.01),
        sampler=dict(
            num_per_video=8,
            positive_ratio=1,
            background_ratio=1,
            incomplete_ratio=6,
            add_gt_as_proposals=True),
        loss_weight=dict(comp_loss_weight=0.1, reg_loss_weight=0.1),
        debug=False))
test_cfg = dict(
    ssn=dict(
        sampler=dict(test_interval=6, batch_size=16),
        evaluater=dict(
            top_k=2000,
            nms=0.2,
            softmax_before_filter=True,
            cls_score_dict=None,
            cls_top_k=2)))
model meta=meta)
  File "/home/lab1210/mmaction2/mmaction/apis/train.py", line 162, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/lab1210/mmaction2/mmaction/models/localizers/base.py", line 121, in train_step
    losses = self.forward(**data_batch)
  File "/home/lab1210/mmaction2/mmaction/models/localizers/base.py", line 55, in forward
    return self.forward_train(imgs, **kwargs)
  File "/home/lab1210/mmaction2/mmaction/models/localizers/ssn.py", line 71, in forward_train
    (x, proposal_scale_factor))
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lab1210/mmaction2/mmaction/models/heads/ssn_head.py", line 390, in forward
    x, proposal_scale_factor)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lab1210/mmaction2/mmaction/models/heads/ssn_head.py", line 110, in forward
    scale_factors[:, 0], num_samples))
  File "/home/lab1210/mmaction2/mmaction/models/heads/ssn_head.py", line 78, in _extract_stage_feature
    part_feat * scale_factors.view(num_samples, 1))
RuntimeError: shape '[56, 1]' is invalid for input of size 8 = dict(
    type='SSN',
    backbone=dict(
        type='ResNet',
        pretrained='torchvision://resnet50',
        depth=50,
        norm_eval=False,
        partial_bn=True),
    spatial_type='avg',
    dropout_ratio=0.8,
    loss_cls=dict(type='SSNLoss'),
    cls_head=dict(
        type='SSNHead',
        dropout_ratio=0.0,
        in_channels=2048,
        num_classes=6,
        consensus=dict(
            type='STPPTrain',
            stpp_stage=(1, 1, 1),
            num_segments_list=(2, 5, 2)),
        use_regression=True),
    train_cfg=dict(
        ssn=dict(
            assigner=dict(
                positive_iou_threshold=0.7,
                background_iou_threshold=0.01,
                incomplete_iou_threshold=0.3,
                background_coverage_threshold=0.02,
                incomplete_overlap_threshold=0.01),
            sampler=dict(
                num_per_video=8,
                positive_ratio=1,
                background_ratio=1,
                incomplete_ratio=6,
                add_gt_as_proposals=True),
            loss_weight=dict(comp_loss_weight=0.1, reg_loss_weight=0.1),
            debug=False)))

error: 

2021-09-13 17:00:57,266 - mmaction - INFO - workflow: [('train', 1)], max: 30 epochs
2021-09-13 17:00:57,266 - mmaction - INFO - Freezing BatchNorm2D except the first one.
Traceback (most recent call last):
  File "tools/train.py", line 197, in <module>
    main()
  File "tools/train.py", line 193, in main
    meta=meta)
  File "/home/lab1210/mmaction2/mmaction/apis/train.py", line 162, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/lab1210/mmaction2/mmaction/models/localizers/base.py", line 121, in train_step
    losses = self.forward(**data_batch)
  File "/home/lab1210/mmaction2/mmaction/models/localizers/base.py", line 55, in forward
    return self.forward_train(imgs, **kwargs)
  File "/home/lab1210/mmaction2/mmaction/models/localizers/ssn.py", line 71, in forward_train
    (x, proposal_scale_factor))
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lab1210/mmaction2/mmaction/models/heads/ssn_head.py", line 390, in forward
    x, proposal_scale_factor)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lab1210/mmaction2/mmaction/models/heads/ssn_head.py", line 110, in forward
    scale_factors[:, 0], num_samples))
  File "/home/lab1210/mmaction2/mmaction/models/heads/ssn_head.py", line 78, in _extract_stage_feature
    part_feat * scale_factors.view(num_samples, 1))
RuntimeError: shape '[56, 1]' is invalid for input of size 8
  ]

Testing error:

[>>>>>>>>>>>>>>>>>>                                ] 25/68, 3.0 task/s, elapsed: 8s, ETA:    14sTraceback (most recent call last):
  File "tools/test.py", line 364, in <module>
    main()
  File "tools/test.py", line 349, in main
    outputs = inference_pytorch(args, cfg, distributed, data_loader)
  File "tools/test.py", line 160, in inference_pytorch
    outputs = single_gpu_test(model, data_loader)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/mmcv/engine/test.py", line 32, in single_gpu_test
    result = model(return_loss=False, **data)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lab1210/mmaction2/mmaction/models/localizers/base.py", line 57, in forward
    return self.forward_test(imgs, **kwargs)
  File "/home/lab1210/mmaction2/mmaction/models/localizers/ssn.py", line 111, in forward_test
    (output, proposal_tick_list, scale_factor_list), test_mode=True)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lab1210/mmaction2/mmaction/models/heads/ssn_head.py", line 408, in forward
    test_scores = self.test_fc(x)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/lab1210/miniconda3/envs/action2/lib/python3.7/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 dim 1 must match mat2 dim 0

**Comment by 1Awei** [comment]
ssn_utils.py line 78, num_frames also has some wrong.

**Comment by kennymckormick** [comment]
@tony2016uestc Would you please take a look at this problem?

**Comment by tony2016uestc** [comment]
If you want to train and test SSN on your own dataset, you have to check 'tag_val_normalized_proposal_list.txt' and regenerate them.

You cannot train with THUMOS14 proposals.

**Comment by 1Awei** [comment]
> If you want to train and test SSN on your own dataset, you have to check 'tag_val_normalized_proposal_list.txt' and regenerate them.
> 
> You cannot train with THUMOS14 proposals.

I used my own proposal file.

**Comment by tony2016uestc** [comment]
> > If you want to train and test SSN on your own dataset, you have to check 'tag_val_normalized_proposal_list.txt' and regenerate them.
> > You cannot train with THUMOS14 proposals.
> 
> I used my own proposal file.

You can check your proposal file and find out the problem.

**Comment by 1Awei** [comment]
> > > If you want to train and test SSN on your own dataset, you have to check 'tag_val_normalized_proposal_list.txt' and regenerate them.
> > > You cannot train with THUMOS14 proposals.
> > 
> > 
> > I used my own proposal file.
> 
> You can check your proposal file and config, and find out the problem.

# 131
042
3851
30
1
2 2124 3306
100
2 0.9180 0.9697 2188 3340
2 0.5285 0.6414 2419 3801
2 0.3538 0.3538 0 3340
2 0.5130 0.5130 1075 3379
0 0.0000 0.0000 0 844
2 0.5497 0.5497 1651 3801
2 0.3240 0.3240 153 3801
2 0.9205 0.9404 2150 3379
2 0.3872 0.3985 460 3225
0 0.0000 0.0000 192 1228
2 0.3754 0.3754 652 3801
0 0.0000 0.0000 192 652
0 0.0000 0.0000 0 460
2 0.6507 0.6831 1612 3225
0 0.0000 0.0000 0 76
2 0.5675 0.6997 2419 3686
0 0.0000 0.0000 38 76
0 0.0000 0.0000 1075 1228
0 0.0000 0.0000 1075 1459
0 0.0000 0.0000 1113 1152
0 0.0000 0.0000 460 1459
0 0.0000 0.0000 1651 1689
0 0.0000 0.0000 153 384
0 0.0000 0.0000 1075 1113
0 0.0000 0.0000 1152 1190
0 0.0000 0.0000 0 883
2 0.8772 1.0000 2227 3264
0 0.0000 0.0000 230 460
0 0.0000 0.0000 1420 1459
0 0.0000 0.0000 1113 1190
2 0.4886 0.4886 1036 3456
0 0.0000 0.0000 1612 1651
0 0.0000 0.0000 1075 1152
0 0.0000 0.0000 1689 1728
0 0.0000 0.0000 1113 1305
2 0.5073 0.8546 2649 3417
0 0.0000 0.0000 0 307
0 0.0000 0.0000 153 614
0 0.0000 0.0000 268 307
0 0.0000 0.0000 1920 1958
0 0.0000 0.0000 614 652
2 0.1822 0.2210 0 2726
0 0.0000 0.0000 614 883
0 0.0000 0.0000 3724 3763
0 0.0000 0.0000 192 307
0 0.0000 0.0000 1651 1728
0 0.0000 0.0000 806 844
0 0.0000 0.0000 230 345
0 0.0000 0.0000 652 691
0 0.0000 0.0000 230 1190
0 0.0000 0.0000 1152 1228
0 0.0000 0.0000 1036 1190
0 0.0000 0.0000 1036 1113
0 0.0000 0.0000 1612 1689
0 0.0000 0.0000 1958 1996
0 0.0000 0.0000 3724 3801
0 0.0000 0.0000 1305 1344
0 0.0000 0.0000 1612 1766
0 0.0000 0.0000 691 729
0 0.0000 0.0000 1420 1497
0 0.0000 0.0000 268 384
0 0.0000 0.0000 460 499
0 0.0000 0.0000 1689 1766
2 0.3737 0.3900 460 3187
0 0.0000 0.0000 1420 1574
0 0.0000 0.0000 1152 1651
0 0.0000 0.0000 0 1728
0 0.0000 0.0000 460 806
0 0.0000 0.0000 1651 1843
2 0.6362 0.6672 1574 3225
0 0.0000 0.0000 652 1228
0 0.0000 0.0000 614 729
0 0.0000 0.0000 268 729
2 0.4548 1.0000 2188 2726
0 0.0000 0.0000 1305 1459
2 0.5514 0.6511 2380 3801
0 0.0000 0.0000 1420 1766
0 0.0000 0.0000 806 883
0 0.0000 0.0000 1574 1651
0 0.0000 0.0000 652 768
0 0.0000 0.0000 3494 3801
0 0.0000 0.0000 1305 1382
0 0.0000 0.0000 1920 1996
0 0.0000 0.0000 1881 1958
0 0.0000 0.0000 1036 1420
0 0.0000 0.0000 691 806
2 0.3382 0.3382 0 3494
0 0.0000 0.0000 268 499
0 0.0000 0.0000 460 614
0 0.0000 0.0000 806 960
2 0.6498 1.0000 2419 3187
0 0.0000 0.0000 806 1574
0 0.0000 0.0000 115 345
0 0.0000 0.0000 691 998
0 0.0000 0.0000 1075 1267
0 0.0000 0.0000 460 537
2 0.1623 0.3546 3033 3801
2 0.8794 0.8794 2073 3417
2 0.3708 0.3708 614 3801
2 0.4809 0.4809 1113 3571

I looked for it before, but I can't recognize the difference between my proposal file and the example。 @tony2016uestc
