### ISSUE TITLE
I added the video data labeled by myself (less than 15 minutes), but there was a limit of 15 minutes frame in the code and an error was reported. I tried to make a change. Is there a faster way to solve this problem?

### ISSUE THREAD

**Issue by gzchenjiajun** [open-mmlab/mmaction2#1157]
I added the video data labeled by myself (less than 15 minutes), but there was a limit of 15 minutes frame in the code and an error was reported. I tried to make a change.
Is there a faster way to solve this problem?

Original Traceback (most recent call last):
  File "/home/psdz/Desktop/tensorrt_env/TensorRT-6.0.1.5/lib/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/psdz/Desktop/tensorrt_env/TensorRT-6.0.1.5/lib/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/psdz/Desktop/tensorrt_env/TensorRT-6.0.1.5/lib/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/psdz/Desktop/mmaction2-master_9_15/mmaction/datasets/base.py", line 289, in __getitem__
    return self.prepare_train_frames(idx)
  File "/home/psdz/Desktop/mmaction2-master_9_15/mmaction/datasets/ava_dataset.py", line 305, in prepare_train_frames
    return self.pipeline(results)
  File "/home/psdz/Desktop/mmaction2-master_9_15/mmaction/datasets/pipelines/compose.py", line 50, in __call__
    data = t(data)
  File "/home/psdz/Desktop/mmaction2-master_9_15/mmaction/datasets/pipelines/loading.py", line 1307, in __call__
    img_bytes = self.file_client.get(filepath)
  File "/home/psdz/Desktop/tensorrt_env/TensorRT-6.0.1.5/lib/open-mmlab/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 306, in get
    return self.client.get(filepath)
  File "/home/psdz/Desktop/tensorrt_env/TensorRT-6.0.1.5/lib/open-mmlab/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 184, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/ava/rawframes/doze_1/img_26999.jpg'

**Comment by kennymckormick** [comment]
Hello, you need to modify the argument `timestamp_start` and `timestamp_end` of the AVA dataset to be compatible with ur own data.

**Comment by gzchenjiajun** [comment]
@kennymckormick 
I know. It's been fixed.
I thought the repo would consider this situation.
Thank you
