### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by kobe233333** [open-mmlab/mmaction2#1240]
(test) theo@theo-MS-7C98:~/tong_lab/mmaction2$ python tools/train.py i3d_r50_video_imgaug_32x2x1_100e_kinetics400_rgb.py 
Traceback (most recent call last):
  File "tools/train.py", line 16, in <module>
    from mmaction.apis import train_model
  File "/home/theo/anaconda3/envs/test/lib/python3.7/site-packages/mmaction/apis/__init__.py", line 2, in <module>
    from .inference import inference_recognizer, init_recognizer
  File "/home/theo/anaconda3/envs/test/lib/python3.7/site-packages/mmaction/apis/inference.py", line 16, in <module>
    from mmaction.models import build_recognizer
  File "/home/theo/anaconda3/envs/test/lib/python3.7/site-packages/mmaction/models/__init__.py", line 2, in <module>
    from .backbones import (C3D, STGCN, X3D, MobileNetV2, MobileNetV2TSM, ResNet,
  File "/home/theo/anaconda3/envs/test/lib/python3.7/site-packages/mmaction/models/backbones/__init__.py", line 12, in <module>
    from .resnet_tin import ResNetTIN
  File "/home/theo/anaconda3/envs/test/lib/python3.7/site-packages/mmaction/models/backbones/resnet_tin.py", line 10, in <module>
    from mmcv.ops import tin_shift
  File "/home/theo/anaconda3/envs/test/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/theo/anaconda3/envs/test/lib/python3.7/site-packages/mmcv/ops/assign_score_withk.py", line 6, in <module>
    '_ext', ['assign_score_withk_forward', 'assign_score_withk_backward'])
  File "/home/theo/anaconda3/envs/test/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 15, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: assign_score_withk_forward miss in module _ext

When i want to train my own data using I3D model, i face this error. Could u help me?

**Comment by Cavaradossi** [comment]
I encountered the same problem when I run train.py in mmtracking. How did you fix it?
