### ISSUE TITLE
RuntimeError when training i3D with kinetics400 

### ISSUE THREAD

**Issue by ImmortalCi** [open-mmlab/mmaction2#1250]
@innerlee @lindahua @yuta1125tp @hellock @MMLAB-CUHK 
Hello!
I ran this:
python tools/train.py /root/wtc/mmaction2-master/configs/recognition/i3d/i3d_r50_video_32x2x1_100e_kinetics400_rgb.py --work-dir /root/wtc/mmaction2-master/work_dirs/i3d_r50_video_32x2x1_100e_kinetics400_rgb --validate --seed 0 --deterministic

to train i3D with videos(without RGB frame and flow to save space).

Here is the error log. How to solve it?

2021-11-02 16:10:41,922 - mmaction - INFO - Checkpoints will be saved to /root/wtc/mmaction2-**master/work_dirs/i3d_r50_video_32x2x1_100e_kinetics400_rgb by HardDiskBackend.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x559a7343fe00] moov atom not found
[16:11:08] /github/workspace/src/video/video_reader.cc:83: ERROR opening: , Invalid data found when processing input**
Traceback (most recent call last):
  File "tools/train.py", line 200, in <module>
    main()
  File "tools/train.py", line 196, in main
    meta=meta)
  File "/root/anaconda3/envs/ASSERT/lib/python3.7/site-packages/mmaction/apis/train.py", line 168, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/root/anaconda3/envs/ASSERT/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/anaconda3/envs/ASSERT/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/root/anaconda3/envs/ASSERT/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/ASSERT/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/ASSERT/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/ASSERT/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/ASSERT/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/ASSERT/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/ASSERT/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/ASSERT/lib/python3.7/site-packages/mmaction/datasets/base.py", line 289, in __getitem__
    return self.prepare_train_frames(idx)
  File "/root/anaconda3/envs/ASSERT/lib/python3.7/site-packages/mmaction/datasets/base.py", line 263, in prepare_train_frames
    return self.pipeline(results)
  File "/root/anaconda3/envs/ASSERT/lib/python3.7/site-packages/mmaction/datasets/pipelines/compose.py", line 50, in __call__
    data = t(data)
  File "/root/anaconda3/envs/ASSERT/lib/python3.7/site-packages/mmaction/datasets/pipelines/loading.py", line 1064, in __call__
    container = decord.VideoReader(file_obj, num_threads=self.num_threads)
  File "/root/anaconda3/envs/ASSERT/lib/python3.7/site-packages/decord/video_reader.py", line 57, in __init__
    raise RuntimeError("Error reading " + uri + "...")
RuntimeError: Error reading 4194304 bytes...

Thanks a lot!

**Comment by kennymckormick** [comment]
Seems that you failed to load a video, would you please enumerate all videos and check if you can successfully load all of them?

**Comment by ImmortalCi** [comment]
Thanks. There is something wrong with my videos dataset. I’m checking it.

**Comment by T-wow** [comment]
How did you solve it？Thanks

**Comment by yangruotong** [comment]
Nothing wrong with my videos dataset and I can successfully load all of them. But But an error is still reported.
