### ISSUE TITLE
RuntimeError: Recognizer3D: Only one file(not dir) is allowed in the zipfile.

### ISSUE THREAD

**Issue by Laowai01** [open-mmlab/mmaction2#1259]
Even changed the pytorch version from 1.5 to 1.6 but to no effect.

**Comment by bit-scientist** [comment]
@Laowai01 Please, give more detailed information about what happened. What command did you run? What changes have you done to that script? What versions of packages are you using? Try to be more specific about the error. And don't forget to include traceback error, one line won't help at all. Thanks

**Comment by kennymckormick** [comment]
Please reopen this issue if you have some updates.

**Comment by FarzanehAskari** [comment]
Same error here with the Timestransform model.
Config file:

```
_base_ = ['../../_base_/default_runtime.py']

# model settings
model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='TimeSformer',
        pretrained=  # noqa: E251
        'https://download.openmmlab.com/mmaction/recognition/timesformer/vit_base_patch16_224.pth',  # noqa: E501
        num_frames=8,
        img_size=224,
        patch_size=16,
        embed_dims=768,
        in_channels=3,
        dropout_ratio=0.,
        transformer_layers=None,
        attention_type='joint_space_time',
        norm_cfg=dict(type='LN', eps=1e-6)),
    cls_head=dict(type='TimeSformerHead', num_classes=12, in_channels=768),
    # model training and testing settings
    train_cfg=None,
    test_cfg=dict(average_clips='prob'))

# dataset settings
dataset_type = 'RawframeDataset'
data_root = 'data/motus_domum/rawframes/'
data_root_val = 'data/motus_domum/rawframes/'
ann_file_train = 'data/motus_domum/annotation_train.txt'
ann_file_val = 'data/motus_domum/annotation_valid.txt'
ann_file_test = 'data/motus_domum/annotation_test.txt'

img_norm_cfg = dict(
    mean=[127.5, 127.5, 127.5], std=[127.5, 127.5, 127.5], to_bgr=False)

train_pipeline = [
    dict(type='SampleFrames', clip_len=8, frame_interval=32, num_clips=1),
    dict(type='RawFrameDecode'),
    dict(type='RandomRescale', scale_range=(256, 320)),
    dict(type='RandomCrop', size=224),
    dict(type='Flip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]
val_pipeline = [
    dict(
        type='SampleFrames',
        clip_len=8,
        frame_interval=32,
        num_clips=1,
        test_mode=True),
    dict(type='RawFrameDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]
test_pipeline = [
    dict(
        type='SampleFrames',
        clip_len=8,
        frame_interval=32,
        num_clips=1,
        test_mode=True),
    dict(type='RawFrameDecode'),
    dict(type='Resize', scale=(-1, 224)),
    dict(type='ThreeCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]
data = dict(
    videos_per_gpu=7,
    workers_per_gpu=2,
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix=data_root,
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix=data_root_val,
        pipeline=val_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=ann_file_test,
        data_prefix=data_root_val,
        pipeline=test_pipeline))

evaluation = dict(
    interval=1, metrics=['top_k_accuracy', 'mean_class_accuracy'])

# optimizer
optimizer = dict(
    type='SGD',
    lr=0.000625,
    momentum=0.9,
    paramwise_cfg=dict(
        custom_keys={
            '.backbone.cls_token': dict(decay_mult=0.0),
            '.backbone.pos_embed': dict(decay_mult=0.0),
            '.backbone.time_embed': dict(decay_mult=0.0)
        }),
    weight_decay=1e-4,
    nesterov=True)  # this lr is used for 8 gpus
optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))
# learning policy
lr_config = dict(policy='step', step=[5, 10])
total_epochs = 150

# runtime settings
checkpoint_config = dict(interval=1)
work_dir = './work_dirs/timesformer_motus_domum_jointST_fineuned'

```
Error:

```
2021-12-20 11:52:18,206 - mmaction - INFO - load model from: https://download.openmmlab.com/mmaction/recognition/timesformer/vit_base_patch16_224.pth
Use load_from_http loader
Traceback (most recent call last):
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/recognizers/base.py", line 110, in __init__
    self.init_weights()
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/recognizers/base.py", line 127, in init_weights
    self.backbone.init_weights()
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/backbones/timesformer.py", line 229, in init_weights
    state_dict = _load_checkpoint(self.pretrained)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 284, in load_from_http
    filename, model_dir=model_dir, map_location=map_location)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/torch/hub.py", line 494, in load_state_dict_from_url
    raise RuntimeError('Only one file(not dir) is allowed in the zipfile')
RuntimeError: Only one file(not dir) is allowed in the zipfile

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 200, in <module>
    main()
  File "tools/train.py", line 158, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/builder.py", line 71, in build_model
    return build_localizer(cfg)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/builder.py", line 63, in build_localizer
    return LOCALIZERS.build(cfg)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/utils/registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
RuntimeError: Recognizer3D: Only one file(not dir) is allowed in the zipfile
```
