### ISSUE TITLE
Error while downloading the Kinetics400

### ISSUE THREAD

**Issue by AslanDevbrat** [open-mmlab/mmaction2#1261]
I was trying to download the Kinetics400 dataset using [your documentation](https://mmaction2.readthedocs.io/en/latest/supported_datasets.html#kinetics-400-600-700) 

First Try moved to this folder 
`cd mmaction2/tools/data/kinetics`

Then I ran the command to download annotation
`bash download_annotations.sh kinetics400`

Then the command for downloading the videos
`bash download_videos.sh kinetics400`

I downloaded some videos video but then got this error
```
download_videos.sh: line 4: conda: command not found
download_videos.sh: line 5: activate: No such file or directory
Collecting youtube-dl
  Downloading youtube_dl-2021.6.6-py2.py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 5.2 MB/s 
Installing collected packages: youtube-dl
Successfully installed youtube-dl-2021.6.6
We are processing kinetics400
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/f23484fd-33b0-4de6-8846-25c53e255db3.%(ext)s" "https://www.youtube.com/watch?v=---QUuC4vJs"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/86dd8ca1-26d0-43f3-b225-013a2c282b0b.%(ext)s" "https://www.youtube.com/watch?v=--56QUhyDQM"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/364918eb-c4e5-446f-b3a0-dc159b599b34.%(ext)s" "https://www.youtube.com/watch?v=--4-0ihtnBU"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/2e88eefe-dcd6-4eca-8f91-2c652f85b96e.%(ext)s" "https://www.youtube.com/watch?v=--3ouPhoy2A"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/d7c71b96-dd1b-4237-92b2-d7f4d252017d.%(ext)s" "https://www.youtube.com/watch?v=--6q_33gNew"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/fed9c5b1-8f7f-4ff0-a818-702d4ba42c99.%(ext)s" "https://www.youtube.com/watch?v=--EaS9P7ZdQ"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/1103a13b-1e29-4bd8-ad7c-15b03c476df8.%(ext)s" "https://www.youtube.com/watch?v=--IPbe5ZMCI"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/cc941dc0-35c1-4a72-bd8c-8577e46acafb.%(ext)s" "https://www.youtube.com/watch?v=--PyMoD3_eg"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/ebbff00b-64c8-4d03-bc7c-07d321c73acb.%(ext)s" "https://www.youtube.com/watch?v=--TBx-Spzis"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/ae4afb04-af68-4f7b-9920-535d044fa293.%(ext)s" "https://www.youtube.com/watch?v=--Ntf6n-j9Q"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/94b1f557-703e-43c2-a3a8-5ae985f54c65.%(ext)s" "https://www.youtube.com/watch?v=--VnA3ztuZg"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/c07d164e-2e0a-449a-8f2d-6e423079ac74.%(ext)s" "https://www.youtube.com/watch?v=--_S9IDQPLg"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/e805f6ff-e481-483c-82f5-fa3cd198f48d.%(ext)s" "https://www.youtube.com/watch?v=--UW3CcUqaU"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/b996a587-2eb2-49c4-9128-a3c317a275c1.%(ext)s" "https://www.youtube.com/watch?v=--bO6XwZ9HI"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/c7ecb519-249b-4c0f-8ada-2cb90e7cac55.%(ext)s" "https://www.youtube.com/watch?v=--feYHvtteA"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/be5d6e50-7b51-4571-9dcb-758840342110.%(ext)s" "https://www.youtube.com/watch?v=--lrRHlpK68"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/6cf6ebab-4aa9-4e4f-b1a2-a5f3aa224034.%(ext)s" "https://www.youtube.com/watch?v=--jD1Yu5ZnQ"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/ece0f933-acb8-4cc9-a8df-4093df1a876c.%(ext)s" "https://www.youtube.com/watch?v=--gx7yb1-x0"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/87fdd884-92d2-40db-9df6-36668d2e62df.%(ext)s" "https://www.youtube.com/watch?v=--mI_-gaZLk"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/6baec13c-708e-43a5-9b66-39591450b52e.%(ext)s" "https://www.youtube.com/watch?v=--j-y5SNUhs"
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.7/dist-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "download.py", line 144, in download_clip_wrapper
    tmp_dir=tmp_dir)
  File "download.py", line 108, in download_clip
    tmp_filename = glob.glob('%s*' % tmp_filename.split('.')[0])[0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "download.py", line 230, in <module>
    main(**vars(p.parse_args()))
  File "download.py", line 197, in main
    for i, row in dataset.iterrows())
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.7/dist-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
IndexError: list index out of range
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/a4a14907-f352-49db-af92-fa5477ee886b.%(ext)s" "https://www.youtube.com/watch?v=--7VUM9MKg4"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/5d10c837-15fe-4943-b854-e757e4363336.%(ext)s" "https://www.youtube.com/watch?v=--07WQ2iBlw"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/f13a5418-3b3d-40e9-ab96-965875283616.%(ext)s" "https://www.youtube.com/watch?v=--7goKgS4kc"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/cc73465b-1cb9-4ccf-93f7-6f3e71a27fbd.%(ext)s" "https://www.youtube.com/watch?v=--33Lscn6sk"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/84734487-68cd-49d7-9c5f-dfe65e8c4ec2.%(ext)s" "https://www.youtube.com/watch?v=--7qK_w-g3Y"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/38c4d7a6-c1c1-4f31-bbc3-24b5223ed58f.%(ext)s" "https://www.youtube.com/watch?v=--8FQVwWH0M"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/5527aaa1-69c5-45e0-97eb-d8b007b5dee0.%(ext)s" "https://www.youtube.com/watch?v=--9s8lCov-I"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/a4f6554d-68bd-4563-9634-0fdf9fc6bc3d.%(ext)s" "https://www.youtube.com/watch?v=--Kr1PZaPDI"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/a9a66c17-ee1c-453f-a7b1-c964c44306c9.%(ext)s" "https://www.youtube.com/watch?v=--ILYNHl3e4"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/7fcde6c7-a21e-4410-b95a-a0ddbc48ff37.%(ext)s" "https://www.youtube.com/watch?v=--GF746y6UM"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/089cdca8-60df-4fc3-9503-9472e3702248.%(ext)s" "https://www.youtube.com/watch?v=--PwWfN1Ae4"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/6600426f-c47b-4abc-9613-f2d7d235a695.%(ext)s" "https://www.youtube.com/watch?v=--RVKBMp_2M"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/c1ced0b5-7f68-47bd-94d5-ea51a07df597.%(ext)s" "https://www.youtube.com/watch?v=--SOz3xjWfA"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/91951d93-5b18-43b5-8aff-cce377911f10.%(ext)s" "https://www.youtube.com/watch?v=--SrV9bGzRA"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/e91a20f8-09d6-4f02-8ada-a79c7c0eea23.%(ext)s" "https://www.youtube.com/watch?v=--TSmh3wj9I"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/df04d7c3-1390-4bf6-9996-ddaba9d7e1e7.%(ext)s" "https://www.youtube.com/watch?v=--dVV4_CSvw"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/dc1e3bb0-c88e-425b-8b1a-876f86869532.%(ext)s" "https://www.youtube.com/watch?v=--bGIeO_7Jo"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/d66ee47a-1904-4381-a420-7cd3332bd8a1.%(ext)s" "https://www.youtube.com/watch?v=--rC9Wkh6HA"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/53055c51-d4d7-4b6c-a766-142b6e9fe47f.%(ext)s" "https://www.youtube.com/watch?v=--Y25nDn2Wk"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/53f5ecff-2bc1-433e-a593-fe1f65fdbb72.%(ext)s" "https://www.youtube.com/watch?v=--gEBElruic"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/6ba0d287-ab17-408d-b39b-fba87016d12c.%(ext)s" "https://www.youtube.com/watch?v=--kbTDDIiP0"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/1de818ee-afb9-47ae-905b-a5dd07098bf5.%(ext)s" "https://www.youtube.com/watch?v=--nQbRBEz2s"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/4b9c6800-08d6-434b-afc8-5d7ea5392012.%(ext)s" "https://www.youtube.com/watch?v=--oEIzy6Esc"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/9bf18990-6230-4824-9338-4abf4c70315f.%(ext)s" "https://www.youtube.com/watch?v=--o545tThdQ"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/6e881c40-d10b-4e10-ad55-97bf44b2792c.%(ext)s" "https://www.youtube.com/watch?v=--oJV4vFNeI"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/051e50b3-d00d-412c-8d5b-745f09c13e69.%(ext)s" "https://www.youtube.com/watch?v=--rd8woSLiM"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/f335d38f-a5b1-4132-8197-a840e6250b2c.%(ext)s" "https://www.youtube.com/watch?v=--sGO9m2Was"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/f6edeefb-5443-441c-b46d-b8c17145017a.%(ext)s" "https://www.youtube.com/watch?v=--uGS0Y4D6k"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/514bd2fd-9c8b-4fee-9792-b788c41c684c.%(ext)s" "https://www.youtube.com/watch?v=--wYHtYMK9o"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/94aab668-118f-4ebd-8fa8-af3e2f77b28f.%(ext)s" "https://www.youtube.com/watch?v=--yCUKj4Oq4"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/2d5ecab5-2a1a-4ef1-879d-f88f48b19b16.%(ext)s" "https://www.youtube.com/watch?v=-0-s1eu4sF4"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/91807f24-34b6-41de-9fea-5178185f61c9.%(ext)s" "https://www.youtube.com/watch?v=-02UO1KSdZ0"
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.7/dist-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "download.py", line 144, in download_clip_wrapper
    tmp_dir=tmp_dir)
  File "download.py", line 108, in download_clip
    tmp_filename = glob.glob('%s*' % tmp_filename.split('.')[0])[0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "download.py", line 230, in <module>
    main(**vars(p.parse_args()))
  File "download.py", line 197, in main
    for i, row in dataset.iterrows())
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.7/dist-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
IndexError: list index out of range
download_videos.sh: line 21: deactivate: No such file or directory
download_videos.sh: line 22: conda: command not found
```

Please tell me what am I doing wrong Why I am getting this list out of index error

**Comment by kennymckormick** [comment]
Not quite sure, can you successfully download a youtube video with this command? 

```
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/.tmp_dir/91807f24-34b6-41de-9fea-5178185f61c9.%(ext)s" "https://www.youtube.com/watch?v=-02UO1KSdZ0"
```
