### ISSUE TITLE
ImportError: cannot import name 'CUDA_HOME' from 'mmcv.utils'

### ISSUE THREAD

**Issue by Eunchan24** [open-mmlab/mmaction2#1264]
Hello

There is an error as below, can you help me?

`python tools/train.py configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py --work-dir work_dirs/slowonly_r50_u48_240e_ntu120_xsub_keypoint --validate --test-best --gpus 1 --seed 0 --deterministic`

`Traceback (most recent call last):
  File "tools/train.py", line 16, in <module>
    from mmaction.apis import train_model
  File "/home/ubuntu/anaconda3/envs/swpark/lib/python3.8/site-packages/mmaction/apis/__init__.py", line 1, in <module>
    from .inference import inference_recognizer, init_recognizer
  File "/home/ubuntu/anaconda3/envs/swpark/lib/python3.8/site-packages/mmaction/apis/inference.py", line 8, in <module>
    from ..datasets.pipelines import Compose
  File "/home/ubuntu/anaconda3/envs/swpark/lib/python3.8/site-packages/mmaction/datasets/__init__.py", line 1, in <module>
    from .activitynet_dataset import ActivityNetDataset
  File "/home/ubuntu/anaconda3/envs/swpark/lib/python3.8/site-packages/mmaction/datasets/activitynet_dataset.py", line 8, in <module>
    from ..core import average_recall_at_avg_proposals
  File "/home/ubuntu/anaconda3/envs/swpark/lib/python3.8/site-packages/mmaction/core/__init__.py", line 2, in <module>
    from .evaluation import *  # noqa: F401, F403
  File "/home/ubuntu/anaconda3/envs/swpark/lib/python3.8/site-packages/mmaction/core/evaluation/__init__.py", line 5, in <module>
    from .eval_hooks import DistEvalHook, EvalHook
  File "/home/ubuntu/anaconda3/envs/swpark/lib/python3.8/site-packages/mmaction/core/evaluation/eval_hooks.py", line 8, in <module>
    from mmaction.utils import get_root_logger
  File "/home/ubuntu/anaconda3/envs/swpark/lib/python3.8/site-packages/mmaction/utils/__init__.py", line 1, in <module>
    from .collect_env import collect_env
  File "/home/ubuntu/anaconda3/envs/swpark/lib/python3.8/site-packages/mmaction/utils/collect_env.py", line 10, in <module>
    from mmcv.utils import CUDA_HOME, get_build_config
ImportError: cannot import name 'CUDA_HOME' from 'mmcv.utils' (/home/ubuntu/anaconda3/envs/swpark/lib/python3.8/site-packages/mmcv/utils/__init__.py)`
Thank you.

**Comment by Eunchan24** [comment]
> This is my environment below.
There's no problem bringing in mmcv.
I'm not good at deep learning, so I don't know what the problem is. Please help me.
> 
(pytorch_p38) ➜  ~ python
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
> import torch
> import mmcv
> torch.__version__
'1.7.0'
> mmcv.__version__
'1.3.17'
> torch.cuda.is_available()
True
>

**Comment by floriandotpy** [comment]
I had the same error when I incorrectly used `mmaction`, not `mmaction2`. 

Maybe that's the same case for you. 

Try the following, then re-run your code:

```
pip uninstall mmaction
pip install mmaction2
```

**Comment by Eunchan24** [comment]
@floriandotpy  Thank you for your solution!
I solved this problem.

**Comment by hamzakhalem** [comment]
can you share your solustion with us
