### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '*/image_00000.jpg'

### ISSUE THREAD

**Issue by jamiechoi1995** [open-mmlab/mmaction2#1277]
when running Spatio-Temporal Action Detection on my cutom ava-style dataset, I got following error:

```python
2021-11-22 08:49:08,117 - mmaction - INFO - Distributed training: False
2021-11-22 08:49:09,405 - mmaction - INFO - Config: model = dict(
    type='FastRCNN',
    backbone=dict(
        type='ResNet3dSlowFast',
        pretrained=None,
        resample_rate=4,
        speed_ratio=4,
        channel_ratio=8,
        slow_pathway=dict(
            type='resnet3d',
            depth=50,
            pretrained=None,
            lateral=True,
            fusion_kernel=7,
            conv1_kernel=(1, 7, 7),
            dilations=(1, 1, 1, 1),
            conv1_stride_t=1,
            pool1_stride_t=1,
            inflate=(0, 0, 1, 1),
            spatial_strides=(1, 2, 2, 1)),
        fast_pathway=dict(
            type='resnet3d',
            depth=50,
            pretrained=None,
            lateral=False,
            base_channels=8,
            conv1_kernel=(5, 7, 7),
            conv1_stride_t=1,
            pool1_stride_t=1,
            spatial_strides=(1, 2, 2, 1))),
    roi_head=dict(
        type='AVARoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor3D',
            roi_layer_type='RoIAlign',
            output_size=8,
            with_temporal_pool=True,
            temporal_pool_mode='max'),
        shared_head=dict(type='ACRNHead', in_channels=4608, out_channels=2304),
        bbox_head=dict(
            type='BBoxHeadAVA',
            dropout_ratio=0.5,
            in_channels=2304,
            num_classes=81,
            multilabel=True)),
    train_cfg=dict(
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssignerAVA',
                pos_iou_thr=0.9,
                neg_iou_thr=0.9,
                min_pos_iou=0.9),
            sampler=dict(
                type='RandomSampler',
                num=32,
                pos_fraction=1,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=1.0,
            debug=False)),
    test_cfg=dict(rcnn=dict(action_thr=0.002)))
dataset_type = 'AVADataset'
data_root = 'data/yolo/rawframes'
anno_root = 'data/yolo/annotations'
ann_file_train = 'data/yolo/annotations/yolo_avasytle.csv'
ann_file_val = 'data/yolo/annotations/yolo_avasytle.csv'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)
train_pipeline = [
    dict(type='SampleAVAFrames', clip_len=10, frame_interval=1),
    dict(type='RawFrameDecode'),
    dict(type='RandomResizedCrop'),
    dict(type='Resize', scale=(608, 416), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_bgr=False),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Rename', mapping=dict(imgs='img')),
    dict(type='ToTensor', keys=['img', 'gt_bboxes', 'gt_labels']),
    dict(
        type='ToDataContainer',
        fields=[dict(key=['gt_bboxes', 'gt_labels'], stack=False)]),
    dict(
        type='Collect',
        keys=['img', 'gt_bboxes', 'gt_labels'],
        meta_keys=['entity_ids'])
]
val_pipeline = [
    dict(
        type='SampleAVAFrames', clip_len=10, frame_interval=1, test_mode=True),
    dict(type='RawFrameDecode'),
    dict(type='Resize', scale=(608, 416), keep_ratio=False),
    dict(type='Flip', flip_ratio=0),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_bgr=False),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Rename', mapping=dict(imgs='img')),
    dict(type='ToTensor', keys=['img', 'gt_bboxes', 'gt_labels']),
    dict(
        type='ToDataContainer',
        fields=[dict(key=['gt_bboxes', 'gt_labels'], stack=False)]),
    dict(
        type='Collect',
        keys=['img', 'gt_bboxes', 'gt_labels'],
        meta_keys=['entity_ids'])
]
data = dict(
    videos_per_gpu=6,
    workers_per_gpu=4,
    val_dataloader=dict(videos_per_gpu=1),
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type='AVADataset',
        ann_file='data/yolo/annotations/yolo_avasytle.csv',
        pipeline=[
            dict(type='SampleAVAFrames', clip_len=10, frame_interval=1),
            dict(type='RawFrameDecode'),
            dict(type='RandomResizedCrop'),
            dict(type='Resize', scale=(608, 416), keep_ratio=False),
            dict(type='Flip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_bgr=False),
            dict(type='FormatShape', input_format='NCTHW'),
            dict(type='Rename', mapping=dict(imgs='img')),
            dict(type='ToTensor', keys=['img', 'gt_bboxes', 'gt_labels']),
            dict(
                type='ToDataContainer',
                fields=[dict(key=['gt_bboxes', 'gt_labels'], stack=False)]),
            dict(
                type='Collect',
                keys=['img', 'gt_bboxes', 'gt_labels'],
                meta_keys=['entity_ids'])
        ],
        filename_tmpl='image_{:05}.jpg',
        exclude_file=None,
        person_det_score_thr=0.9,
        data_prefix='data/yolo/rawframes'),
    val=dict(
        type='AVADataset',
        ann_file='data/yolo/annotations/yolo_avasytle.csv',
        pipeline=[
            dict(
                type='SampleAVAFrames',
                clip_len=10,
                frame_interval=1,
                test_mode=True),
            dict(type='RawFrameDecode'),
            dict(type='Resize', scale=(608, 416), keep_ratio=False),
            dict(type='Flip', flip_ratio=0),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_bgr=False),
            dict(type='FormatShape', input_format='NCTHW'),
            dict(type='Rename', mapping=dict(imgs='img')),
            dict(type='ToTensor', keys=['img', 'gt_bboxes', 'gt_labels']),
            dict(
                type='ToDataContainer',
                fields=[dict(key=['gt_bboxes', 'gt_labels'], stack=False)]),
            dict(
                type='Collect',
                keys=['img', 'gt_bboxes', 'gt_labels'],
                meta_keys=['entity_ids'])
        ],
        filename_tmpl='image_{:05}.jpg',
        exclude_file=None,
        person_det_score_thr=0.9,
        data_prefix='data/yolo/rawframes'),
    test=dict(
        type='AVADataset',
        ann_file='data/yolo/annotations/yolo_avasytle.csv',
        pipeline=[
            dict(
                type='SampleAVAFrames',
                clip_len=10,
                frame_interval=1,
                test_mode=True),
            dict(type='RawFrameDecode'),
            dict(type='Resize', scale=(608, 416), keep_ratio=False),
            dict(type='Flip', flip_ratio=0),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_bgr=False),
            dict(type='FormatShape', input_format='NCTHW'),
            dict(type='Rename', mapping=dict(imgs='img')),
            dict(type='ToTensor', keys=['img', 'gt_bboxes', 'gt_labels']),
            dict(
                type='ToDataContainer',
                fields=[dict(key=['gt_bboxes', 'gt_labels'], stack=False)]),
            dict(
                type='Collect',
                keys=['img', 'gt_bboxes', 'gt_labels'],
                meta_keys=['entity_ids'])
        ],
        filename_tmpl='image_{:05}.jpg',
        exclude_file=None,
        person_det_score_thr=0.9,
        data_prefix='data/yolo/rawframes'))
optimizer = dict(type='SGD', lr=0.075, momentum=0.9, weight_decay=1e-05)
optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))
lr_config = dict(
    policy='CosineAnnealing',
    by_epoch=False,
    min_lr=0,
    warmup='linear',
    warmup_by_epoch=True,
    warmup_iters=2,
    warmup_ratio=0.1)
total_epochs = 10
checkpoint_config = dict(interval=1)
workflow = [('train', 1)]
evaluation = dict(interval=1)
log_config = dict(interval=20, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/slowfast_acrn_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb_DEBUG'
load_from = None
resume_from = None
find_unused_parameters = False
gpu_ids = range(0, 1)
omnisource = False
module_hooks = []

2021-11-22 08:49:11,821 - mmaction - INFO - 16787 out of 16787 frames are valid.
fatal: not a git repository (or any parent up to mount point /HDATA)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2021-11-22 08:49:37,765 - mmaction - INFO - Start running, host: root@baa72fc4eb0b, work_dir: /mmaction2-0.19.0/work_dirs/slowfast_acrn_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb_DEBUG
2021-11-22 08:49:37,765 - mmaction - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) CosineAnnealingLrUpdaterHook
(NORMAL      ) CheckpointHook
(VERY_LOW    ) TextLoggerHook
 --------------------
before_train_epoch:
(VERY_HIGH   ) CosineAnnealingLrUpdaterHook
(LOW         ) IterTimerHook
(VERY_LOW    ) TextLoggerHook
 --------------------
before_train_iter:
(VERY_HIGH   ) CosineAnnealingLrUpdaterHook
(LOW         ) IterTimerHook
 --------------------
after_train_iter:
(ABOVE_NORMAL) OptimizerHook
(NORMAL      ) CheckpointHook
(LOW         ) IterTimerHook
(VERY_LOW    ) TextLoggerHook
 --------------------
after_train_epoch:
(NORMAL      ) CheckpointHook
(VERY_LOW    ) TextLoggerHook
 --------------------
before_val_epoch:
(LOW         ) IterTimerHook
(VERY_LOW    ) TextLoggerHook
 --------------------
before_val_iter:
(LOW         ) IterTimerHook
 --------------------
after_val_iter:
(LOW         ) IterTimerHook
 --------------------
after_val_epoch:
(VERY_LOW    ) TextLoggerHook
 --------------------
2021-11-22 08:49:37,766 - mmaction - INFO - workflow: [('train', 1)], max: 10 epochs
Traceback (most recent call last):
  File "tools/train.py", line 200, in <module>
    main()
  File "tools/train.py", line 196, in main
    meta=meta)
  File "/mmaction2-0.19.0/mmaction/apis/train.py", line 168, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mmaction2-0.19.0/mmaction/datasets/base.py", line 289, in __getitem__
    return self.prepare_train_frames(idx)
  File "/mmaction2-0.19.0/mmaction/datasets/ava_dataset.py", line 305, in prepare_train_frames
    return self.pipeline(results)
  File "/mmaction2-0.19.0/mmaction/datasets/pipelines/compose.py", line 50, in __call__
    data = t(data)
  File "/mmaction2-0.19.0/mmaction/datasets/pipelines/loading.py", line 1299, in __call__
    img_bytes = self.file_client.get(filepath)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/fileio/file_client.py", line 307, in get
    return self.client.get(filepath)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/fileio/file_client.py", line 185, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/image_00000.jpg'
```

**Comment by jamiechoi1995** [comment]
according to https://github.com/open-mmlab/mmaction2/blob/2ff37975b9ea5851a071909c9847b89132c5f99d/docs/faq.md#data
start_index is used to set the offset. However, start_index is not used in RawFrameDecode.

**Comment by kennymckormick** [comment]
Close this issue since the linked PR is merged.

**Comment by zhangmingwang001** [comment]
你好，请问这个问题是怎么解决的
