### ISSUE TITLE
BrokenPipeError

### ISSUE THREAD

**Issue by yanhan13944047669** [open-mmlab/mmaction2#1311]
hi，When I try to run the file test to verify the model posec3d, the following error occurs：

**Comment by yanhan13944047669** [comment]
File "<string>", line 1, in <module>
  File "F:\Anaconda\Anaconda3\envs\mmcv\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "F:\Anaconda\Anaconda3\envs\mmcv\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
MemoryError
Traceback (most recent call last):
  File "F:/长理/研究方向/人体姿态估计/CODE/Re-ID CO/mmaction2-master/tools/test.py", line 366, in <module>
    main()
  File "F:/长理/研究方向/人体姿态估计/CODE/Re-ID CO/mmaction2-master/tools/test.py", line 351, in main
    outputs = inference_pytorch(args, cfg, distributed, data_loader)
  File "F:/长理/研究方向/人体姿态估计/CODE/Re-ID CO/mmaction2-master/tools/test.py", line 162, in inference_pytorch
    outputs = single_gpu_test(model, data_loader)
  File "f:\anaconda\anaconda3\envs\mmcv\mmcv-master\mmcv\engine\test.py", line 31, in single_gpu_test
    for data in data_loader:
  File "F:\Anaconda\Anaconda3\envs\mmcv\lib\site-packages\torch\utils\data\dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "F:\Anaconda\Anaconda3\envs\mmcv\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "F:\Anaconda\Anaconda3\envs\mmcv\lib\site-packages\torch\utils\data\dataloader.py", line 914, in __init__
    w.start()
  File "F:\Anaconda\Anaconda3\envs\mmcv\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "F:\Anaconda\Anaconda3\envs\mmcv\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\Anaconda\Anaconda3\envs\mmcv\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "F:\Anaconda\Anaconda3\envs\mmcv\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "F:\Anaconda\Anaconda3\envs\mmcv\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by yanhan13944047669** [comment]
What is the reason for this error and how can I solve it?
thanks.

**Comment by kennymckormick** [comment]
Hi, yanhan, 
    I'm not sure what is the problem. BTW, we do not officially support Windows now, maybe you can try MMAction2 on LINUX platforms.

**Comment by kkdd0717** [comment]
> Hi, yanhan, I'm not sure what is the problem. BTW, we do not officially support Windows now, maybe you can try MMAction2 on LINUX platforms.

ok,thanks
