### ISSUE TITLE
Syntax error when training resume from official pretrained cpkt

### ISSUE THREAD

**Issue by IzouGend** [open-mmlab/mmaction2#1333]
I trained a video-recogniton model on ucf101. 
System: Ubuntu 18.04LTS
python: 3.8.11
PyTorch: 1.9.0
mmcv-full: 1.4.0
CUDA: 11.0
GPU: GeForce RTX 2080TI x 3  **(GPU number matters?)**
When I trained from scratch by commamd line below:
python tools/train.py  configs/recognition/tsn/tsn_r50_1x1x3_75e_ucf101_rgb.py --gpus 2
**there was no problem. Inference using official pretrained ckpt was also ok.** 

When I trained using official pretrained cpkt:
python tools/train.py  configs/recognition/tsn/tsn_r50_1x1x3_75e_ucf101_rgb.py --gpus 2 --resume-from checkpoints/tsn_r50_1x1x3_75e_ucf101_rgb_20201023-d85ab600.pth
**Some error occured as below:**

2021-12-17 15:14:36,251 - mmaction - INFO - These parameters in pretrained checkpoint are not loaded: {'fc.weight', 'fc.bias'}
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2021-12-17 15:14:51,153 - mmaction - INFO - load checkpoint from local path: checkpoints/tsn_r50_1x1x3_75e_ucf101_rgb_20201023-d85ab600.pth
Traceback (most recent call last):
  File "/root/miniconda3/envs/yolov5-1/lib/python3.8/site-packages/mmcv/utils/config.py", line 101, in _validate_py_syntax
    ast.parse(content)
  File "/root/miniconda3/envs/yolov5-1/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  **File "<unknown>", line 1
    /mnt/cache/duanhaodong/mmaction2/configs/ucf101/lr_1.py
    ^
SyntaxError: invalid syntax**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 200, in <module>
    main()
  File "tools/train.py", line 188, in main
    train_model(
  File "/Data_HDD_4T/mmaction2-master/mmaction/apis/train.py", line 162, in train_model
    runner.resume(cfg.resume_from)
  File "/root/miniconda3/envs/yolov5-1/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 372, in resume
    config = mmcv.Config.fromstring(
  File "/root/miniconda3/envs/yolov5-1/lib/python3.8/site-packages/mmcv/utils/config.py", line 361, in fromstring
    cfg = Config.fromfile(temp_file.name)
  File "/root/miniconda3/envs/yolov5-1/lib/python3.8/site-packages/mmcv/utils/config.py", line 331, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/root/miniconda3/envs/yolov5-1/lib/python3.8/site-packages/mmcv/utils/config.py", line 205, in _file2dict
    Config._validate_py_syntax(filename)
  File "/root/miniconda3/envs/yolov5-1/lib/python3.8/site-packages/mmcv/utils/config.py", line 103, in _validate_py_syntax
    raise SyntaxError('There are syntax errors in config '
**SyntaxError: There are syntax errors in config file /tmp/tmpw3lz37_m.py: invalid syntax (<unknown>, line 1)**
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f0850735f70>
Traceback (most recent call last):
  File "/root/miniconda3/envs/yolov5-1/lib/python3.8/tempfile.py", line 440, in __del__
    self.close()
  File "/root/miniconda3/envs/yolov5-1/lib/python3.8/tempfile.py", line 436, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpt4g72gg9/tmpsuv8u4r5.py'

How can I deal with this problem?

**Comment by IzouGend** [comment]
The problem has been solved.

**Comment by yingkaining** [comment]
@IzouGend I meet the same problem. How to solve it.

**Comment by dreamerlin** [comment]
> @IzouGend I meet the same problem. How to solve it.

It mainly caused by your syntax error in your config files

**Comment by yingkaining** [comment]
I will check my config file. Many thanks
