### ISSUE TITLE
KeyError: 'FastRCNN is not in the models registry'

### ISSUE THREAD

**Issue by kbwzy** [open-mmlab/mmaction2#1363]
when i exect the followinng command: 
python demo/long_video_demo.py configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb.py checkpoints/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb_20201217-ae225e97.pth /home/XXX/work/05_sources/gitlab/slowfast/demo/AVA/SlowFast测试视频/打架.mp4 tools/data/ava/label_map.txt /home/XXX/work/05_sources/gitlab/slowfast/demo/AVA/SlowFast测试视频/打架2.mp4 --label-color 255 255 0

i get the log:
Traceback (most recent call last):
  File "demo/long_video_demo.py", line 265, in <module>
    main()
  File "demo/long_video_demo.py", line 236, in main
    model = init_recognizer(cfg, args.checkpoint, device=args.device)
  File "/home/horine/work/05_sources/gitlab/mmaction2/mmaction/apis/inference.py", line 46, in init_recognizer
    model = build_recognizer(config.model, test_cfg=config.get('test_cfg'))
  File "/home/horine/work/05_sources/gitlab/mmaction2/mmaction/models/builder.py", line 53, in build_recognizer
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/horine/miniconda3/envs/mmaction/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/horine/miniconda3/envs/mmaction/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/horine/miniconda3/envs/mmaction/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')

it's there a mistake in the command script?why init_recognizer can't call sucessfull

**Comment by kennymckormick** [comment]
You should not use long_video_demo to test Spatio-temporal detection models, use demo_spatiotemporal_det instead
