### ISSUE TITLE
KeyError: 'filename'

### ISSUE THREAD

**Issue by devloper13** [open-mmlab/mmaction2#1381]
I was able to finetune I3D over my dataset (pretrained on kinetics 400). I did this using the colab tutorial notebook: https://github.com/open-mmlab/mmaction2/blob/master/demo/mmaction2_tutorial.ipynb

But when I tried the same on my g4dn instance (aws) it produces the following error:

```
2022-01-12 09:44:06,852 - mmaction - INFO - load model from: torchvision://resnet50
load checkpoint from torchvision path: torchvision://resnet50
2022-01-12 09:44:07,095 - mmaction - INFO - These parameters in the 2d checkpoint are not loaded: {'fc.bias', 'fc.weight'}
2022-01-12 09:44:09,231 - mmaction - INFO - load checkpoint from http path: https://download.openmmlab.com/mmaction/recognition/i3d/i3d_r50_32x2x1_100e_kinetics400_rgb/i3d_r50_32x2x1_100e_kinetics400_rgb_20200614-c25ef9a4.pth
2022-01-12 09:44:09,340 - mmaction - WARNING - The model and loaded state dict do not match exactly

size mismatch for cls_head.fc_cls.weight: copying a param with shape torch.Size([400, 2048]) from checkpoint, the shape in current model is torch.Size([6, 2048]).
size mismatch for cls_head.fc_cls.bias: copying a param with shape torch.Size([400]) from checkpoint, the shape in current model is torch.Size([6]).
2022-01-12 09:44:09,340 - mmaction - INFO - Start running, host: root@a7748c7073ac, work_dir: /mmaction2/work_dir
2022-01-12 09:44:09,341 - mmaction - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) CheckpointHook                     
(NORMAL      ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) EvalHook                           
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_iter:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) EvalHook                           
(LOW         ) IterTimerHook                      
 -------------------- 
after_train_iter:
(ABOVE_NORMAL) OptimizerHook                      
(NORMAL      ) CheckpointHook                     
(NORMAL      ) EvalHook                           
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) CheckpointHook                     
(NORMAL      ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_epoch:
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_epoch:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_run:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
2022-01-12 09:44:09,341 - mmaction - INFO - workflow: [('train', 1)], max: 10 epochs
2022-01-12 09:44:09,341 - mmaction - INFO - Checkpoints will be saved to /mmaction2/work_dir by HardDiskBackend.
/opt/conda/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py:222: UserWarning: runner.meta is None. Creating an empty one.
  warnings.warn('runner.meta is None. Creating an empty one.')
Traceback (most recent call last):
  File "tools/train_colab.py", line 82, in <module>
    main()
  File "tools/train_colab.py", line 80, in main
    train_model(model, datasets, cfg, distributed=False, validate=True)
  File "/mmaction2/mmaction/apis/train.py", line 204, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mmaction2/mmaction/datasets/base.py", line 289, in __getitem__
    return self.prepare_train_frames(idx)
  File "/mmaction2/mmaction/datasets/rawframe_dataset.py", line 170, in prepare_train_frames
    return self.pipeline(results)
  File "/mmaction2/mmaction/datasets/pipelines/compose.py", line 50, in __call__
    data = t(data)
  File "/mmaction2/mmaction/datasets/pipelines/loading.py", line 1065, in __call__
    file_obj = io.BytesIO(self.file_client.get(results['filename']))
KeyError: 'filename'
```

From what I can understand, it's running a function 'DecordInit' inside 'loading.py' which is meant for videos? I'm using RawframeDataset which had a variable 'filename_tmpl', so should be calling 'RawFrameDecode' instead? I used the exact same code from colab tutorial to train but it failed on my ec2 (g4dn) instance.

**Comment by dreamerlin** [comment]
You should use `VideoDataset` since you use videos rather than frames.

BTW, if you find our repo is useful you can give us a star 😆

**Comment by devloper13** [comment]
Starred! Definutely useful.

By the way, I'm using frames and not videos.

**Comment by devloper13** [comment]
Oh I just noticed train_pipeline , val_pipeline and test_pipeline all have dict(type='DecordInit'). What is it that? Do we need to change that for Rawframe?

**Comment by dreamerlin** [comment]
Yes, you should use a frame pipeline like https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_320p_1x1x3_100e_kinetics400_rgb.py#L39-L53

**Comment by dreamerlin** [comment]
Decord is used to decode videos into frames on the fly

**Comment by devloper13** [comment]
Thanks!

**Comment by CURRYZJW** [comment]
can i see you true config.py
