### ISSUE TITLE
Clarification on ST-GCN for multi-person videos

### ISSUE THREAD

**Issue by FarzanehAskari** [open-mmlab/mmaction2#1412]
In ST-GCN model, is there any restriction on the number of people in the video? The ntu_pose_extraction.py script pads the skeleton to a maximum number of people, so that part is good. I am wondering, is somewhere in the code for ST-GCN a certain number of subjects (e.g., 1, 2) are picked or the model runs for any given number of people in the .pkl file?

Thank you

**Comment by kennymckormick** [comment]
Here: https://github.com/open-mmlab/mmaction2/blob/7c94243542985db813bb9021f97c95b59d136e52/mmaction/datasets/pipelines/formatting.py#L448. FormatGCNInput pick two persons as the network input (pad zero if there is only one person).
Actually, you can use any number of persons as GCN input, but remember to be consistent in training and testing.

**Comment by FarzanehAskari** [comment]
Thank you. So I changed this number to 10 and now I have the error below:
```
`Traceback (most recent call last):
  File "/home/fay/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/212.5284.44/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/fay/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/212.5284.44/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/fay/Desktop/metalab/mmaction2/tools/train.py", line 201, in <module>
    main()
  File "/home/fay/Desktop/metalab/mmaction2/tools/train.py", line 197, in main
    meta=meta)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/apis/train.py", line 205, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/skeleton_gcn/base.py", line 152, in train_step
    losses = self(skeletons, label, return_loss=True)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/skeleton_gcn/base.py", line 106, in forward
    return self.forward_train(keypoint, label, **kwargs)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/skeleton_gcn/skeletongcn.py", line 18, in forward_train
    loss = self.cls_head.loss(output, gt_labels)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/heads/base.py", line 92, in loss
    labels.detach().cpu().numpy(), (1, 5))
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/core/evaluation/accuracy.py", line 145, in top_k_accuracy
    match_array = np.logical_or.reduce(max_k_preds == labels, axis=1)
numpy.AxisError: axis 1 is out of bounds for array of dimension 0
`
```

And here is my test config file: I have two classes and there can be up to 10 people in my videos. 

```
model = dict(
    type='SkeletonGCN',
    backbone=dict(
        type='STGCN',
        in_channels=3,
        edge_importance_weighting=True,
        graph_cfg=dict(layout='coco', strategy='spatial')),
    cls_head=dict(
        type='STGCNHead',
        num_classes=2,
        in_channels=256,
        loss_cls=dict(type='CrossEntropyLoss')),
    train_cfg=None,
    test_cfg=None)

dataset_type = 'PoseDataset'
ann_file_train = '/home/fay/Desktop/metalab/mmaction2/data/motus_domum/video_sample/train/train_sample_motus_h.pkl'
ann_file_val = '/home/fay/Desktop/metalab/mmaction2/data/motus_domum/video_sample/valid/valid_sample_motus_h.pkl'
ann_file_test = '/home/fay/Desktop/metalab/mmaction2/data/motus_domum/video_sample/test/test_sample_motus_h.pkl'
train_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM'),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]
val_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM'),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]
test_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM'),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]
data = dict(
    videos_per_gpu=2,
    workers_per_gpu=2,
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix='',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix='',
        pipeline=val_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=ann_file_test,
        data_prefix='',
        pipeline=test_pipeline))

# optimizer
optimizer = dict(
    type='SGD', lr=0.0125, momentum=0.9, weight_decay=0.0001, nesterov=True)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='step', step=[10, 50])
total_epochs = 1
checkpoint_config = dict(interval=5)
evaluation = dict(interval=5, metrics=['top_k_accuracy'])
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])

# runtime settings
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = '/home/fay/Desktop/metalab/mmaction2/work_dirs/stgcn_test_15/'
load_from = '/home/fay/Desktop/metalab/mmaction2/checkpoints/stgcn/stgcn_80e_ntu60_xsub_keypoint-e7bb9653.pth'
resume_from = None
workflow = [('train', 1)]`
```

**Comment by FarzanehAskari** [comment]
Thank you. So I fixed this number to 15, as well as the `test_format_gcn_input` from the `test_formatting.py` 
Now I have the error below:
```
Traceback (most recent call last):
  File "/home/fay/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/212.5284.44/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/fay/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/212.5284.44/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/fay/Desktop/metalab/mmaction2/tools/train.py", line 201, in <module>
    main()
  File "/home/fay/Desktop/metalab/mmaction2/tools/train.py", line 197, in main
    meta=meta)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/apis/train.py", line 205, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/skeleton_gcn/base.py", line 152, in train_step
    losses = self(skeletons, label, return_loss=True)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/skeleton_gcn/base.py", line 106, in forward
    return self.forward_train(keypoint, label, **kwargs)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/skeleton_gcn/skeletongcn.py", line 18, in forward_train
    loss = self.cls_head.loss(output, gt_labels)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/heads/base.py", line 92, in loss
    labels.detach().cpu().numpy(), (1, 5))
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/core/evaluation/accuracy.py", line 145, in top_k_accuracy
    match_array = np.logical_or.reduce(max_k_preds == labels, axis=1)
numpy.AxisError: axis 1 is out of bounds for array of dimension 0
```
I am running on a costume dataset where videos can have up to ten people and I have two class actions. Below is my config file:

```
model = dict(
    type='SkeletonGCN',
    backbone=dict(
        type='STGCN',
        in_channels=3,
        edge_importance_weighting=True,
        graph_cfg=dict(layout='coco', strategy='spatial')),
    cls_head=dict(
        type='STGCNHead',
        num_classes=2,
        in_channels=256,
        loss_cls=dict(type='CrossEntropyLoss')),
    train_cfg=None,
    test_cfg=None)

dataset_type = 'PoseDataset'
ann_file_train = '/home/fay/Desktop/metalab/mmaction2/data/motus_domum/video_sample/train/train_sample_motus_h.pkl'
ann_file_val = '/home/fay/Desktop/metalab/mmaction2/data/motus_domum/video_sample/valid/valid_sample_motus_h.pkl'
ann_file_test = '/home/fay/Desktop/metalab/mmaction2/data/motus_domum/video_sample/test/test_sample_motus_h.pkl'
train_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM'),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]
val_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM'),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]
test_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM'),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]
data = dict(
    videos_per_gpu=2,
    workers_per_gpu=2,
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix='',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix='',
        pipeline=val_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=ann_file_test,
        data_prefix='',
        pipeline=test_pipeline))

# optimizer
optimizer = dict(
    type='SGD', lr=0.0125, momentum=0.9, weight_decay=0.0001, nesterov=True)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='step', step=[10, 50])
total_epochs = 1
checkpoint_config = dict(interval=5)
evaluation = dict(interval=5, metrics=['top_k_accuracy'])
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])

# runtime settings
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = '/home/fay/Desktop/metalab/mmaction2/work_dirs/stgcn_test_15/'
load_from = '/home/fay/Desktop/metalab/mmaction2/checkpoints/stgcn/stgcn_80e_ntu60_xsub_keypoint-e7bb9653.pth'
resume_from = None
workflow = [('train', 1)]

```

**Comment by FarzanehAskari** [comment]
Thank you, I have chnaged this number to 15. And now I receive the error below:

```
Traceback (most recent call last):
  File "/home/fay/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/212.5284.44/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/fay/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/212.5284.44/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/fay/Desktop/metalab/mmaction2/tools/train.py", line 201, in <module>
    main()
  File "/home/fay/Desktop/metalab/mmaction2/tools/train.py", line 197, in main
    meta=meta)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/apis/train.py", line 205, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/skeleton_gcn/base.py", line 152, in train_step
    losses = self(skeletons, label, return_loss=True)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/skeleton_gcn/base.py", line 106, in forward
    return self.forward_train(keypoint, label, **kwargs)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/skeleton_gcn/skeletongcn.py", line 18, in forward_train
    loss = self.cls_head.loss(output, gt_labels)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/heads/base.py", line 92, in loss
    labels.detach().cpu().numpy(), (1, 5))
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/core/evaluation/accuracy.py", line 145, in top_k_accuracy
    match_array = np.logical_or.reduce(max_k_preds == labels, axis=1)
numpy.AxisError: axis 1 is out of bounds for array of dimension 0
```
Here is my config file. I have two classes and my videos can include up to 15 people. 

```
model = dict(
    type='SkeletonGCN',
    backbone=dict(
        type='STGCN',
        in_channels=3,
        edge_importance_weighting=True,
        graph_cfg=dict(layout='coco', strategy='spatial')),
    cls_head=dict(
        type='STGCNHead',
        num_classes=2,
        in_channels=256,
        loss_cls=dict(type='CrossEntropyLoss')),
    train_cfg=None,
    test_cfg=None)

dataset_type = 'PoseDataset'
ann_file_train = '/home/fay/Desktop/metalab/mmaction2/data/motus_domum/video_sample/train/train_sample_motus_h.pkl'
ann_file_val = '/home/fay/Desktop/metalab/mmaction2/data/motus_domum/video_sample/valid/valid_sample_motus_h.pkl'
ann_file_test = '/home/fay/Desktop/metalab/mmaction2/data/motus_domum/video_sample/test/test_sample_motus_h.pkl'
train_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM'),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]
val_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM'),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]
test_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM'),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]
data = dict(
    videos_per_gpu=2,
    workers_per_gpu=2,
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix='',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix='',
        pipeline=val_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=ann_file_test,
        data_prefix='',
        pipeline=test_pipeline))

# optimizer
optimizer = dict(
    type='SGD', lr=0.0125, momentum=0.9, weight_decay=0.0001, nesterov=True)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='step', step=[10, 50])
total_epochs = 1
checkpoint_config = dict(interval=5)
evaluation = dict(interval=5, metrics=['top_k_accuracy'])
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])

# runtime settings
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = '/home/fay/Desktop/metalab/mmaction2/work_dirs/stgcn_test_15/'
load_from = '/home/fay/Desktop/metalab/mmaction2/checkpoints/stgcn/stgcn_80e_ntu60_xsub_keypoint-e7bb9653.pth'
resume_from = None
workflow = [('train', 1)]

```

Thank you.

**Comment by kennymckormick** [comment]
Sorry, I can not figure out what is the problem. Maybe you can post several data samples here. 
BTW, you should set num_person to be 15 in ur config, but setting it as default will not lead to an error. 

Or, @gengenkai , would you please check this issue?

**Comment by FarzanehAskari** [comment]
Thank you for pointing out the num_person setting in the config file. So after I set that to 15 now I have this error:
```
Traceback (most recent call last):
  File "tools/train.py", line 201, in <module>
    main()
  File "tools/train.py", line 197, in main
    meta=meta)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/apis/train.py", line 205, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/skeleton_gcn/base.py", line 152, in train_step
    losses = self(skeletons, label, return_loss=True)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/skeleton_gcn/base.py", line 106, in forward
    return self.forward_train(keypoint, label, **kwargs)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/skeleton_gcn/skeletongcn.py", line 16, in forward_train
    output = self.cls_head(x)
  File "/home/fay/miniconda3/envs/env_motus/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fay/Desktop/metalab/mmaction2/mmaction/models/heads/stgcn_head.py", line 56, in forward
    1).mean(dim=1)
RuntimeError: shape '[0, 15, -1, 1, 1]' is invalid for input of size 1024
```

I set it to 15 in model configs:

```
model = dict(
    type='SkeletonGCN',
    backbone=dict(
        type='STGCN',
        in_channels=3,
        edge_importance_weighting=True,
        graph_cfg=dict(layout='coco', strategy='spatial')),
    cls_head=dict(
        type='STGCNHead',
        num_classes=2,
        num_person=15,
        in_channels=256,
        loss_cls=dict(type='CrossEntropyLoss')),
    train_cfg=None,
    test_cfg=None)
```

**Comment by FarzanehAskari** [comment]
[sameples.zip](https://github.com/open-mmlab/mmaction2/files/7981264/sameples.zip)
Here are a few data samples. I attached my train, valid, and test .pkl files.

**Comment by gengenkai** [comment]
> num_person to be 15 in ur config, but setting it as default will not lead to an error.

From the error information above, x.shape in dim 0 is less than the num_person you set here, so you could check the dimension of x in the previous process and find out the problem.

**Comment by kennymckormick** [comment]
Hi, FarzanehAskari.  To set num_person,  you also need to set  dict(type='FormatGCNInput', input_format='NCTVM', num_person=15). 
Correctly set, I haven't met any problems when running experiments with your config and data. If you still have problems, would you please try to use dist_train.sh to launch jobs?

**Comment by FarzanehAskari** [comment]
Thank you @kennymckormick, for the tip. Setting the num_person in the train, valid, test as well as model config solved the issue! Here is my final config for feature reference. I appreciate your prompt support.

```
model = dict(
    type='SkeletonGCN',
    backbone=dict(
        type='STGCN',
        in_channels=3,
        edge_importance_weighting=True,
        graph_cfg=dict(layout='coco', strategy='spatial')),
    cls_head=dict(
        type='STGCNHead',
        num_classes=2,
        num_person=15,
        in_channels=256,
        loss_cls=dict(type='CrossEntropyLoss')),
    train_cfg=None,
    test_cfg=None)

dataset_type = 'PoseDataset'
ann_file_train = '.video_sample/train/train_sample_motus_h.pkl'
ann_file_val = '/./video_sample/valid/valid_sample_motus_h.pkl'
ann_file_test = './video_sample/test/test_sample_motus_h.pkl'
train_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM',num_person=15 ),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]
val_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM', num_person=15),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]
test_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM', num_person=15),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]
data = dict(
    videos_per_gpu=2,
    workers_per_gpu=2,
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix='',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix='',
        pipeline=val_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=ann_file_test,
        data_prefix='',
        pipeline=test_pipeline))

# optimizer
optimizer = dict(
    type='SGD', lr=0.0125, momentum=0.9, weight_decay=0.0001, nesterov=True)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='step', step=[10, 50])
total_epochs = 20
checkpoint_config = dict(interval=5)
evaluation = dict(interval=5, metrics=['top_k_accuracy'])
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])

# runtime settings
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './mmaction2/work_dirs/stgcn_test_15/'
load_from = './mmaction2/checkpoints/stgcn/stgcn_80e_ntu60_xsub_keypoint-e7bb9653.pth'
resume_from = None
workflow = [('train', 1)]
```

**Comment by kennymckormick** [comment]
Glad to help u.

**Comment by FarzanehAskari** [comment]
This [response](https://github.com/open-mmlab/mmaction2/issues/1412#issuecomment-1027737447) from @kennymckormick solved the issue.
