### ISSUE TITLE
get_flops.py doesn't work for spatial-temporal action detection models

### ISSUE THREAD

**Issue by coldmanck** [open-mmlab/mmaction2#1429]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

1. `get_flops.py` doesn't work for spatial-temporal action detection models while it works for action recognition models. Namely, it successfully prints results if I run for `configs/recognition/slowonly/slowonly_r50_8x8x1_256e_kinetics400_rgb.py`; however, an error as follows happened when I ran for `configs/detection/ava/slowonly_kinetics_pretrained_r50_4x16x1_20e_ava_rgb.py`.

2. For action recognition models, `get_flops.py` prints **exactly the same** numbers for GFlops and Params for SlowOnly-8x8 and SlowOnly-4x16: that is, **298.33 GFLOPs** and **Params 32.45 M**.  However, according to [the original SlowFast paper Table 2(g)](https://arxiv.org/pdf/1812.03982v1.pdf), SlowOnly-4x16 should be 20.9 GFLOPs while SllowOnly-8x8 should be 41.9 GFLOPs. Not only are the numbers different from the original paper, but also the same numbers for 8x8 and 4x16.

**Reproduction**

1. What command or script did you run?

```
python tools/analysis/get_flops.py configs/detection/ava/slowonly_kinetics_pretrained_r50_4x16x1_20e_ava_rgb.py --shape 1 3 32 340 256
```
prints the following error message:
```
Traceback (most recent call last):
  File "tools/analysis/get_flops.py", line 73, in <module>
    main()
  File "tools/analysis/get_flops.py", line 51, in main
    test_cfg=cfg.get('test_cfg'))
  File "/path/to/mmaction2/mmaction/models/builder.py", line 53, in build_recognizer
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/path/to/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/path/to/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/path/to/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'FastRCNN is not in the models registry'
```

and 

```
python tools/analysis/get_flops.py configs/recognition/slowonly/slowonly_r50_8x8x1_256e_kinetics400_rgb.py --shape 1 3 32 340 256
python tools/analysis/get_flops.py configs/recognition/slowonly/slowonly_r50_4x16x1_256e_kinetics400_rgb.py --shape 1 3 32 340 256
```

prints the same outputs:
```
Input shape: (1, 3, 32, 340, 256)
Flops: 298.33 GFLOPs
Params: 32.45 M
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

No

3. What dataset did you use?

AVA v2.1

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Debian 8.3.0-6) 8.3.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.10.0+cu111
OpenCV: 4.5.5
MMCV: 1.4.4
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMAction2: 0.21.0+276c1a7
```
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source] 
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Comment by coldmanck** [comment]
Hope can get any developer to help with my issue! Thanks

**Comment by kennymckormick** [comment]
Hi, @coldmanck , you can not get the accurate FLOPs of a spatio-temporal action detection model, since the FLOPs also depends on the number of proposals, which is dynamic. But I think you can use the mmcv API `get_model_complexity_info` to get the FLOPs of the detector backbone (which is the slowonly here). The backbone FLOPs is the majority of a whole detector.
