### ISSUE TITLE
Error in training 2s-AGCN

### ISSUE THREAD

**Issue by nyanmn** [open-mmlab/mmaction2#1430]
When I train 2s-AGCN, I have error as 
`RuntimeError: running_mean should contain 51 elements not 75`

What could be wrong in training?
My training command is

```
python tools/train.py configs/skeleton/2s-agcn/2sagcn_80e_ntu60_xsub_keypoint_3d.py \
    --work-dir work_dirs/2sagcn_80e_ntu60_xsub_keypoint_3d \
    --validate --seed 0 --deterministic
```

Full errors are
```
Traceback (most recent call last):
  File "tools/train.py", line 205, in <module>
    main()
  File "tools/train.py", line 201, in main
    meta=meta)
  File "/home/sysadmin/Nyan/mmaction2/mmaction/apis/train.py", line 204, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/sysadmin/Nyan/mmaction2/mmaction/models/skeleton_gcn/base.py", line 152, in train_step
    losses = self(skeletons, label, return_loss=True)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sysadmin/Nyan/mmaction2/mmaction/models/skeleton_gcn/base.py", line 106, in forward
    return self.forward_train(keypoint, label, **kwargs)
  File "/home/sysadmin/Nyan/mmaction2/mmaction/models/skeleton_gcn/skeletongcn.py", line 15, in forward_train
    x = self.extract_feat(skeletons)
  File "/home/sysadmin/Nyan/mmaction2/mmaction/models/skeleton_gcn/base.py", line 119, in extract_feat
    x = self.backbone(skeletons)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sysadmin/Nyan/mmaction2/mmaction/models/backbones/agcn.py", line 329, in forward
    x = self.data_bn(x)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py", line 2058, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 51 elements not 75

```

**Comment by gengenkai** [comment]
> When I train 2s-AGCN, I have error as `RuntimeError: running_mean should contain 51 elements not 75`
> 
> What could be wrong in training? My training command is
> 
> ```
> python tools/train.py configs/skeleton/2s-agcn/2sagcn_80e_ntu60_xsub_keypoint_3d.py \
>     --work-dir work_dirs/2sagcn_80e_ntu60_xsub_keypoint_3d \
>     --validate --seed 0 --deterministic
> ```
> 
> Full errors are
> 
> ```
> Traceback (most recent call last):
>   File "tools/train.py", line 205, in <module>
>     main()
>   File "tools/train.py", line 201, in main
>     meta=meta)
>   File "/home/sysadmin/Nyan/mmaction2/mmaction/apis/train.py", line 204, in train_model
>     runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
>   File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
>     self.run_iter(data_batch, train_mode=True, **kwargs)
>   File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
>     **kwargs)
>   File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
>     return self.module.train_step(*inputs[0], **kwargs[0])
>   File "/home/sysadmin/Nyan/mmaction2/mmaction/models/skeleton_gcn/base.py", line 152, in train_step
>     losses = self(skeletons, label, return_loss=True)
>   File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/sysadmin/Nyan/mmaction2/mmaction/models/skeleton_gcn/base.py", line 106, in forward
>     return self.forward_train(keypoint, label, **kwargs)
>   File "/home/sysadmin/Nyan/mmaction2/mmaction/models/skeleton_gcn/skeletongcn.py", line 15, in forward_train
>     x = self.extract_feat(skeletons)
>   File "/home/sysadmin/Nyan/mmaction2/mmaction/models/skeleton_gcn/base.py", line 119, in extract_feat
>     x = self.backbone(skeletons)
>   File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/sysadmin/Nyan/mmaction2/mmaction/models/backbones/agcn.py", line 329, in forward
>     x = self.data_bn(x)
>   File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
>     self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
>   File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py", line 2058, in batch_norm
>     training, momentum, eps, torch.backends.cudnn.enabled
> RuntimeError: running_mean should contain 51 elements not 75
> ```

Hi, nyanmn. If you did not modify the config file, the error maybe occured in the data you used. Please follow the script tools/data/skeleton/gen_ntu_rgb_raw.py to convert the ntu-rgb+d raw skeleton data into our format.

**Comment by kennymckormick** [comment]
You can follow the instructions from @gengenkai ~
