### ISSUE TITLE
AttributeError: 'EpochBasedRunner' object has no attribute 'data_loader'

### ISSUE THREAD

**Issue by zhangluustb** [open-mmlab/mmaction2#144]
> python tools/train.py configs/recognition/slowfast/slowfast_r50_4x8x1_256e_jester_rgb.py  --validate

error info:
Traceback (most recent call last):
  File "/export/mmaction2/tools/train.py", line 146, in <module>
    main()
  File "/export/mmaction2/tools/train.py", line 142, in main
    meta=meta)
  File "/export/mmaction2/mmaction/apis/train.py", line 111, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/zhanglu/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 103, in run
    self.call_hook('before_run')
  File "/home/zhanglu/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 298, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/zhanglu/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/lr_updater.py", line 114, in before_run
    epoch_len = len(runner.data_loader)
AttributeError: 'EpochBasedRunner' object has no attribute 'data_loader'

The same error will occur with the csn model.

**Comment by SuX97** [comment]
Could you please share the version of your mmcv being used? `epoch_len = len(runner.data_loader)` is called in `before_train_epoch` not in `before_run`.

**Comment by wykang** [comment]
I also the same error when I run slowfast model. 
My mmcv version is 1.0.5

The "epoch_len = len(runner.data_loader)" line is called when I use learning rate warmup options.

**Comment by SuX97** [comment]
I recommand you to use the latest mmcv and build it from souce. A possible explanation is that your mmcv still uses `epoch_len = len(runner.data_loader)` when `before_run` hook is called, before which the `self.data_loader` is not assigned. It is now fixed the latest mmcv. Chech [this](https://github.com/open-mmlab/mmcv/commit/edbbc0f2158ed140fadf91dd033133d60b03c437#diff-0476de76154341f1b8598ab91c8cdb0f) out.

**Comment by wykang** [comment]
Thank you for quick response. 
I resolved my problem with your suggestion!

**Comment by HHeron01** [comment]
Traceback (most recent call last):
  File "./tools/train.py", line 268, in <module>
    main()
  File "./tools/train.py", line 257, in main
    train_model(
  File "/workspace/temp_all/lane_project/mmdet3d/apis/train.py", line 349, in train_model
    train_detector(
  File "/workspace/temp_all/lane_project/mmdet3d/apis/train.py", line 324, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.max_loops)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 131, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 56, in train
    self.call_hook('after_train_epoch')
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/workspace/temp_all/lane_project/mmdet3d/core/hook/bevlane_visu.py", line 30, in after_train_epoch
    if runner.data_batch.get("maps"):
AttributeError: 'EpochBasedRunner' object has no attribute 'data_batch'
