### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices

### ISSUE THREAD

**Issue by jamiechoi1995** [open-mmlab/mmaction2#1456]
I got the following error when specifiying class_weight
```
Traceback (most recent call last):
  File "tools/train.py", line 200, in <module>
    main()
  File "tools/train.py", line 196, in main
    meta=meta)
  File "mmaction/apis/train.py", line 196, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "mmcv-1.3.17/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "mmcv-1.3.17/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "mmcv-1.3.17/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "mmcv-1.3.17/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "mmaction/models/recognizers/base.py", line 295, in train_step
    losses = self(imgs, label, return_loss=True, **aux_info)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "mmaction/models/recognizers/base.py", line 257, in forward
    return self.forward_train(imgs, label, **kwargs)
  File "mmaction/models/recognizers/recognizer3d.py", line 26, in forward_train
    loss_cls = self.cls_head.loss(cls_score, gt_labels, **kwargs)
  File "mmaction/models/heads/base.py", line 108, in loss
    loss_cls = self.loss_cls(cls_score, labels, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "mmaction/models/losses/base.py", line 37, in forward
    ret = self._forward(*args, **kwargs)
  File "mmaction/models/losses/cross_entropy_loss.py", line 61, in _forward
    lsm = lsm * self.class_weight.unsqueeze(0)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by kennymckormick** [comment]
Hi, Jamie, make sure you are using the latest master code~
