### ISSUE TITLE
AssertionError: Invalid device id

### ISSUE THREAD

**Issue by vasanth4224** [open-mmlab/mmaction2#1464]
Traceback (most recent call last):
  File "tools/train.py", line 200, in <module>
    main()
  File "tools/train.py", line 196, in main
    meta=meta)
  File "/media/a/Data-2/mmaction2/mmaction/apis/train.py", line 92, in train_model
    model.cuda(cfg.gpu_ids[0]), device_ids=cfg.gpu_ids)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 27, in __init__
    super(MMDataParallel, self).__init__(*args, dim=dim, **kwargs)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 142, in __init__
    _check_balance(self.device_ids)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 23, in _check_balance
    dev_props = _get_devices_properties(device_ids)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 459, in _get_devices_properties
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 459, in <listcomp>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 442, in _get_device_attr
    return get_member(torch.cuda)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 459, in <lambda>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/cuda/__init__.py", line 309, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id

when I start training custom posec3d and I got with this error. Anyone can help me to fix this error?

**Comment by dreamerlin** [comment]
You can Try distributed training

**Comment by kennymckormick** [comment]
For distributed training, please use ./tools/dist_train.sh {config} {num_gpu} {other_args}.

**Comment by vasanth4224** [comment]
(open-mmlab) a@r4611:/media/a/2TB/MMAction2/mmaction2$ bash tools/dist_train.sh configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py --work-dir work_dirs/slowonly_r50_u48_240e_ntu120_xsub_keypoint --validate --test-best --gpus 1 --seed 0 --deterministic
/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
Traceback (most recent call last):
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 564, in determine_local_world_size
    return int(nproc_per_node)
ValueError: invalid literal for int() with base 10: '--work-dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 709, in run
    config, cmd, cmd_args = config_from_args(args)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 617, in config_from_args
    nproc_per_node = determine_local_world_size(args.nproc_per_node)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 582, in determine_local_world_size
    raise ValueError(f"Unsupported nproc_per_node value: {nproc_per_node}")
ValueError: Unsupported nproc_per_node value: --work-dir

When I start distributed training, I got this error. could you please help me to fix this error?

**Comment by kennymckormick** [comment]
should be
bash tools/dist_train.sh configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py 1 --work-dir work_dirs/slowonly_r50_u48_240e_ntu120_xsub_keypoint --validate --test-best --seed 0 --deterministic
