### ISSUE TITLE
'new_backbone' is not in the models registry

### ISSUE THREAD

**Issue by JXIONG008** [open-mmlab/mmaction2#1467]
Thanks for your error report and we appreciate it a lot.
If you feel we have help you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

according to the instruction on https://mmaction2.readthedocs.io/en/latest/tutorials/5_new_modules.html to add a ResNeXt backbone

**Reproduction**

1. What command or script did you run?

```
python tools/train.py configs/recognition/tsm/resnext_test.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Define a new backbone (https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnext.py) and used in the config file :

```
_base_ = [
     '../../_base_/schedules/sgd_tsm_50e.py',
    '../../_base_/default_runtime.py'
]

# model settings
model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='ResNeXt',
        depth=50,
        num_stages=4,
        out_indices=(3, ),
        groups=32,
        width_per_group=4,
        style='pytorch'),
    cls_head=dict(
        type='TSMHead',
        num_classes=101,
        in_channels=2048,
        spatial_type='avg',
        consensus=dict(type='AvgConsensus', dim=1),
        dropout_ratio=0.4,
        init_std=0.01,
        num_segments=8),
    test_cfg=dict(average_clips=None)
)
    

```

3. What dataset did you use?
UCF101

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error traceback here.

```
File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmaction/models/recognizers/base.py", line 76, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmaction/models/builder.py", line 30, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'ResNeXt is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 201, in <module>
    main()
  File "tools/train.py", line 156, in main
    model = build_model(
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmaction/models/builder.py", line 71, in build_model
    return build_localizer(cfg)
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmaction/models/builder.py", line 63, in build_localizer
    return LOCALIZERS.build(cfg)
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "Recognizer3D: 'ResNeXt is not in the models registry'"
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by irvingzhang0512** [comment]
Do you add `@BACKBONES.register_module()` before your self-defined class?

```python
@BACKBONES.register_module()
class ResNeXt(nn.Module):

```

**Comment by JXIONG008** [comment]
> Do you add `@BACKBONES.register_module()` before your self-defined class?
> 
> ```python
> @BACKBONES.register_module()
> class ResNeXt(nn.Module):
> ```

yes, the relevant part is below:

`@BACKBONES.register_module()
class ResNeXt(ResNet):
    """ResNeXt backbone.

    Args:
        depth (int): Depth of resnet, from {18, 34, 50, 101, 152}.
        in_channels (int): Number of input image channels. Default: 3.
        num_stages (int): Resnet stages. Default: 4.
        groups (int): Group of resnext.
        base_width (int): Base width of resnext.
        strides (Sequence[int]): Strides of the first block of each stage.
        dilations (Sequence[int]): Dilation of each stage.
        out_indices (Sequence[int]): Output from which stages.
        style (str): `pytorch` or `caffe`. If set to "pytorch", the stride-two
            layer is the 3x3 conv layer, otherwise the stride-two layer is
            the first 1x1 conv layer.
        frozen_stages (int): Stages to be frozen (all param fixed). -1 means
            not freezing any parameters.
        norm_cfg (dict): dictionary to construct and config norm layer.
        norm_eval (bool): Whether to set norm layers to eval mode, namely,
            freeze running stats (mean and var). Note: Effect on Batch Norm
            and its variants only.
        with_cp (bool): Use checkpoint or not. Using checkpoint will save some
            memory while slowing down the training speed.
        zero_init_residual (bool): whether to use zero init for last norm layer
            in resblocks to let them behave as identity.
    """

    arch_settings = {
        50: (Bottleneck, (3, 4, 6, 3)),
        101: (Bottleneck, (3, 4, 23, 3)),
        152: (Bottleneck, (3, 8, 36, 3))
    }

    def __init__(self, groups=1, base_width=4, **kwargs):
        self.groups = groups
        self.base_width = base_width
        super(ResNeXt, self).__init__(**kwargs)

    

    def make_res_layer(self, **kwargs):
        """Pack all blocks in a stage into a ``ResLayer``"""
        return ResLayer(
            groups=self.groups,
            base_width=self.base_width,
            base_channels=self.base_channels,
            **kwargs)`

**Comment by JXIONG008** [comment]
> Do you add `@BACKBONES.register_module()` before your self-defined class?
> 
> ```python
> @BACKBONES.register_module()
> class ResNeXt(nn.Module):
> ```

I wonder how do I choose the model type in the config file, as the error says that "Recognizer3D: 'ResNeXt is not in the models registry'"? Or by right if I add @BACKBONES.register_module(), it should be automatically register?

**Comment by dreamerlin** [comment]
Try to add it in `__init__.py` ?

**Comment by JXIONG008** [comment]
> Try to add it in `__init__.py` ?

Thanks for your reply! I have strictly follow the instruction listed:
1. add the `@BACKBONES.register_module()` in my self-defined backbone;
2. add in `__init__.py` (both import and `_all_`;
3. add in the config file

The error msg came out when I try to train the model

**Comment by gengenkai** [comment]
> * e run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
> * You may add addition that may be helpful for locating the problem, such as
>   
>   * How you installed PyTorch [e.g.,

Hi. Have you added the custom module in the models/__init__.py and models/backbones/__int__,py? 
You could refer to this pr https://github.com/open-mmlab/mmaction2/pull/1123/files for adding your custom module.

**Comment by gengenkai** [comment]
> > Try to add it in `__init__.py` ?
> 
> Thanks for your reply! I have strictly follow the instruction listed:
> 
> 1. add the `@BACKBONES.register_module()` in my self-defined backbone;
> 2. add in `__init__.py` (both import and `_all_`;
> 3. add in the config file
> 
> The error msg came out when I try to train the model. I wonder if there is any way to tell if I have successfully registered my new backbone, or if I still need to import the file somewhere?

Hi. Have you added the custom module in the models/__init__.py and models/backbones/__init__.py?
You could refer to this pr https://github.com/open-mmlab/mmaction2/pull/1123/files for adding your custom module.

**Comment by JXIONG008** [comment]
> Hi, yes.
1. models/backbones/int
<img width="737" alt="image" src="https://user-images.githubusercontent.com/44230458/155274248-d4736a23-09ea-425f-b3d2-10c37e473eba.png">
2. models/init.py
![image](https://user-images.githubusercontent.com/44230458/155274421-c4da941a-7420-4773-86ee-f086512661f2.png)

**Comment by dreamerlin** [comment]
> Thanks for your error report and we appreciate it a lot. If you feel we have help you, give us a STAR! laughing
> 
> **Checklist**
> 
> 1. I have searched related issues but cannot get the expected help.
> 2. The bug has not been fixed in the latest version.
> 
> **Describe the bug**
> 
> according to the instruction on https://mmaction2.readthedocs.io/en/latest/tutorials/5_new_modules.html to add a ResNeXt backbone
> 
> **Reproduction**
> 
> 1. What command or script did you run?
> 
> ```
> python tools/train.py configs/recognition/tsm/resnext_test.py
> ```
> 
> 2. Did you make any modifications on the code or config? Did you understand what you have modified?
>    Define a new backbone (https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnext.py) and used in the config file, no error or warning triggered
> 
> ```
> _base_ = [
>      '../../_base_/schedules/sgd_tsm_50e.py',
>     '../../_base_/default_runtime.py'
> ]
> 
> # model settings
> model = dict(
>     type='Recognizer3D',
>     backbone=dict(
>         type='ResNeXt',
>         depth=50,
>         num_stages=4,
>         out_indices=(3, ),
>         groups=32,
>         width_per_group=4,
>         style='pytorch'),
>     cls_head=dict(
>         type='TSMHead',
>         num_classes=101,
>         in_channels=2048,
>         spatial_type='avg',
>         consensus=dict(type='AvgConsensus', dim=1),
>         dropout_ratio=0.4,
>         init_std=0.01,
>         num_segments=8),
>     test_cfg=dict(average_clips=None)
> )
>     
> ```
> 
> 3. What dataset did you use?
>    UCF101
> 
> **Environment**
> 
> 1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
> 2. You may add addition that may be helpful for locating the problem, such as
>    
>    * How you installed PyTorch [e.g., pip, conda, source]
>    * Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
> 
> **Error traceback**
> 
> If applicable, paste the error traceback here.
> 
> ```
> File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
>     return obj_cls(**args)
>   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmaction/models/recognizers/base.py", line 76, in __init__
>     self.backbone = builder.build_backbone(backbone)
>   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmaction/models/builder.py", line 30, in build_backbone
>     return BACKBONES.build(cfg)
>   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
>     return self.build_func(*args, **kwargs, registry=self)
>   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
>     return build_from_cfg(cfg, registry, default_args)
>   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
>     raise KeyError(
> KeyError: 'ResNeXt is not in the models registry'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "tools/train.py", line 201, in <module>
>     main()
>   File "tools/train.py", line 156, in main
>     model = build_model(
>   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmaction/models/builder.py", line 71, in build_model
>     return build_localizer(cfg)
>   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmaction/models/builder.py", line 63, in build_localizer
>     return LOCALIZERS.build(cfg)
>   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
>     return self.build_func(*args, **kwargs, registry=self)
>   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
>     return build_from_cfg(cfg, registry, default_args)
>   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
>     raise type(e)(f'{obj_cls.__name__}: {e}')
> KeyError: "Recognizer3D: 'ResNeXt is not in the models registry'"
> ```
> 
> **Bug fix**
> 
> If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

I found that your environment call the mmaction2 package rather than your projects

maybe you can try

export PYTHONPATH=`pwd`:$PYTHONPATH

in your project root dir

**Comment by JXIONG008** [comment]
> > Thanks for your error report and we appreciate it a lot. If you feel we have help you, give us a STAR! laughing
> > **Checklist**
> > 
> > 1. I have searched related issues but cannot get the expected help.
> > 2. The bug has not been fixed in the latest version.
> > 
> > **Describe the bug**
> > according to the instruction on https://mmaction2.readthedocs.io/en/latest/tutorials/5_new_modules.html to add a ResNeXt backbone
> > **Reproduction**
> > 
> > 1. What command or script did you run?
> > 
> > ```
> > python tools/train.py configs/recognition/tsm/resnext_test.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Did you make any modifications on the code or config? Did you understand what you have modified?
> >    Define a new backbone (https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnext.py) and used in the config file, no error or warning triggered
> > 
> > ```
> > _base_ = [
> >      '../../_base_/schedules/sgd_tsm_50e.py',
> >     '../../_base_/default_runtime.py'
> > ]
> > 
> > # model settings
> > model = dict(
> >     type='Recognizer3D',
> >     backbone=dict(
> >         type='ResNeXt',
> >         depth=50,
> >         num_stages=4,
> >         out_indices=(3, ),
> >         groups=32,
> >         width_per_group=4,
> >         style='pytorch'),
> >     cls_head=dict(
> >         type='TSMHead',
> >         num_classes=101,
> >         in_channels=2048,
> >         spatial_type='avg',
> >         consensus=dict(type='AvgConsensus', dim=1),
> >         dropout_ratio=0.4,
> >         init_std=0.01,
> >         num_segments=8),
> >     test_cfg=dict(average_clips=None)
> > )
> >     
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. What dataset did you use?
> >    UCF101
> > 
> > **Environment**
> > 
> > 1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
> > 2. You may add addition that may be helpful for locating the problem, such as
> >    
> >    * How you installed PyTorch [e.g., pip, conda, source]
> >    * Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
> > 
> > **Error traceback**
> > If applicable, paste the error traceback here.
> > ```
> > File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
> >     return obj_cls(**args)
> >   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmaction/models/recognizers/base.py", line 76, in __init__
> >     self.backbone = builder.build_backbone(backbone)
> >   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmaction/models/builder.py", line 30, in build_backbone
> >     return BACKBONES.build(cfg)
> >   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
> >     return self.build_func(*args, **kwargs, registry=self)
> >   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
> >     return build_from_cfg(cfg, registry, default_args)
> >   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
> >     raise KeyError(
> > KeyError: 'ResNeXt is not in the models registry'
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "tools/train.py", line 201, in <module>
> >     main()
> >   File "tools/train.py", line 156, in main
> >     model = build_model(
> >   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmaction/models/builder.py", line 71, in build_model
> >     return build_localizer(cfg)
> >   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmaction/models/builder.py", line 63, in build_localizer
> >     return LOCALIZERS.build(cfg)
> >   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
> >     return self.build_func(*args, **kwargs, registry=self)
> >   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
> >     return build_from_cfg(cfg, registry, default_args)
> >   File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
> >     raise type(e)(f'{obj_cls.__name__}: {e}')
> > KeyError: "Recognizer3D: 'ResNeXt is not in the models registry'"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Bug fix**
> > If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!
> 
> I found that your environment call the mmaction2 package rather than your projects
> 
> maybe you can try
> 
> ```
> export PYTHONPATH=`pwd`:$PYTHONPATH
> ```
> 
> in your project root dir

thanks for your reply, though this didn't work.
I resolved the issue by trying the following commands in my root dir, kind of like a re-install?
`
python setup.py develop
pip install -v -e .
`

**Comment by dreamerlin** [comment]
Yep, it seems you didn't install the local repo. BTW, that command works for me.
