### ISSUE TITLE
ResNeXt: __init__() got an unexpected keyword argument 'expansion'

### ISSUE THREAD

**Issue by JXIONG008** [open-mmlab/mmaction2#1468]
**Checklist**

1. I have searched related issues but cannot get the expected help. ☑️
2. The bug has not been fixed in the latest version. ☑️

**Describe the bug**

tried mmcl.resnext before, but want to further modify the structure, hence register a new backbone for ResNeXt.

**Reproduction**

1. What command or script did you run?

```
python tools/train.py configs/recognition/tsm/resnext_test.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
backbone code from here : https://github.com/open-mmlab/mmclassification/blob/master/mmcls/models/backbones/resnext.py

3. What dataset did you use?

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
- Have tried to import backbone from mmcl directly, worked fine
- Tried https://github.com/open-mmlab/mmaction2/issues/1382 , seems not relevant

**Error traceback**

If applicable, paste the error traceback here.

```
2022-02-23 21:27:55,490 - mmaction - INFO - Set random seed to 534571979, deterministic: False
Traceback (most recent call last):
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/fyp/FYP_Jingxi/mmaction2/mmaction/models/backbones/resnext.py", line 797, in __init__
    super(ResNeXt, self).__init__(depth, **kwargs)
  File "/home/fyp/FYP_Jingxi/mmaction2/mmaction/models/backbones/resnext.py", line 524, in __init__
    res_layer = self.make_res_layer(
  File "/home/fyp/FYP_Jingxi/mmaction2/mmaction/models/backbones/resnext.py", line 800, in make_res_layer
    return ResLayer(
  File "/home/fyp/FYP_Jingxi/mmaction2/mmaction/models/backbones/resnext.py", line 379, in __init__
    block(
  File "/home/fyp/FYP_Jingxi/mmaction2/mmaction/models/backbones/resnext.py", line 696, in __init__
    super(Bottleneck, self).__init__(in_channels, out_channels, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'expansion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/fyp/FYP_Jingxi/mmaction2/mmaction/models/recognizers/base.py", line 76, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/home/fyp/FYP_Jingxi/mmaction2/mmaction/models/builder.py", line 30, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: ResNeXt: __init__() got an unexpected keyword argument 'expansion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 201, in <module>
    main()
  File "tools/train.py", line 156, in main
    model = build_model(
  File "/home/fyp/FYP_Jingxi/mmaction2/mmaction/models/builder.py", line 71, in build_model
    return build_localizer(cfg)
  File "/home/fyp/FYP_Jingxi/mmaction2/mmaction/models/builder.py", line 63, in build_localizer
    return LOCALIZERS.build(cfg)
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: Recognizer2D: ResNeXt: __init__() got an unexpected keyword argument 'expansion'
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by c-liangyu** [comment]
Please give your config file and show WHERE and WHY you pass the argument `'expansion'`
