### ISSUE TITLE
ValueError: Unsupported nproc_per_node value: --work-dir

### ISSUE THREAD

**Issue by vasanth4224** [open-mmlab/mmaction2#1476]
(open-mmlab) a@r4611:/media/a/2TB/MMAction2/mmaction2$ bash tools/dist_train.sh configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoints.py --work-dir work_dirs/slowonly_r50_u48_240e_ntu120_xsub_keypoints --validate --test-best --gpus 1 --seed 0 --deterministic 
/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
Traceback (most recent call last):
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 564, in determine_local_world_size
    return int(nproc_per_node)
ValueError: invalid literal for int() with base 10: '--work-dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 709, in run
    config, cmd, cmd_args = config_from_args(args)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 617, in config_from_args
    nproc_per_node = determine_local_world_size(args.nproc_per_node)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 582, in determine_local_world_size
    raise ValueError(f"Unsupported nproc_per_node value: {nproc_per_node}")
ValueError: Unsupported nproc_per_node value: --work-dir

When I execute dist_train, I got this error. Anyone can help me to fix this error?

**Comment by dreamerlin** [comment]
https://github.com/open-mmlab/mmaction2/blob/master/tools/dist_train.sh#L4

The second argument should be GPUS number

**Comment by vasanth4224** [comment]
(open-mmlab) a@r4611:/media/a/2TB/MMAction2/mmaction2$ bash tools/dist_train.sh configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py --work-dir work_dirs/slowonly_r50_u48_240e_ntu120_xsub_keypoint --validate --test-best --gpus 1 --seed 0 --deterministic
/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects --local_rank argument to be set, please
change it to read from os.environ['LOCAL_RANK'] instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

FutureWarning,
Traceback (most recent call last):
File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 564, in determine_local_world_size
return int(nproc_per_node)
ValueError: invalid literal for int() with base 10: '--work-dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in
main()
File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
launch(args)
File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
run(args)
File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 709, in run
config, cmd, cmd_args = config_from_args(args)
File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 617, in config_from_args
nproc_per_node = determine_local_world_size(args.nproc_per_node)
File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 582, in determine_local_world_size
raise ValueError(f"Unsupported nproc_per_node value: {nproc_per_node}")
ValueError: Unsupported nproc_per_node value: --work-dir

 could you please help me to fix this error?

**Comment by dreamerlin** [comment]
bash tools/dist_train.sh configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoints.py 1 --work-dir work_dirs/slowonly_r50_u48_240e_ntu120_xsub_keypoints --validate --test-best --seed 0 --deterministic

**Comment by dreamerlin** [comment]
You can give us an star if you find it is helpful~

**Comment by vasanth4224** [comment]
(mmlab) a@r4611:/media/a/2TB/MMAction2/mmaction2$ bash tools/dist_train.sh configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoints.py 1 --work-dir work_dirs/slowonly_r50_u48_240e_ntu120_xsub_keypoints --validate --test-best --seed 0 --deterministic
/home/a/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
Traceback (most recent call last):
  File "/home/a/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 564, in determine_local_world_size
    return int(nproc_per_node)
ValueError: invalid literal for int() with base 10: 'configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoints.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a/anaconda3/envs/mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/a/anaconda3/envs/mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/a/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/a/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/a/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/a/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 709, in run
    config, cmd, cmd_args = config_from_args(args)
  File "/home/a/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 617, in config_from_args
    nproc_per_node = determine_local_world_size(args.nproc_per_node)
  File "/home/a/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 582, in determine_local_world_size
    raise ValueError(f"Unsupported nproc_per_node value: {nproc_per_node}")
ValueError: Unsupported nproc_per_node value: configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoints.py

'dist_train' also not working for me.

**Comment by vasanth4224** [comment]
python tools/train.py configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoints.py --work-dir work_dirs/slowonly_r50_u48_240e_ntu120_xsub_keypoints --validate --gpus 1 --seed 0 --deterministic  

without '--test-best' the above code is working. Thank you. could you please help me how to find best training file (.pth)?

**Comment by dreamerlin** [comment]
We will provide them to you (after ECCV ddl)

**Comment by kennymckormick** [comment]
> (mmlab) a@r4611:/media/a/2TB/MMAction2/mmaction2$ bash tools/dist_train.sh configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoints.py 1 --work-dir work_dirs/slowonly_r50_u48_240e_ntu120_xsub_keypoints --validate --test-best --seed 0 --deterministic /home/a/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated and will be removed in future. Use torchrun. Note that --use_env is set by default in torchrun. If your script expects `--local_rank` argument to be set, please change it to read from `os.environ['LOCAL_RANK']` instead. See https://pytorch.org/docs/stable/distributed.html#launch-utility for further instructions
> 
> FutureWarning, Traceback (most recent call last): File "/home/a/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 564, in determine_local_world_size return int(nproc_per_node) ValueError: invalid literal for int() with base 10: 'configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoints.py'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/a/anaconda3/envs/mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "/home/a/anaconda3/envs/mmlab/lib/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals) File "/home/a/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in main() File "/home/a/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main launch(args) File "/home/a/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch run(args) File "/home/a/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 709, in run config, cmd, cmd_args = config_from_args(args) File "/home/a/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 617, in config_from_args nproc_per_node = determine_local_world_size(args.nproc_per_node) File "/home/a/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 582, in determine_local_world_size raise ValueError(f"Unsupported nproc_per_node value: {nproc_per_node}") ValueError: Unsupported nproc_per_node value: configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoints.py
> 
> 'dist_train' also not working for me.

Are you sure you can not run this command successfully: 
```bash
bash tools/dist_train.sh configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py --work-dir work_dirs/slowonly_r50_u48_240e_ntu120_xsub_keypoint --validate --test-best --gpus 1 --seed 0 --deterministic
```

I can run it. Does ur machine have at least one GPU?

**Comment by AIzealotwu** [comment]
bash tools/dist_train.sh configs/mask_rcnn_semi_auto_germinal_center/mask-rcnn_r101-caffe_fpn_ms-poly-3x_germinal_center.py --work-dir work_dirs/slowonly_r50_u48_240e_ntu120_xsub_keypoint -- 
validate --test-best --gpus 8 --seed 0 --deterministic\
/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py:183: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 654, in determine_local_world_size
    return int(nproc_per_node)
ValueError: invalid literal for int() with base 10: '--work-dir'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 198, in <module>
    main()
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 194, in main
    launch(args)
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 179, in launch
    run(args)
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 869, in run
    config, cmd, cmd_args = config_from_args(args)
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 754, in config_from_args
    nproc_per_node = determine_local_world_size(args.nproc_per_node)
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 681, in determine_local_world_size
    raise ValueError(f"Unsupported nproc_per_node value: {nproc_per_node}") from e
ValueError: Unsupported nproc_per_node value: --work-dir
> ls
Command 'validate' not found, did you mean:
  command 'svalidate' from deb xmlbeans (3.0.2-1)
Try: apt install <deb name>
(openmmlab) xuym@ps:~/mmdetection$ bash tools/dist_train.sh configs/mask_rcnn_semi_auto_germinal_center/mask-rcnn_r101-caffe_fpn_ms-poly-3x_germinal_center.py --work-dir work_dirs/slowonly_r50_u48_240e_ntu120_xsub_keypoint -- 
validate --test-best --gpus 8 --seed 0 --deterministic\
/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py:183: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 654, in determine_local_world_size
    return int(nproc_per_node)
ValueError: invalid literal for int() with base 10: '--work-dir'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 198, in <module>
    main()
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 194, in main
    launch(args)
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 179, in launch
    run(args)
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 869, in run
    config, cmd, cmd_args = config_from_args(args)
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 754, in config_from_args
    nproc_per_node = determine_local_world_size(args.nproc_per_node)
  File "/home/xuym/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 681, in determine_local_world_size
    raise ValueError(f"Unsupported nproc_per_node value: {nproc_per_node}") from e
ValueError: Unsupported nproc_per_node value: --work-dir

This could not work in my machine. Could you find out what kind of problems happended?

**Comment by AIzealotwu** [comment]
You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module

After adding my customed pipline.py 
something wrong did happen.
