### ISSUE TITLE
demo_video_structuralize.py AttributeError(f'Module {name} not found')

### ISSUE THREAD

**Issue by vasanth4224** [open-mmlab/mmaction2#1504]
(open-mmlab) C:\Users\admin\Desktop\mmaction2\mmaction2>python demo/demo_video_structuralize.py
load checkpoint from http path: http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth
Performing Human Detection for each frame
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 300/300, 10.9 task/s, elapsed: 28s, ETA:     0sUse rgb-based recognition
load checkpoint from http path: https://download.openmmlab.com/mmaction/recognition/tsn/tsn_r50_1x1x3_100e_kinetics400_rgb/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth
Traceback (most recent call last):
  File "c:\users\admin\desktop\mmaction2\mmaction2\mmaction\core\hooks\output.py", line 46, in register
    layer = rgetattr(module, name)
  File "c:\users\admin\desktop\mmaction2\mmaction2\mmaction\core\hooks\output.py", line 70, in rgetattr
    return functools.reduce(_getattr, [obj] + attr.split('.'))
  File "c:\users\admin\desktop\mmaction2\mmaction2\mmaction\core\hooks\output.py", line 68, in _getattr
    return getattr(obj, attr, *args)
  File "C:\Users\admin\anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'Recognizer2D' object has no attribute 'C:/Users/admin/Desktop/mmaction2/mmaction2/tools/data/kinetics/label_map_k400'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo/demo_video_structuralize.py", line 797, in <module>
    main()
  File "demo/demo_video_structuralize.py", line 726, in main
    action_result = rgb_based_action_recognition(args)
  File "demo/demo_video_structuralize.py", line 498, in rgb_based_action_recognition
    args.label_map)
  File "c:\users\admin\desktop\mmaction2\mmaction2\mmaction\apis\inference.py", line 179, in inference_recognizer
    with OutputHook(model, outputs=outputs, as_tensor=as_tensor) as h:
  File "c:\users\admin\desktop\mmaction2\mmaction2\mmaction\core\hooks\output.py", line 23, in __init__
    self.register(module)
  File "c:\users\admin\desktop\mmaction2\mmaction2\mmaction\core\hooks\output.py", line 49, in register
    raise AttributeError(f'Module {name} not found')
AttributeError: Module C:/Users/admin/Desktop/mmaction2/mmaction2/tools/data/kinetics/label_map_k400.txt not found

Anyone can help me to fix this error?

**Comment by dreamerlin** [comment]
Cause by a BC breaking, we fix it in https://github.com/open-mmlab/mmaction2/pull/1507

**Comment by vasanth4224** [comment]
Thank you @dreamerlin . It's working.
