### ISSUE TITLE
AttributeError: 'MMDistributedDataParallel' object has no attribute '_sync_params'

### ISSUE THREAD

**Issue by michael-camilleri** [open-mmlab/mmaction2#1536]
When trying to train models I keep getting this error:

 AttributeError: 'MMDistributedDataParallel' object has no attribute '_sync_params'

I am running through torch.distributed.launch (so distributed training), in my case with 8 gpus and sometimes with 1 and same thing happens. Here is the stack trace:

Traceback (most recent call last):
  File "tools/train.py", line 222, in <module>
    main()
  File "tools/train.py", line 218, in main
    meta=meta)
  File "/mnt/cdtds_cluster_home/code/MMAction/mmaction/apis/train.py", line 228, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/mnt/cdtds_cluster_home/code/MMCV/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/mnt/cdtds_cluster_home/code/MMCV/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/mnt/cdtds_cluster_home/code/MMCV/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/mnt/cdtds_cluster_home/code/MMCV/mmcv/parallel/distributed.py", line 48, in train_step
    self._sync_params()
  File "/home/miniconda3/envs/py3mma/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1186, in __getattr__
    type(self).__name__, name))
AttributeError: 'MMDistributedDataParallel' object has no attribute '_sync_params'
/home/miniconda3/envs/py3mma/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 34855) of binary: /home/miniconda3/envs/py3mma/bin/python
Traceback (most recent call last):
  File "/home/miniconda3/envs/py3mma/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/miniconda3/envs/py3mma/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/miniconda3/envs/py3mma/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/miniconda3/envs/py3mma/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/miniconda3/envs/py3mma/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/miniconda3/envs/py3mma/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/home/miniconda3/envs/py3mma/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/miniconda3/envs/py3mma/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED

Thanks

**Comment by dreamerlin** [comment]
https://github.com/open-mmlab/mmaction2/issues/1525

**Comment by michael-camilleri** [comment]
Thanks. Following that.

**Comment by michael-camilleri** [comment]
Now I am getting a segmentation fault when I try to generate the feature-bank: how can I debug through that trace?

**Comment by kennymckormick** [comment]
@michael-camilleri  Could you demonstrate the situation more clearly? For example, at which step the segmentation fault is thrown out?
