### ISSUE TITLE
ntu_pose_extraction.py KeyError: 'center'

### ISSUE THREAD

**Issue by siyangbing** [open-mmlab/mmaction2#1621]
when i use python ntu_pose_extraction.py /home/bing/视频/test/11/1.mp4 /home/bing/视频/test/11.pkl to create pkl , it show error! @[bit-scientist](https://github.com/bit-scientist)

  File "/home/bing/project/mmaction2/tools/data/skeleton/ntu_pose_extraction.py", line 346, in <module>
    anno = ntu_pose_extraction(args.video, args.skip_postproc)
  File "/home/bing/project/mmaction2/tools/data/skeleton/ntu_pose_extraction.py", line 315, in ntu_pose_extraction
    pose_results = pose_inference(args, frame_paths, det_results)
  File "/home/bing/project/mmaction2/tools/data/skeleton/ntu_pose_extraction.py", line 303, in pose_inference
    pose = inference_top_down_pose_model(model, f, d, format='xyxy')[0]
  File "/home/bing/anaconda3/envs/mm_action/lib/python3.9/site-packages/mmcv/utils/misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  File "/home/bing/anaconda3/envs/mm_action/lib/python3.9/site-packages/mmpose/apis/inference.py", line 380, in inference_top_down_pose_model
    poses, heatmap = _inference_single_pose_model(
  File "/home/bing/anaconda3/envs/mm_action/lib/python3.9/site-packages/mmpose/apis/inference.py", line 247, in _inference_single_pose_model
    data = test_pipeline(data)
  File "/home/bing/anaconda3/envs/mm_action/lib/python3.9/site-packages/mmpose/datasets/pipelines/shared_transform.py", line 107, in __call__
    data = t(data)
  File "/home/bing/anaconda3/envs/mm_action/lib/python3.9/site-packages/mmpose/datasets/pipelines/top_down_transform.py", line 289, in __call__
    c = results['center']
KeyError: 'center'

Process finished with exit code 1

**Comment by nngg11** [comment]
**Same problem here**

I have the same problem. But in my case I'm using the UCF-101 dataset samples. The command I call is:

`python demo/demo_skeleton.py demo/ucf_sample.avi demo/ucf_sample_out.mp4 --config configs/skeleton/posec3d/slowonly_kinetics400_pretrained_r50_u48_120e_ucf101_split1_keypoint.py --checkpoint checkpoints/slowonly_kinetics400_pretrained_r50_u48_120e_ucf101_split1_keypoint-cae8aa4a.pth --det-config demo/faster_rcnn_r50_fpn_2x_coco.py --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth --pose-config demo/hrnet_w32_coco_256x192.py --pose-checkpoint https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth --label-map tools/data/ucf101/label_map.txt`

And the output of the program is:

```
load checkpoint from local path: checkpoints/slowonly_kinetics400_pretrained_r50_u48_120e_ucf101_split1_keypoint-cae8aa4a.pth
load checkpoint from http path: http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth
Performing Human Detection for each frame
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 206/206, 6.1 task/s, elapsed: 34s, ETA:     0sload checkpoint from http path: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth
Performing Human Pose Estimation for each frame
[                                                  ] 0/206, elapsed: 0s, ETA:Traceback (most recent call last):
  File "demo/demo_skeleton.py", line 253, in <module>
    main()
  File "demo/demo_skeleton.py", line 205, in main
    pose_results = pose_inference(args, frame_paths, det_results)
  File "demo/demo_skeleton.py", line 174, in pose_inference
    pose = inference_top_down_pose_model(model, f, d, format='xyxy')[0]
  File "C:\Users\usuario\anaconda3\envs\testing\lib\site-packages\mmcv\utils\misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  File "C:\Users\usuario\anaconda3\envs\testing\lib\site-packages\mmpose\apis\inference.py", line 380, in inference_top_down_pose_model
    poses, heatmap = _inference_single_pose_model(
  File "C:\Users\usuario\anaconda3\envs\testing\lib\site-packages\mmpose\apis\inference.py", line 247, in _inference_single_pose_model
    data = test_pipeline(data)
  File "C:\Users\usuario\anaconda3\envs\testing\lib\site-packages\mmpose\datasets\pipelines\shared_transform.py", line 107, in __call__
    data = t(data)
  File "C:\Users\usuario\anaconda3\envs\testing\lib\site-packages\mmpose\datasets\pipelines\top_down_transform.py", line 289, in __call__
    c = results['center']
KeyError: 'center'
```

**Comment by nngg11** [comment]
I think we need to download the COCO dataset (skeleton version) and add the files to $MMACTION2/data/coco/, just following the instructions in https://github.com/open-mmlab/mmpose/blob/master/docs/en/tasks/2d_body_keypoint.md#coco. I will try this and let you know. In the meantime, let's see if another person knows or finds the solution.

**Comment by nngg11** [comment]
I have found the error. You just need to run the following commands (I'm assuming you have the last version of mmpose installed, which is the 0.26.0):

`pip uninstall mmpose
pip install mmpose==0.25.1`

And it worked!

This is due the change in https://github.com/open-mmlab/mmpose/blob/dev-0.25/mmpose/apis/inference.py#L250 and https://github.com/open-mmlab/mmpose/blob/dev-0.26/mmpose/apis/inference.py#L213. Note the changes in the `data` dictionary, and thus giving our error.

Let me know if it fixed for you as well @siyangbing 👍.

**Comment by nngg11** [comment]
I have found the error. You just need to run the following commands (I'm assuming you have the last version of mmpose installed, which is the 0.26.0):

`pip uninstall mmpose`
`pip install mmpose==0.25.1`

And it worked!

This is due the change in https://github.com/open-mmlab/mmpose/blob/dev-0.25/mmpose/apis/inference.py#L250 and https://github.com/open-mmlab/mmpose/blob/dev-0.26/mmpose/apis/inference.py#L213. Note the changes in the data dictionary, and thus giving our error.

Let me know if it fixed for you as well @siyangbing 👍.

**Comment by siyangbing** [comment]
> I have found the error. You just need to run the following commands (I'm assuming you have the last version of mmpose installed, which is the 0.26.0):
> 
> `pip uninstall mmpose` `pip install mmpose==0.25.1`
> 
> And it worked!
> 
> This is due the change in https://github.com/open-mmlab/mmpose/blob/dev-0.25/mmpose/apis/inference.py#L250 and https://github.com/open-mmlab/mmpose/blob/dev-0.26/mmpose/apis/inference.py#L213. Note the changes in the data dictionary, and thus giving our error.
> 
> Let me know if it fixed for you as well @siyangbing +1.

it works, hope mmpose==0.26.0 will fix it.
