### ISSUE TITLE
download_videos.sh kinetics400, but File "download.py" IndexError: list index out of rang

### ISSUE THREAD

**Issue by wolf-bailang** [open-mmlab/mmaction2#1634]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

I am using this command "bash download_videos.sh kinetics400" on ubuntu 20.04. But it prompts "File "download.py" IndexError: list index out of rang". The result is that all the action name files in the kinetics400/videos_train/ and kinetics400/videos_val folders are empty, for example, there is no corresponding video file in /zumba/.

Why is the video file not being downloaded?

Error Traceback
###########
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/cpslabzjb/anaconda3/envs/ActionCLIPpy3.8/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/cpslabzjb/anaconda3/envs/ActionCLIPpy3.8/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/cpslabzjb/anaconda3/envs/ActionCLIPpy3.8/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 593, in __call__
    return self.func(*args, **kwargs)
  File "/home/cpslabzjb/anaconda3/envs/ActionCLIPpy3.8/lib/python3.8/site-packages/joblib/parallel.py", line 252, in __call__
    return [func(*args, **kwargs)
  File "/home/cpslabzjb/anaconda3/envs/ActionCLIPpy3.8/lib/python3.8/site-packages/joblib/parallel.py", line 252, in <listcomp>
    return [func(*args, **kwargs)
  File "download.py", line 139, in download_clip_wrapper
    downloaded, log = download_clip(
  File "download.py", line 108, in download_clip
    tmp_filename = glob.glob('%s*' % tmp_filename.split('.')[0])[0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "download.py", line 232, in <module>
    main(**vars(p.parse_args()))
  File "download.py", line 194, in main
    status_list = Parallel(
  File "/home/cpslabzjb/anaconda3/envs/ActionCLIPpy3.8/lib/python3.8/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/home/cpslabzjb/anaconda3/envs/ActionCLIPpy3.8/lib/python3.8/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/cpslabzjb/anaconda3/envs/ActionCLIPpy3.8/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 540, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/cpslabzjb/anaconda3/envs/ActionCLIPpy3.8/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/home/cpslabzjb/anaconda3/envs/ActionCLIPpy3.8/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
IndexError: list index out of range
###########

**Comment by Dai-Wenxun** [comment]
Hi, @wolf-bailang, 
This is because the original video is not downloaded successfully, please check your network status, then try again.

**Comment by wolf-bailang** [comment]
OK, thanks!
