### ISSUE TITLE
Cannot Infer long-term feature bank for LFB

### ISSUE THREAD

**Issue by Xylobyte** [open-mmlab/mmaction2#1635]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

I run into a strange error when trying to infer the long term feature bank for LFB.

**Reproduction**

1. As described in the LFB README "Train" section part a, I use the [slowonly_r50_4x16x1 checkpoint](https://download.openmmlab.com/mmaction/detection/ava/slowonly_kinetics_pretrained_r50_4x16x1_20e_ava_rgb/slowonly_kinetics_pretrained_r50_4x16x1_20e_ava_rgb_20201217-40061d5f.pth) as well as the lfb_slowonly_r50_ava_infer.py config. I ran the following 

```
python tools/test.py configs/detection/lfb/lfb_slowonly_r50_ava_infer.py checkpoints/lfb/slowonly_kinetics_pretrained_r50_4x16x1_20e_ava_rgb_20201217-40061d5f.pth --eval mAP
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No.
4. What dataset did you use?
AVA 2.1 was the intended dataset but I didn't get that far.

**Environment**
```
sys.platform: linux
Python: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA RTX A6000
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.5, V11.5.119
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.11.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.12.0
OpenCV: 4.5.5
MMCV: 1.5.0
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 11.5
MMAction2: 0.24.0+c7b45f0
```
Packages installed with Anaconda and pip

**Error traceback**

```
/ascldap/users/dxgrieg/mmaction2/mmaction/utils/setup_env.py:32: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/ascldap/users/dxgrieg/mmaction2/mmaction/utils/setup_env.py:42: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(

Inferring LFB...
load checkpoint from local path: checkpoints/lfb/slowonly_kinetics_pretrained_r50_4x16x1_20e_ava_rgb_20201217-40061d5f.pth
Traceback (most recent call last):
  File "/ascldap/users/dxgrieg/mmaction2/tools/test.py", line 371, in <module>
    main()
  File "/ascldap/users/dxgrieg/mmaction2/tools/test.py", line 356, in main
    outputs = inference_pytorch(args, cfg, distributed, data_loader)
  File "/ascldap/users/dxgrieg/mmaction2/tools/test.py", line 161, in inference_pytorch
    model, default_device, default_args=dict(device_ids=cfg.gpu_ids))
  File "/ascldap/users/dxgrieg/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/utils/config.py", line 513, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/ascldap/users/dxgrieg/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/utils/config.py", line 49, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'
Exception ignored in: <function LFBInferHead.__del__ at 0x7f2ec91123b0>
Traceback (most recent call last):
  File "/ascldap/users/dxgrieg/mmaction2/mmaction/models/heads/lfb_infer_head.py", line 112, in __del__
  File "/ascldap/users/dxgrieg/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/torch/serialization.py", line 377, in save
  File "/ascldap/users/dxgrieg/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/torch/serialization.py", line 231, in _open_file_like
  File "/ascldap/users/dxgrieg/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/torch/serialization.py", line 212, in __init__
NameError: name 'open' is not defined
```

**Comment by wangbo-zhao** [comment]
I think that you forget to set "gpu_ids".
`AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'.`

**Comment by Xylobyte** [comment]
Is "gpu_ids" set in the config file? I'm not seeing any other configs with this parameter included. The test.py file doesn't allow that paramter to be passed either.

**Comment by wangbo-zhao** [comment]
Sorry. This is a bug, which will be fixed in the future version. You can try replacing "/ascldap/users/dxgrieg/mmaction2/tools/test.py", line 161 with
`        model = build_dp(
            model, default_device, default_args=dict(device_ids=[0]))`.

**Comment by Xylobyte** [comment]
That seemed to have fixed it. Thank you!
