### ISSUE TITLE
train.py错误

### ISSUE THREAD

**Issue by QueenW1998** [open-mmlab/mmaction2#1650]
IndexError: list index out of range
请问在训练的时候遇到这个问题应该怎么解决，制作的数据集动作有5类，运行train.py时报错的

**Comment by makecent** [comment]
More detailed error message is needed. Seems like a very basic python error.

**Comment by QueenW1998** [comment]
已经开始训练后又失败了,中间省略号处打印出了一些东西：
H:\WH\MM\mmaction2-master\mmaction\utils\setup_env.py:32: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
H:\WH\MM\mmaction2-master\mmaction\utils\setup_env.py:42: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
H:/WH/MM/mmaction2-master/tools/train.py:114: UserWarning: The Args `gpu_ids` and `gpus` are only used in non-distributed mode and we highly encourage you to use distributed mode, i.e., launch training with dist_train.sh. The two args will be deperacted.
  warnings.warn(
H:/WH/MM/mmaction2-master/tools/train.py:120: UserWarning: Non-distributed training can only use 1 gpu now. We will use the 1st one in gpu_ids. 
  warnings.warn(
'gcc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
fatal: not a git repository (or any of the parent directories): .git
......
2022-05-31 14:52:53,614 - mmaction - INFO - Set random seed to 642864535, deterministic: False
2022-05-31 14:52:54,204 - mmaction - INFO - 57 out of 57 frames are valid.
fatal: not a git repository (or any of the parent directories): .git
2022-05-31 14:52:58,376 - mmaction - INFO - load checkpoint from http path: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb/slowfast_r50_4x16x1_256e_kinetics400_rgb_20200704-bcde7ed7.pth
Downloading: "https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb/slowfast_r50_4x16x1_256e_kinetics400_rgb_20200704-bcde7ed7.pth" to C:\Users\Administrator/.cache\torch\hub\checkpoints\slowfast_r50_4x16x1_256e_kinetics400_rgb_20200704-bcde7ed7.pth
100%|██████████| 132M/132M [00:21<00:00, 6.31MB/s]
2022-05-31 14:53:21,125 - mmaction - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: cls_head.fc_cls.weight, cls_head.fc_cls.bias

missing keys in source state_dict: roi_head.bbox_head.fc_cls.weight, roi_head.bbox_head.fc_cls.bias

2022-05-31 14:53:21,143 - mmaction - INFO - Start running, host: Administrator@PC-20171227YPZJ, work_dir: H:\WH\MM\mmaction2-master\tools\test
2022-05-31 14:53:21,143 - mmaction - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) CheckpointHook                     
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) StepLrUpdaterHook                  
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_iter:
(VERY_HIGH   ) StepLrUpdaterHook                  
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
 -------------------- 
after_train_iter:
(ABOVE_NORMAL) OptimizerHook                      
(NORMAL      ) CheckpointHook                     
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) CheckpointHook                     
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_epoch:
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_epoch:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_run:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
2022-05-31 14:53:21,143 - mmaction - INFO - workflow: [('train', 1)], max: 200 epochs
2022-05-31 14:53:21,144 - mmaction - INFO - Checkpoints will be saved to H:\WH\MM\mmaction2-master\tools\test by HardDiskBackend.
E:\Anaconda\envs\mmact2\lib\site-packages\torch\nn\functional.py:3499: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn(
2022-05-31 14:54:12,652 - mmaction - INFO - Epoch [1][20/29]	lr: 2.452e-02, eta: 4:08:04, time: 2.575, data_time: 1.948, memory: 2767, recall@thr=0.5: 0.2583, prec@thr=0.5: 0.1972, recall@top3: 0.7292, prec@top3: 0.2431, recall@top5: 1.0000, prec@top5: 0.2000, loss_action_cls: 5.7351, loss: 5.7351, grad_norm: 44.8260
completed: 0, elapsed: 0sTraceback (most recent call last):
  File "H:/WH/MM/mmaction2-master/tools/train.py", line 224, in <module>
    main()
  File "H:/WH/MM/mmaction2-master/tools/train.py", line 212, in main
    train_model(
  File "H:\WH\MM\mmaction2-master\mmaction\apis\train.py", line 232, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "E:\Anaconda\envs\mmact2\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "E:\Anaconda\envs\mmact2\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "E:\Anaconda\envs\mmact2\lib\site-packages\mmcv\runner\base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "E:\Anaconda\envs\mmact2\lib\site-packages\mmcv\runner\hooks\evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "E:\Anaconda\envs\mmact2\lib\site-packages\mmcv\runner\hooks\evaluation.py", line 273, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "E:\Anaconda\envs\mmact2\lib\site-packages\mmcv\runner\hooks\evaluation.py", line 361, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "H:\WH\MM\mmaction2-master\mmaction\datasets\ava_dataset.py", line 368, in evaluate
    results2csv(self, results, temp_file, self.custom_classes)
  File "H:\WH\MM\mmaction2-master\mmaction\core\evaluation\ava_utils.py", line 38, in results2csv
    if isinstance(results[0], list):
IndexError: list index out of range

Process finished with exit code 1

**Comment by makecent** [comment]
The content replaced by the ellipsis is useful for us to know what config you are using. Please also provide it.

**Comment by QueenW1998** [comment]
E:\Anaconda\envs\mmact2\python.exe H:/WH/MM/mmaction2-0.22.0/tools/train.py
H:\WH\MM\mmaction2-0.22.0\mmaction\utils\setup_env.py:32: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
H:\WH\MM\mmaction2-0.22.0\mmaction\utils\setup_env.py:42: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
H:/WH/MM/mmaction2-0.22.0/tools/train.py:114: UserWarning: The Args `gpu_ids` and `gpus` are only used in non-distributed mode and we highly encourage you to use distributed mode, i.e., launch training with dist_train.sh. The two args will be deperacted.
  warnings.warn(
H:/WH/MM/mmaction2-0.22.0/tools/train.py:120: UserWarning: Non-distributed training can only use 1 gpu now. We will use the 1st one in gpu_ids. 
  warnings.warn(
'gcc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
fatal: not a git repository (or any of the parent directories): .git
2022-06-01 11:34:54,112 - mmaction - INFO - Environment info:
------------------------------------------------------------
sys.platform: win32
Python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0,1,2,3: TITAN Xp
CUDA_HOME: C:\ProgramData\NVIDIA GPU Computing Toolkit\v8.0
GCC: n/a
PyTorch: 1.8.0+cu101
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.4
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.1, CUDNN_VERSION=7.6.4, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, 

TorchVision: 0.9.0+cu101
OpenCV: 4.5.5
MMCV: 1.4.5
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 10.1
MMAction2: 0.22.0+
------------------------------------------------------------

2022-06-01 11:34:54,113 - mmaction - INFO - Distributed training: False
2022-06-01 11:34:55,935 - mmaction - INFO - Config: model = dict(
    type='FastRCNN',
    backbone=dict(
        type='ResNet3dSlowFast',
        pretrained=None,
        resample_rate=8,
        speed_ratio=8,
        channel_ratio=8,
        slow_pathway=dict(
            type='resnet3d',
            depth=50,
            pretrained=None,
            lateral=True,
            conv1_kernel=(1, 7, 7),
            dilations=(1, 1, 1, 1),
            conv1_stride_t=1,
            pool1_stride_t=1,
            inflate=(0, 0, 1, 1),
            spatial_strides=(1, 2, 2, 1)),
        fast_pathway=dict(
            type='resnet3d',
            depth=50,
            pretrained=None,
            lateral=False,
            base_channels=8,
            conv1_kernel=(5, 7, 7),
            conv1_stride_t=1,
            pool1_stride_t=1,
            spatial_strides=(1, 2, 2, 1))),
    roi_head=dict(
        type='AVARoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor3D',
            roi_layer_type='RoIAlign',
            output_size=8,
            with_temporal_pool=True),
        bbox_head=dict(
            type='BBoxHeadAVA',
            in_channels=2304,
            num_classes=5,
            topk=(1, 1),
            multilabel=True,
            dropout_ratio=0.5)),
    train_cfg=dict(
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssignerAVA',
                pos_iou_thr=0.9,
                neg_iou_thr=0.9,
                min_pos_iou=0.9),
            sampler=dict(
                type='RandomSampler',
                num=32,
                pos_fraction=1,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=1.0,
            debug=False)),
    test_cfg=dict(rcnn=dict(action_thr=0.002)))
dataset_type = 'AVADataset'
data_root = 'H:/WH/MM/mmaction2-0.22.0/data/ava/rawframes'
anno_root = 'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations'
ann_file_train = 'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_train_v2.1.csv'
ann_file_val = 'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_val_v2.1.csv'
exclude_file_train = 'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_train_excluded_timestamps_v2.1.csv'
exclude_file_val = 'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_val_excluded_timestamps_v2.1.csv'
label_file = 'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_action_list_v2.1.pbtxt'
proposal_file_train = 'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_dense_proposals_train.FAIR.recall_93.9.pkl'
proposal_file_val = 'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_dense_proposals_val.FAIR.recall_93.9.pkl'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)
train_pipeline = [
    dict(type='SampleAVAFrames', clip_len=32, frame_interval=2),
    dict(type='RawFrameDecode'),
    dict(type='RandomRescale', scale_range=(256, 320)),
    dict(type='RandomCrop', size=256),
    dict(type='Flip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_bgr=False),
    dict(type='FormatShape', input_format='NCTHW', collapse=True),
    dict(type='Rename', mapping=dict(imgs='img')),
    dict(type='ToTensor', keys=['img', 'proposals', 'gt_bboxes', 'gt_labels']),
    dict(
        type='ToDataContainer',
        fields=[
            dict(key=['proposals', 'gt_bboxes', 'gt_labels'], stack=False)
        ]),
    dict(
        type='Collect',
        keys=['img', 'proposals', 'gt_bboxes', 'gt_labels'],
        meta_keys=['scores', 'entity_ids'])
]
val_pipeline = [
    dict(
        type='SampleAVAFrames', clip_len=32, frame_interval=2, test_mode=True),
    dict(type='RawFrameDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_bgr=False),
    dict(type='FormatShape', input_format='NCTHW', collapse=True),
    dict(type='Rename', mapping=dict(imgs='img')),
    dict(type='ToTensor', keys=['img', 'proposals']),
    dict(type='ToDataContainer', fields=[dict(key='proposals', stack=False)]),
    dict(
        type='Collect',
        keys=['img', 'proposals'],
        meta_keys=['scores', 'img_shape'],
        nested=True)
]
data = dict(
    videos_per_gpu=2,
    workers_per_gpu=2,
    val_dataloader=dict(videos_per_gpu=1),
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type='AVADataset',
        ann_file=
        'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_train_v2.1.csv',
        exclude_file=
        'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_train_excluded_timestamps_v2.1.csv',
        pipeline=[
            dict(type='SampleAVAFrames', clip_len=32, frame_interval=2),
            dict(type='RawFrameDecode'),
            dict(type='RandomRescale', scale_range=(256, 320)),
            dict(type='RandomCrop', size=256),
            dict(type='Flip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_bgr=False),
            dict(type='FormatShape', input_format='NCTHW', collapse=True),
            dict(type='Rename', mapping=dict(imgs='img')),
            dict(
                type='ToTensor',
                keys=['img', 'proposals', 'gt_bboxes', 'gt_labels']),
            dict(
                type='ToDataContainer',
                fields=[
                    dict(
                        key=['proposals', 'gt_bboxes', 'gt_labels'],
                        stack=False)
                ]),
            dict(
                type='Collect',
                keys=['img', 'proposals', 'gt_bboxes', 'gt_labels'],
                meta_keys=['scores', 'entity_ids'])
        ],
        label_file=
        'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_action_list_v2.1.pbtxt',
        proposal_file=
        'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_dense_proposals_train.FAIR.recall_93.9.pkl',
        person_det_score_thr=0.9,
        timestamp_start=2,
        timestamp_end=58,
        num_classes=5,
        start_index=1,
        data_prefix='H:/WH/MM/mmaction2-0.22.0/data/ava/rawframes'),
    val=dict(
        type='AVADataset',
        ann_file=
        'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_val_v2.1.csv',
        exclude_file=
        'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_val_excluded_timestamps_v2.1.csv',
        pipeline=[
            dict(
                type='SampleAVAFrames',
                clip_len=32,
                frame_interval=2,
                test_mode=True),
            dict(type='RawFrameDecode'),
            dict(type='Resize', scale=(-1, 256)),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_bgr=False),
            dict(type='FormatShape', input_format='NCTHW', collapse=True),
            dict(type='Rename', mapping=dict(imgs='img')),
            dict(type='ToTensor', keys=['img', 'proposals']),
            dict(
                type='ToDataContainer',
                fields=[dict(key='proposals', stack=False)]),
            dict(
                type='Collect',
                keys=['img', 'proposals'],
                meta_keys=['scores', 'img_shape'],
                nested=True)
        ],
        label_file=
        'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_action_list_v2.1.pbtxt',
        proposal_file=
        'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_dense_proposals_val.FAIR.recall_93.9.pkl',
        person_det_score_thr=0.9,
        timestamp_start=2,
        timestamp_end=58,
        num_classes=5,
        start_index=1,
        data_prefix='H:/WH/MM/mmaction2-0.22.0/data/ava/rawframes'),
    test=dict(
        type='AVADataset',
        ann_file=
        'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_val_v2.1.csv',
        exclude_file=
        'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_val_excluded_timestamps_v2.1.csv',
        pipeline=[
            dict(
                type='SampleAVAFrames',
                clip_len=32,
                frame_interval=2,
                test_mode=True),
            dict(type='RawFrameDecode'),
            dict(type='Resize', scale=(-1, 256)),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_bgr=False),
            dict(type='FormatShape', input_format='NCTHW', collapse=True),
            dict(type='Rename', mapping=dict(imgs='img')),
            dict(type='ToTensor', keys=['img', 'proposals']),
            dict(
                type='ToDataContainer',
                fields=[dict(key='proposals', stack=False)]),
            dict(
                type='Collect',
                keys=['img', 'proposals'],
                meta_keys=['scores', 'img_shape'],
                nested=True)
        ],
        label_file=
        'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_action_list_v2.1.pbtxt',
        proposal_file=
        'H:/WH/MM/mmaction2-0.22.0/data/ava/annotations/ava_dense_proposals_val.FAIR.recall_93.9.pkl',
        person_det_score_thr=0.9,
        timestamp_start=2,
        timestamp_end=58,
        num_classes=5,
        start_index=1,
        data_prefix='H:/WH/MM/mmaction2-0.22.0/data/ava/rawframes'))
optimizer = dict(type='SGD', lr=0.1125, momentum=0.9, weight_decay=1e-05)
optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))
lr_config = dict(
    policy='step',
    step=[10, 15],
    warmup='linear',
    warmup_by_epoch=True,
    warmup_iters=5,
    warmup_ratio=0.1)
total_epochs = 20
checkpoint_config = dict(interval=1)
workflow = [('train', 1)]
evaluation = dict(interval=1, save_best='mAP@0.5IOU')
log_config = dict(interval=20, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = 'test1'
load_from = 'H:\WH\MM\mmaction2-0.22.0\weights\slowfast_r50_4x16x1_256e_kinetics400_rgb_20200704-bcde7ed7.pth'
resume_from = None
find_unused_parameters = False
gpu_ids = [1]
omnisource = False
module_hooks = []

2022-06-01 11:34:55,936 - mmaction - INFO - Set random seed to 479320385, deterministic: False
2022-06-01 11:34:56,476 - mmaction - INFO - 10 out of 10 frames are valid.
fatal: not a git repository (or any of the parent directories): .git
2022-06-01 11:35:00,384 - mmaction - INFO - load checkpoint from local path: H:\WH\MM\mmaction2-0.22.0\weights\slowfast_r50_4x16x1_256e_kinetics400_rgb_20200704-bcde7ed7.pth
2022-06-01 11:35:00,626 - mmaction - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: cls_head.fc_cls.weight, cls_head.fc_cls.bias

missing keys in source state_dict: roi_head.bbox_head.fc_cls.weight, roi_head.bbox_head.fc_cls.bias

2022-06-01 11:35:00,645 - mmaction - INFO - Start running, host: Administrator@PC-20171227YPZJ, work_dir: H:\WH\MM\mmaction2-0.22.0\tools\test1
2022-06-01 11:35:00,645 - mmaction - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) CheckpointHook                     
(NORMAL      ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) EvalHook                           
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_iter:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) EvalHook                           
(LOW         ) IterTimerHook                      
 -------------------- 
after_train_iter:
(ABOVE_NORMAL) OptimizerHook                      
(NORMAL      ) CheckpointHook                     
(NORMAL      ) EvalHook                           
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) CheckpointHook                     
(NORMAL      ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_epoch:
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_epoch:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_run:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
2022-06-01 11:35:00,645 - mmaction - INFO - workflow: [('train', 1)], max: 20 epochs
2022-06-01 11:35:00,645 - mmaction - INFO - Checkpoints will be saved to H:\WH\MM\mmaction2-0.22.0\tools\test1 by HardDiskBackend.
E:\Anaconda\envs\mmact2\lib\site-packages\torch\nn\functional.py:3499: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn(
2022-06-01 11:35:24,707 - mmaction - INFO - Saving checkpoint at 1 epochs
completed: 0, elapsed: 0sTraceback (most recent call last):
  File "H:/WH/MM/mmaction2-0.22.0/tools/train.py", line 224, in <module>
    main()
  File "H:/WH/MM/mmaction2-0.22.0/tools/train.py", line 212, in main
    train_model(
  File "H:\WH\MM\mmaction2-0.22.0\mmaction\apis\train.py", line 228, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "E:\Anaconda\envs\mmact2\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "E:\Anaconda\envs\mmact2\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "E:\Anaconda\envs\mmact2\lib\site-packages\mmcv\runner\base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "E:\Anaconda\envs\mmact2\lib\site-packages\mmcv\runner\hooks\evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "E:\Anaconda\envs\mmact2\lib\site-packages\mmcv\runner\hooks\evaluation.py", line 273, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "E:\Anaconda\envs\mmact2\lib\site-packages\mmcv\runner\hooks\evaluation.py", line 361, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "H:\WH\MM\mmaction2-0.22.0\mmaction\datasets\ava_dataset.py", line 368, in evaluate
    results2csv(self, results, temp_file, self.custom_classes)
  File "H:\WH\MM\mmaction2-0.22.0\mmaction\core\evaluation\ava_utils.py", line 38, in results2csv
    if isinstance(results[0], list):
IndexError: list index out of range

Process finished with exit code 1

**Comment by makecent** [comment]
Looks like your validation results is empty. Could you please try run the following script to check your validation dataset:
```python
from mmcv import Config
from mmaction.datasets.builder import build_dataset, build_dataloader

cfg = Config.fromfile("path-to-your-config")
val_dataset = build_dataset(cfg.data.val, dict(test_mode=True))
print(len(val_dataset))
dataloader_setting = dict(
    videos_per_gpu=cfg.data.get('videos_per_gpu', 1),
    workers_per_gpu=cfg.data.get('workers_per_gpu', 1),
    shuffle=False)
dataloader_setting = dict(dataloader_setting,
                          **cfg.data.get('val_dataloader', {}))
val_dataloader = build_dataloader(val_dataset, **dataloader_setting)
print(len(val_dataloader.dataset))
```

**Comment by QueenW1998** [comment]
Thank you very much, and I have solved it！

**Comment by makecent** [comment]
@QueenW1998 You are welcome. You may close the issue, and if possible, give a brief description about how you solve the problem, so others encountering the same probelm in ther future can get hints.

**Comment by muxiddin19** [comment]
> 

Hello Dear! I also faced this issue. Can you please give me detail on how to recreate the data set, as I have data in 5 folders, and each folder have its subfolders? Thanks a a lot!
