### ISSUE TITLE
Training with new classes

### ISSUE THREAD

**Issue by zambranohally** [open-mmlab/mmaction2#1667]
Hi hope someone will help me on this. Thanks in advance
I have previously trained my action detection using skeleton with two classes.
After that I trained again and added 1 class. I modify the config num_classes = 3 and load_from=<output from previous training>.
The training is successful, however, I got this error when running demo_skeleton. What did I do wrong?
![image](https://user-images.githubusercontent.com/63218980/173482682-5104b506-a6e3-49b8-93c2-10053c98c769.png)

**Comment by dreamerlin** [comment]
I guess
1. something wrong with ur ckpt
2. pytorch version mismatching, try to use `_use_new_zipfile_serialization=False` when saving

**Comment by QueenW1998** [comment]
您好，请问我总共有个类别类，通过将训练出来保存的权重文件，重新加载到demo中测试是的时候，需要对那些参数进行修改呢？报错情况如下：
 E:\Anaconda\envs\mmact2_skeleton\python.exe H:/mmaction2-0.22.0/demo/webcam_demo_spatiotemporal_det.py
det_config H:/mmaction2-0.22.0/mmdetection-2.20.0/configs/yolox/yolox_l_8x8_300e_coco.py
args.det_checkpoint H:/WH/mmaction2-0.22.0/weights/yolox_l_8x8_300e_coco_20211126_140236-d3bd2b23.pth
args.device cuda:0
load checkpoint from local path: H:/mmaction2-0.22.0/weights/yolox_l_8x8_300e_coco_20211126_140236-d3bd2b23.pth
load checkpoint from local path: H:\mmaction2-0.22.0\tools\test1\latest.pth
DEBUG:__main__:Read thread: 4594 ms, 14 fps
DEBUG:__main__:Read thread: 658 ms, 12 fps
DEBUG:__main__:Read thread: 639 ms, 13 fps
E:\Anaconda\envs\mmact2_skeleton\lib\site-packages\torch\nn\functional.py:3499: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn(
DEBUG:__main__:Read thread: 731 ms, 11 fps
Traceback (most recent call last):
  File "H:/mmaction2-0.22.0/demo/webcam_demo_spatiotemporal_det.py", line 874, in <module>
    main(parse_args())
  File "H:/Wmmaction2-0.22.0/demo/webcam_demo_spatiotemporal_det.py", line 852, in main
    stdet_predictor.predict(task)
  File "H:/mmaction2-0.22.0/demo/webcam_demo_spatiotemporal_det.py", line 337, in predict
    if result[class_id][bbox_id, 4] > self.score_thr:   #4改成5
IndexError: index 0 is out of bounds for axis 0 with size 0

Process finished with exit code 1

**Comment by zambranohally** [comment]
@dreamerlin Thank you for responding
I got it working now. The problem is the checkpoint itself, the file is corrupt when I downloaded it in jupyter notebook.
