### ISSUE TITLE
How to solve "numpy.core._exceptions.MemoryError" ?

### ISSUE THREAD

**Issue by Prot-debug** [open-mmlab/mmaction2#1673]
Hello,

When I used the code [https://github.com/open-mmlab/mmaction2/blob/master/tools/data/activitynet/tsn_feature_extraction.py](url) to extract video features, `numpy.core._exceptions.MemoryError` occured. I think the reason this error happened is because each video file is too big to load in memory. But I don't know how to modify the related codes to load into memory in batches, instead of the whole video. 
Can someone help me with this？Thanks a lot. The following is the relevant information of the error.

> Traceback (most recent call last):
  File "../tools/data/activitynet/tsn_feature_extraction_tvseries_rgb.py", line 164, in <module>
    main()
  File "../tools/data/activitynet/tsn_feature_extraction_tvseries_rgb.py", line 126, in main
    sample = data_pipeline(tmpl)
  File "/root/disk/project/mmaction2/mmaction/datasets/pipelines/compose.py", line 50, in __call__
    data = t(data)
  File "/root/disk/project/mmaction2/mmaction/datasets/pipelines/augmentations.py", line 1407, in __call__
    imgs = np.empty((n, h, w, c), dtype=np.float32)
numpy.core._exceptions.MemoryError: Unable to allocate 136. GiB for an array with shape (29328, 576, 720, 3) and data type float32

**Comment by hukkai** [comment]
You can cut the long videos into short videos, extract the features of these  short videos and then concat them back.
