### ISSUE TITLE
Cannot test the trained model

### ISSUE THREAD

**Issue by GenMoat** [open-mmlab/mmaction2#1694]
Hi,

I have trained a timesformer model and saved all the checkpoints.

However, I am trying to do inference with the checkpoint, so I typed in terminal:

python tools/test.py /home/campus.ncl.ac.uk/b6029647/mmaction2/configs/recognition/timesformer/my_trans.py /home/campus.ncl.ac.uk/b6029647/mmaction2/configs/recognition/timesformer/something/epoch_14.pth --out /home/campus.ncl.ac.uk/b6029647/mmaction2/configs/recognition/timesformer/something/test.json --eval top_k_accuracy mean_class_accuracy 

and I got the error:

/home/campus.ncl.ac.uk/b6029647/mmaction2/mmaction/utils/setup_env.py:32: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/home/campus.ncl.ac.uk/b6029647/mmaction2/mmaction/utils/setup_env.py:42: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
load checkpoint from local path: /home/campus.ncl.ac.uk/b6029647/mmaction2/configs/recognition/timesformer/shake_yawn/epoch_14.pth
Traceback (most recent call last):
  File "tools/test.py", line 371, in <module>
    main()
  File "tools/test.py", line 356, in main
    outputs = inference_pytorch(args, cfg, distributed, data_loader)
  File "tools/test.py", line 161, in inference_pytorch
    model, default_device, default_args=dict(device_ids=cfg.gpu_ids))
  File "/home/campus.ncl.ac.uk/b6029647/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 519, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/campus.ncl.ac.uk/b6029647/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'

Thanks.

**Comment by GenMoat** [comment]
Okay I have solved it, by adding 'gpu_ids=[1]' in my config file.
