### ISSUE TITLE
/home/mmaction2# AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'

### ISSUE THREAD

**Issue by YTHmamba** [open-mmlab/mmaction2#1695]
2022-07-06 10:05:46,141 - mmaction - INFO - Set random seed to 69861830, deterministic: False
2022-07-06 10:05:47,126 - mmaction - INFO - load model from: https://download.openmmlab.com/mmaction/recognition/c3d/c3d_sports1m_pretrain_20201016-dcc47ddc.pth
2022-07-06 10:05:47,127 - mmaction - INFO - load checkpoint from http path: https://download.openmmlab.com/mmaction/recognition/c3d/c3d_sports1m_pretrain_20201016-dcc47ddc.pth
Traceback (most recent call last):
  File "tools/train.py", line 222, in <module>
    main()
  File "tools/train.py", line 210, in main
    train_model(
  File "/home/mmaction2/mmaction/apis/train.py", line 92, in train_model
    num_gpus=len(cfg.gpu_ids),
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/config.py", line 519, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'
root@62c40227d18b00c193086657:/home/mmaction2# AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'

I have encountered the above problem, does anyone know how to solve it, I would be very grateful ！

**Comment by hukkai** [comment]
@hukkai I think the example has a bug. You need to specify **--gpus** or **--gpu-ids** option (https://github.com/open-mmlab/mmaction2/blob/12f16c15b02681a596323bafeac5b2e97cae7f3b/tools/train.py#L45). 

However, the way you are using is for non-distributed training. It is recommended to use distributed training script: https://github.com/open-mmlab/mmaction2/blob/master/tools/dist_train.sh.

**Comment by talhaubaid** [comment]
I m facing thhis isseu while testing. I m running tools/test.py file
AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'

**Comment by talhaubaid** [comment]
I m following this link 
https://github.com/open-mmlab/mmaction2/blob/master/configs/localization/bmn/README.md
 
while running this 
(python tools/test.py C:\Users\ASDF\Desktop\mmaction2\configs\localization\bmn\bmn_400x100_2x8_9e_activitynet_feature.py  C:\Users\ASDF\Desktop\mmaction2\configs\localization\bmn\bmn_400x100_9e_activitynet_feature_20200619-42a3b111.pth --eval AR@AN --out new_results.json)

command I am having following error

``` python
Traceback (most recent call last):
  File "tools/test.py", line 372, in <module>
    main()
  File "tools/test.py", line 357, in main
    outputs = inference_pytorch(args, cfg, distributed, data_loader)
  File "tools/test.py", line 162, in inference_pytorch
    model, default_device, default_args=dict(device_ids=cfg.gpu_ids))
  File "C:\Users\ASDF\anaconda3\envs\open-mmlab\lib\site-packages\mmcv\utils\config.py", line 519, in __getattr__
    return getattr(self._cfg_dict, name)
  File "C:\Users\ASDF\anaconda3\envs\open-mmlab\lib\site-packages\mmcv\utils\config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'

(open-mmlab) C:\Users\ASDF\Desktop\mmaction2>AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'

```

**Comment by YRWFWHU** [comment]
I encounter this bug too. wish to be solved quickly.

**Comment by hukkai** [comment]
@YRWFWHU It is already solved.

> @hukkai I think the example has a bug. You need to specify **--gpus** or **--gpu-ids** option (
> 
> https://github.com/open-mmlab/mmaction2/blob/12f16c15b02681a596323bafeac5b2e97cae7f3b/tools/train.py#L45
> 
> ).
> However, the way you are using is for non-distributed training. It is recommended to use distributed training script: https://github.com/open-mmlab/mmaction2/blob/master/tools/dist_train.sh.

https://github.com/open-mmlab/mmaction2/issues/1695#issuecomment-1214136884

**Comment by talhaubaid** [comment]
@hukkai what about testing file ?

> @YRWFWHU It is already solved.
> 
> > @hukkai I think the example has a bug. You need to specify **--gpus** or **--gpu-ids** option (
> > https://github.com/open-mmlab/mmaction2/blob/12f16c15b02681a596323bafeac5b2e97cae7f3b/tools/train.py#L45
> > 
> > ).
> > However, the way you are using is for non-distributed training. It is recommended to use distributed training script: https://github.com/open-mmlab/mmaction2/blob/master/tools/dist_train.sh.
> 
> [#1695 (comment)](https://github.com/open-mmlab/mmaction2/issues/1695#issuecomment-1214136884)

@hukkai what about the testing file? It is not getting the gpu_ids. So I hard coded it and It worked for me. Just do this. To solve this replace the cfg.gpu_ids with [0]. As in testing file it is not getting gpu ids. 
(https://github.com/open-mmlab/mmaction2/blob/master/tools/test.py)
