### ISSUE TITLE
train  slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb on AVA2.1

### ISSUE THREAD

**Issue by w815526955** [open-mmlab/mmaction2#1707]
Thanks for your error report and we appreciate it a lot.
If you feel we have help you, give us a STAR! :satisfied:

**Checklist**

**Describe the bug**

I processed the AVA using the processing script of the dataset, and as a result, no relevant pictures were found during the training process. After my inspection, I found that the frame rate of most of the videos in the data set is not 30FPS, but the data is processed according to 30FPS, resulting in less than 27000 pictures generated per video, so no relevant pictures will be found. How to solve this problem please?

Traceback (most recent call last):
  File "/data1/Hatcher/model/Action_Recognition/mmaction2/tools/train.py", line 224, in <module>
    main()
  File "/data1/Hatcher/model/Action_Recognition/mmaction2/tools/train.py", line 212, in main
center_index: 16801,FPS:30
    train_model(
  File "/data1/Hatcher/model/Action_Recognition/mmaction2/mmaction/apis/train.py", line 232, in train_model
timestamp:1460,timestamp_start:900,fps:30
start:16769,end:16833,center_index:16801
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/data1/Hatcher/anaconda3/envs/open-mmlab3/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
i:0,frame_idx:16768
    epoch_runner(data_loaders[i], **kwargs)
  File "/data1/Hatcher/anaconda3/envs/open-mmlab3/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/data1/Hatcher/anaconda3/envs/open-mmlab3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/data1/Hatcher/anaconda3/envs/open-mmlab3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/data1/Hatcher/anaconda3/envs/open-mmlab3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/data1/Hatcher/anaconda3/envs/open-mmlab3/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data1/Hatcher/anaconda3/envs/open-mmlab3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/data1/Hatcher/anaconda3/envs/open-mmlab3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data1/Hatcher/anaconda3/envs/open-mmlab3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data1/Hatcher/model/Action_Recognition/mmaction2/mmaction/datasets/base.py", line 289, in __getitem__
    return self.prepare_train_frames(idx)
  File "/data1/Hatcher/model/Action_Recognition/mmaction2/mmaction/datasets/ava_dataset.py", line 312, in prepare_train_frames
    return self.pipeline(results)
  File "/data1/Hatcher/model/Action_Recognition/mmaction2/mmaction/datasets/pipelines/compose.py", line 50, in __call__
    data = t(data)
  File "/data1/Hatcher/model/Action_Recognition/mmaction2/mmaction/datasets/pipelines/loading.py", line 1307, in __call__
    img_bytes = self.file_client.get(filepath)
  File "/data1/Hatcher/anaconda3/envs/open-mmlab3/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 992, in get
    return self.client.get(filepath)
  File "/data1/Hatcher/anaconda3/envs/open-mmlab3/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 517, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data1/Hatcher/model/Action_Recognition/mmaction2/data/ava/rawframes/7g37N3eoQ9s/img_24539.jpg'

**Reproduction**

1. What command or script did you run?
python tools/train.py configs/detection/ava/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb.py
```
A placeholder for the command.
```
python tools/train.py configs/detection/ava/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb.py
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. no
4. What dataset did you use?
AVA 2.1
**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error traceback here.

```
A placeholder for traceback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by w815526955** [comment]
Thank you for your reply, I checked the pipeline, although the script you provided is 30FPS, but the video itself is 25FPS, in this case, the number of frames drawn will not reach 27000. Do not guide me if my understanding is correct, thank you

**Comment by hukkai** [comment]
Obviously your understanding is not correct. No matter what the original FPS is for the video, the frames are extracted in 30 FPS so it can reach 27000 frames. I have just confirmed this by checking my dataset. If you find some videos shorter than 27000 frames, then some operations in your data preparation part may be wrong.

**Comment by w815526955** [comment]
In the data processing stage, there is a script to cut the 15min video, I checked the original video, if the frame rate is 25FPS, and then cut out the 15min video, then the maximum number of frames can only reach 15*60*25 =22500. And in the process of extracting frames, many video results are 22500 frames. How do you understand this question?

**Comment by hukkai** [comment]
In the script to cut videos, the videos are converted to 30 FPS:
https://github.com/open-mmlab/mmaction2/blob/12f16c15b02681a596323bafeac5b2e97cae7f3b/tools/data/ava/cut_videos.sh#L32

**Comment by w815526955** [comment]
Although the video information shows 30FPS, when it is actually played, the frame rate of the video is only 25FPS. For details, please refer to the picture. thanks
![image](https://user-images.githubusercontent.com/53477572/179145323-0e1eb386-5303-4bd3-a296-107d0e14efd5.png)
