### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'mmaction/.mim'

### ISSUE THREAD

**Issue by YTHmamba** [open-mmlab/mmaction2#1811]
Traceback (most recent call last):
  File "setup.py", line 163, in <module>
    add_mim_extension()
  File "setup.py", line 125, in add_mim_extension
    os.makedirs(mim_path, exist_ok=True)
  File "/home/isac/anaconda3/envs/mmaction/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'mmaction/.mim'

Does anyone have any of these problems? How do you solve them, I need your help

**Comment by hukkai** [comment]
@YTHmamba you need to put the mmaction folder on some directory where you have write access.

**Comment by YTHmamba** [comment]
Thank you very much. I have solved it
