### ISSUE TITLE
Inference for custom trained PoseC3D AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'

### ISSUE THREAD

**Issue by taliegemen** [open-mmlab/mmaction2#1827]
Hello I am getting the following error when I run the code:
`!python tools/test.py configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py checkpoints/160.pth --eval top_k_accuracy mean_class_accuracy --out result.pkl`

`load checkpoint from local path: checkpoints/160.pth
Traceback (most recent call last):
  File "tools/test.py", line 371, in <module>
    main()
  File "tools/test.py", line 356, in main
    outputs = inference_pytorch(args, cfg, distributed, data_loader)
  File "tools/test.py", line 161, in inference_pytorch
    model, default_device, default_args=dict(device_ids=cfg.gpu_ids))
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/config.py", line 519, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'`

What should be changed so I can make inference work?
Thanks

**Comment by taliegemen** [comment]
I solved this issue by adding the code below to the `slowonly_r50_u48_240e_ntu120_xsub_keypoint.py` config file:
`gpu_ids = [0]`
