### ISSUE TITLE
[HVU] _forward() missing 2 required positional arguments: 'mask' and 'category_mask'

### ISSUE THREAD

**Issue by CrossStyle** [open-mmlab/mmaction2#1946]
Hello, 

First, thanks for your effort in providing this repo.

I am currently using the TSN model to train on the HVU dataset, and I got these errors `_forward() missing 2 required positional arguments: 'mask' and 'category_mask'`. I have collected 'mask' and 'category_mask' in the pipeline, but it seems not working. Or should I modify the `Recognizer2D`? Below is the full config and log.

```
sys.platform: win32
Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3070 Laptop GPU
CUDA_HOME: None
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30140 for x64
GCC: n/a
PyTorch: 1.8.1
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829913
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, 
TorchVision: 0.9.1
OpenCV: 4.5.1
MMCV: 1.5.2
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 11.1
MMAction2: 0.24.1+0ec7953
------------------------------------------------------------
2022-09-22 11:17:21,383 - mmaction - INFO - Config: model = dict(
    type='Recognizer2D',
    backbone=dict(
        type='ResNet',
        pretrained='torchvision://resnet18',
        depth=18,
        norm_eval=False),
    cls_head=dict(
        type='TSNHead',
        num_classes=3142,
        in_channels=512,
        spatial_type='avg',
        consensus=dict(type='AvgConsensus', dim=1),
        dropout_ratio=0.4,
        init_std=0.01,
        multi_class=True,
        loss_cls=dict(type='HVULoss')),
    train_cfg=None,
    test_cfg=dict(average_clips=None))
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))
lr_config = dict(policy='step', step=[40, 80])
total_epochs = 100
checkpoint_config = dict(interval=1)
log_config = dict(interval=20, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
opencv_num_threads = 0
mp_start_method = 'fork'
category_nums = [739, 117, 291, 69, 1678, 248]
target_cate = 'action'
categories = ['action', 'attribute', 'concept', 'event', 'object', 'scene']
dataset_type = 'HVUDataset'
data_root = 'D:/code/act_intent/src/act_reg/mmaction2/data/hvu/videos_val'
data_root_val = 'D:/code/act_intent/src/act_reg/mmaction2/data/hvu/videos_val'
ann_file_train = 'D:/code/act_intent/src/act_reg/mmaction2/data/hvu/hvu_val_video.json'
ann_file_val = 'D:/code/act_intent/src/act_reg/mmaction2/data/hvu/hvu_val_video.json'
ann_file_test = 'D:/code/act_intent/src/act_reg/mmaction2/data/hvu/hvu_val_video.json'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)
train_pipeline = [
    dict(type='LoadHVULabel'),
    dict(type='DecordInit'),
    dict(type='SampleFrames', clip_len=1, frame_interval=1, num_clips=8),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='RandomResizedCrop'),
    dict(type='Resize', scale=(224, 224), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_bgr=False),
    dict(type='FormatShape', input_format='NCHW'),
    dict(
        type='Collect',
        keys=['imgs', 'label', 'mask', 'category_mask'],
        meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]
val_pipeline = [
    dict(type='LoadHVULabel'),
    dict(type='DecordInit'),
    dict(
        type='SampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=8,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='CenterCrop', crop_size=256),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_bgr=False),
    dict(type='FormatShape', input_format='NCHW'),
    dict(
        type='Collect',
        keys=['imgs', 'label', 'mask', 'category_mask'],
        meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]
test_pipeline = [
    dict(type='LoadHVULabel'),
    dict(type='DecordInit'),
    dict(
        type='SampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=25,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='ThreeCrop', crop_size=256),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_bgr=False),
    dict(type='FormatShape', input_format='NCHW'),
    dict(
        type='Collect',
        keys=['imgs', 'label', 'mask', 'category_mask'],
        meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]
data = dict(
    videos_per_gpu=1,
    workers_per_gpu=2,
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type='HVUDataset',
        ann_file=
        'D:/code/act_intent/src/act_reg/mmaction2/data/hvu/hvu_val_video.json',
        data_prefix=
        'D:/code/act_intent/src/act_reg/mmaction2/data/hvu/videos_val',
        pipeline=[
            dict(type='LoadHVULabel'),
            dict(type='DecordInit'),
            dict(
                type='SampleFrames', clip_len=1, frame_interval=1,
                num_clips=8),
            dict(type='DecordDecode'),
            dict(type='Resize', scale=(-1, 256)),
            dict(type='RandomResizedCrop'),
            dict(type='Resize', scale=(224, 224), keep_ratio=False),
            dict(type='Flip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_bgr=False),
            dict(type='FormatShape', input_format='NCHW'),
            dict(
                type='Collect',
                keys=['imgs', 'label', 'mask', 'category_mask'],
                meta_keys=[]),
            dict(type='ToTensor', keys=['imgs', 'label'])
        ],
        tag_categories=[
            'action', 'attribute', 'concept', 'event', 'object', 'scene'
        ],
        tag_category_nums=[739, 117, 291, 69, 1678, 248],
        multi_class=True),
    val=dict(
        type='HVUDataset',
        ann_file=
        'D:/code/act_intent/src/act_reg/mmaction2/data/hvu/hvu_val_video.json',
        data_prefix=
        'D:/code/act_intent/src/act_reg/mmaction2/data/hvu/videos_val',
        pipeline=[
            dict(type='LoadHVULabel'),
            dict(type='DecordInit'),
            dict(
                type='SampleFrames',
                clip_len=1,
                frame_interval=1,
                num_clips=8,
                test_mode=True),
            dict(type='DecordDecode'),
            dict(type='Resize', scale=(-1, 256)),
            dict(type='CenterCrop', crop_size=256),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_bgr=False),
            dict(type='FormatShape', input_format='NCHW'),
            dict(
                type='Collect',
                keys=['imgs', 'label', 'mask', 'category_mask'],
                meta_keys=[]),
            dict(type='ToTensor', keys=['imgs', 'label'])
        ],
        tag_categories=[
            'action', 'attribute', 'concept', 'event', 'object', 'scene'
        ],
        tag_category_nums=[739, 117, 291, 69, 1678, 248],
        multi_class=True),
    test=dict(
        type='HVUDataset',
        ann_file=
        'D:/code/act_intent/src/act_reg/mmaction2/data/hvu/hvu_val_video.json',
        data_prefix=
        'D:/code/act_intent/src/act_reg/mmaction2/data/hvu/videos_val',
        pipeline=[
            dict(type='LoadHVULabel'),
            dict(type='DecordInit'),
            dict(
                type='SampleFrames',
                clip_len=1,
                frame_interval=1,
                num_clips=25,
                test_mode=True),
            dict(type='DecordDecode'),
            dict(type='Resize', scale=(-1, 256)),
            dict(type='ThreeCrop', crop_size=256),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_bgr=False),
            dict(type='FormatShape', input_format='NCHW'),
            dict(
                type='Collect',
                keys=['imgs', 'label', 'mask', 'category_mask'],
                meta_keys=[]),
            dict(type='ToTensor', keys=['imgs', 'label'])
        ],
        tag_categories=[
            'action', 'attribute', 'concept', 'event', 'object', 'scene'
        ],
        tag_category_nums=[739, 117, 291, 69, 1678, 248],
        multi_class=True))
evaluation = dict(interval=2, metrics=['mean_average_precision'])
work_dir = './work_dirs\my_config'
gpu_ids = [0]
omnisource = False
module_hooks = []
2022-09-22 11:17:21,383 - mmaction - INFO - Set random seed to 20, deterministic: False
load checkpoint from torchvision path: torchvision://resnet18
2022-09-22 11:17:21,586 - mmaction - INFO - These parameters in pretrained checkpoint are not loaded: {'fc.weight', 'fc.bias'}
2022-09-22 11:17:23,415 - mmaction - INFO - Start running, host: MSI-NB@MSI-NB, work_dir: D:\code\act_intent\src\act_reg\mmaction2\work_dir\work_dirs\my_config
2022-09-22 11:17:23,415 - mmaction - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) CheckpointHook                     
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) StepLrUpdaterHook                  
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_iter:
(VERY_HIGH   ) StepLrUpdaterHook                  
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
 -------------------- 
after_train_iter:
(ABOVE_NORMAL) OptimizerHook                      
(NORMAL      ) CheckpointHook                     
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) CheckpointHook                     
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_epoch:
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_epoch:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_run:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
2022-09-22 11:17:23,415 - mmaction - INFO - workflow: [('train', 1)], max: 100 epochs
2022-09-22 11:17:23,415 - mmaction - INFO - Checkpoints will be saved to D:\code\act_intent\src\act_reg\mmaction2\work_dir\work_dirs\my_config by HardDiskBackend.
Traceback (most recent call last):
  File "C:\Users\MSI-NB\.conda\envs\torch\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2020.3.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.3.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/code/act_intent/src/act_reg/mmaction2/work_dir/my_train.py", line 117, in <module>
    train_model(
  File "C:\Users\MSI-NB\.conda\envs\torch\lib\site-packages\mmaction\apis\train.py", line 232, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "C:\Users\MSI-NB\.conda\envs\torch\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 130, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "C:\Users\MSI-NB\.conda\envs\torch\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 51, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "C:\Users\MSI-NB\.conda\envs\torch\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "C:\Users\MSI-NB\.conda\envs\torch\lib\site-packages\mmcv\parallel\data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "C:\Users\MSI-NB\.conda\envs\torch\lib\site-packages\mmaction\models\recognizers\base.py", line 307, in train_step
    losses = self(imgs, label, return_loss=True, **aux_info)
  File "C:\Users\MSI-NB\.conda\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\MSI-NB\.conda\envs\torch\lib\site-packages\mmaction\models\recognizers\base.py", line 269, in forward
    return self.forward_train(imgs, label, **kwargs)
  File "C:\Users\MSI-NB\.conda\envs\torch\lib\site-packages\mmaction\models\recognizers\recognizer2d.py", line 45, in forward_train
    loss_cls = self.cls_head.loss(cls_score, gt_labels, **kwargs)
  File "C:\Users\MSI-NB\.conda\envs\torch\lib\site-packages\mmaction\models\heads\base.py", line 110, in loss
    loss_cls = self.loss_cls(cls_score, labels, **kwargs)
  File "C:\Users\MSI-NB\.conda\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\MSI-NB\.conda\envs\torch\lib\site-packages\mmaction\models\losses\base.py", line 38, in forward
    ret = self._forward(*args, **kwargs)
TypeError: _forward() missing 2 required positional arguments: 'mask' and 'category_mask'
```

**Comment by CrossStyle** [comment]
I changed the train_cfg in the TSN config to `train_cfg=dict(aux_info=['mask', 'category_mask'])`, and it works.
