### ISSUE TITLE
ConfigDict' object has no attribute 'gpu_id

### ISSUE THREAD

**Issue by Alasile** [open-mmlab/mmaction2#1968]
I'm getting this error while training and don't know how to fix it, does anyone know how to fix it?

``2022-10-04 17:36:36,121 - mmaction - INFO - Set random seed to 0, deterministic: True
Traceback (most recent call last):
  File "tools/train.py", line 222, in <module>
    main()
  File "tools/train.py", line 210, in main
    train_model(
  File "/root/mmaction/mmaction2/mmaction/apis/train.py", line 92, in train_model
    num_gpus=len(cfg.gpu_id),
  File "/root/miniconda3/envs/mmact/lib/python3.8/site-packages/mmcv/utils/config.py", line 510, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/root/miniconda3/envs/mmact/lib/python3.8/site-packages/mmcv/utils/config.py", line 48, in __getattr__
    raise ex
**AttributeError: 'ConfigDict' object has no attribute 'gpu_id'**
``

**Comment by P-jiahui** [comment]
You should add gpu_ids=[1] in config file
If using multiple cards, specify a column such as dual cards: gpu_ids=[0,1]

**Comment by hukkai** [comment]
@Alasile If you have any further questions, feel free to re-open the issue.
