### ISSUE TITLE
Modifying the size of num_clips of train in videodataset will cause topk calculation error in evaluation

### ISSUE THREAD

**Issue by P-jiahui** [open-mmlab/mmaction2#1979]
Is num_clips the size of batchsize?
Modifying the size of num_clips of train in videodataset will cause topk calculation error in evaluation.

I pasted the error follow：

Traceback (most recent call last):
  File "/data/pengjiahui/mmaction2-master/tools/train.py", line 222, in <module>
    main()
  File "/data/pengjiahui/mmaction2-master/tools/train.py", line 210, in main
    train_model(
  File "/data/pengjiahui/mmaction2-master/mmaction/apis/train.py", line 238, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/pengjiahui/opt/anaconda3/envs/yowo/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/pengjiahui/opt/anaconda3/envs/yowo/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/pengjiahui/opt/anaconda3/envs/yowo/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/pengjiahui/opt/anaconda3/envs/yowo/lib/python3.9/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/data/pengjiahui/mmaction2-master/mmaction/models/recognizers/base.py", line 301, in train_step
    losses = self(imgs, label, return_loss=True, **aux_info)
  File "/home/pengjiahui/opt/anaconda3/envs/yowo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/pengjiahui/mmaction2-master/mmaction/models/recognizers/base.py", line 263, in forward
    return self.forward_train(imgs, label, **kwargs)
  File "/data/pengjiahui/mmaction2-master/mmaction/models/recognizers/recognizer3d.py", line 27, in forward_train
    loss_cls = self.cls_head.loss(cls_score, gt_labels, **kwargs)
  File "/data/pengjiahui/mmaction2-master/mmaction/models/heads/base.py", line 101, in loss
    top_k_acc = top_k_accuracy(cls_score.detach().cpu().numpy(),
  File "/data/pengjiahui/mmaction2-master/mmaction/core/evaluation/accuracy.py", line 150, in top_k_accuracy
    match_array = np.logical_or.reduce(max_k_preds == labels, axis=1)
numpy.AxisError: axis 1 is out of bounds for array of dimension 0

**Comment by hukkai** [comment]
@P-jiahui `num_clips` is the number of clips sampled for a single input, not batch size. For TSN/TSM models of N segments, N is `num_clips`. For most other models like slowfast, I3D, etc,  `num_clips`  should be 1 during training. Which model do you use?

**Comment by P-jiahui** [comment]
@hukkai i I am using the slowfast model, when I set num_clips greater than 1, the evaluation function reports an error

**Comment by hukkai** [comment]
@P-jiahui Did you modify any codes? Can I have a look at your configs? num_clips greater than 1 can be used during testing:
https://github.com/open-mmlab/mmaction2/blob/bbf24c88e3b68d2a6cb615478c2f5d07c97a95d5/configs/recognition/slowfast/slowfast_r101_8x8x1_256e_kinetics400_rgb.py#L80

**Comment by hukkai** [comment]
@P-jiahui Do you solve this problem?

**Comment by hukkai** [comment]
@P-jiahui If you need to further discuss this problem, fee free to re-open the issue. Thanks!

**Comment by WANGCHAO1996** [comment]
> @P-jiahui `num_clips` is the number of clips sampled for a single input, not batch size. For TSN/TSM models of N segments, N is `num_clips`. For most other models like slowfast, I3D, etc, `num_clips` should be 1 during training. Which model do you use?

你好 我在使用tsm训练自己数据集时也遇到这个问题 我的数据共两类 每类的每个视频只有4-6fps 当我把num_clips设置为4时也会出现这个错误 请问怎么修改呢

**Comment by WANGCHAO1996** [comment]
> > @P-jiahui `num_clips` is the number of clips sampled for a single input, not batch size. For TSN/TSM models of N segments, N is `num_clips`. For most other models like slowfast, I3D, etc, `num_clips` should be 1 during training. Which model do you use?
> 
> 你好 我在使用tsm训练自己数据集时也遇到这个问题 我的数据共两类 每类的每个视频只有4-6fps 当我把num_clips设置为4时也会出现这个错误 请问怎么修改呢

9, in loss_by_feat
    top_k_acc = top_k_accuracy(cls_scores.detach().cpu().numpy(),
  File "/home/cwang/work/project/huapo_2/mmaction2-main/mmaction/evaluation/functional/accuracy.py", line 149, in top_k_accuracy
    match_array = np.logical_or.reduce(max_k_preds == labels, axis=1)
numpy.AxisError: axis 1 is out of bounds for array of dimension 0
