### ISSUE TITLE
AssertionError: epoch number is missing!

### ISSUE THREAD

**Issue by syjxxxx** [open-mmlab/mmaction2#2005]
Traceback (most recent call last):
  File "tools/train.py", line 222, in <module>
    main()
  File "tools/train.py", line 218, in main
    meta=meta)
  File "/opt/conda/lib/python3.7/site-packages/mmaction2-0.24.1-py3.7.egg/mmaction/apis/train.py", line 241, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.7/site-packages/mmaction2-0.24.1-py3.7.egg/mmaction/models/recognizers/base.py", line 322, in train_step
    losses = self(imgs, label, return_loss=True, **aux_info)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmaction2-0.24.1-py3.7.egg/mmaction/models/recognizers/base.py", line 283, in forward
    return self.forward_train(imgs, label, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmaction2-0.24.1-py3.7.egg/mmaction/models/recognizers/recognizer3d.py", line 27, in forward_train
    loss_cls = self.cls_head.loss(cls_score, gt_labels, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmaction2-0.24.1-py3.7.egg/mmaction/models/heads/base.py", line 110, in loss
    loss_cls = self.loss_cls(cls_score, labels, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmaction2-0.24.1-py3.7.egg/mmaction/models/losses/base.py", line 38, in forward
    ret = self._forward(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmaction2-0.24.1-py3.7.egg/mmaction/models/losses/edl_loss.py", line 186, in _forward
    annealing_coef = self.compute_annealing_coef(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmaction2-0.24.1-py3.7.egg/mmaction/models/losses/edl_loss.py", line 147, in compute_annealing_coef
    assert 'epoch' in kwargs, "epoch number is missing!"
AssertionError: epoch number is missing!
Experiments finished!
I ran into this problem after adding another loss.

**Comment by Dai-Wenxun** [comment]
How do you define your `edl_loss`? It seems the error came from the loss instead of mmaction2.

**Comment by syjxxxx** [comment]
As you said, the reason for the error is the use of loss. And I found relevant problems in other people's problems. the corresponding answer states: Add an annealing switcher in the config file: annealing_runner = True. I don't know which config file it is.
