### ISSUE TITLE
v1.0 checkpoint KeyError and TypeError

### ISSUE THREAD

**Issue by austinmw** [open-mmlab/mmaction2#2052]
Thanks for your error report and we appreciate it a lot.
If you feel we have help you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

Hi, I tried training a TSN model using v1.0.0rc1 and when loading in pretrained weights from the v1.0 downloads page I got a `KeyError` that the checkpoint doesn't have the key `message_hub`. Also when I instead don't use any `load_from`, I get `TypeError: expected string or bytes-like object`.

**Reproduction**

1. What command or script did you run?

```
mpirun --host algo-1-6ub03 -np 4 --allow-run-as-root --tag-output --oversubscribe -mca btl_tcp_if_include eth0 -mca oob_tcp_if_include eth0 -mca plm_rsh_no_tree_spawn 1 -mca pml ob1 -mca btl ^openib -mca orte_abort_on_non_zero_status 1 -mca btl_vader_single_copy_mechanism none -mca plm_rsh_num_concurrent 1 -x NCCL_SOCKET_IFNAME=eth0 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x SMDATAPARALLEL_USE_SINGLENODE=1 -x FI_PROVIDER=efa -x RDMAV_FORK_SAFE=1 -x LD_PRELOAD=/opt/conda/lib/python3.8/site-packages/gethostname.cpython-38-x86_64-linux-gnu.so -verbose -x NCCL_DEBUG=VERSION smddprun /opt/conda/bin/python3.8 -m mpi4py sagemaker_train.py --cfg-options seed=0 log_level='INFO' env_cfg.dist_cfg.backend='smddp' val_evaluator.collect_device='gpu' default_hooks.checkpoint.save_best='auto' default_hooks.logger.interval=10 visualizer.save_dir='/opt/ml/checkpoints' train_dataloader.dataset.data_prefix.video='/opt/ml/input/data/dataset/train/' val_dataloader.dataset.data_prefix.video='/opt/ml/input/data/dataset/val/' test_dataloader.dataset.data_prefix.video='/opt/ml/input/data/dataset/val/' train_dataloader.dataset.ann_file='/opt/ml/input/data/dataset/kinetics_tiny_train_video.txt' val_dataloader.dataset.ann_file='/opt/ml/input/data/dataset/kinetics_tiny_val_video.txt' test_dataloader.dataset.ann_file='/opt/ml/input/data/dataset/kinetics_tiny_val_video.txt' model.cls_head.num_classes=2 train_cfg.max_epochs=5 train_cfg.val_interval=1 load_from='https://download.openmmlab.com/mmaction/v1.0/recognition/tsn/tsn_imagenet-pretrained-r50_8xb32-1x1x3-100e_kinetics400-rgb/tsn_imagenet-pretrained-r50_8xb32-1x1x3-100e_kinetics400-rgb_20220906-cd10898e.pth' --config configs/recognition/tsn/tsn_imagenet-pretrained-r50_8xb32-1x1x3-100e_kinetics400-rgb.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

Just the above

4. What dataset did you use?

Kinetics-400 Tiny

**Environment**

Got error running collect_env.py:
```
Traceback (most recent call last):
  File "mmaction/utils/collect_env.py", line 2, in <module>
    from mmengine.utils import get_git_hash
  File "/opt/conda/lib/python3.8/site-packages/mmengine/__init__.py", line 3, in <module>
    from .config import *
  File "/opt/conda/lib/python3.8/site-packages/mmengine/config/__init__.py", line 2, in <module>
    from .config import Config, ConfigDict, DictAction
  File "/opt/conda/lib/python3.8/site-packages/mmengine/config/config.py", line 15, in <module>
    from typing import Any, Optional, Sequence, Tuple, Union
  File "/opt/mmaction2/mmaction/utils/typing.py", line 3, in <module>
    from typing import Dict, List, Optional, Tuple, Union
ImportError: cannot import name 'Dict' from partially initialized module 'typing' (most likely due to a circular import) (/opt/mmaction2/mmaction/utils/typing.py)
```

**Error traceback**

```
jp6brp45aq-algo-1-6ub03 | ErrorMessage "KeyError: 'message_hub'
jp6brp45aq-algo-1-6ub03 |  Traceback (most recent call last)
jp6brp45aq-algo-1-6ub03 |  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
jp6brp45aq-algo-1-6ub03 |  return _run_code(code, main_globals, None,
jp6brp45aq-algo-1-6ub03 |  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
jp6brp45aq-algo-1-6ub03 |  exec(code, run_globals)
jp6brp45aq-algo-1-6ub03 |  File "/opt/conda/lib/python3.8/site-packages/mpi4py/__main__.py", line 7, in <module>
jp6brp45aq-algo-1-6ub03 |  main()
jp6brp45aq-algo-1-6ub03 |  File "/opt/conda/lib/python3.8/site-packages/mpi4py/run.py", line 198, in main
jp6brp45aq-algo-1-6ub03 |  run_command_line(args)
jp6brp45aq-algo-1-6ub03 |  File "/opt/conda/lib/python3.8/site-packages/mpi4py/run.py", line 47, in run_command_line
jp6brp45aq-algo-1-6ub03 |  run_path(sys.argv[0], run_name='__main__')
jp6brp45aq-algo-1-6ub03 |  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
jp6brp45aq-algo-1-6ub03 |  return _run_module_code(code, init_globals, run_name,
jp6brp45aq-algo-1-6ub03 |  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
jp6brp45aq-algo-1-6ub03 |  _run_code(code, mod_globals, init_globals,
jp6brp45aq-algo-1-6ub03 |  File "sagemaker_train.py", line 241, in <module>
jp6brp45aq-algo-1-6ub03 |  File "sagemaker_train.py", line 232, in main
jp6brp45aq-algo-1-6ub03 |  runner.train()
jp6brp45aq-algo-1-6ub03 |  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1650, in train
jp6brp45aq-algo-1-6ub03 |  self.load_or_resume()
jp6brp45aq-algo-1-6ub03 |  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1596, in load_or_resume
jp6brp45aq-algo-1-6ub03 |  self.resume(resume_from)
jp6brp45aq-algo-1-6ub03 |  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1951, in resume
jp6brp45aq-algo-1-6ub03 |  self.message_hub.load_state_dict(checkpoint['message_hub'])
jp6brp45aq-algo-1-6ub03 |  KeyError: 'message_hub'"
```

And when not passing `load_from`:

```
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:Traceback (most recent call last):
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    return _run_code(code, main_globals, None,
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    exec(code, run_globals)
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/mpi4py/__main__.py", line 7, in <module>
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    main()
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/mpi4py/run.py", line 198, in main
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    run_command_line(args)
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/mpi4py/run.py", line 47, in run_command_line
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    run_path(sys.argv[0], run_name='__main__')
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    return _run_module_code(code, init_globals, run_name,
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    _run_code(code, mod_globals, init_globals,
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    exec(code, run_globals)
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "sagemaker_train.py", line 241, in <module>
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    main()
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "sagemaker_train.py", line 232, in main
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    runner.train()
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1650, in train
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    self.load_or_resume()
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1596, in load_or_resume
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    self.resume(resume_from)
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1898, in resume
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    checkpoint = self.load_checkpoint(filename, map_location=device)
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 2005, in load_checkpoint
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    checkpoint = _load_checkpoint(filename, map_location=map_location)
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 463, in _load_checkpoint
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 253, in load_checkpoint
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    checkpoint_loader = cls._get_checkpoint_loader(filename)
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 235, in _get_checkpoint_loader
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    if re.match(p, path) is not None:
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/re.py", line 191, in match
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:    return _compile(pattern, flags).match(string)
3x66w1kni5-algo-1-qixrs | [1,mpirank:0,algo-1]<stderr>:TypeError: expected string or bytes-like object
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hukkai** [comment]
@austinmw Hi, did you use any resume? The error comes from a resume function but if you just load the model, the resume function should not be called. We tested to load this checkpoint, and it works OK.

**Comment by Dai-Wenxun** [comment]
Can you show me the full config?

**Comment by cir7** [comment]
@austinmw detailed useage about `resume`and `load_from`  is as followed: 
  - If `resume=True` and `load_from` is not None, resume training from the checkpoint in `load_from`.
  - If `resume=True` and `load_from` is None, try to resume from the latest checkpoint in the work directory.
  - If `resume=False` and `load_from` is not None, only load the checkpoint, not resume training.
  - If `resume=False` and `load_from` is None, do not load nor resume.

**Comment by austinmw** [comment]
Hi, I have args.resume set to False and double checked, but it still gets to the `load_or_resume` function with mmengine v0.3.1:

> erf4ifr82s-algo-1-rmlq4 |  runner.train()
> erf4ifr82s-algo-1-rmlq4 |  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1650, in train
> erf4ifr82s-algo-1-rmlq4 |  self.load_or_resume()

https://github.com/open-mmlab/mmengine/blob/v0.3.1/mmengine/runner/runner.py#L1650
