### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/ucf101/annotations/classInd.txt'

### ISSUE THREAD

**Issue by 1Smallwhite2** [open-mmlab/mmaction2#2064]
bash generate_rawframes_filelist.sh

parse frames under directory data/ucf101/rawframes/
frame directory analysis done
Traceback (most recent call last):
  File "tools/data/build_file_list.py", line 271, in <module>
    main()
  File "tools/data/build_file_list.py", line 199, in main
    splits = parse_ucf101_splits(args.level)
  File "E:\MyGithub\mmaction2\tools\data\parse_file_list.py", line 98, in parse_ucf101_splits
    with open(class_index_file, 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'data/ucf101/annotations/classInd.txt'
Filelist for rawframes generated.

**Comment by hukkai** [comment]
@1Smallwhite2 did you prepare the annotations as mentioned here? https://github.com/open-mmlab/mmaction2/tree/master/tools/data/ucf101#step-1-prepare-annotations
