### ISSUE TITLE
 No such file or directory for training image

### ISSUE THREAD

**Issue by nyanmn** [open-mmlab/mmaction2#2115]
I am training for mmaction2 for custom dataset. Dataset is produced as ava dataset format.
Have csv files and pkl files.

The error is as follows.
```
Traceback (most recent call last):
  File "tools/train.py", line 222, in <module>
    main()
  File "tools/train.py", line 218, in main
    meta=meta)
  File "/home/sysadmin/HumanAction/mmaction2/mmaction/apis/train.py", line 232, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/sysadmin/HumanAction/mmcv/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/sysadmin/HumanAction/mmcv/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/sysadmin/anaconda3/envs/open-mm/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/sysadmin/anaconda3/envs/open-mm/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/sysadmin/anaconda3/envs/open-mm/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/sysadmin/anaconda3/envs/open-mm/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/sysadmin/anaconda3/envs/open-mm/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sysadmin/anaconda3/envs/open-mm/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sysadmin/anaconda3/envs/open-mm/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sysadmin/HumanAction/mmaction2/mmaction/datasets/base.py", line 289, in __getitem__
    return self.prepare_train_frames(idx)
  File "/home/sysadmin/HumanAction/mmaction2/mmaction/datasets/ava_dataset.py", line 312, in prepare_train_frames
    return self.pipeline(results)
  File "/home/sysadmin/HumanAction/mmaction2/mmaction/datasets/pipelines/compose.py", line 50, in __call__
    data = t(data)
  File "/home/sysadmin/HumanAction/mmaction2/mmaction/datasets/pipelines/loading.py", line 1301, in __call__
    img_bytes = self.file_client.get(filepath)
  File "/home/sysadmin/HumanAction/mmcv/mmcv/fileio/file_client.py", line 1017, in get
    return self.client.get(filepath)
  File "/home/sysadmin/HumanAction/mmcv/mmcv/fileio/file_client.py", line 538, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/ActivityDetection/ava/rawframes/standrew_stand_230/img_11039.jpg'

```

I don't have that image in my rawframes folder.
I can list down all images in the `standrew_stand_230` folder from both csv file and pkl file as follows.

All images listed in train pkl file under the folder `standrew_stand_230`  are

```
standrew_stand_230,0000   [[0.424 0.282 0.488 0.696 0.999]]
standrew_stand_230,0009   [[0.421 0.285 0.488 0.7   0.999]]
standrew_stand_230,0018   [[0.422 0.289 0.488 0.701 0.999]]
standrew_stand_230,0027   [[0.421 0.29  0.488 0.698 0.999]]
standrew_stand_230,0036   [[0.421 0.288 0.488 0.698 0.999]]
standrew_stand_230,0045   [[0.417 0.29  0.489 0.702 0.999]]
standrew_stand_230,0054   [[0.418 0.287 0.489 0.702 0.999]]
standrew_stand_230,0063   [[0.419 0.285 0.488 0.703 0.999]]
standrew_stand_230,0072   [[0.422 0.284 0.488 0.701 0.999]]
standrew_stand_230,0081   [[0.422 0.283 0.488 0.702 0.999]]
standrew_stand_230,0090   [[0.421 0.278 0.487 0.706 0.999]]
standrew_stand_230,0099   [[0.42  0.278 0.487 0.703 0.999]]
standrew_stand_230,0108   [[0.421 0.279 0.486 0.702 0.999]]
standrew_stand_230,0117   [[0.419 0.281 0.487 0.708 0.999]]
standrew_stand_230,0126   [[0.415 0.287 0.487 0.705 0.999]]
standrew_stand_230,0135   [[0.419 0.283 0.485 0.701 0.999]]
standrew_stand_230,0144   [[0.412 0.283 0.482 0.696 0.999]]
standrew_stand_230,0153   [[0.413 0.283 0.479 0.696 0.999]]
standrew_stand_230,0162   [[0.414 0.283 0.479 0.695 0.999]]
standrew_stand_230,0171   [[0.414 0.282 0.479 0.696 0.999]]
standrew_stand_230,0180   [[0.414 0.283 0.479 0.695 0.999]]
standrew_stand_230,0189   [[0.414 0.287 0.48  0.696 0.999]]
standrew_stand_230,0198   [[0.413 0.29  0.481 0.696 0.999]]
standrew_stand_230,0207   [[0.418 0.288 0.485 0.704 0.999]]
standrew_stand_230,0216   [[0.42  0.287 0.487 0.699 0.999]]
standrew_stand_230,0225   [[0.42  0.287 0.488 0.7   0.999]]
standrew_stand_230,0234   [[0.419 0.286 0.487 0.702 0.999]]
standrew_stand_230,0243   [[0.42  0.286 0.487 0.702 0.999]]
standrew_stand_230,0252   [[0.42  0.288 0.487 0.702 0.999]]
standrew_stand_230,0261   [[0.42  0.286 0.487 0.701 0.999]]
standrew_stand_230,0270   [[0.422 0.283 0.488 0.702 0.999]]
standrew_stand_230,0279   [[0.422 0.283 0.488 0.702 0.999]]
standrew_stand_230,0288   [[0.422 0.284 0.488 0.702 0.999]]
standrew_stand_230,0297   [[0.422 0.283 0.487 0.704 0.999]]
standrew_stand_230,0306   [[0.422 0.288 0.486 0.704 0.999]]
standrew_stand_230,0315   [[0.42  0.287 0.487 0.705 0.999]]
standrew_stand_230,0324   [[0.418 0.286 0.487 0.704 0.999]]
standrew_stand_230,0333   [[0.418 0.286 0.487 0.704 0.999]]
standrew_stand_230,0342   [[0.412 0.288 0.483 0.697 0.999]]
standrew_stand_230,0351   [[0.413 0.288 0.483 0.697 0.999]]
standrew_stand_230,0360   [[0.412 0.287 0.483 0.696 0.999]]
standrew_stand_230,0369   [[0.412 0.285 0.483 0.697 0.999]]
standrew_stand_230,0378   [[0.412 0.287 0.483 0.698 0.999]]
standrew_stand_230,0387   [[0.419 0.285 0.486 0.703 0.999]]
standrew_stand_230,0396   [[0.42  0.287 0.487 0.702 0.999]]
standrew_stand_230,0405   [[0.42  0.287 0.487 0.702 0.999]]
standrew_stand_230,0414   [[0.42  0.286 0.487 0.705 0.999]]
standrew_stand_230,0423   [[0.42  0.286 0.487 0.705 0.999]]
standrew_stand_230,0432   [[0.419 0.286 0.487 0.703 0.999]]
standrew_stand_230,0441   [[0.42  0.286 0.487 0.703 0.999]]
standrew_stand_230,0450   [[0.42  0.288 0.488 0.704 0.999]]
standrew_stand_230,0459   [[0.42  0.288 0.488 0.703 0.999]]
standrew_stand_230,0468   [[0.42  0.288 0.488 0.703 0.999]]
standrew_stand_230,0477   [[0.42  0.287 0.487 0.703 0.999]]
standrew_stand_230,0486   [[0.419 0.288 0.488 0.702 0.999]]
standrew_stand_230,0495   [[0.42  0.287 0.487 0.703 0.999]]
standrew_stand_230,0504   [[0.42  0.287 0.488 0.705 0.999]]
standrew_stand_230,0513   [[0.42  0.286 0.488 0.702 0.999]]
standrew_stand_230,0522   [[0.42  0.288 0.488 0.702 0.999]]
standrew_stand_230,0531   [[0.423 0.288 0.487 0.701 0.999]]
standrew_stand_230,0540   [[0.423 0.288 0.488 0.699 0.999]]
standrew_stand_230,0549   [[0.423 0.287 0.488 0.7   0.999]]
standrew_stand_230,0558   [[0.421 0.287 0.488 0.701 0.999]]
standrew_stand_230,0567   [[0.421 0.286 0.488 0.701 0.999]]
standrew_stand_230,0576   [[0.42  0.287 0.488 0.7   0.999]]
standrew_stand_230,0585   [[0.42  0.287 0.488 0.701 0.999]]
standrew_stand_230,0594   [[0.421 0.288 0.488 0.702 0.999]]
standrew_stand_230,0603   [[0.422 0.289 0.488 0.703 0.999]]
standrew_stand_230,0612   [[0.423 0.29  0.488 0.7   0.999]]
standrew_stand_230,0621   [[0.422 0.289 0.488 0.701 0.999]]
standrew_stand_230,0630   [[0.422 0.288 0.488 0.702 0.999]]
standrew_stand_230,0639   [[0.422 0.289 0.488 0.7   0.999]]
standrew_stand_230,0648   [[0.422 0.288 0.488 0.701 0.999]]
standrew_stand_230,0657   [[0.422 0.288 0.488 0.702 0.999]]
standrew_stand_230,0666   [[0.422 0.288 0.488 0.701 0.999]]
standrew_stand_230,0675   [[0.422 0.287 0.489 0.702 0.999]]
standrew_stand_230,0684   [[0.422 0.288 0.488 0.698 0.999]]
standrew_stand_230,0693   [[0.423 0.291 0.489 0.699 0.999]]
standrew_stand_230,0702   [[0.423 0.291 0.489 0.7   0.999]]
standrew_stand_230,0711   [[0.423 0.292 0.49  0.699 0.999]]
standrew_stand_230,0720   [[0.423 0.291 0.49  0.7   0.999]]
standrew_stand_230,0729   [[0.422 0.289 0.49  0.701 0.999]]
standrew_stand_230,0738   [[0.424 0.29  0.489 0.7   0.999]]
standrew_stand_230,0747   [[0.424 0.288 0.489 0.699 0.999]]
standrew_stand_230,0756   [[0.423 0.288 0.489 0.701 0.999]]
standrew_stand_230,0765   [[0.423 0.287 0.489 0.703 0.999]]
standrew_stand_230,0774   [[0.424 0.288 0.489 0.703 0.999]]
standrew_stand_230,0783   [[0.424 0.288 0.489 0.702 0.999]]
standrew_stand_230,0792   [[0.422 0.285 0.489 0.702 0.999]]
standrew_stand_230,0801   [[0.424 0.284 0.489 0.701 0.999]]
standrew_stand_230,0810   [[0.423 0.283 0.489 0.702 0.999]]
standrew_stand_230,0819   [[0.422 0.284 0.489 0.702 0.999]]
standrew_stand_230,0828   [[0.422 0.285 0.489 0.703 0.999]]
standrew_stand_230,0837   [[0.423 0.287 0.489 0.704 0.999]]
standrew_stand_230,0846   [[0.423 0.284 0.489 0.701 0.999]]
standrew_stand_230,0855   [[0.423 0.285 0.489 0.701 0.999]]
standrew_stand_230,0864   [[0.423 0.287 0.489 0.701 0.999]]
standrew_stand_230,0873   [[0.421 0.284 0.489 0.703 0.999]]
standrew_stand_230,0882   [[0.422 0.285 0.489 0.702 0.999]]
standrew_stand_230,0891   [[0.422 0.286 0.489 0.702 0.999]]
standrew_stand_230,0900   [[0.422 0.286 0.488 0.701 0.999]]
standrew_stand_230,0909   [[0.422 0.286 0.489 0.704 0.999]]
standrew_stand_230,0918   [[0.422 0.289 0.489 0.704 0.999]]
standrew_stand_230,0927   [[0.422 0.289 0.489 0.702 0.999]]
standrew_stand_230,0936   [[0.422 0.287 0.49  0.702 0.999]]
standrew_stand_230,0945   [[0.423 0.288 0.49  0.703 0.999]]
standrew_stand_230,0954   [[0.423 0.287 0.489 0.703 0.999]]
standrew_stand_230,0963   [[0.423 0.286 0.489 0.701 0.999]]
standrew_stand_230,0972   [[0.422 0.286 0.489 0.704 0.999]]
standrew_stand_230,0981   [[0.421 0.284 0.489 0.704 0.999]]
standrew_stand_230,0990   [[0.422 0.288 0.489 0.703 0.999]]
standrew_stand_230,0999   [[0.421 0.285 0.489 0.704 0.999]]
standrew_stand_230,1008   [[0.422 0.286 0.489 0.702 0.999]]
standrew_stand_230,1017   [[0.424 0.285 0.489 0.703 0.999]]
standrew_stand_230,1026   [[0.422 0.287 0.489 0.703 0.999]]
standrew_stand_230,1035   [[0.421 0.286 0.488 0.705 0.999]]
standrew_stand_230,1044   [[0.422 0.284 0.488 0.703 0.999]]
standrew_stand_230,1053   [[0.421 0.286 0.488 0.701 0.999]]
standrew_stand_230,1062   [[0.421 0.286 0.488 0.704 0.999]]
standrew_stand_230,1071   [[0.422 0.286 0.488 0.702 0.999]]
standrew_stand_230,1080   [[0.422 0.288 0.489 0.702 0.999]]
standrew_stand_230,1089   [[0.422 0.288 0.489 0.704 0.999]]
standrew_stand_230,1098   [[0.423 0.286 0.489 0.702 0.999]]
standrew_stand_230,1107   [[0.422 0.285 0.489 0.702 0.999]]
standrew_stand_230,1116   [[0.423 0.285 0.488 0.701 0.999]]
standrew_stand_230,1125   [[0.424 0.285 0.488 0.696 0.999]]
standrew_stand_230,1134   [[0.423 0.284 0.488 0.695 0.999]]
standrew_stand_230,1143   [[0.423 0.285 0.489 0.701 0.999]]
standrew_stand_230,1152   [[0.423 0.284 0.489 0.704 0.999]]
standrew_stand_230,1161   [[0.423 0.282 0.488 0.702 0.999]]
standrew_stand_230,1170   [[0.421 0.281 0.489 0.705 0.999]]
standrew_stand_230,1179   [[0.418 0.284 0.489 0.701 0.999]]
standrew_stand_230,1188   [[0.416 0.288 0.489 0.702 0.999]]
standrew_stand_230,1197   [[0.415 0.29  0.488 0.704 0.999]]
standrew_stand_230,1206   [[0.417 0.285 0.487 0.701 0.999]]
standrew_stand_230,1215   [[0.416 0.286 0.487 0.698 0.999]]
standrew_stand_230,1224   [[0.416 0.285 0.488 0.7   0.999]]
standrew_stand_230,1233   [[0.417 0.285 0.488 0.699 0.999]]
standrew_stand_230,1242   [[0.42  0.285 0.489 0.698 0.999]]
standrew_stand_230,1251   [[0.419 0.286 0.489 0.7   0.999]]
standrew_stand_230,1260   [[0.419 0.285 0.489 0.7   0.999]]
standrew_stand_230,1269   [[0.422 0.286 0.489 0.696 0.999]]
standrew_stand_230,1278   [[0.421 0.288 0.489 0.696 0.999]]
standrew_stand_230,1287   [[0.422 0.286 0.49  0.697 0.999]]
standrew_stand_230,1296   [[0.423 0.287 0.491 0.693 0.999]]
standrew_stand_230,1305   [[0.423 0.286 0.491 0.696 0.999]]
standrew_stand_230,1314   [[0.423 0.288 0.491 0.696 0.999]]
standrew_stand_230,1323   [[0.423 0.286 0.491 0.697 0.999]]
standrew_stand_230,1332   [[0.422 0.286 0.491 0.696 0.999]]
standrew_stand_230,1341   [[0.43  0.289 0.49  0.694 0.999]]
standrew_stand_230,1350   [[0.432 0.288 0.489 0.695 0.999]]
standrew_stand_230,1359   [[0.432 0.289 0.489 0.695 0.999]]
standrew_stand_230,1368   [[0.431 0.289 0.489 0.695 0.999]]
standrew_stand_230,1377   [[0.431 0.289 0.489 0.695 0.999]]
standrew_stand_230,1386   [[0.431 0.288 0.489 0.697 0.999]]
standrew_stand_230,1395   [[0.432 0.29  0.489 0.694 0.999]]
standrew_stand_230,1404   [[0.432 0.289 0.49  0.698 0.999]]
standrew_stand_230,1413   [[0.431 0.29  0.49  0.698 0.999]]
standrew_stand_230,1422   [[0.432 0.29  0.49  0.696 0.999]]
standrew_stand_230,1431   [[0.43  0.29  0.49  0.696 0.999]]
standrew_stand_230,1440   [[0.421 0.291 0.49  0.697 0.999]]
standrew_stand_230,1449   [[0.424 0.286 0.491 0.695 0.999]]
standrew_stand_230,1458   [[0.423 0.289 0.491 0.695 0.999]]
standrew_stand_230,1467   [[0.425 0.288 0.49  0.694 0.999]]
standrew_stand_230,1476   [[0.426 0.289 0.489 0.696 0.999]]
standrew_stand_230,1485   [[0.426 0.289 0.49  0.696 0.999]]
standrew_stand_230,1494   [[0.423 0.287 0.491 0.698 0.999]]
standrew_stand_230,1503   [[0.424 0.288 0.49  0.695 0.999]]
standrew_stand_230,1512   [[0.42  0.289 0.49  0.698 0.999]]
standrew_stand_230,1521   [[0.42  0.289 0.49  0.698 0.999]]
standrew_stand_230,1530   [[0.42  0.289 0.49  0.697 0.999]]
standrew_stand_230,1539   [[0.42  0.29  0.491 0.697 0.999]]
standrew_stand_230,1548   [[0.419 0.291 0.491 0.699 0.999]]
standrew_stand_230,1557   [[0.42  0.29  0.491 0.698 0.999]]
standrew_stand_230,1566   [[0.421 0.291 0.491 0.697 0.999]]
standrew_stand_230,1575   [[0.421 0.29  0.49  0.698 0.999]]
standrew_stand_230,1584   [[0.42  0.29  0.49  0.696 0.999]]
standrew_stand_230,1593   [[0.421 0.29  0.49  0.696 0.999]]
standrew_stand_230,1602   [[0.42  0.29  0.49  0.698 0.999]]
standrew_stand_230,1611   [[0.421 0.291 0.491 0.698 0.999]]
standrew_stand_230,1620   [[0.42  0.293 0.491 0.699 0.999]]
standrew_stand_230,1629   [[0.419 0.291 0.491 0.699 0.999]]
standrew_stand_230,1638   [[0.42  0.291 0.49  0.699 0.999]]
standrew_stand_230,1647   [[0.42  0.291 0.491 0.696 0.999]]
standrew_stand_230,1656   [[0.421 0.292 0.491 0.697 0.999]]
standrew_stand_230,1665   [[0.422 0.29  0.49  0.695 0.999]]
standrew_stand_230,1674   [[0.42  0.288 0.49  0.696 0.999]]
standrew_stand_230,1683   [[0.423 0.291 0.49  0.695 0.999]]
standrew_stand_230,1692   [[0.424 0.292 0.489 0.693 0.999]]
standrew_stand_230,1701   [[0.424 0.289 0.49  0.694 0.999]]
standrew_stand_230,1710   [[0.425 0.29  0.49  0.693 0.999]]
standrew_stand_230,1719   [[0.425 0.29  0.489 0.693 0.999]]

```

All images listed in train csv file under the folder `standrew_stand_230`  are

```
standrew_stand_230,0,0.424,0.282,0.488,0.696,12,1
standrew_stand_230,9,0.421,0.285,0.488,0.7,12,1
standrew_stand_230,18,0.422,0.289,0.488,0.701,12,1
standrew_stand_230,27,0.421,0.29,0.488,0.698,12,1
standrew_stand_230,36,0.421,0.288,0.488,0.698,12,1
standrew_stand_230,45,0.417,0.29,0.489,0.702,12,1
standrew_stand_230,54,0.418,0.287,0.489,0.702,12,1
standrew_stand_230,63,0.419,0.285,0.488,0.703,12,1
standrew_stand_230,72,0.422,0.284,0.488,0.701,12,1
standrew_stand_230,81,0.422,0.283,0.488,0.702,12,1
standrew_stand_230,90,0.421,0.278,0.487,0.706,12,1
standrew_stand_230,99,0.42,0.278,0.487,0.703,12,1
standrew_stand_230,108,0.421,0.279,0.486,0.702,12,1
standrew_stand_230,117,0.419,0.281,0.487,0.708,12,1
standrew_stand_230,126,0.415,0.287,0.487,0.705,12,1
standrew_stand_230,135,0.419,0.283,0.485,0.701,12,1
standrew_stand_230,144,0.412,0.283,0.482,0.696,12,1
standrew_stand_230,153,0.413,0.283,0.479,0.696,12,1
standrew_stand_230,162,0.414,0.283,0.479,0.695,12,1
standrew_stand_230,171,0.414,0.282,0.479,0.696,12,1
standrew_stand_230,180,0.414,0.283,0.479,0.695,12,1
standrew_stand_230,189,0.414,0.287,0.48,0.696,12,1
standrew_stand_230,198,0.413,0.29,0.481,0.696,12,1
standrew_stand_230,207,0.418,0.288,0.485,0.704,12,1
standrew_stand_230,216,0.42,0.287,0.487,0.699,12,1
standrew_stand_230,225,0.42,0.287,0.488,0.7,12,1
standrew_stand_230,234,0.419,0.286,0.487,0.702,12,1
standrew_stand_230,243,0.42,0.286,0.487,0.702,12,1
standrew_stand_230,252,0.42,0.288,0.487,0.702,12,1
standrew_stand_230,261,0.42,0.286,0.487,0.701,12,1
standrew_stand_230,270,0.422,0.283,0.488,0.702,12,1
standrew_stand_230,279,0.422,0.283,0.488,0.702,12,1
standrew_stand_230,288,0.422,0.284,0.488,0.702,12,1
standrew_stand_230,297,0.422,0.283,0.487,0.704,12,1
standrew_stand_230,306,0.422,0.288,0.486,0.704,12,1
standrew_stand_230,315,0.42,0.287,0.487,0.705,12,1
standrew_stand_230,324,0.418,0.286,0.487,0.704,12,1
standrew_stand_230,333,0.418,0.286,0.487,0.704,12,1
standrew_stand_230,342,0.412,0.288,0.483,0.697,12,1
standrew_stand_230,351,0.413,0.288,0.483,0.697,12,1
standrew_stand_230,360,0.412,0.287,0.483,0.696,12,1
standrew_stand_230,369,0.412,0.285,0.483,0.697,12,1
standrew_stand_230,378,0.412,0.287,0.483,0.698,12,1
standrew_stand_230,387,0.419,0.285,0.486,0.703,12,1
standrew_stand_230,396,0.42,0.287,0.487,0.702,12,1
standrew_stand_230,405,0.42,0.287,0.487,0.702,12,1
standrew_stand_230,414,0.42,0.286,0.487,0.705,12,1
standrew_stand_230,423,0.42,0.286,0.487,0.705,12,1
standrew_stand_230,432,0.419,0.286,0.487,0.703,12,1
standrew_stand_230,441,0.42,0.286,0.487,0.703,12,1
standrew_stand_230,450,0.42,0.288,0.488,0.704,12,1
standrew_stand_230,459,0.42,0.288,0.488,0.703,12,1
standrew_stand_230,468,0.42,0.288,0.488,0.703,12,1
standrew_stand_230,477,0.42,0.287,0.487,0.703,12,1
standrew_stand_230,486,0.419,0.288,0.488,0.702,12,1
standrew_stand_230,495,0.42,0.287,0.487,0.703,12,1
standrew_stand_230,504,0.42,0.287,0.488,0.705,12,1
standrew_stand_230,513,0.42,0.286,0.488,0.702,12,1
standrew_stand_230,522,0.42,0.288,0.488,0.702,12,1
standrew_stand_230,531,0.423,0.288,0.487,0.701,12,1
standrew_stand_230,540,0.423,0.288,0.488,0.699,12,1
standrew_stand_230,549,0.423,0.287,0.488,0.7,12,1
standrew_stand_230,558,0.421,0.287,0.488,0.701,12,1
standrew_stand_230,567,0.421,0.286,0.488,0.701,12,1
standrew_stand_230,576,0.42,0.287,0.488,0.7,12,1
standrew_stand_230,585,0.42,0.287,0.488,0.701,12,1
standrew_stand_230,594,0.421,0.288,0.488,0.702,12,1
standrew_stand_230,603,0.422,0.289,0.488,0.703,12,1
standrew_stand_230,612,0.423,0.29,0.488,0.7,12,1
standrew_stand_230,621,0.422,0.289,0.488,0.701,12,1
standrew_stand_230,630,0.422,0.288,0.488,0.702,12,1
standrew_stand_230,639,0.422,0.289,0.488,0.7,12,1
standrew_stand_230,648,0.422,0.288,0.488,0.701,12,1
standrew_stand_230,657,0.422,0.288,0.488,0.702,12,1
standrew_stand_230,666,0.422,0.288,0.488,0.701,12,1
standrew_stand_230,675,0.422,0.287,0.489,0.702,12,1
standrew_stand_230,684,0.422,0.288,0.488,0.698,12,1
standrew_stand_230,693,0.423,0.291,0.489,0.699,12,1
standrew_stand_230,702,0.423,0.291,0.489,0.7,12,1
standrew_stand_230,711,0.423,0.292,0.49,0.699,12,1
standrew_stand_230,720,0.423,0.291,0.49,0.7,12,1
standrew_stand_230,729,0.422,0.289,0.49,0.701,12,1
standrew_stand_230,738,0.424,0.29,0.489,0.7,12,1
standrew_stand_230,747,0.424,0.288,0.489,0.699,12,1
standrew_stand_230,756,0.423,0.288,0.489,0.701,12,1
standrew_stand_230,765,0.423,0.287,0.489,0.703,12,1
standrew_stand_230,774,0.424,0.288,0.489,0.703,12,1
standrew_stand_230,783,0.424,0.288,0.489,0.702,12,1
standrew_stand_230,792,0.422,0.285,0.489,0.702,12,1
standrew_stand_230,801,0.424,0.284,0.489,0.701,12,1
standrew_stand_230,810,0.423,0.283,0.489,0.702,12,1
standrew_stand_230,819,0.422,0.284,0.489,0.702,12,1
standrew_stand_230,828,0.422,0.285,0.489,0.703,12,1
standrew_stand_230,837,0.423,0.287,0.489,0.704,12,1
standrew_stand_230,846,0.423,0.284,0.489,0.701,12,1
standrew_stand_230,855,0.423,0.285,0.489,0.701,12,1
standrew_stand_230,864,0.423,0.287,0.489,0.701,12,1
standrew_stand_230,873,0.421,0.284,0.489,0.703,12,1
standrew_stand_230,882,0.422,0.285,0.489,0.702,12,1
standrew_stand_230,891,0.422,0.286,0.489,0.702,12,1
standrew_stand_230,900,0.422,0.286,0.488,0.701,12,1
standrew_stand_230,909,0.422,0.286,0.489,0.704,12,1
standrew_stand_230,918,0.422,0.289,0.489,0.704,12,1
standrew_stand_230,927,0.422,0.289,0.489,0.702,12,1
standrew_stand_230,936,0.422,0.287,0.49,0.702,12,1
standrew_stand_230,945,0.423,0.288,0.49,0.703,12,1
standrew_stand_230,954,0.423,0.287,0.489,0.703,12,1
standrew_stand_230,963,0.423,0.286,0.489,0.701,12,1
standrew_stand_230,972,0.422,0.286,0.489,0.704,12,1
standrew_stand_230,981,0.421,0.284,0.489,0.704,12,1
standrew_stand_230,990,0.422,0.288,0.489,0.703,12,1
standrew_stand_230,999,0.421,0.285,0.489,0.704,12,1
standrew_stand_230,1008,0.422,0.286,0.489,0.702,12,1
standrew_stand_230,1017,0.424,0.285,0.489,0.703,12,1
standrew_stand_230,1026,0.422,0.287,0.489,0.703,12,1
standrew_stand_230,1035,0.421,0.286,0.488,0.705,12,1
standrew_stand_230,1044,0.422,0.284,0.488,0.703,12,1
standrew_stand_230,1053,0.421,0.286,0.488,0.701,12,1
standrew_stand_230,1062,0.421,0.286,0.488,0.704,12,1
standrew_stand_230,1071,0.422,0.286,0.488,0.702,12,1
standrew_stand_230,1080,0.422,0.288,0.489,0.702,12,1
standrew_stand_230,1089,0.422,0.288,0.489,0.704,12,1
standrew_stand_230,1098,0.423,0.286,0.489,0.702,12,1
standrew_stand_230,1107,0.422,0.285,0.489,0.702,12,1
standrew_stand_230,1116,0.423,0.285,0.488,0.701,12,1
standrew_stand_230,1125,0.424,0.285,0.488,0.696,12,1
standrew_stand_230,1134,0.423,0.284,0.488,0.695,12,1
standrew_stand_230,1143,0.423,0.285,0.489,0.701,12,1
standrew_stand_230,1152,0.423,0.284,0.489,0.704,12,1
standrew_stand_230,1161,0.423,0.282,0.488,0.702,12,1
standrew_stand_230,1170,0.421,0.281,0.489,0.705,12,1
standrew_stand_230,1179,0.418,0.284,0.489,0.701,12,1
standrew_stand_230,1188,0.416,0.288,0.489,0.702,12,1
standrew_stand_230,1197,0.415,0.29,0.488,0.704,12,1
standrew_stand_230,1206,0.417,0.285,0.487,0.701,12,1
standrew_stand_230,1215,0.416,0.286,0.487,0.698,12,1
standrew_stand_230,1224,0.416,0.285,0.488,0.7,12,1
standrew_stand_230,1233,0.417,0.285,0.488,0.699,12,1
standrew_stand_230,1242,0.42,0.285,0.489,0.698,12,1
standrew_stand_230,1251,0.419,0.286,0.489,0.7,12,1
standrew_stand_230,1260,0.419,0.285,0.489,0.7,12,1
standrew_stand_230,1269,0.422,0.286,0.489,0.696,12,1
standrew_stand_230,1278,0.421,0.288,0.489,0.696,12,1
standrew_stand_230,1287,0.422,0.286,0.49,0.697,12,1
standrew_stand_230,1296,0.423,0.287,0.491,0.693,12,1
standrew_stand_230,1305,0.423,0.286,0.491,0.696,12,1
standrew_stand_230,1314,0.423,0.288,0.491,0.696,12,1
standrew_stand_230,1323,0.423,0.286,0.491,0.697,12,1
standrew_stand_230,1332,0.422,0.286,0.491,0.696,12,1
standrew_stand_230,1341,0.43,0.289,0.49,0.694,12,1
standrew_stand_230,1350,0.432,0.288,0.489,0.695,12,1
standrew_stand_230,1359,0.432,0.289,0.489,0.695,12,1
standrew_stand_230,1368,0.431,0.289,0.489,0.695,12,1
standrew_stand_230,1377,0.431,0.289,0.489,0.695,12,1
standrew_stand_230,1386,0.431,0.288,0.489,0.697,12,1
standrew_stand_230,1395,0.432,0.29,0.489,0.694,12,1
standrew_stand_230,1404,0.432,0.289,0.49,0.698,12,1
standrew_stand_230,1413,0.431,0.29,0.49,0.698,12,1
standrew_stand_230,1422,0.432,0.29,0.49,0.696,12,1
standrew_stand_230,1431,0.43,0.29,0.49,0.696,12,1
standrew_stand_230,1440,0.421,0.291,0.49,0.697,12,1
standrew_stand_230,1449,0.424,0.286,0.491,0.695,12,1
standrew_stand_230,1458,0.423,0.289,0.491,0.695,12,1
standrew_stand_230,1467,0.425,0.288,0.49,0.694,12,1
standrew_stand_230,1476,0.426,0.289,0.489,0.696,12,1
standrew_stand_230,1485,0.426,0.289,0.49,0.696,12,1
standrew_stand_230,1494,0.423,0.287,0.491,0.698,12,1
standrew_stand_230,1503,0.424,0.288,0.49,0.695,12,1
standrew_stand_230,1512,0.42,0.289,0.49,0.698,12,1
standrew_stand_230,1521,0.42,0.289,0.49,0.698,12,1
standrew_stand_230,1530,0.42,0.289,0.49,0.697,12,1
standrew_stand_230,1539,0.42,0.29,0.491,0.697,12,1
standrew_stand_230,1548,0.419,0.291,0.491,0.699,12,1
standrew_stand_230,1557,0.42,0.29,0.491,0.698,12,1
standrew_stand_230,1566,0.421,0.291,0.491,0.697,12,1
standrew_stand_230,1575,0.421,0.29,0.49,0.698,12,1
standrew_stand_230,1584,0.42,0.29,0.49,0.696,12,1
standrew_stand_230,1593,0.421,0.29,0.49,0.696,12,1
standrew_stand_230,1602,0.42,0.29,0.49,0.698,12,1
standrew_stand_230,1611,0.421,0.291,0.491,0.698,12,1
standrew_stand_230,1620,0.42,0.293,0.491,0.699,12,1
standrew_stand_230,1629,0.419,0.291,0.491,0.699,12,1
standrew_stand_230,1638,0.42,0.291,0.49,0.699,12,1
standrew_stand_230,1647,0.42,0.291,0.491,0.696,12,1
standrew_stand_230,1656,0.421,0.292,0.491,0.697,12,1
standrew_stand_230,1665,0.422,0.29,0.49,0.695,12,1
standrew_stand_230,1674,0.42,0.288,0.49,0.696,12,1
standrew_stand_230,1683,0.423,0.291,0.49,0.695,12,1
standrew_stand_230,1692,0.424,0.292,0.489,0.693,12,1
standrew_stand_230,1701,0.424,0.289,0.49,0.694,12,1
standrew_stand_230,1710,0.425,0.29,0.49,0.693,12,1
standrew_stand_230,1719,0.425,0.29,0.489,0.693,12,1
```

I don't have that image `img_11039.jpg` in `rawframes/standrew_stand_230` folder. Also in train csv file and train pkl file.
Why I have that error?

**Comment by nyanmn** [comment]
I found discussion [here](https://github.com/open-mmlab/mmaction2/issues/806).
That means I need 30 fps and 15min long video.
My current videos are not 15 mins long.

**Comment by kesaroid** [comment]
I got the same error. `tsn_feature_extraction.py` for ActivityNet is looking for files that don't exist. For both rgb & flow frames.
I am not sure what is causing the script to look for frames that don't exist after flow extraction.
