### ISSUE TITLE
Error trying to run demo_skeleton.py

### ISSUE THREAD

**Issue by mvidela31** [open-mmlab/mmaction2#2151]
Hi everybody,

I tried to run the [`demo/demo_skeleton.py`](https://github.com/open-mmlab/mmaction2/blob/master/demo/demo_skeleton.py) demo in Google Colab following the packages installation of [`demo/mmaction2_tutorial.ipynb`](https://github.com/open-mmlab/mmaction2/blob/master/demo/mmaction2_tutorial.ipynb) (I also installed the `mmpose` package through `!git clone https://github.com/open-mmlab/mmpose.git
&& cd mmpose && pip install -e .`). However, I'm getting the following error:
```python
!python demo/demo_skeleton.py --video /content/my_video.mp4 --out-filename /content/my_video_out.mp4
```
```python
/usr/local/lib/python3.8/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "demo/demo_skeleton.py", line 23, in <module>
    from mmpose.apis import (inference_top_down_pose_model, init_pose_model,
  File "/content/mmpose/mmpose/apis/__init__.py", line 2, in <module>
    from .inference import (collect_multi_frames, inference_bottom_up_pose_model,
  File "/content/mmpose/mmpose/apis/inference.py", line 17, in <module>
    from mmpose.datasets.dataset_info import DatasetInfo
  File "/content/mmpose/mmpose/datasets/__init__.py", line 7, in <module>
    from .datasets import (  # isort:skip
  File "/content/mmpose/mmpose/datasets/datasets/__init__.py", line 2, in <module>
    from ...deprecated import (TopDownFreiHandDataset, TopDownOneHand10KDataset,
  File "/content/mmpose/mmpose/deprecated.py", line 5, in <module>
    from .datasets.datasets.base import Kpt2dSviewRgbImgTopDownDataset
  File "/content/mmpose/mmpose/datasets/datasets/base/__init__.py", line 2, in <module>
    from .kpt_2d_sview_rgb_img_bottom_up_dataset import \
  File "/content/mmpose/mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_bottom_up_dataset.py", line 8, in <module>
    from xtcocotools.coco import COCO
  File "/usr/local/lib/python3.8/dist-packages/xtcocotools/coco.py", line 58, in <module>
    from . import mask as maskUtils
  File "/usr/local/lib/python3.8/dist-packages/xtcocotools/mask.py", line 3, in <module>
    import xtcocotools._mask as _mask
  File "xtcocotools/_mask.pyx", line 1, in init xtcocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

I think this error could be caused by a package version incompatibility. These are my package versions:
```
torch==1.9.0+cu111
mmcv-full==1.7.0
mmaction==0.24.1
mmdet==2.26.0
mmpose==0.29.0
```

Any suggestions for running this script successfully would be greatly appreciated.

Many thanks.

**Comment by Dai-Wenxun** [comment]
I suggest you open an issue in MMPose, bro!
