### ISSUE TITLE
Change the mmaction2 model to onnx failed.

### ISSUE THREAD

**Issue by yinghaodang** [open-mmlab/mmaction2#2161]
I have trained a .pth file, 
I want to deploy this model, and I read this: https://github.com/open-mmlab/mmaction2/blob/master/docs/en/tutorials/6_export_model.md

this is my code: python tools/deployment/pytorch2onnx.py configs/recognition/tsm/tsm_r50_video_1x1x8_50e_kinetics400_rgb.py my_code/checkpoints/best_top1_acc_epoch_18.pth --shape 1 1 3 224 224 --verify

but I got the wrong answer:
===================
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 165, in <module>
    pytorch2onnx(
  File "tools/deployment/pytorch2onnx.py", line 69, in pytorch2onnx
    torch.onnx.export(
  File "E:\miniconda3\envs\mmcv\lib\site-packages\torch\onnx\utils.py", line 504, in export
    _export(
  File "E:\miniconda3\envs\mmcv\lib\site-packages\torch\onnx\utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "E:\miniconda3\envs\mmcv\lib\site-packages\torch\onnx\utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "E:\miniconda3\envs\mmcv\lib\site-packages\torch\onnx\utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "E:\miniconda3\envs\mmcv\lib\site-packages\torch\onnx\utils.py", line 891, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "E:\miniconda3\envs\mmcv\lib\site-packages\torch\jit\_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "E:\miniconda3\envs\mmcv\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\miniconda3\envs\mmcv\lib\site-packages\torch\jit\_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "E:\miniconda3\envs\mmcv\lib\site-packages\torch\jit\_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "E:\miniconda3\envs\mmcv\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\miniconda3\envs\mmcv\lib\site-packages\torch\nn\modules\module.py", line 1178, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: forward_dummy() got multiple values for argument 'softmax'
===================
I don't know why.

**Comment by yinghaodang** [comment]
I can't put the pth file on the github...
I can use the codes below to inference the model.
```
import warnings
warnings.filterwarnings("ignore")
from mmcv import Config
from mmaction.apis import inference_recognizer, init_recognizer


# ===========前处理部分=============
cfg = Config.fromfile("../configs/recognition/tsm/"
                      "tsm_r50_video_1x1x8_50e_kinetics400_rgb.py")
cfg.model.cls_head.num_classes = 2

checkpoint = "checkpoints/best_top1_acc_epoch_18.pth"
model = init_recognizer(cfg, checkpoint=checkpoint, device='cuda:0')

# ===========推理部分==============
# 选择视频进行推理
video = "fight/cam1_1.mp4"
label = './label.txt'

# results 类似这样：[(类别1,得分1)(类别2,得分2),...]
results = inference_recognizer(model, video)

# ============后处理部分============
labels = ["no fight", 'fight']
# 取出得分最高的，并获得其类别
results = labels[results[0][0]]
print(results)
```

**Comment by yinghaodang** [comment]
The New year is passed, please.

**Comment by cookielicker** [comment]
use lower torch version，for example 1.10.1
