### ISSUE TITLE
About BSN Testing phase

### ISSUE THREAD

**Issue by Michael-Ray-Sirius** [open-mmlab/mmaction2#2193]
I run the code as instruments of BSN and BMN successfully, but when I run the code:
  python tools/test.py configs/localization/bsn/bsn_pem_400x100_1x16_20e_activitynet_feature.py work_dirs/bsn_400x100_20e_1x16_activitynet_feature/tem_epoch_20.pth --eval AR@AN --out work_dirs/bsn_400x100_20e_1x16_activitynet_feature/results.json --cfg-options gpu_ids=[0]
##推理 BSN(PEM) 模型，并计算 ‘AR@AN’ 指标，输出结果文件。

I got the error :
  Traceback (most recent call last):
  File "tools/test.py", line 371, in <module>
    main()
  File "tools/test.py", line 356, in main
    outputs = inference_pytorch(args, cfg, distributed, data_loader)
  File "tools/test.py", line 162, in inference_pytorch
    outputs = single_gpu_test(model, data_loader)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/engine/test.py", line 34, in single_gpu_test
    for data in data_loader:
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/mmaction2/mmaction/datasets/base.py", line 287, in __getitem__
    return self.prepare_test_frames(idx)
  File "/root/mmaction2/mmaction/datasets/activitynet_dataset.py", line 94, in prepare_test_frames
    return self.pipeline(results)
  File "/root/mmaction2/mmaction/datasets/pipelines/compose.py", line 50, in __call__
    data = t(data)
  File "/root/mmaction2/mmaction/datasets/pipelines/loading.py", line 1817, in __call__
    pgm_proposals = np.loadtxt(
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1042, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 532, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /root/mmaction2/work_dirs/bsn_400x100_20e_1x16_activitynet_feature/pgm_proposals/v_--1DO2V4K74.csv not found.

But I got the pgm_proposals and pgm_features as the command :
  python tools/misc/bsn_proposal_generation.py configs/localization/bsn/bsn_pgm_400x100_activitynet_feature.py --mode train
successfully.

What's wrong with my code or what should I do to adjust the config file?

**Comment by cir7** [comment]
Hi, @Michael-Ray-Sirius , please make sure that the path `/root/mmaction2/work_dirs/bsn_400x100_20e_1x16_activitynet_feature/pgm_proposals/v--1DO2V4K74.csv` is valid.
