### ISSUE TITLE
Activitynet feature postprocessing error

### ISSUE THREAD

**Issue by kesaroid** [open-mmlab/mmaction2#2196]
Hi, I am trying to concat RGB and Flow features for activitynet using `activitynet_feature_postprocessing.py` for 1 single video.
I reduced this `pool = multiprocessing.Pool(1)` from 32 to 1, as I was getting a paging error on windows. The paths are correct.
But I am getting the following error. 

```
>python activitynet_feature_postprocessing.py --rgb ../../../data/ActivityNet/rgb_feat --flow ../../../data/ActivityNet/flow_feat --dest ../../../data/ActivityNet/mmaction_feat
E:\anaconda\envs\openmmlab\lib\site-packages\mmcv\__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/openmmlab/mmcv/blob/master/docs/en/compatibility.md for more details.                                                                        'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last): File "E:\anaconda\envs\openmmlab\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
File "E:\anaconda\envs\openmmlab\lib\multiprocessing\pool.py", line 44, in mapstar 
    return list(map(*args))
File "D:\AIRS\experiments\mmaction2\tools\data\activitynet\activitynet_feature_postprocessing.py", line 68, in merge_feat                                                                                                                         
    rgb_feat = load(osp.join(args.rgb, name)) 
AttributeError: 'NoneType' object has no attribute 'rgb'
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last): 
File "activitynet_feature_postprocessing.py", line 99, in <module>
    main() 
File "activitynet_feature_postprocessing.py", line 95, in mainpool.map(merge_feat, rgb_feat)
File "E:\anaconda\envs\openmmlab\lib\multiprocessing\pool.py", line 268, in map 
    return self._map_async(func, iterable, mapstar, chunksize).get()
File "E:\anaconda\envs\openmmlab\lib\multiprocessing\pool.py", line 657, in get raise self._value
AttributeError: 'NoneType' object has no attribute 'rgb'
```

Any help would be appreciated. Thank you.

**Comment by kesaroid** [comment]
Update: This error only happened in the windows installation. 
On ubuntu, it concatenated the features seamlessly.

**Comment by kesaroid** [comment]
This is just an error due to multi-processing not having access to the args.
The issue can be resolved by making args global
