### ISSUE TITLE
Error: No module named 'mmcv.runner'

### ISSUE THREAD

**Issue by RongchangLi** [open-mmlab/mmaction2#2216]
Thanks for your error report and we appreciate it a lot.
If you feel we have help you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

I installed the mmaction2 at 1.x branch. When prepare the Diving48 dataset, it report error: 'No module named 'mmcv.runner'

**Reproduction**

```
bash generate_videos_filelist.sh
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
   No
4. What dataset did you use?
  Diving48

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
Unfortunately, it report an error when run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py`.
```
Traceback (most recent call last):
  File "/data/Disk_A/rongchang/ex_ideas/mappings/2023/mmaction2/mmaction/utils/collect_env.py", line 2, in <module>
    from mmengine.utils import get_git_hash
  File "/data/Disk_A/rongchang/.conda/envs/mmaction2_1/lib/python3.10/site-packages/mmengine/__init__.py", line 3, in <module>
    from .config import *
  File "/data/Disk_A/rongchang/.conda/envs/mmaction2_1/lib/python3.10/site-packages/mmengine/config/__init__.py", line 2, in <module>
    from .config import Config, ConfigDict, DictAction
  File "/data/Disk_A/rongchang/.conda/envs/mmaction2_1/lib/python3.10/site-packages/mmengine/config/config.py", line 15, in <module>
    from typing import Any, Optional, Sequence, Tuple, Union
  File "/data/Disk_A/rongchang/ex_ideas/mappings/2023/mmaction2/mmaction/utils/typing.py", line 3, in <module>
    from typing import Dict, List, Optional, Tuple, Union
ImportError: cannot import name 'Dict' from partially initialized module 'typing' (most likely due to a circular import) (/data/Disk_A/rongchang/ex_ideas/mappings/2023/mmaction2/mmaction/utils/typing.py)
```

3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch
```
     conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
 ```

**Error traceback**

If applicable, paste the error traceback here.

```
Traceback (most recent call last):
  File "/data/Disk_A/rongchang/ex_ideas/mappings/2023/mmaction2/tools/data/build_file_list.py", line 8, in <module>
    from mmcv.runner import set_random_seed
ModuleNotFoundError: No module named 'mmcv.runner'
Traceback (most recent call last):
  File "/data/Disk_A/rongchang/ex_ideas/mappings/2023/mmaction2/tools/data/build_file_list.py", line 8, in <module>
    from mmcv.runner import set_random_seed
ModuleNotFoundError: No module named 'mmcv.runner'

```

**Bug fix**

**Comment by hukkai** [comment]
@RongchangLi I think it is a bug and we will fix it soon. Thanks

**Comment by hukkai** [comment]
https://github.com/open-mmlab/mmaction2/pull/2227/files Fixed here @RongchangLi  Thanks
