### ISSUE TITLE
error:python3 tools/test.py configs/recognition/tsm/tsm_r50_1x1x8_50e_sthv2_rgb.py ./tsm.onnx --out resultonnx2.json --eval top_k_accuracy mean_class_accuracy --onnx

### ISSUE THREAD

**Issue by zhangzj03** [open-mmlab/mmaction2#2258]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
[                           ] 104/24777, 0.6 task/s, elapsed: 171s, [                           ] 105/24777, 0.6 task/s, elapsed: 172s, [                           ] 106/24777, 0.6 task/s, elapsed: 174s, [>>>>>>>>>>>>>>>>>>>>>>>] 24777/24777, 0.4 task/s, elapsed: 65305s, ETA:     0s^[[D
writing results to resultonnx2.json
Traceback (most recent call last):
  File "tools/test.py", line 371, in <module>
    main()
  File "tools/test.py", line 365, in main
    eval_res = dataset.evaluate(outputs, **eval_config)
  File "/workspace/mmaction2/mmaction/datasets/base.py", line 175, in evaluate
    assert len(results) == len(self), (
AssertionError: The length of results is not equal to the dataset len: 148662 != 24777

**Comment by hukkai** [comment]
@zhangzj03 How does this error happen? Did you press control + D and then get this error? Or you just waited for the program to finish and got this error?

**Comment by zhangzj03** [comment]
@hukkai I waited for the program to fininsh and got this error!
