### ISSUE TITLE
Key error :  ActionVisualizer is not in the visualizer registry during testing in mmaction2-1.x branch 

### ISSUE THREAD

**Issue by a-github-learner** [open-mmlab/mmaction2#2276]
Hi, I try to use mmaction2-1.x branch to train posec3d module. I got 
```
KeyError: 'ActionVisualizer is not in the visualizer registry. Please check whether the value of  ActionVisualizer  is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module.
```
 However, the module can be smoothly trained with totally the same config. I would like to ask how to solve this problem?

### Here is my command line in test:
```
CUDA_VISIBLE_DEVICES=1,2 bash /media/6t/XJY_FILES/Gym/mmaction2-1.x/tools/dist_test.sh /media/6t/XJY_FILES/Gym/mmaction2-1.x/configs/skeleton/posec3d/slowonly_r50_u48_240e_gym_amp.py /media/6t/XJY_FILES/Gym/mmaction2-1.x/work_dirs/posec3d/slowonly_r50_u48_240e_gym_Kp_amp/best_acc/top1_epoch_227.pth  2 --dump ./output_files/slowonly_r50_u48_240e_gym_Kp_amp_best.pkl 
```

### Here is my command line in train:
```
CUDA_VISIBLE_DEVICES=1,2 bash ./tools/dist_train.sh /media/6t/XJY_FILES/Gym/mmaction2-1.x/configs/skeleton/posec3d/slowonly_r50_u48_240e_gym_Kp_amp.py 2 --seed 1594917024 --amp
```
### Here is my config:
```
03/08 16:41:06 - mmengine - INFO - Config:
default_scope = 'mmaction'
default_hooks = dict(
    runtime_info=dict(type='RuntimeInfoHook'),
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=20, ignore_last=False),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(
        type='CheckpointHook', interval=1, save_best='auto', max_keep_ckpts=3),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    sync_buffers=dict(type='SyncBuffersHook'))
env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
log_processor = dict(type='LogProcessor', window_size=20, by_epoch=True)
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='ActionVisualizer', vis_backends=[dict(type='LocalVisBackend')])
log_level = 'INFO'
load_from = '/media/6t/XJY_FILES/Gym/mmaction2-1.x/work_dirs/posec3d/slowonly_r50_u48_240e_gym_Kp_amp/best_acc/top1_epoch_227.pth'
resume = False
model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='ResNet3dSlowOnly',
        depth=50,
        pretrained=None,
        in_channels=17,
        base_channels=32,
        num_stages=3,
        out_indices=(2, ),
        stage_blocks=(4, 6, 3),
        conv1_stride_s=1,
        pool1_stride_s=1,
        inflate=(0, 1, 1),
        spatial_strides=(2, 2, 2),
        temporal_strides=(1, 1, 2),
        dilations=(1, 1, 1)),
    cls_head=dict(
        type='I3DHead',
        in_channels=512,
        num_classes=99,
        spatial_type='avg',
        dropout_ratio=0.5,
        average_clips='prob'),
    train_cfg=dict(),
    test_cfg=dict(average_clis='prob'))
dataset_type = 'PoseDataset'
ann_file = '/media/6t/XJY_FILES/Gym/mmaction2-master/tools/data/gym/gym_hrnet.pkl'
left_kp = [1, 3, 5, 7, 9, 11, 13, 15]
right_kp = [2, 4, 6, 8, 10, 12, 14, 16]
train_pipeline = [
    dict(type='UniformSampleFrames', clip_len=48),
    dict(type='PoseDecode'),
    dict(type='PoseCompact', hw_ratio=1.0, allow_imgpad=True),
    dict(type='Resize', scale=(-1, 64)),
    dict(type='RandomResizedCrop', area_range=(0.56, 1.0)),
    dict(type='Resize', scale=(56, 56), keep_ratio=False),
    dict(
        type='Flip',
        flip_ratio=0.5,
        left_kp=[1, 3, 5, 7, 9, 11, 13, 15],
        right_kp=[2, 4, 6, 8, 10, 12, 14, 16]),
    dict(
        type='GeneratePoseTarget',
        sigma=0.6,
        use_score=True,
        with_kp=True,
        with_limb=False),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='PackActionInputs')
]
val_pipeline = [
    dict(type='UniformSampleFrames', clip_len=48, num_clips=1, test_mode=True),
    dict(type='PoseDecode'),
    dict(type='PoseCompact', hw_ratio=1.0, allow_imgpad=True),
    dict(type='Resize', scale=(-1, 64)),
    dict(type='CenterCrop', crop_size=64),
    dict(
        type='GeneratePoseTarget',
        sigma=0.6,
        use_score=True,
        with_kp=True,
        with_limb=False),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='PackActionInputs')
]
test_pipeline = [
    dict(
        type='UniformSampleFrames', clip_len=48, num_clips=10, test_mode=True),
    dict(type='PoseDecode'),
    dict(type='PoseCompact', hw_ratio=1.0, allow_imgpad=True),
    dict(type='Resize', scale=(-1, 64)),
    dict(type='CenterCrop', crop_size=64),
    dict(
        type='GeneratePoseTarget',
        sigma=0.6,
        use_score=True,
        with_kp=True,
        with_limb=False,
        double=True,
        left_kp=[1, 3, 5, 7, 9, 11, 13, 15],
        right_kp=[2, 4, 6, 8, 10, 12, 14, 16]),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='PackActionInputs')
]
train_dataloader = dict(
    batch_size=16,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='PoseDataset',
        ann_file=
        '/media/6t/XJY_FILES/Gym/mmaction2-master/tools/data/gym/gym_hrnet.pkl',
        split='train',
        pipeline=[
            dict(type='UniformSampleFrames', clip_len=48),
            dict(type='PoseDecode'),
            dict(type='PoseCompact', hw_ratio=1.0, allow_imgpad=True),
            dict(type='Resize', scale=(-1, 64)),
            dict(type='RandomResizedCrop', area_range=(0.56, 1.0)),
            dict(type='Resize', scale=(56, 56), keep_ratio=False),
            dict(
                type='Flip',
                flip_ratio=0.5,
                left_kp=[1, 3, 5, 7, 9, 11, 13, 15],
                right_kp=[2, 4, 6, 8, 10, 12, 14, 16]),
            dict(
                type='GeneratePoseTarget',
                sigma=0.6,
                use_score=True,
                with_kp=True,
                with_limb=False),
            dict(type='FormatShape', input_format='NCTHW'),
            dict(type='PackActionInputs')
        ]))
val_dataloader = dict(
    batch_size=16,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='PoseDataset',
        ann_file=
        '/media/6t/XJY_FILES/Gym/mmaction2-master/tools/data/gym/gym_hrnet.pkl',
        split='val',
        pipeline=[
            dict(
                type='UniformSampleFrames',
                clip_len=48,
                num_clips=1,
                test_mode=True),
            dict(type='PoseDecode'),
            dict(type='PoseCompact', hw_ratio=1.0, allow_imgpad=True),
            dict(type='Resize', scale=(-1, 64)),
            dict(type='CenterCrop', crop_size=64),
            dict(
                type='GeneratePoseTarget',
                sigma=0.6,
                use_score=True,
                with_kp=True,
                with_limb=False),
            dict(type='FormatShape', input_format='NCTHW'),
            dict(type='PackActionInputs')
        ],
        test_mode=True))
test_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='PoseDataset',
        ann_file=
        '/media/6t/XJY_FILES/Gym/mmaction2-master/tools/data/gym/gym_hrnet.pkl',
        split='val',
        pipeline=[
            dict(
                type='UniformSampleFrames',
                clip_len=48,
                num_clips=10,
                test_mode=True),
            dict(type='PoseDecode'),
            dict(type='PoseCompact', hw_ratio=1.0, allow_imgpad=True),
            dict(type='Resize', scale=(-1, 64)),
            dict(type='CenterCrop', crop_size=64),
            dict(
                type='GeneratePoseTarget',
                sigma=0.6,
                use_score=True,
                with_kp=True,
                with_limb=False,
                double=True,
                left_kp=[1, 3, 5, 7, 9, 11, 13, 15],
                right_kp=[2, 4, 6, 8, 10, 12, 14, 16]),
            dict(type='FormatShape', input_format='NCTHW'),
            dict(type='PackActionInputs')
        ],
        test_mode=True))
val_evaluator = dict(type='AccMetric')
test_evaluator = [
    dict(type='AccMetric'),
    dict(
        type='DumpResults',
        out_file_path=
        './output_files/slowonly_r50_u48_240e_gym_Kp_amp_best.pkl'
    )
]
train_cfg = dict(
    type='EpochBasedTrainLoop', max_epochs=240, val_begin=1, val_interval=1)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')
param_scheduler = [
    dict(
        type='CosineAnnealingLR',
        eta_min=0,
        T_max=240,
        by_epoch=True,
        convert_to_iter_based=True)
]
optim_wrapper = dict(
    optimizer=dict(type='SGD', lr=0.05, momentum=0.9, weight_decay=0.0003),
    clip_grad=dict(max_norm=40, norm_type=2))
workflow = [('train', 1), ('val', 1)]
evaluation = dict(
    interval=1,
    save_best='mean_class_accuracy',
    metrics=['top_k_accuracy', 'mean_class_accuracy'],
    topk=(1, 5))
dist_params = dict(backend='nccl')
log_config = dict(interval=20, hooks=[dict(type='TextLoggerHook')])
work_dir = './work_dirs/posec3d/slowonly_r50_u48_240e_gym_Kp_amp'
launcher = 'pytorch'
```

### Here is my Key error:
```
03/08 16:41:06 - mmengine - WARNING - Failed to import `None.registry` make sure the registry.py exists in `None` package.
03/08 16:41:06 - mmengine - WARNING - Failed to search registry with scope "mmaction" in the "visualizer" registry tree. As a workaround, the current "visualizer" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmaction" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "/media/6t/XJY_FILES/Gym/mmaction2-1.x/tools/test.py", line 118, in <module>
    main()
  File "/media/6t/XJY_FILES/Gym/mmaction2-1.x/tools/test.py", line 111, in main
    runner = Runner.from_cfg(cfg)
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/mmengine/runner/runner.py", line 431, in from_cfg
    runner = cls(
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/mmengine/runner/runner.py", line 385, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/mmengine/runner/runner.py", line 767, in build_visualizer
    return VISUALIZERS.build(visualizer)
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'ActionVisualizer is not in the visualizer registry. Please check whether the value of `ActionVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
Traceback (most recent call last):
  File "/media/6t/XJY_FILES/Gym/mmaction2-1.x/tools/test.py", line 118, in <module>
    main()
  File "/media/6t/XJY_FILES/Gym/mmaction2-1.x/tools/test.py", line 111, in main
    runner = Runner.from_cfg(cfg)
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/mmengine/runner/runner.py", line 431, in from_cfg
    runner = cls(
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/mmengine/runner/runner.py", line 385, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/mmengine/runner/runner.py", line 767, in build_visualizer
    return VISUALIZERS.build(visualizer)
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'ActionVisualizer is not in the visualizer registry. Please check whether the value of `ActionVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2715337) of binary: /media/6t/anaconda3/envs/open-mmlab-1.x/bin/python
Traceback (most recent call last):
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
```

**Comment by a-github-learner** [comment]
@wkq-wukaiqi  Thank you for your timely reply! I checked the version of my mmengine and found it was 0.6.0. Then I ran the command: ` pip install -v -e . ` under mmaction2-1.x folder and mmaction2-1.x environment, then the problem is solved. There might be something wrong with basic packages and cause this problem.
Here is my log information :
```
Using pip 22.3.1 from /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/pip (python 3.8)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///media/6t/XJY_FILES/Gym/mmaction2-1.x
  Running command python setup.py egg_info
  running egg_info
  creating /tmp/pip-pip-egg-info-7hcet2rc/mmaction2.egg-info
  writing /tmp/pip-pip-egg-info-7hcet2rc/mmaction2.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-7hcet2rc/mmaction2.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-7hcet2rc/mmaction2.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-7hcet2rc/mmaction2.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-7hcet2rc/mmaction2.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-7hcet2rc/mmaction2.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-7hcet2rc/mmaction2.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Requirement already satisfied: decord>=0.4.1 in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from mmaction2==1.0.0rc3) (0.6.0)
Requirement already satisfied: einops in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from mmaction2==1.0.0rc3) (0.6.0)
Requirement already satisfied: matplotlib in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from mmaction2==1.0.0rc3) (3.7.0)
Requirement already satisfied: numpy in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from mmaction2==1.0.0rc3) (1.23.5)
Requirement already satisfied: opencv-contrib-python in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from mmaction2==1.0.0rc3) (4.7.0.72)
Requirement already satisfied: Pillow in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from mmaction2==1.0.0rc3) (9.3.0)
Requirement already satisfied: scipy in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from mmaction2==1.0.0rc3) (1.10.1)
Requirement already satisfied: torch>=1.3 in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from mmaction2==1.0.0rc3) (1.13.1+cu116)
Requirement already satisfied: typing-extensions in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from torch>=1.3->mmaction2==1.0.0rc3) (4.4.0)
Requirement already satisfied: python-dateutil>=2.7 in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from matplotlib->mmaction2==1.0.0rc3) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from matplotlib->mmaction2==1.0.0rc3) (4.38.0)
Requirement already satisfied: packaging>=20.0 in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from matplotlib->mmaction2==1.0.0rc3) (23.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from matplotlib->mmaction2==1.0.0rc3) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from matplotlib->mmaction2==1.0.0rc3) (0.11.0)
Requirement already satisfied: pyparsing>=2.3.1 in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from matplotlib->mmaction2==1.0.0rc3) (3.0.9)
Requirement already satisfied: importlib-resources>=3.2.0 in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from matplotlib->mmaction2==1.0.0rc3) (5.12.0)
Requirement already satisfied: contourpy>=1.0.1 in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from matplotlib->mmaction2==1.0.0rc3) (1.0.7)
Requirement already satisfied: zipp>=3.1.0 in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib->mmaction2==1.0.0rc3) (3.15.0)
Requirement already satisfied: six>=1.5 in /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib->mmaction2==1.0.0rc3) (1.16.0)
Installing collected packages: mmaction2
  Running setup.py develop for mmaction2
    Running command python setup.py develop
    running develop
    running egg_info
    writing mmaction2.egg-info/PKG-INFO
    writing dependency_links to mmaction2.egg-info/dependency_links.txt
    writing requirements to mmaction2.egg-info/requires.txt
    writing top-level names to mmaction2.egg-info/top_level.txt
    reading manifest file 'mmaction2.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    writing manifest file 'mmaction2.egg-info/SOURCES.txt'
    running build_ext
    Creating /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/mmaction2.egg-link (link to .)
    Adding mmaction2 1.0.0rc3 to easy-install.pth file

    Installed /media/6t/XJY_FILES/Gym/mmaction2-1.x
    /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /media/6t/anaconda3/envs/open-mmlab-1.x/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
Successfully installed mmaction2-1.0.0rc3
```

**Comment by YuktiADY** [comment]
> I just had the same problem, and I checked my mmengine version by running this command: `python -c 'import mmengine;print(mmengine.__version__)'` Mine was too old and after I update it to version 0.6.0, this problem is solved.

Hello ,

I am also facing the same issue.

I have checked the mmengine version its 0.6.0.

Intitially I have cloned or downloaded the repository . when i check using git branch it shows 'master'

Since i have to do 3d action and 2d action recogntion. I upgrade to main branch using the below command

git clone --branch main https://github.com/open-mmlab/mmaction2.git

After doing when i check git branch it shows branch 'main'

When i run training script.
I have cloned or downloaded the repository . when i check using git branch it shows 'master'

Since i have to do 3d action and 2d action recogntion. How can i upgrade to main branch .

Can i do in the same folder where i cloned the repo with this command.
git clone --branch main https://github.com/open-mmlab/mmaction2.git

After doing when i check git branch it shows branch 'main'

When i run the training script
python tools/train.py configs/skeleton/stgcn/stgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-3d.py --work-dir ./work_dirs/stgcn_80e_ntu60_xsub_keypoint_3d/omnilab_today --seed 0 --deterministic --cfg-options  gpu_ids=[0]

Traceback 
raceback (most recent call last):
  File "/home/yukti/mmaction2/mmaction2/tools/train.py", line 135, in <module>
    main()
  File "/home/yukti/mmaction2/mmaction2/tools/train.py", line 128, in main
    runner = Runner.from_cfg(cfg)
  File "/home/yukti/miniconda3/envs/demo_copy1/lib/python3.10/site-packages/mmengine/runner/runner.py", line 431, in from_cfg
    runner = cls(
  File "/home/yukti/miniconda3/envs/demo_copy1/lib/python3.10/site-packages/mmengine/runner/runner.py", line 385, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "/home/yukti/miniconda3/envs/demo_copy1/lib/python3.10/site-packages/mmengine/runner/runner.py", line 767, in build_visualizer
    return VISUALIZERS.build(visualizer)
  File "/home/yukti/miniconda3/envs/demo_copy1/lib/python3.10/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/yukti/miniconda3/envs/demo_copy1/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'ActionVisualizer is not in the visualizer registry. Please check whether the value of `ActionVisualizer` is correct r it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

Can you please help how did you solve this issue ?

**Comment by gzy12138** [comment]
Modify the following part of the code:
![image](https://user-images.githubusercontent.com/109784769/231721695-b9c6d0dc-a330-433a-844d-5029d69b2478.png)

**Comment by cir7** [comment]
This problem may be due to some upstream packages not being installed correctly, or a version incompatibility issue.  
For users who encounter this problem, please check your running environment, and make sure it satisfies the requirements as mentioned in [installation doc](https://mmaction2.readthedocs.io/en/latest/get_started/installation.html#troubleshooting).

**Comment by Li-XYi** [comment]
Sometimes, maybe this config file `/media/6t/XJY_FILES/Gym/mmaction2-1.x/configs/skeleton/posec3d/slowonly_r50_u48_240e_gym_amp.py` doesn't extend the base config ‘default_runtime.py’ in `mmaction2/configs/_base_`. 

you could try to add "\_base\_ = \'mmaction2/configs/\_base\_/default_runtime.py\' " at the top of your config file like this:

```bash
_base_ = 'mmaction2/configs/_base_/default_runtime.py'  # you should use your own path of the default_runtime.py file

default_scope = 'mmaction'
default_hooks = dict(
    runtime_info=dict(type='RuntimeInfoHook'),
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=20, ignore_last=False),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(
        type='CheckpointHook', interval=1, save_best='auto', max_keep_ckpts=3),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    sync_buffers=dict(type='SyncBuffersHook'))
env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
log_processor = dict(type='LogProcessor', window_size=20, by_epoch=True)
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='ActionVisualizer', vis_backends=[dict(type='LocalVisBackend')])
log_level = 'INFO'
load_from = '/media/6t/XJY_FILES/Gym/mmaction2-1.x/work_dirs/posec3d/slowonly_r50_u48_240e_gym_Kp_amp/best_acc/top1_epoch_227.pth'
resume = False
……

```

hope to help you!
