### ISSUE TITLE
Training on Custom Dataset.

### ISSUE THREAD

**Issue by YuktiADY** [open-mmlab/mmaction2#2278]
Hello Team,

I am doing skeletal based action recognition using STGCN method where my annotation is .jsonformat where in my dataset I am feeding the poses. 
Below is the format of my annotation:
"images": [{"file_name": "xxxx.png", "id": xxxx, "width": 1200, "height": 1200, "coco_url": "", "flickr_url": "", "license": 1, "date_captured": "xx-xx-xx", "cvat_task_id": "162", "action": "turnleft", "performer": "xxxx", "room": "livingroom"}. There are total 16 actions .

I can feed the direct poses or joints as input as annotation file in xml format ? Is it necessary to use annotation file in json format.

When i am trying to train the model i am getting this error:

Traceback (most recent call last):
  File "tools/train.py", line 222, in <module>
    main()
  File "tools/train.py", line 218, in main
    meta=meta)
  File "/home/yukti/mmaction2/mmaction/apis/train.py", line 232, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yukti/mmaction2/mmaction/datasets/base.py", line 289, in __getitem__
    return self.prepare_train_frames(idx)
  File "/home/yukti/mmaction2/mmaction/datasets/base.py", line 252, in prepare_train_frames
    results = copy.deepcopy(self.video_infos[idx])
KeyError: 2

I think i need to make in two changes in base.py file 

1.  def load_json_annotations(self):
        """Load json annotation file to get video information."""
        video_infos = mmcv.load(self.ann_file)
        num_videos = len(video_infos)
        path_key = 'frame_dir' if 'frame_dir' in video_infos[0] else 'filename'
        for i in range(num_videos):
            path_value = video_infos[i][path_key]
            if self.data_prefix is not None:
                path_value = osp.join(self.data_prefix, path_value)
            video_infos[i][path_key] = path_value
            if self.multi_class:
                assert self.num_classes is not None
            else:
                assert len(video_infos[i]['label']) == 1
                video_infos[i]['label'] = video_infos[i]['label'][0]
        return video_infos

2. def evaluate(self,
                 results,
                 metrics='top_k_accuracy',
                 metric_options=dict(top_k_accuracy=dict(topk=(1, 5))),
                 logger=None,
                 **deprecated_kwargs):

**Comment by cir7** [comment]
@YuktiADY 
could you share your entire training config?

**Comment by YuktiADY** [comment]
> @YuktiADY could you share your entire training config?

@cir7  Please find below the config:

model = dict(
    type='SkeletonGCN',
    backbone=dict(
        type='STGCN',
        in_channels=3,
        edge_importance_weighting=True,
        graph_cfg=dict(layout='coco', strategy='spatial')),
    cls_head=dict(
        type='STGCNHead',
        #num_classes=60,
        num_classes=16,
        in_channels=256,
        loss_cls=dict(type='CrossEntropyLoss')),
    train_cfg=None,
    test_cfg=None)

#dataset_type = 'PoseDataset'
dataset_type = 'OmnilabDataset'
#ann_file_train = 'data/posec3d/ntu60_xsub_train.pkl'
ann_file_train = '/home/yukti/mmaction2/Dataset/train_dataset.json'
#ann_file_val = 'data/posec3d/ntu60_xsub_val.pkl'
ann_file_val = '/home/yukti/mmaction2/Dataset/val_dataset.json'
train_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM'),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoints', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoints'])
]
val_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM'),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]
test_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM'),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]
data = dict(
    videos_per_gpu=16,
    workers_per_gpu=2,
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix='',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix='',
        pipeline=val_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix='',
        pipeline=test_pipeline))

# optimizer
optimizer = dict(
    type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0001, nesterov=True)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='step', step=[10, 50])
total_epochs = 80
checkpoint_config = dict(interval=5)
evaluation = dict(interval=5, metrics=['top_k_accuracy'])
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])

# runtime settings
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/stgcn_80e_ntu60_xsub_keypoint/'
load_from = None
resume_from = None
workflow = [('train', 1)]

**Comment by cir7** [comment]
@YuktiADY 
why do you want to build a custom dataset and what have you modified?

**Comment by YuktiADY** [comment]
> @YuktiADY why do you want to build a custom dataset and what have you modified?

@cir7  the dataset i am using is custom, and have to use for M.thesis. I am basically passing a json as input to the train_pipeline which has the following: info, license, category, images and annotations (LIKE COCO FORMAT)
_______
train_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM'),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])

**So could you tell me, what are these TYPE**

Do I have to make changes in this dict: type as per my json file?
**for instance: type=info or type=annotations, keys=[annotations]**

Can you clarify this??

**Comment by cir7** [comment]
@YuktiADY 
I suggest you convert your dataset to the format we used, rather than build a custom dataset. we provide several pose anno pkl, you can take them as reference.
`train_pipline` consists of data transforms, which transform the original json file to a tensor feed into the network.
`type` is the transform class type, and remain keys are the args for the transform.
I strongly recommend you read the [document](https://mmaction2.readthedocs.io/en/latest/tutorials/1_config.html) to understand the structure of the codebase.

**Comment by YuktiADY** [comment]
@cir7 

 def prepare_train_frames(self, idx):
        """Prepare the frames for training given the index."""
        results = copy.deepcopy(self.video_infos[idx])

Could you please tell me what index value is it fetching? are these index values for each frame per video or what???

For example:
frame 0: 000000.jpg
frame 1: 000001.jpg

Are these the index, 0,1 ..... that it is fetching??

NEED SOME CLARIFICATION :))))

**Comment by YuktiADY** [comment]
> @YuktiADY the `idx` is the video index in data list, same as `index` in `__getitem__()` of `torch.utils.data.Dataset`. frame index is generated in `SampleFrames`. If you have no additional requirements, I don't think it is necessary to customize the dataset.

@cir7 
I checked the pkl file using
import pickle
with open('data/gym_val.pkl', 'rb') as f:
    data = pickle.load(f)

I found that type(data) is LIST. Please below :
Then i need to convert my json to list of dictionaries then it should work ..
{'frame_dir': '0LtLS9wROrk_002407_002435_0019_0021',
 'label': 79,
 'img_shape': (720, 1280),
 'original_shape': (720, 1280),
 'total_frames': 53,
 'keypoint': array([[[[646. , 332.2],
          [648.5, 332.2],
          [604. , 176.6]]]], dtype=float16),
 'keypoint_score': array([[[0.5054 , 0.5674 , 0.6274 , 0.529  , 0.4932 , 0.3323 , 0.3145 ,
          0.4375 , 0.3315 , 0.519  , 0.3972 , 0.4734 , 0.5303 , 0.4268 ,
          0.4158 , 0.4873 , 0.5044 ],
         [0.6895 , 0.739  , 0.802  , 0.6284 , 0.758  , 0.642  , 0.7305 ,
          0.822  , 0.6846 , 0.9097 , 0.8057 , 0.684  , 0.6855 , 0.8794 ,
          0.8037 , 0.576  , 0.55   ]]], dtype=float16)}

**Comment by YuktiADY** [comment]
@cir7  Could you please answer my queries. It will be really helpful. Else i cant proceed with work Thesis work as there is a deadline.

Hope you understand.

Thanks in advance !

**Comment by Dai-Wenxun** [comment]
Could you please give me an example of your JSON file?

**Comment by Dai-Wenxun** [comment]
You must organize your data format according to [ntu60_val](https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_val.pkl). These keys are required if you use our `PoseDataset` and the `pipeline` you are using now: `label, img_shape, total_frames, and keypoint`. Note that the shape of the `keypoint` is `(num_persion, total_frames, num_keypoints (e.g., for COCO-17, this value is 17), 2 (corresponding the x, y coordinates respectively))`. The key, `img_shape`, will be used in `PoseNormalize` to normalize the data distribution if you are using 2D skeleton data.

**Comment by YuktiADY** [comment]
> {"description": "", "url": "", "version": "1.0", "year": "2023", "contributor": "", "date_created": "02/05/23"}, [{"url": "", "id": 1, "name": ""}], [{"supercategory": "person", "id": 1, "name": "person", "keypoints": ["nose", "left_eye", "right_eye", "left_ear", "right_ear", "left_shoulder", "right_shoulder", "left_elbow", "right_elbow", "left_wrist", "right_wrist", "left_hip", "right_hip", "left_knee", "right_knee", "left_ankle", "right_ankle"], "skeleton": [[16, 14], [14, 12], [17, 15], [15, 13], [12, 13], [6, 12], [7, 13], [6, 7], [6, 8], [7, 9], [8, 10], [9, 11], [2, 3], [1, 2], [1, 3], [2, 4], [3, 5], [4, 6], [5, 7]]}], [{"file_name": "xxxx.png", "id": 2082, "width": 1200, "height": 1200, "coco_url": "", "flickr_url": "", "license": 1, , "cvat_task_id": "162", "action": "turnleft", "performer": "xxx", "room": "xxx"], [{"iscrowd": 0, "category_id": 1, "id": 0, "image_id": 2082, "bbox": [766.0, 447.5, 230.0, 135.0], "area": 31050.0, "num_keypoints": 17, "keypoints": [945.44, 463.19, 2, 949.47, 463.19, 2, 949.5, 461.2, 1, 953.49, 473.26, 2, 975.9, 493.4, 1, 903.15, 491.38, 2, 945.44, 521.59, 2, 858.84, 493.4, 2, 915.23, 547.77, 2, 832.66, 483.33, 2, 891.06, 559.85, 2, 852.8, 519.58, 2, 870.92, 537.7, 2, 821.0, 537.9, 2, 838.7, 527.63, 1, 780.3, 569.92, 2, 814.9, 522.8, 2]}

@Dai-Wenxun  This is the structure of my json annotation file

{"description": "", "url": "", "version": "1.0", "year": "2023", "contributor": "", "date_created": "02/05/23"}, [{"url": "", "id": 1, "name": ""}], [{"supercategory": "person", "id": 1, "name": "person", "keypoints": ["nose", "left_eye", "right_eye", "left_ear", "right_ear", "left_shoulder", "right_shoulder", "left_elbow", "right_elbow", "left_wrist", "right_wrist", "left_hip", "right_hip", "left_knee", "right_knee", "left_ankle", "right_ankle"], "skeleton": [[16, 14], [14, 12], [17, 15], [15, 13], [12, 13], [6, 12], [7, 13], [6, 7], [6, 8], [7, 9], [8, 10], [9, 11], [2, 3], [1, 2], [1, 3], [2, 4], [3, 5], [4, 6], [5, 7]]}], [{"file_name": "xxxx.png", "id": 2082, "width": 1200, "height": 1200, "coco_url": "", "flickr_url": "", "license": 1, , "cvat_task_id": "162", "action": "turnleft", "performer": "xxx", "room": "xxx"], [{"iscrowd": 0, "category_id": 1, "id": 0, "image_id": 2082, "bbox": [766.0, 447.5, 230.0, 135.0], "area": 31050.0, "num_keypoints": 17, "keypoints": [945.44, 463.19, 2, 949.47, 463.19, 2, 949.5, 461.2, 1, 953.49, 473.26, 2, 975.9, 493.4, 1, 903.15, 491.38, 2, 945.44, 521.59, 2, 858.84, 493.4, 2, 915.23, 547.77, 2, 832.66, 483.33, 2, 891.06, 559.85, 2, 852.8, 519.58, 2, 870.92, 537.7, 2, 821.0, 537.9, 2, 838.7, 527.63, 1, 780.3, 569.92, 2, 814.9, 522.8, 2]}
Awaiting your response.

**Comment by YuktiADY** [comment]
> You must organize your data format according to [ntu60_val](https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_val.pkl). These keys are required if you use our `PoseDataset` and the `pipeline` you are using now: `label, img_shape, total_frames, and keypoint`. Note that the shape of the `keypoint` is `(num_persion, total_frames, num_keypoints (e.g., for COCO-17, this value is 17), 2 (corresponding the x, y coordinates respectively))`. The key, `img_shape`, will be used in `PoseNormalize` to normalize the data distribution if you are using 2D skeleton data.

@cir7 I did some changes in the config which are below

dataset_type = 'MyDataset'
ann_file_val = '/home/yukti/mmaction2/Dataset/val_dataset.json'
train_pipeline = [
    dict(type='PaddingWithLoop', clip_len=300),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', input_format='NCTVM'),
    dict(type='PoseNormalize'),
    dict(type='Collect', keys=['keypoints', 'action'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])

2. Also created class of my dataset  (@DATASETS.register_module()
class MyDataset(BaseDataset):

Changed this function as mine is json file 
def load_annotations(self):
        """Load annotation file to get video information."""
        #assert self.ann_file.endswith('.pkl')
        assert self.ann_file.endswith('.json')
        return self.load_json_annotations()
        
So could you please tell me with my above shown json file how to proceed further ?

**Comment by cir7** [comment]
@YuktiADY 
just follow @Dai-Wenxun mentioned, convert your json file to the required format as a pkl file. As far as I have information so far, the `MyDataset` is not needed.

**Comment by YuktiADY** [comment]
@Dai-Wenxun @Cir7 If you look at my json which has frames . Do i need to make changes in ntu_pose_extraction.py 
How do i pass my images as i dont have video.
def extract_frame(video_path):
    dname = gen_id()
    os.makedirs(dname, exist_ok=True)
    frame_tmpl = osp.join(dname, 'img_{:05d}.jpg')
    vid = cv2.VideoCapture(video_path)
    frame_paths = []
    flag, frame = vid.read()
    cnt = 0
    while flag:
        frame_path = frame_tmpl.format(cnt + 1)
        frame_paths.append(frame_path)

        cv2.imwrite(frame_path, frame)
        cnt += 1
        flag, frame = vid.read()

    return frame_paths

**Comment by cir7** [comment]
@YuktiADY 
1. all keys in [ntu60_val](https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_val.pkl) are required. `frame_dir` can be any unique name for each video.  `img_shape` is (width, height). skeleton action recognition infers from a sequence of keypoints, and can't handle keypoints from one image, if the images can be concatenated as a video, you must reorganize the keypoints to shape like (num_persion, total_frames, num_keypoints (e.g., for COCO-17, this value is 17), 2 (corresponding the x, y coordinates respectively).
2. `ntu_pose_extraction.py` can only handle video input, you can modify the script or convert your images to a video.

**Comment by Dipankar1997161** [comment]
From the readme file for skeleton generator, the following question arise:

>>> So that we provide a script to generate pose annotations for videos in NTURGB+D datasets, which generate a dictionary and save it as a single pickle file. 

**Question: In this particular line, I believe,  the pickle file generated will consists of the keypoints, score, image_shape, ..... etc. Is this the case?**

>>> You can create a list which contain all annotation dictionaries of corresponding videos and save them as a pickle file. Then you can get the ntu60_xsub_train.pkl, ntu60_xsub_val.pkl, ntu120_xsub_train.pkl, ntu120_xsub_val.pkl that we used in training.

>>>> **You can create a list which contain all annotation dictionaries of corresponding videos.**

**Question: But in order to generate the above pickle file in my FIRST QUESTION, do I need to explicitly pass an annotation file in JSON or some other format for the model to generate the necessary skeleton ? or The pickle file generated from the video can be split into train, val pickle file for further training???** 

##  For example
I download a random video from google which is around 30 seconds long. DO I need to create an annotation file SEPARATELY for this sample video???  OR does the ntu_pose_extraction.py will generated all the necessary annotation for me??

Hope it was clear!! It is actually urgent since I am handling my thesis. With your help, I can move on to the next stages of training.

@YuktiADY  @cir7 @Dai-Wenxun

**Comment by cir7** [comment]
Hi, @Dipankar1997161
1. yes, the script will generate a pickle file that contains all keys mentioned above.
2. the script doesn't need any other input except a video. but the script can only process a single video each time, so you need to save them to a list, which can be used in our repo.
3. `pose_results` is a np.ndarray with shape `(num_person, num_frame, 17, 3)`, contains the keypoints info of the video 
4. the script `ntu_pose_extraction.py` is designed to process the NTU dataset, we can not guarantee its effectiveness on other videos.
5. I believe that all the answers can be found in the code. How about trying to read and debug them?

**Comment by Dipankar1997161** [comment]
@cir7 
Thanks for the response. 
Actually I read the code, however, I needed some clarification whether my interpretation was correct or not. Thanks for the input. 
I will read it again and make the changes wherever necessary for my own dataset, as you clearly mentioned that this file is specially designed for ntu dataset.

@YuktiADY  you can ask your questions if you wish to. I understood my part.

**Comment by YuktiADY** [comment]
@cir7 
so I created a pickle file as per ntu format, but the 'label' in your case is an integer
'label': 48,

however, in my case it is a string
'label': 'fall-on-face',

For this a class file would be required, lets say:
0: dancing
1: walking

and so one,

I found 1 file which is:
label_map_ntu120.txt

however, where is the following file accessed?? Because I would also have to create 1 and pass my file as well.

I have a total of 16 action class.

DO let me know. Have a great day

**Comment by cir7** [comment]
@YuktiADY 
the label is just an index, just map each category to an index as you want.  just make sure the label is from 0 to num_class - 1, 15 for your case.

**Comment by YuktiADY** [comment]
@cir7  I mapped the action according to an index. In my pickle file the values of kps score is 1 for all. I am getting the below error 
File "tools/train.py", line 218, in main
    meta=meta)
  File "/home/yukti/mmaction2/mmaction/apis/train.py", line 232, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yukti/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yukti/mmaction2/mmaction/datasets/base.py", line 303, in __getitem__
    return self.prepare_train_frames(idx)
  File "/home/yukti/mmaction2/mmaction/datasets/base.py", line 276, in prepare_train_frames
    return self.pipeline(results)
  File "/home/yukti/mmaction2/mmaction/datasets/pipelines/compose.py", line 50, in __call__
    data = t(data)
  File "/home/yukti/mmaction2/mmaction/datasets/pipelines/pose_loading.py", line 187, in __call__
    frame_inds].astype(np.float32)
IndexError: index 1 is out of bounds for axis 1 with size 1
Could you please guide me in this ?

**Comment by cir7** [comment]
@YuktiADY 
The log can't give enough info to locate the issue, it looks like the keypoint shape is not matched as required, my suggestion is to try to use the pickle data we provided and find the difference from your data.

**Comment by YuktiADY** [comment]
Thanks for the feedback @cir7 
@cir7 
I made the pickle file according to the format of NTU and tried training it and changing the hyperparameters (lr, no of epochs)
in the config  i changed the   num_classes=16,

2023-03-21 00:40:58,071 - mmaction - INFO - Saving checkpoint at 80 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 20/20, 11.9 task/s, elapsed: 2s, ETA:     0s2023-03-21 00:40:59,911 - mmaction - INFO - Evaluating top_k_accuracy ...
2023-03-21 00:40:59,911 - mmaction - INFO -
**top1_acc        0.0000
top5_acc        0.1500**

The top1_acc is seems to be 0.000 and top5_acc 0.1500. This means model is not learning only . Can you provide your valuable suggestion what can i do.

**Comment by cir7** [comment]
@YuktiADY
that is as expected. I have no idea why the performance is slow, you can try:
1.  visualize your dataset to make sure that it is as expected
2.  use pre-train checkpoint if your dataset is small
3.  try tuning hyperparameters.

**Comment by cir7** [comment]
@YuktiADY 
1. usually, val set and test set are the same, the model doesn't train on val set. you can split a test set as you want
2. Specifying load_from in config file is enough.

**Comment by YuktiADY** [comment]
@cir7 since my data is small . Could you please tell me way how can i increase my data i.e doing time series data augmentation. Each action has 60 frames. 

Awaiting for your response.

**Comment by Dipankar1997161** [comment]
@YuktiADY

I searched for a few papers for data augmentation, particularly for activity recognition. 
See if this helps

https://arxiv.org/abs/2109.01081

https://www.mdpi.com/2076-3417/11/23/11481

https://ieeexplore.ieee.org/document/8972313

Thanks.

**Comment by YuktiADY** [comment]
> You must organize your data format according to [ntu60_val](https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_val.pkl). These keys are required if you use our `PoseDataset` and the `pipeline` you are using now: `label, img_shape, total_frames, and keypoint`. Note that the shape of the `keypoint` is `(num_persion, total_frames, num_keypoints (e.g., for COCO-17, this value is 17), 2 (corresponding the x, y coordinates respectively))`. The key, `img_shape`, will be used in `PoseNormalize` to normalize the data distribution if you are using 2D skeleton data.



> @
> 
>     1. all keys in [ntu60_val](https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_val.pkl) are required. `frame_dir` can be any unique name for each video.  `img_shape` is (width, height). skeleton action recognition infers from a sequence of keypoints, and can't handle keypoints from one image, if the images can be concatenated as a video, you must reorganize the keypoints to shape like (num_persion, total_frames, num_keypoints (e.g., for COCO-17, this value is 17), 2 (corresponding the x, y coordinates respectively).
> 
>     2. `ntu_pose_extraction.py` can only handle video input, you can modify the script or convert your images to a video.

@cir7 @Dai-Wenxun  Is this  [ntu60_val](https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_val.pkl) pkl file same for 3d action recogntion too ? Because i have to do 3d action recogntion on my custom dataset.  
The  keys are 
'frame_dir':
  'label': 
  'img_shape': 
  'original_shape': 
  'total_frames': 
  'keypoint': x,y,z coordinates
  'keypoint_score': 
          
But this keypoint score key is required for 3d action ?
