### ISSUE TITLE
ValueError: Cannot infer the rule for key 0_char_recall, thus a specific rule must be specified.

### ISSUE THREAD

**Issue by miraclefan777** [open-mmlab/mmaction2#2298]
Traceback (most recent call last):
  File "tools/train.py", line 243, in <module>
    run_train_cmd(args)
  File "tools/train.py", line 231, in run_train_cmd
    train_detector(
  File "/gemini/code/mmocr/mmocr/apis/train.py", line 155, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/epoch_based_runner.py", line 58, in train
    self.call_hook('after_train_epoch')
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/hooks/evaluation.py", line 271, in after_train_epoch
    self._do_evaluate(runner)
  File "/usr/local/lib/python3.8/dist-packages/mmdet/core/evaluation/eval_hooks.py", line 63, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/hooks/evaluation.py", line 387, in evaluate
    self._init_rule(self.rule, list(eval_res.keys())[0])
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/hooks/evaluation.py", line 198, in _init_rule
    raise ValueError(f'Cannot infer the rule for key '
ValueError: Cannot infer the rule for key 0_char_recall, thus a specific rule must be specified.

**Comment by hukkai** [comment]
@miraclefan777 It seems the issue is from `mmocr`?
