### ISSUE TITLE
TypeError: forward_train() missing 2 required positional arguments: 'gt_bboxes' and 'gt_labels' From MMdetect even though i am training SlowFast from mmaction2

### ISSUE THREAD

**Issue by eliethesaiyan** [open-mmlab/mmaction2#2309]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
While training SlowFast with FastRCNN , Validation fails with the error above.However, the error comes from mmdetection even though i am not using any configuration related to mmdetect. 

I am training on custom Dataset that neet AVADataset requirements, indeed, training works well.However, everytime validation is started , i get the following error
```bash
2023-03-23 13:41:59,273 - mmaction - INFO - Epoch [1][210/213]  lr: 3.112e-03, eta: 0:00:02, time: 0.953, data_time: 0.000, memory: 20645, recall@thr=0.5: 0.7558, prec@thr=0.5: 0.7525, recall@top3: 0.9020, prec@top3: 0.3007, recall@top5: 0.9134, prec@top5: 0.1827, loss_action_cls: 0.2409, loss: 0.2409, grad_norm: 0.5401
2023-03-23 13:42:01,615 - mmaction - INFO - Saving checkpoint at 1 epochs
Traceback (most recent call last):
  File "trainer.py", line 58, in <module>
    run(cfg)
  File "trainer.py", line 22, in run
    train_model(model, datasets, cfg, distributed=False, validate=False)
  File "/home/jama/gitclones/behavior_recognition/mmaction2/mmaction/apis/train.py", line 232, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/jama/anaconda3/envs/jama/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/jama/anaconda3/envs/jama/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/jama/anaconda3/envs/load/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 72, in val
    self.run_iter(data_batch, train_mode=False)
  File "/home/jama/anaconda3/envs/jama/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 34, in run_iter
    outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)
  File "/home/jama/anaconda3/envs/jama/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 99, in val_step
    return self.module.val_step(*inputs[0], **kwargs[0])
  File "/home/jama/gitclones/behavior_recognition/mmdetection/mmdet/models/detectors/base.py", line 263, in val_step
    losses = self(**data)
  File "/home/jama/anaconda3/envs/jama/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jama/anaconda3/envs/jama/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/home/jama/gitclones/behavior_recognition/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
TypeError: forward_train() missing 2 required positional arguments: 'gt_bboxes' and 'gt_labels'
```
and my config is 
```python
model = dict(
    type='FastRCNN',
    backbone=dict(
        type='ResNet3dSlowFast',
        pretrained=None,
        resample_rate=8,
        speed_ratio=8,
        channel_ratio=8,
        slow_pathway=dict(
            type='resnet3d',
            depth=50,
            pretrained=None,
            lateral=True,
            conv1_kernel=(1, 7, 7),
            dilations=(1, 1, 1, 1),
            conv1_stride_t=1,
            pool1_stride_t=1,
            inflate=(0, 0, 1, 1),
            spatial_strides=(1, 2, 2, 1)),
        fast_pathway=dict(
            type='resnet3d',
            depth=50,
            pretrained=None,
            lateral=False,
            base_channels=8,
            conv1_kernel=(5, 7, 7),
            conv1_stride_t=1,
            pool1_stride_t=1,
            spatial_strides=(1, 2, 2, 1))),
    roi_head=dict(
        type='AVARoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor3D',
            roi_layer_type='RoIAlign',
            output_size=8,
            with_temporal_pool=True),
        bbox_head=dict(
            type='BBoxHeadAVA',
            in_channels=2304,
            num_classes=12,
            topk=(3,5),
            multilabel=True,
            dropout_ratio=0.5)),
    train_cfg=dict(
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssignerAVA',
                pos_iou_thr=0.9,
                neg_iou_thr=0.9,
                min_pos_iou=0.9),
            sampler=dict(
                type='RandomSampler',
                num=32,
                pos_fraction=1,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=1.0,
            debug=False)),
    test_cfg=dict(rcnn=dict(action_thr=0.002)))


dataset_type = 'AVADataset'


data_root = '/home/jama/data/behavior/data/ava/rawframes'
anno_root = '/home/jama/data/behaviordata/ava/annotations'
ann_file_train = f'{anno_root}/ava_train.csv'
ann_file_val = f'{anno_root}/ava_val.csv'

exclude_file_train = f'{anno_root}/excluded_timestamps.csv'
exclude_file_val = f'{anno_root}/excluded_timestamps.csv'

label_file = f'{anno_root}/activity.pbtxt'

proposal_file_train = (f'{anno_root}/train_proposal.pkl')
proposal_file_val = f'{anno_root}/val_proposal.pkl'

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)

train_pipeline = [
    dict(type='SampleAVAFrames', clip_len=32, frame_interval=1),
    dict(type='RawFrameDecode'),
    dict(type='RandomRescale', scale_range=(256,320)),
    dict(type='RandomCrop', size=256),
    dict(type='Flip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW', collapse=True),
    # Rename is needed to use mmdet detectors
    dict(type='Rename', mapping=dict(imgs='img')),
    dict(type='ToTensor', keys=['img', 'proposals', 'gt_bboxes', 'gt_labels']),
    dict(
        type='ToDataContainer',
        fields=[
            dict(key=['proposals', 'gt_bboxes', 'gt_labels'], stack=False)
        ]),
    dict(
        type='Collect',
        keys=['img', 'proposals', 'gt_bboxes', 'gt_labels'],
        meta_keys=['scores', 'entity_ids'])
]
# The testing is w/o. any cropping / flipping
val_pipeline = [
    dict(
        type='SampleAVAFrames', clip_len=32, frame_interval=1, test_mode=True),
    dict(type='RawFrameDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW', collapse=True),
    # Rename is needed to use mmdet detectors
    dict(type='Rename', mapping=dict(imgs='img')),
    dict(type='ToTensor', keys=['img', 'proposals','gt_bboxes','gt_labels']),
    dict(
        type='ToDataContainer', 
        fields=[
            dict(key=['proposals','gt_bboxes','gt_labels' ], stack=False)
        ]),
    dict(
        type='Collect',
        #keys=['img', 'proposals', 'gt_bboxes', 'gt_labels' ],
        #meta_keys=['scores', 'img_shape','gt_bboxes','gt_labels'],
        #nested=True)
        keys=['img', 'proposals' ],
        meta_keys=['scores', 'img_shape'],
        nested=True)
]

data = dict(
    videos_per_gpu=4,
    workers_per_gpu=4,
    val_dataloader=dict(videos_per_gpu=1),
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        num_classes=12,
        timestamp_end=8,
        exclude_file=exclude_file_train,
        pipeline=train_pipeline,
        label_file=label_file,
        proposal_file=proposal_file_train,
        person_det_score_thr=0.6,
        data_prefix=data_root),
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        num_classes=12,
        timestamp_end=8,
        exclude_file=exclude_file_val,
        pipeline=val_pipeline,
        label_file=label_file,
        proposal_file=proposal_file_val,
        person_det_score_thr=0.1,
        data_prefix=data_root))
data['test'] = data['val']

optimizer = dict(type='SGD', lr=0.1125, momentum=0.9, weight_decay=0.00001)
# this lr is used for 8 gpus

optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))
# learning policy

lr_config = dict(
    policy='step',
    step=[10, 15],
    warmup='linear',
    warmup_by_epoch=True,
    warmup_iters=5,
    warmup_ratio=0.1)
total_epochs = 4 #initially 66 
checkpoint_config = dict(interval=1)
workflow = [('train',1),('val',1)]
evaluation = dict(interval=1, save_best='mAP@0.5IOU')
log_config = dict(
    interval=20, hooks=[
        dict(type='TextLoggerHook'),
    ])
dist_params = dict(backend='nccl')
log_level = 'INFO'
#work_dir = ('./work_dirs/ava/'
            #'slowfast_kinetics_pretrained_r50_4x16x1_20e_ava_rgb')
#load_from = ('https://download.openmmlab.com/mmaction/recognition/slowfast/' 
#slowfast_r50_4x16x1_256e_kinetics400_rgb/' 'slowfast_r50_4x16x1_256e_kinetics400_rgb_20200704-bcde7ed7.pth')
resume_from = None
#find_unused_parameters = False
```
**Reproduction**

1. What command or script did you run?
My training script
```
import torch, torchvision
import mmaction
import mmcv
import os
import os.path as osp
from mmcv import Config
from mmcv.runner import set_random_seed
from mmaction.datasets import build_dataset
from mmaction.models import build_model
from mmaction.apis import train_model
from mmaction.apis import single_gpu_test
from mmaction.datasets import build_dataloader
from mmcv.parallel import MMDataParallel
set_random_seed(0, deterministic=False)

def run(cfg):
    datasets = [build_dataset(cfg.data.train)]
    datasets.append(build_dataset(cfg.data.val))
    model = build_model(cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('val_cfg'))
    mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
    print(f'Config:\n{cfg.pretty_text}')
    train_model(model, datasets, cfg, distributed=False, validate=True)

    #EVAL process
    dataset = build_dataset(cfg.data.test, dict(test_mode=True))
    data_loader = build_dataloader(
        dataset,
        videos_per_gpu=1,
        workers_per_gpu=cfg.data.workers_per_gpu,
        dist=False,
        shuffle=False)
model = MMDataParallel(model, device_ids=[0])
    outputs = single_gpu_test(model, data_loader)
    print('test')
    eval_config = cfg.evaluation
    eval_config.pop('interval', None)
    eval_config.pop('save_best', None)
    eval_res = dataset.evaluate(outputs, **eval_config)
    for name, val in eval_res.items():
        print(f'{name}: {val:.04f}')

if __name__ == '__main__':
    MMACTION_DIR = os.path.join(os.path.expanduser('~/'),'gitclones','behavior_recognition', 'mmaction2')
    cfg = Config.fromfile(os.path.join(MMACTION_DIR, 'configs/detection/ava/ava_4x16_1_20e.py'))
    cfg.setdefault('omnisource', False)
    cfg.data.videos_per_gpu = 18
    #cfg.optimizer.lr = cfg.optimizer.lr / 8 
    cfg.optimizer.lr = cfg.optimizer.lr / 10
    cfg.total_epochs = 1
    cfg.work_dir = './slow_fast_eval_' + str(cfg.total_epochs)
    cfg.load_from = './slow_fast_full_data66/latest.pth'
    cfg.checkpoint_config.interval = 5
    cfg.log_config.interval = 10
                                                                                                              
```

**Comment by eliethesaiyan** [comment]
@Dai-Wenxun , any idea?

**Comment by Dai-Wenxun** [comment]
I'm working on it.

**Comment by eliethesaiyan** [comment]
@Dai-Wenxun , thank you very much.
I traced the issue [here](https://github.com/open-mmlab/mmcv/blob/9fcf48c4c8cdb9d7b5f48f8f10aec08a3aaa3459/mmcv/runner/fp16_utils.py#L119) , It seems somehow, `forward_train` manages to have access to validation dataloader. At least,  i am seeing the keys used in `Collect` transform look similar to those of validation pipeline rather than  those used in `Collect` transform of training pipeline. I also think that the number of video loaded one gpu might have to do with it. Some [similar](https://github.com/open-mmlab/mmaction2/issues/421) but not the same issue.
```bash
 {'img': [tensor([[[[[ 2.1462,  1.1872,  1.2728,  ...,  1.3584,  1.3927,  1.4098],
           [ 2.2147,  1.3070,  1.2557,  ...,  1.4269,  1.4440,  1.4269],
           [ 2.2147,  1.5297,  1.2557,  ...,  1.4954,  1.4269,  1.4440],
           ...,
           [-0.7577, -0.7752, -0.7577,  ...,  0.2402,  0.2402,  0.2227],
           [-0.7752, -0.7927, -0.7577,  ...,  0.2227,  0.2402,  0.1527],
           [-0.7752, -0.7752, -0.7052,  ...,  0.1702,  0.1702,  0.1527]]   
       device='cuda:0')], 'proposals': [[tensor([[  0.,   0., 256., 455.]], device='cuda:0'),], device='cuda:0'), tensor([[  0.,   0., 256., 455.]], device='cuda:0'), tensor([[  0.,   0., 256., 455.]], device='cuda:0')]], 'img_metas': [[{'scores': array([1]), 'img_shape': (455, 256)}, {'scores': array([1]), 'img_shape': (455, 256)}, {'scores': array([1]), 'img_shape': (455, 256)}, {'scores': array([1]), 'img_shape': (455, 256)}, {'scores': array([1]), 'img_shape': (455, 256)}, {'scores': array([1]), 'img_shape': (455, 256)}, {'scores': array([1]), 'img_shape': (455, 256)}]]}
Traceback (most recent call last):
  File "trainer.py", line 58, in <module>
    run(cfg)
  File "trainer.py", line 22, in run
    train_model(model, datasets, cfg, distributed=False, validate=True)
  File "/home/jama/gitclones/behavior_recognition/mmaction2/mmaction/apis/train.py", line 232, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/jama/anaconda3/envs/jamat/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
   .......
   return self.forward_train(img, img_metas, **kwargs)
TypeError: forward_train() missing 2 required positional arguments: 'gt_bboxes' and 'gt_labels'
```

**Comment by eliethesaiyan** [comment]
@Dai-Wenxun , I also reduced the number of videos per gpu, 16,8,4,1. but it did not change anything.

**Comment by Dai-Wenxun** [comment]
![image](https://user-images.githubusercontent.com/58767402/227535010-93586575-3579-4dbd-ad61-5c703b6cb1e3.png)
Replace the referenced code with the following:
```
model = mode.cuda()
```
During the validation process, the detector should call `forward_test` instead of `forward_train`, which does not require 'gt_bboxes' and 'gt_labels'. The forward of the detector is controlled by `return_loss`, https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/base.py#L171-L174.

**Comment by eliethesaiyan** [comment]
@Dai-Wenxun .The initial code does reach that line. The error comes from 
`` train_model(model, datasets, cfg, distributed=False, validate=True)``
every second iteration after evaluation.
