### ISSUE TITLE
mmengine - Failed to import mmaction.models

### ISSUE THREAD

**Issue by ptoupas** [open-mmlab/mmaction2#2333]
Hi,

I have created a FRESH anaconda environment with `python 3.10`. I have installed `pytorch 1.13.1` with `CUDA 11.6` using the pip command as it is given in the official site with the instructions.

After that I have followed the instruction from the mmaction2 official site (https://mmaction2.readthedocs.io/en/1.x/get_started.html) and installed all the necessary dependencies with mim as instructed and the mmaction2 library on `1.x` branch from source using `pip install -v -e .` 

Everything was perfect up to this point. So i tried to verify the installation as instructed in the site as well by downloading a config and checkpoint file and trying to run the demo with the following command:
```
# The demo.mp4 and label_map_k400.txt are both from Kinetics-400
python demo/demo.py tsn_imagenet-pretrained-r50_8xb32-1x1x8-100e_kinetics400-rgb.py \
    tsn_imagenet-pretrained-r50_8xb32-1x1x8-100e_kinetics400-rgb_20220906-2692d16c.pth \
    demo/demo.mp4 tools/data/kinetics/label_map_k400.txt
```

I got the following error from the command above:
```
04/03 13:21:30 - mmengine - WARNING - Failed to import mmaction.models, please check the location of the registry model is correct.
Traceback (most recent call last):
  File "/home/ptoupas/Development/mmaction2/demo/demo.py", line 158, in <module>
    main()
  File "/home/ptoupas/Development/mmaction2/demo/demo.py", line 119, in main
    model = init_recognizer(cfg, args.checkpoint, device=args.device)
  File "/home/ptoupas/Development/mmaction2/mmaction/apis/inference.py", line 44, in init_recognizer
    model = MODELS.build(config.model)
  File "/home/ptoupas/anaconda3/envs/py310/lib/python3.10/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/ptoupas/anaconda3/envs/py310/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 241, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ptoupas/anaconda3/envs/py310/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'Recognizer2D is not in the model registry. Please check whether the value of `Recognizer2D` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
```

Has anyone seen this before or know what might causing this issue?

PS:
Trying to generate this issue I wanted to follow the instructions and tried to get the necessary environment information using this command `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` and i got the following error as well so this is why I haven't provided the respective info:
```
Traceback (most recent call last):
  File "/home/ptoupas/Development/mmaction2/mmaction/utils/collect_env.py", line 2, in <module>
    from mmengine.utils import get_git_hash
  File "/home/ptoupas/anaconda3/envs/py310/lib/python3.10/site-packages/mmengine/__init__.py", line 3, in <module>
    from .config import *
  File "/home/ptoupas/anaconda3/envs/py310/lib/python3.10/site-packages/mmengine/config/__init__.py", line 2, in <module>
    from .config import Config, ConfigDict, DictAction
  File "/home/ptoupas/anaconda3/envs/py310/lib/python3.10/site-packages/mmengine/config/config.py", line 15, in <module>
    from typing import Any, Optional, Sequence, Tuple, Union
  File "/home/ptoupas/Development/mmaction2/mmaction/utils/typing.py", line 3, in <module>
    from typing import Dict, List, Optional, Tuple, Union
ImportError: cannot import name 'Dict' from partially initialized module 'typing' (most likely due to a circular import) (/home/ptoupas/Development/mmaction2/mmaction/utils/typing.py)
```

**Comment by leexinhao** [comment]
You could see [issue2201](https://github.com/open-mmlab/mmaction2/issues/2201), just change the name of `mmaction/utils/typing.py` such as `xx_typing.py`.

**Comment by ptoupas** [comment]
@leexinhao Thanks a lot for that, but that's a side issue problem which I only found when posting the original issue.
The main question is regarding the `failed to import mmaction.models` thing.

**Comment by leexinhao** [comment]
> @leexinhao Thanks a lot for that, but that's a side issue problem which I only found when posting the original issue. The main question is regarding the `failed to import mmaction.models` thing.

Can you import the `mmaction.models` successfully in other cases? And did you modify the original `demo.py`? In my experience, if the environment is installed correctly, this error is usually caused by incorrect modifications in the script

**Comment by ptoupas** [comment]
@leexinhao I can import `mmaction.models` in a clean script. I think the issue comes from the mmengine and the specific version which I am using there. Is there any combination of mmaction mmcv and mmengine which might not work?

**Comment by leexinhao** [comment]
The safest way to install both libraries is to use the source code, especially mmcv, which contains some cuda operators that might not work properly with mim or pip.

**Comment by ptoupas** [comment]
@leexinhao Alright thanks I will have that in mind. However I got the following combination of mm libraries working in case anyone come across the same problem.
```
mmaction2             1.0.0rc3 
mmcv                  2.0.0rc4
mmdet                 3.0.0rc6
mmengine              0.7.1
```
One note here is that I have used pip instead of mim (I think with mim the same setup was not working properly)
