### ISSUE TITLE
IndexError: AVADataset: index 2 is out of bounds for axis 0 with size 2

### ISSUE THREAD

**Issue by Rainforest-jpg** [open-mmlab/mmaction2#2354]
### Branch

master branch (0.x version, such as `v0.10.0`, or `dev` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

get this problem when I train my dataset. It do not happen, when I just train one label, after trainning two label the error happened.

### Describe the bug

2023-04-08 13:46:35,209 - mmaction - INFO - Set random seed to 2061779335, deterministic: False
Traceback (most recent call last):
  File "D:\anaconda3\envs\mmaction2\lib\site-packages\mmcv\utils\registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "D:\mmaction2\mmaction2-master\mmaction\datasets\ava_dataset.py", line 139, in __init__
    super().__init__(
  File "D:\mmaction2\mmaction2-master\mmaction\datasets\base.py", line 89, in __init__
    self.video_infos = self.load_annotations()
  File "D:\mmaction2\mmaction2-master\mmaction\datasets\ava_dataset.py", line 259, in load_annotations
    bboxes, labels, entity_ids = self.parse_img_record(
  File "D:\mmaction2\mmaction2-master\mmaction\datasets\ava_dataset.py", line 197, in parse_img_record
    label[valid_labels] = 1.
IndexError: index 2 is out of bounds for axis 0 with size 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\mmaction2\mmaction2-master\tools\train.py", line 226, in <module>
    main()
  File "D:\mmaction2\mmaction2-master\tools\train.py", line 194, in main
    datasets = [build_dataset(cfg.data.train)]
  File "D:\mmaction2\mmaction2-master\mmaction\datasets\builder.py", line 40, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "D:\anaconda3\envs\mmaction2\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
IndexError: AVADataset: index 2 is out of bounds for axis 0 with size 2

Process finished with exit code 1

**Comment by Rainforest-jpg** [comment]
I used mmaction2 containing slowfast，to do this project. and https://www.bilibili.com/video/av212321328/?vd_source=4e6282d0c36125b6e7df4389e94ed7a9 is the trainning method.

**Comment by Rainforest-jpg** [comment]
the num_classes haven't increased.

**Comment by FMK-ai** [comment]
“IndexError: index 2 is out of bounds for axis 0 with size 2”  Pls have you solved this problem
