### ISSUE TITLE
demo_spatiotemporal_det.py error 2

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [open-mmlab/mmaction2#2393]
### The doc issue

When I run demo_spatiotemporal_det.py, the following error occurred.
```
$ python3 demo/demo_spatiotemporal_det.py demo/demo.mp4 demo/demo_spatiotemporal_det.mp4 --config configs/detection/slowonly/slowonly_kinetics400-pretrained-r101_8xb16-8x8x1-20e_ava21-rgb.py --checkpoint https://download.openmmlab.com/mmaction/detection/ava/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb_20201217-16378594.pth --det-config demo/demo_configs/faster-rcnn_r50_fpn_2x_coco_infer.py --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth --det-score-thr 0.9 --action-score-thr 0.5 --label-map tools/data/ava/label_map.txt --predict-stepsize 8 --output-stepsize 4 --output-fps 6
Traceback (most recent call last):
  File "/home/dl/openmmlab/mmaction2/mmaction/apis/inference.py", line 130, in detection_inference
    from mmdet.apis import inference_detector, init_detector
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .det_inferencer import DetInferencer
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/apis/det_inferencer.py", line 21, in <module>
    from mmdet.evaluation import INSTANCE_OFFSET
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/evaluation/__init__.py", line 3, in <module>
    from .metrics import *  # noqa: F401,F403
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/evaluation/metrics/__init__.py", line 3, in <module>
    from .coco_metric import CocoMetric
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/evaluation/metrics/coco_metric.py", line 16, in <module>
    from mmdet.datasets.api_wrappers import COCO, COCOeval
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/datasets/__init__.py", line 14, in <module>
    from .utils import get_loading_pipeline
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/datasets/utils.py", line 5, in <module>
    from mmdet.datasets.transforms import LoadAnnotations, LoadPanopticAnnotations
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/datasets/transforms/__init__.py", line 6, in <module>
    from .formatting import ImageToTensor, PackDetInputs, ToTensor, Transpose
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/datasets/transforms/formatting.py", line 9, in <module>
    from mmdet.structures.bbox import BaseBoxes
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/structures/bbox/__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/structures/bbox/base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/structures/mask/__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/structures/mask/structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at10TensorBase8data_ptrIdEEPT_v

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo/demo_spatiotemporal_det.py", line 373, in <module>
    main()
  File "demo/demo_spatiotemporal_det.py", line 274, in main
    human_detections, _ = detection_inference(args.det_config,
  File "/home/dl/openmmlab/mmaction2/mmaction/apis/inference.py", line 133, in detection_inference
    raise ImportError('Failed to import `inference_detector` and '
ImportError: Failed to import `inference_detector` and `init_detector` from `mmdet.apis`. These apis are required in this inference api! 
```
It seems to be a mmdet.apis error.
Please let me know how to fix it.

**Comment by cir7** [comment]
Do you have mmdet installed in your environment? if so, please make sure that the version is higher than 3.0.0 as mentioned in the [troubleshooting](https://mmaction2.readthedocs.io/en/latest/get_started/installation.html#troubleshooting).

**Comment by Ishihara-Masabumi** [comment]
I installed mmdet higher than 3.0.0, as below.
```
mim install mmdet==3.0.0rc6
```
But, the result is the same.

**Comment by Dai-Wenxun** [comment]
what's your version of `mmcv`?

**Comment by mzhadigerov** [comment]
how did you solve this?
