### ISSUE TITLE
[Bug] AttributeError: 'PoseDataSample' object has no attribute '_pred_instances'

### ISSUE THREAD

**Issue by MengHao666** [open-mmlab/mmaction2#2407]
### Branch

main branch (0.x version, such as `v0.10.0`, or `dev` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

sys.platform: win32
Python: 3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3080
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
NVCC: Cuda compilation tools, release 11.3, V11.3.109
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.28.29915 版
GCC: n/a
PyTorch: 1.12.1
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.1
OpenCV: 4.7.0
MMEngine: 0.7.2
MMAction2: 1.0.0+02e9c02

### Describe the bug

(open-mmlab) E:\PycharmProjects>python ./mmaction2/mmaction/utils/collect_env.py
Traceback (most recent call last):
  File "./mmaction2/mmaction/utils/collect_env.py", line 2, in <module>
    from mmengine.utils import get_git_hash
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmengine\__init__.py", line 3, in <module>
    from .config import *
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmengine\config\__init__.py", line 2, in <module>
    from .config import Config, ConfigDict, DictAction
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmengine\config\config.py", line 15, in <module>
    from typing import Any, Optional, Sequence, Tuple, Union
  File "E:\PycharmProjects\mmaction2\mmaction\utils\typing.py", line 3, in <module>
    from typing import Dict, List, Optional, Tuple, Union
ImportError: cannot import name 'Dict' from partially initialized module 'typing' (most likely due to a circular import) (E:\PycharmProjects\mmaction2\mmaction\utils\typing.py)

### Reproduces the problem - command or script

> python demo/demo_skeleton.py D:/MocapData/QS/20220916_QS/video/cam1/cropped/zuoqi_HS_Idle_001_cam1_cropped.mp4 D:/MocapData/QS/20220916_QS/video/cam1/cropped/zuoqi_HS_Idle_001_cam1_cropped_hmdb_out.mp4 --config configs/skeleton/posec3d/slowonly_kinetics400-pretrained-r50_8xb16-u48-120e_hmdb51-split1-keypoint.py --checkpoint checkpoints/slowonly_kinetics400-pretrained-r50_8xb16-u48-120e_hmdb51-split1-keypoint_20220815-17eaa484.pth --det-config demo/demo_configs/faster-rcnn_r50_fpn_2x_coco_infer.py --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth --det-score-thr 0.9 --det-cat-id 0 --pose-config demo/demo_configs/td-hm_hrnet-w32_8xb64-210e_coco-256x192_infer.py --pose-checkpoint https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth --label-map tools/data/hmdb51/label_map.txt

### Reproduces the problem - error message

> (open-mmlab) E:\PycharmProjects\mmaction2>python demo/demo_skeleton.py D:/MocapData/QS/20220916_QS/video/cam1/cropped/zuoqi_HS_Idle_001_cam1_cropped.mp4 D:/MocapData/QS/20220916_QS/video/cam1/cropped/zuoqi_HS_Idle_001_cam1_cropped_hmdb_out.mp4 --config configs/skeleton/posec3d/slowonly_kinetics400-pretrained-r50_8xb16-u48-120e_hmdb51-split1-keypoint.py --checkpoint checkpoints/slowonly_kinetics400-pretrained-r50_8xb16-u48-120e_hmdb51-split1-keypoint_20220815-17eaa484.pth --det-config demo/demo_configs/faster-rcnn_r50_fpn_2x_coco_infer.py --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth --det-score-thr 0.9 --det-cat-id 0 --pose-config demo/demo_configs/td-hm_hrnet-w32_8xb64-210e_coco-256x192_infer.py --pose-checkpoint https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth --label-map tools/data/hmdb51/label_map.txt
Loads checkpoint by http backend from path: http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth
Performing Human Detection for each frame
[                                                  ] 0/1294, elapsed: 0s, ETA:04/17 20:30:05 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
04/17 20:30:05 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1294/1294, 23.8 task/s, elapsed: 54s, ETA:     0s
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth
Performing Human Pose Estimation for each frame
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  ] 1263/1294, 8.5 task/s, elapsed: 148s, ETA:     4sTraceback (most recent call last):
  File "demo/demo_skeleton.py", line 189, in <module>
    main()
  File "demo/demo_skeleton.py", line 145, in main
    pose_results, pose_data_samples = pose_inference(args.pose_config,
  File "e:\pycharmprojects\mmaction2\mmaction\apis\inference.py", line 202, in pose_inference
    poses = pose_data_sample.pred_instances.to_dict()
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmpose\structures\pose_data_sample.py", line 72, in pred_instances
    return self._pred_instances
AttributeError: 'PoseDataSample' object has no attribute '_pred_instances'

**Comment by atou0004** [comment]
### I am also facing the same issue as well
### Environment

sys.platform: win32
Python: 3.8.16
GPU 0: NVIDIA GeForce RTX 3060 Ti
NVCC: Cuda compilation tools, release 12.1, V12.1.66
Pytorch: 2.0.0+cu118
torch.cuda.is_available() : True
Pytorch compiling details:
(https://gist.github.com/atou0004/71ab20c5587fe63030e14adc2685e59e)
Packages in the env:
(https://gist.github.com/atou0004/909e995c9984fdc36cc8f3831a9ba28c)


### There's no issue if I am using the demo_skeleton.mp4

> (openmmlab) C:\Users\PC\mmaction2>python demo/demo_skeleton.py demo/demo_skeleton.mp4 demo/demo_skeleton_out.mp4 --config configs/skeleton/posec3d/slowonly_kinetics400-pretrained-r50_8xb16-u48-120e_hmdb51-split1-keypoint.py --checkpoint checkpoints/slowonly_kinetics400-pretrained-r50_8xb16-u48-120e_hmdb51-split1-keypoint_20220815-17eaa484.pth --det-config demo/demo_configs/faster-rcnn_r50_fpn_2x_coco_infer.py --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth --det-score-thr 0.9 --det-cat-id 0 --pose-config demo/demo_configs/td-hm_hrnet-w32_8xb64-210e_coco-256x192_infer.py --pose-checkpoint https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth --label-map tools/data/hmdb51/label_map.txt
Loads checkpoint by http backend from path: http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth
Performing Human Detection for each frame
[                                                  ] 0/72, elapsed: 0s, ETA:04/25 06:07:31 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
04/25 06:07:31 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 72/72, 10.7 task/s, elapsed: 7s, ETA:     0s
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth
Performing Human Pose Estimation for each frame
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 72/72, 15.8 task/s, elapsed: 5s, ETA:     0s
Loads checkpoint by local backend from path: checkpoints/slowonly_kinetics400-pretrained-r50_8xb16-u48-120e_hmdb51-split1-keypoint_20220815-17eaa484.pth
04/25 06:07:45 - mmengine - WARNING - `Visualizer` backend is not initialized because save_dir is None.
Drawing skeleton for each frame
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 72/72, 6.3 task/s, elapsed: 11s, ETA:     0s
Moviepy - Building video demo/demo_skeleton_out.mp4.
Moviepy - Writing video demo/demo_skeleton_out.mp4

> Moviepy - Done !
> Moviepy - video ready demo/demo_skeleton_out.mp4


### But when I use another video, I get the error

> (openmmlab) C:\Users\PC\mmaction2>python demo/demo_skeleton.py demo/demo.mp4 demo/demo_out.mp4 --config configs/skeleton/posec3d/slowonly_kinetics400-pretrained-r50_8xb16-u48-120e_hmdb51-split1-keypoint.py --checkpoint checkpoints/slowonly_kinetics400-pretrained-r50_8xb16-u48-120e_hmdb51-split1-keypoint_20220815-17eaa484.pth --det-config demo/demo_configs/faster-rcnn_r50_fpn_2x_coco_infer.py --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth --det-score-thr 0.9 --det-cat-id 0 --pose-config demo/demo_configs/td-hm_hrnet-w32_8xb64-210e_coco-256x192_infer.py --pose-checkpoint https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth --label-map tools/data/hmdb51/label_map.txt
Loads checkpoint by http backend from path: http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth
Performing Human Detection for each frame
[                                                  ] 0/280, elapsed: 0s, ETA:04/25 06:04:16 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
04/25 06:04:16 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 280/280, 15.4 task/s, elapsed: 18s, ETA:     0s
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth
Performing Human Pose Estimation for each frame
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>                 ] 187/280, 13.9 task/s, elapsed: 13s, ETA:     7sTraceback (most recent call last):
  File "demo/demo_skeleton.py", line 189, in <module>
    main()
  File "demo/demo_skeleton.py", line 145, in main
    pose_results, pose_data_samples = pose_inference(args.pose_config,
  File "c:\users\pc\mmaction2\mmaction\apis\inference.py", line 201, in pose_inference
    poses = pose_data_sample.pred_instances.to_dict()
  File "C:\Users\PC\anaconda3\envs\openmmlab\lib\site-packages\mmpose\structures\pose_data_sample.py", line 71, in pred_instances
    return self._pred_instances
AttributeError: 'PoseDataSample' object has no attribute '_pred_instances'

**Comment by hukkai** [comment]
@MengHao666 @atou0004 Can you send me your video that make the error so that I can debug?

**Comment by atou0004** [comment]
@hukkai The video (demo.mp4) I used is in the demo folder

**Comment by hukkai** [comment]
@MengHao666 @atou0004 I see the points. The reason is that you test a video without human skeletons detected, thus  'PoseDataSample' object contains no pred_instances. We will make this error more clear.

**Comment by atou0004** [comment]
Thank you for the clarification. I appreciate your help. Can you please provide some guidance on what I can do to prepare my video so that the model can detect the skeletons? Alternatively, do you have any other suggestions on how I can resolve this issue?

**Comment by MengHao666** [comment]
> @MengHao666 @atou0004 Can you send me your video that make the error so that I can debug?

it seems that it could not handle the scence where the man was occluded or no man in video at some frames. The code may need to be modify to be more robust.

**Comment by MABatin** [comment]
Hi @MengHao666, did you find a solution/workaround for this issue?

**Comment by Dai-Wenxun** [comment]
We are fixing it, please hold on.

**Comment by MABatin** [comment]
@Dai-Wenxun I have found a workaround for this as mentioned in the following comment. 
https://github.com/open-mmlab/mmaction2/issues/2459#issuecomment-1538406539

**Comment by chg0901** [comment]
> @Dai-Wenxun I have found a workaround for this as mentioned in the following comment. [#2459 (comment)](https://github.com/open-mmlab/mmaction2/issues/2459#issuecomment-1538406539)

This is not work for me.


> @MengHao666 @atou0004 I see the points. The reason is that you test a video without human skeletons detected, thus 'PoseDataSample' object contains no pred_instances. We will make this error more clear.

And I think this is one of the reason that I have a similar error (AttributeError: 'PoseDataSample' object has no attribute '_gt_fields')
