### ISSUE TITLE
Step 2. Verify the inference demo. problem

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [open-mmlab/mmaction2#2414]
### The doc issue

I run the inference according to Step 2. Verify the inference demo. in https://mmaction2.readthedocs.io/en/latest/get_started/installation.html.
But, the following error occurred.
```
$ conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/dl/miniconda3/envs/openmmlab3

  added / updated specs:
    - pytorch-cuda=11.7
    - pytorch==1.13.1
    - torchaudio==0.13.1
    - torchvision==0.14.1


The following packages will be UPDATED:

  cuda-cudart                            11.6.55-he381448_0 --> 11.7.99-0 
  cuda-cupti                            11.6.124-h86345e5_0 --> 11.7.101-0 
  cuda-libraries                                   11.6.1-0 --> 11.7.1-0 
  cuda-nvrtc                            11.6.124-h020bade_0 --> 11.7.99-0 
  cuda-nvtx                             11.6.124-h0630a44_0 --> 11.7.91-0 
  cuda-runtime                                     11.6.1-0 --> 11.7.1-0 
  libcublas                           11.9.2.110-h5e84587_0 --> 11.10.3.66-0 
  libcufft                            10.7.1.112-hf425ae0_0 --> 10.7.2.124-h4fbf590_0 
  libcusolver                         11.3.4.124-h33c3c4e_0 --> 11.4.0.1-0 
  libcusparse                         11.7.2.124-h7538f96_0 --> 11.7.4.91-0 
  libnpp                              11.6.3.124-hd2722f0_0 --> 11.7.4.75-0 
  libnvjpeg                           11.6.2.124-hd473ad6_0 --> 11.8.0.2-0 
  pytorch-cuda       pytorch/noarch::pytorch-cuda-11.6-h86~ --> pytorch/linux-64::pytorch-cuda-11.7-h778d358_3 


Proceed ([y]/n)? y


Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
$ python demo/demo.py tsn_imagenet-pretrained-r50_8xb32-1x1x8-100e_kinetics400-rgb.py     tsn_imagenet-pretrained-r50_8xb32-1x1x8-100e_kinetics400-rgb_20220906-2692d16c.pth     demo/demo.mp4 tools/data/kinetics/label_map_k400.txt
/home/dl/miniconda3/envs/openmmlab3/lib/python3.8/site-packages/mmcv/cnn/bricks/transformer.py:33: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv`` rather than ``mmcv-lite`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Loads checkpoint by local backend from path: tsn_imagenet-pretrained-r50_8xb32-1x1x8-100e_kinetics400-rgb_20220906-2692d16c.pth
Traceback (most recent call last):
  File "demo/demo.py", line 158, in <module>
    main()
  File "demo/demo.py", line 119, in main
    model = init_recognizer(cfg, args.checkpoint, device=args.device)
  File "/home/dl/openmmlab3/mmaction2/mmaction/apis/inference.py", line 49, in init_recognizer
    model.to(device)
  File "/home/dl/miniconda3/envs/openmmlab3/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 202, in to
    return super().to(*args, **kwargs)
  File "/home/dl/miniconda3/envs/openmmlab3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/home/dl/miniconda3/envs/openmmlab3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/dl/miniconda3/envs/openmmlab3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 688, in _apply
    self._buffers[key] = fn(buf)
  File "/home/dl/miniconda3/envs/openmmlab3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/dl/miniconda3/envs/openmmlab3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```
What's wrong with it?

**Comment by cir7** [comment]
This is an issue about PyTorch installation, please make sure you have successfully installed PyTorch.
