### ISSUE TITLE
config file missing

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [open-mmlab/mmaction2#2415]
### The doc issue

I run demo_spatiotemporal_det.py.
But the following error occurred.
```
$ python demo/demo_spatiotemporal_det.py demo/demo.mp4 demo/demo_spatiotemporal_det.mp4 \
>     --config configs/detection/ava/slowonly_kinetics400-pretrained-r101_8xb16-8x8x1-20e_ava21-rgb.py \
>     --checkpoint https://download.openmmlab.com/mmaction/detection/ava/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb_20201217-16378594.pth \
>     --det-config demo/demo_configs/faster-rcnn_r50_fpn_2x_coco_infer.py \
>     --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth \
>     --det-score-thr 0.9 \
>     --action-score-thr 0.5 \
>     --label-map tools/data/ava/label_map.txt \
>     --predict-stepsize 8 \
>     --output-stepsize 4 \
>     --output-fps 6
Traceback (most recent call last):
  File "demo/demo_spatiotemporal_det.py", line 373, in <module>
    main()
  File "demo/demo_spatiotemporal_det.py", line 247, in main
    config = mmengine.Config.fromfile(args.config)
  File "/home/dl/miniconda3/envs/openmmlab4/lib/python3.8/site-packages/mmengine/config/config.py", line 177, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/home/dl/miniconda3/envs/openmmlab4/lib/python3.8/site-packages/mmengine/config/config.py", line 449, in _file2dict
    check_file_exist(filename)
  File "/home/dl/miniconda3/envs/openmmlab4/lib/python3.8/site-packages/mmengine/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/home/dl/openmmlab4/mmaction2/configs/detection/ava/slowonly_kinetics400-pretrained-r101_8xb16-8x8x1-20e_ava21-rgb.py" does not exist
```
Maybe slowonly_kinetics400-pretrained-r101_8xb16-8x8x1-20e_ava21-rgb.py is missing.
Please give me slowonly_kinetics400-pretrained-r101_8xb16-8x8x1-20e_ava21-rgb.py.

**Comment by cir7** [comment]
similar issue in #2418 , you could refer to the solution there
