### ISSUE TITLE
[Bug] Cannot evaluate multi-label classification

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmaction2#2416]
### Branch

1.x branch (1.x version, such as `v1.0.0rc2`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

```
Python: 3.9.0 (default, Jul 27 2022, 17:09:22) [GCC 8.4.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 2070 Super with Max-Q Design
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 10.1, V10.1.24
GCC: gcc (Ubuntu 8.4.0-3ubuntu2) 8.4.0
PyTorch: 1.10.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1+cu113
OpenCV: 4.7.0
MMEngine: 0.7.2
MMAction2: 1.0.0+dc6b9c9
```

### Describe the bug

The evaluation of a multi-label classification task fails with the following error:

```
Traceback (most recent call last):
  File "mmaction2/tools/train.py", line 135, in <module>
    main()
  File "mmaction2/tools/train.py", line 131, in main
    runner.train()
  File ".pyenv/versions/mmaction2/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1706, in train
    model = self.train_loop.run()  # type: ignore
  File ".pyenv/versions/mmaction2/lib/python3.9/site-packages/mmengine/runner/loops.py", line 102, in run
    self.runner.val_loop.run()
  File ".pyenv/versions/mmaction2/lib/python3.9/site-packages/mmengine/runner/loops.py", line 363, in run
    self.run_iter(idx, data_batch)
  File ".pyenv/versions/mmaction2/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File ".pyenv/versions/mmaction2/lib/python3.9/site-packages/mmengine/runner/loops.py", line 384, in run_iter
    self.evaluator.process(data_samples=outputs, data_batch=data_batch)
  File ".pyenv/versions/mmaction2/lib/python3.9/site-packages/mmengine/evaluator/evaluator.py", line 60, in process
    metric.process(data_batch, _data_samples)
  File "mmaction2/mmaction/evaluation/metrics/acc_metric.py", line 97, in process
    result['label'] = label['item'].item()
ValueError: only one element tensors can be converted to Python scalars
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 18441) of binary: .pyenv/versions/mmaction2/bin/python
Traceback (most recent call last):
  File ".pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".pyenv/versions/mmaction2/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File ".pyenv/versions/mmaction2/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File ".pyenv/versions/mmaction2/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File ".pyenv/versions/mmaction2/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File ".pyenv/versions/mmaction2/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File ".pyenv/versions/mmaction2/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-20_11:39:47
  host      : thinkpak-ark
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 18441)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

On closer inspection, the content of `label['item']` is not actually a single-element tensor. But rather a list tensor, like so: `tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0.], device='cuda:0')`.
        
Hence calling `.item()` on it fails.

### Reproduces the problem - code sample

Just a training script.

### Reproduces the problem - command or script

Just a training script.

**Comment by Dai-Wenxun** [comment]
Could you please show me your full config?

**Comment by cosfrist** [comment]
你好：   邮件内容已收到，我会尽快处理，谢谢   祝好！

**Comment by rlleshi** [comment]
Sure @Dai-Wenxun 

```
_base_ = ['../_base_/default_runtime.py']

# model settings
num_classes = 20
num_frames = 8
model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='UniFormerV2',
        input_resolution=224,
        patch_size=16,
        width=768,
        layers=12,
        heads=12,
        t_size=num_frames,
        dw_reduction=1.5,
        backbone_drop_path_rate=0.,
        temporal_downsample=False,
        no_lmhra=True,
        double_lmhra=True,
        return_list=[8, 9, 10, 11],
        n_layers=4,
        n_dim=768,
        n_head=12,
        mlp_factor=4.,
        drop_path_rate=0.,
        mlp_dropout=[0.5, 0.5, 0.5, 0.5],
        clip_pretrained=True,
        pretrained='ViT-B/16'),
    cls_head=dict(
        type='UniFormerHead',
        dropout_ratio=0.5,
        in_channels=768,
        average_clips='prob',
        num_classes=num_classes,
        multi_class=True),
    data_preprocessor=dict(
        type='ActionDataPreprocessor',
        mean=[114.75, 114.75, 114.75],
        std=[57.375, 57.375, 57.375],
        format_shape='NCTHW'))

# dataset settings
dataset_type = 'VideoDataset'
ann_file_train = f'train.txt'
ann_file_val = f'val.txt'
ann_file_test = ann_file_val

file_client_args = dict(io_backend='disk')
train_pipeline = [
    dict(type='DecordInit', **file_client_args),
    dict(type='UniformSample', clip_len=num_frames, num_clips=1),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(
        type='PytorchVideoWrapper',
        op='RandAugment',
        magnitude=7,
        num_layers=4),
    dict(type='RandomResizedCrop'),
    dict(type='Resize', scale=(224, 224), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='PackActionInputs')
]

val_pipeline = [
    dict(type='DecordInit', **file_client_args),
    dict(
        type='UniformSample', clip_len=num_frames, num_clips=1,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 224)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='PackActionInputs')
]

test_pipeline = [
    dict(type='DecordInit', **file_client_args),
    dict(
        type='UniformSample', clip_len=num_frames, num_clips=4,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 224)),
    dict(type='ThreeCrop', crop_size=224),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='PackActionInputs')
]

train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix=dict(video=''),
        pipeline=train_pipeline,
        multi_class=True,
        num_classes=num_classes))
val_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix=dict(video=''),
        pipeline=val_pipeline,
        test_mode=True,
        multi_class=True,
        num_classes=num_classes))
test_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        ann_file=ann_file_test,
        data_prefix=dict(video=''),
        pipeline=test_pipeline,
        test_mode=True,
        multi_class=True,
        num_classes=num_classes))

val_evaluator = dict(type='AccMetric',
                     num_classes=num_classes,
                     metric_list=('mmit_mean_average_precision'))
test_evaluator = dict(type='AccMetric',
                     num_classes=num_classes,
                     metric_list=('mmit_mean_average_precision'))
train_cfg = dict(
    type='EpochBasedTrainLoop', max_epochs=55, val_begin=1, val_interval=1)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')

base_lr = 1e-5
optim_wrapper = dict(
    optimizer=dict(
        type='AdamW', lr=base_lr, betas=(0.9, 0.999), weight_decay=0.05),
    paramwise_cfg=dict(norm_decay_mult=0.0, bias_decay_mult=0.0),
    clip_grad=dict(max_norm=20, norm_type=2))

param_scheduler = [
    dict(
        type='LinearLR',
        start_factor=0.1,
        by_epoch=True,
        begin=0,
        end=5,
        convert_to_iter_based=True),
    dict(
        type='CosineAnnealingLR',
        T_max=50,
        eta_min_ratio=0.1,
        by_epoch=True,
        begin=5,
        end=55,
        convert_to_iter_based=True)
]

default_hooks = dict(
    checkpoint=dict(interval=1, max_keep_ckpts=5), logger=dict(interval=500))

# Default setting for scaling LR automatically
#   - `enable` means enable scaling LR automatically
#       or not by default.
#   - `base_batch_size` = (8 GPUs) x (8 samples per GPU).
auto_scale_lr = dict(enable=True, base_batch_size=2)
load_from = 'work_dir/uniformevr2/uniformerv2-base-p16-res224_clip-kinetics710-pre_8xb32-u8_kinetics400-rgb_20230313-75be0806.pth'

```

**Comment by Dai-Wenxun** [comment]
I fixed this bug in https://github.com/open-mmlab/mmaction2/pull/2425. You can pull the latest main to update these modifications. 

BTW, the `num_classes` is not needed by `AccMetric`, since the label has been converted to a tensor with shape `(C, )` in [BaseActionDataset](https://github.com/open-mmlab/mmaction2/blob/main/mmaction/datasets/base.py#L61-L64).
```python
val_evaluator = dict(type='AccMetric',
#                     num_classes=num_classes,
                     metric_list=('mmit_mean_average_precision'))
test_evaluator = dict(type='AccMetric',
#                     num_classes=num_classes,
                     metric_list=('mmit_mean_average_precision'))
```

**Comment by rlleshi** [comment]
Thanks! 

Yep, but there used to be an assert there for `mmit_mean_average_precision` metric. But I guess you removed it with the latest PR.
