### ISSUE TITLE
`AVARoIHead` and `BBoxHeadAVA ` class definition problem   |  `AVARoIHead` 和 `BBoxHeadAVA ` 类定义问题

### ISSUE THREAD

**Issue by yhArcadia** [open-mmlab/mmaction2#2417]
### The doc issue

The following problems were encountered when trying slowfast training:
尝试slowfast训练时遇到如下问题：
```SH
Traceback (most recent call last):
    File "/root/mmengine/mmengine/registry/build_functions.py", line 122, in build_from_cfg 
        obj = obj_cls(**args) # type: ignore 
    File "/root/miniconda3/lib/python3.8/site-packages/mmdet/models/roi_heads/base_roi_head.py", line 32, in __init__ 
        self.init_bbox_head(bbox_roi_extractor, bbox_head) 
    File "/root/miniconda3/lib/python3.8/site-packages/mmdet/models/roi_heads/standard_roi_head.py", line 39, in 
init_bbox_head 
        self.bbox_head = MODELS.build(bbox_head) 
    File "/root/mmengine/mmengine/registry/registry.py", line 548, in build 
        return self.build_func(cfg, *args, **kwargs, registry=self) 
    File "/root/mmengine/mmengine/registry/build_functions.py", line 250, in build_model_from_cfg 
        return build_from_cfg(cfg, registry, default_args) 
    File "/root/mmengine/mmengine/registry/build_functions.py", line 144, in build_from_cfg 
        raise type(e)( 
AssertionError: class `BBoxHeadAVA` in mmaction/models/roi_heads/bbox_heads/bbox_head.py: 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
    File "/root/mmengine/mmengine/registry/build_functions.py", line 122, in build_from_cfg 
        obj = obj_cls(**args) # type: ignore 
    File "/root/miniconda3/lib/python3.8/site-packages/mmdet/models/detectors/fast_rcnn.py", line 19, in __init__ 
        super().__init__( 
    File "/root/miniconda3/lib/python3.8/site-packages/mmdet/models/detectors/two_stage.py", line 61, in __init__ 
        self.roi_head = MODELS.build(roi_head) 
    File "/root/mmengine/mmengine/registry/registry.py", line 548, in build 
        return self.build_func(cfg, *args, **kwargs, registry=self) 
    File "/root/mmengine/mmengine/registry/build_functions.py", line 250, in build_model_from_cfg 
        return build_from_cfg(cfg, registry, default_args) 
    File "/root/mmengine/mmengine/registry/build_functions.py", line 144, in build_from_cfg 
        raise type(e)( 
AssertionError: class `AVARoIHead` in mmaction/models/roi_heads/roi_head.py: class `BBoxHeadAVA` in mmaction/models/roi_heads/bbox_heads/bbox_head.py: 
```

>The version is mian-1.0.0
版本为main-1.0.0
The other package version:
其他包版本：
![9e627e1ca3aa3930dfc987dc011481d](https://user-images.githubusercontent.com/85126209/233424511-1671fb80-4eb0-4a5d-953f-1d91126850a8.jpg)

**Comment by Dai-Wenxun** [comment]
In MMAction2 1.0, there is no `mmcv-full`. please follow this tutorial to install the dependencies.  https://mmaction2.readthedocs.io/en/latest/get_started/installation.html#troubleshooting

**Comment by a773808735** [comment]
Did you solve your problem?

**Comment by a773808735** [comment]
Traceback (most recent call last):
  File "/home/sstc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/sstc/lwx/mmaction2/mmaction/models/roi_heads/bbox_heads/bbox_head.py", line 113, in __init__
    assert all([k < num_classes for k in self.topk])
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sstc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/sstc/lwx/mmaction2/mmdet/models/roi_heads/base_roi_head.py", line 32, in __init__
    self.init_bbox_head(bbox_roi_extractor, bbox_head)
  File "/home/sstc/lwx/mmaction2/mmdet/models/roi_heads/standard_roi_head.py", line 39, in init_bbox_head
    self.bbox_head = MODELS.build(bbox_head)
  File "/home/sstc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/sstc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 241, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/sstc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
AssertionError: class `BBoxHeadAVA` in mmaction/models/roi_heads/bbox_heads/bbox_head.py: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sstc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/sstc/lwx/mmaction2/mmdet/models/detectors/fast_rcnn.py", line 19, in __init__
    super().__init__(
  File "/home/sstc/lwx/mmaction2/mmdet/models/detectors/two_stage.py", line 61, in __init__
    self.roi_head = MODELS.build(roi_head)
  File "/home/sstc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/sstc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 241, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/sstc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
AssertionError: class `AVARoIHead` in mmaction/models/roi_heads/roi_head.py: class `BBoxHeadAVA` in mmaction/models/roi_heads/bbox_heads/bbox_head.py: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sstc/lwx/mmaction2/train.py", line 137, in <module>
    main()
  File "/home/sstc/lwx/mmaction2/train.py", line 130, in main
    runner = Runner.from_cfg(cfg)
  File "/home/sstc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/home/sstc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 406, in __init__
    self.model = self.build_model(model)
  File "/home/sstc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 813, in build_model
    model = MODELS.build(model)
  File "/home/sstc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/sstc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 241, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/sstc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
AssertionError: class `FastRCNN` in mmdet/models/detectors/fast_rcnn.py: class `AVARoIHead` in mmaction/models/roi_heads/roi_head.py: class `BBoxHeadAVA` in mmaction/models/roi_heads/bbox_heads/bbox_head.py: 

Process finished with exit code 1

**Comment by yhArcadia** [comment]
> Did you solve your problem?

Yes, in `roi head`, find `bbox head`, add an attribute: `topk=(1,n)`。`1` Keep the default，`n` is the number of actions
