### ISSUE TITLE
How to Use RawframeDataset for training

### ISSUE THREAD

**Issue by KunLiam** [open-mmlab/mmaction2#2431]
### Branch

1.x branch (1.x version, such as `v1.0.0rc2`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

Most of the requirements mentioned are installed

### Describe the bug

In the configs file, you changed the RawframeDataset to VideoDataset. If I want to continue using RawframeDataset for training, What parameters in the config file need to be replaced or modified, and what other py files need to be modified?Now the code is not very friendly to the video frame data set due to your further modification, could you please tell me how to modify it, thank you

### Reproduces the problem - error message

Video frame data used on your updated version of the video data, the code won't run

### Additional information

In the configs file, you changed the RawframeDataset to VideoDataset. If I want to continue using RawframeDataset for training, What parameters in the config file need to be replaced or modified, and what other py files need to be modified?
Now the code is not very friendly to the video frame data set due to your further modification, could you please tell me how to modify it, thank you

**Comment by Dai-Wenxun** [comment]
This [trn config](https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/trn/trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv1-rgb.py) employs `RawframeDataset` for training, you can modify your config file according to this.

**Comment by KunLiam** [comment]
> This [trn config](https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/trn/trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv1-rgb.py) employs `RawframeDataset` for training, you can modify your config file according to this.

Thank you. I'll try

**Comment by KunLiam** [comment]
> This [trn config](https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/trn/trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv1-rgb.py) employs `RawframeDataset` for training, you can modify your config file according to this.

As you said, I was able to run through the video frame code using trn config. I was doing a two-class problem, so I changed num_classes=400 to num_classes=2. But according to its config file I modified 'c3d_sports1m-pretrained_8xb30-16x11-45e_ucF101-rgb.py' and 'Uniformerv2-base-p16-res224_clip-kinetics710-pre_u8_kinetics400-rgp.py', there are problems in the running of these two files. I would be very grateful if you could help solve them.

Next, I'll list the modified configuration file and the two error messages for both files:

First, the modified configuration file is as follows:
{file_client_args = dict(io_backend='disk')
sthv1_flip_label_map = {2: 4, 4: 2, 30: 41, 41: 30, 52: 66, 66: 52}
train_pipeline = [
    dict(type='SampleFrames', clip_len=1, frame_interval=1, num_clips=8),
    dict(type='RawFrameDecode', **file_client_args),
    dict(type='Resize', scale=(-1, 256)),
    dict(
        type='MultiScaleCrop',
        input_size=224,
        scales=(1, 0.875, 0.75, 0.66),
        random_crop=False,
        max_wh_scale_gap=1,
        num_fixed_crops=13),
    dict(type='Resize', scale=(224, 224), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5, flip_label_map=sthv1_flip_label_map),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='PackActionInputs')
]
val_pipeline = [
    dict(
        type='SampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=8,
        test_mode=True),
    dict(type='RawFrameDecode', **file_client_args),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='PackActionInputs')
]
test_pipeline = [
    dict(
        type='SampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=8,
        twice_sample=True,
        test_mode=True),
    dict(type='RawFrameDecode', **file_client_args),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='ThreeCrop', crop_size=256),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='PackActionInputs')
]
train_dataloader = dict(
    batch_size=16,
    num_workers=8,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix=dict(img=data_root),
        filename_tmpl='img_{:05}.jpg',
        pipeline=train_pipeline))
val_dataloader = dict(
    batch_size=16,
    num_workers=8,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix=dict(img=data_root_val),
        filename_tmpl='img_{:05}.jpg',
        pipeline=val_pipeline,
        test_mode=True))
test_dataloader = dict(
    batch_size=1,
    num_workers=8,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix=dict(img=data_root_val),
        filename_tmpl='img_{:05}.jpg',
        pipeline=test_pipeline,
        test_mode=True))}

Second, running 'c3d_sports1m-pretrained_8xb30-16x11-45e_ucF101-rgb.py' generates an error:
{Traceback (most recent call last):
  File "./tools/train.py", line 135, in <module>
    main()
  File "./tools/train.py", line 131, in main
    runner.train()
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1706, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 120, in train_step
    data = self.module.data_preprocessor(data, training=True)
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/LK/Video_Processing/mmaction2-main/mmaction/models/data_preprocessors/data_preprocessor.py", line 82, in forward
    return self.forward_onesample(data, training=training)
  File "/data/LK/Video_Processing/mmaction2-main/mmaction/models/data_preprocessors/data_preprocessor.py", line 105, in forward_onesample
    inputs, data_samples = self.preprocess(inputs, data_samples, training)
  File "/data/LK/Video_Processing/mmaction2-main/mmaction/models/data_preprocessors/data_preprocessor.py", line 137, in preprocess
    batch_inputs = (batch_inputs - self.mean) / self.std
RuntimeError: The size of tensor a (8) must match the size of tensor b (3) at non-singleton dimension 1}

Based on the traceback information, a RuntimeError occurs, I tried to change (type='FormatShape', input_format='NCHW') to (type='FormatShape', input_format='NCTHW'), but I got another error:
{Traceback (most recent call last):
  File "./tools/train.py", line 135, in <module>
    main()
  File "./tools/train.py", line 131, in main
    runner.train()
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1706, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 121, in train_step
    losses = self._run_forward(data, mode='loss')
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 161, in _run_forward
    results = self(**data, mode=mode)
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/LK/Video_Processing/mmaction2-main/mmaction/models/recognizers/base.py", line 223, in forward
    return self.loss(inputs, data_samples, **kwargs)
  File "/data/LK/Video_Processing/mmaction2-main/mmaction/models/recognizers/base.py", line 132, in loss
    self.extract_feat(inputs,
  File "/data/LK/Video_Processing/mmaction2-main/mmaction/models/recognizers/recognizer3d.py", line 98, in extract_feat
    x = self.backbone(inputs)
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/LK/Video_Processing/mmaction2-main/mmaction/models/backbones/c3d.py", line 125, in forward
    x = self.pool2(x)
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/pooling.py", line 244, in forward
    return F.max_pool3d(input, self.kernel_size, self.stride,
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/_jit_internal.py", line 484, in fn
    return if_false(*args, **kwargs)
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/functional.py", line 868, in _max_pool3d
    return torch.max_pool3d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: Given input size: (128x1x112x112). Calculated output size: (128x0x56x56). Output size is too small}

Third, error of running 'uniformerv2-base-p16-res224_clip-kinetics710-pre_u8_kinetics400-rgb.py' :
{Traceback (most recent call last):
  File "./tools/train.py", line 135, in <module>
    main()
  File "./tools/train.py", line 131, in main
    runner.train()
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1692, in train
    self._init_model_weights()
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 899, in _init_model_weights
    model.init_weights()
  File "/data/LK/Video_Processing/mmaction2-main/mmaction/models/recognizers/base.py", line 110, in init_weights
    super().init_weights()
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/model/base_module.py", line 130, in init_weights
    m.init_weights()
  File "/data/LK/Video_Processing/mmaction2-main/mmaction/models/heads/uniformer_head.py", line 109, in init_weights
    msg = self.load_state_dict(state_dict, strict=False)
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UniFormerHead:
	size mismatch for fc_cls.weight: copying a param with shape torch.Size([400, 768]) from checkpoint, the shape in current model is torch.Size([2, 768]).
	size mismatch for fc_cls.bias: copying a param with shape torch.Size([400]) from checkpoint, the shape in current model is torch.Size([2])}

I really hope to get your help. I have been using video frames in the last version, but I was caught off guard by the updated version. Thank you!

**Comment by KunLiam** [comment]
> 

I would be grateful if you could help me answer these questions.

**Comment by Dai-Wenxun** [comment]
For `C3D`, which is a 3D conv net, you can't use the 2D pipeline to train this model. Please compare these two different pipelines: [3D](https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/c3d/c3d_sports1m-pretrained_8xb30-16x1x1-45e_ucf101-rgb.py#L16) and [2D](https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/trn/trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv1-rgb.py#L17).

For `UniformerV2`, this is because of the wrong shape of the `cls_head` for pretrained weights.  just remove this `init_cfg` to not load from pretrained weights https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/uniformerv2/uniformerv2-base-p16-res224_clip-kinetics710-pre_u8_kinetics400-rgb.py#L41.

**Comment by KunLiam** [comment]
> For `C3D`, which is a 3D conv net, you can't use the 2D pipeline to train this model. Please compare these two different pipelines: [3D](https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/c3d/c3d_sports1m-pretrained_8xb30-16x1x1-45e_ucf101-rgb.py#L16) and [2D](https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/trn/trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv1-rgb.py#L17).
> 
> For `UniformerV2`, this is because of the wrong shape of the `cls_head` for pretrained weights. just remove this `init_cfg` to not load from pretrained weights https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/uniformerv2/uniformerv2-base-p16-res224_clip-kinetics710-pre_u8_kinetics400-rgb.py#L41.

Thank you, I did it！

**Comment by KunLiam** [comment]
According to your tips, the training code did run through, but I made an error in the process of testing. I wonder if you have encountered the same problem before?

The instructions I run are: 
[CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2  PORT=29501  ./tools/dist_test.sh configs/recognition/uniformerv2/uniformerv2-base-p16-res224_clip-kinetics710-pre_u8_kinetics400-rgb.py work_dirs/uniformerv2-base-p16-res224_clip-kinetics710-pre_u8_kinetics400-rgb/best_acc_top1_epoch_363.pth 1]

But there is a mistake, could you help to solve it, I would be grateful!

[Traceback (most recent call last):
  File "./tools/test.py", line 118, in <module>
    main()
  File "./tools/test.py", line 114, in main
    runner.test()
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1752, in test
    metrics = self.test_loop.run()  # type: ignore
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 434, in run
    for idx, data_batch in enumerate(self.dataloader):
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 406, in __getitem__
    data = self.prepare_data(idx)
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 797, in prepare_data
    return self.pipeline(data_info)
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 59, in __call__
    data = t(data)
  File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/data/LK/Video_Processing/mmaction2-main/mmaction/datasets/transforms/processing.py", line 1167, in transform
    assert crop_h == img_h or crop_w == img_w
AssertionError]

**Comment by KunLiam** [comment]
According to your tips, the training code did run through, but I made an error in the process of testing. I wonder if you have encountered the same problem before?

The instructions I run are:
`CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 PORT=29501 ./tools/dist_test.sh configs/recognition/uniformerv2/uniformerv2-base-p16-res224_clip-kinetics710-pre_u8_kinetics400-rgb.py work_dirs/uniformerv2-base-p16-res224_clip-kinetics710-pre_u8_kinetics400-rgb/best_acc_top1_epoch_363.pth 1`

But there is a mistake, could you help to solve it, I would be grateful!

`Traceback (most recent call last):
File "./tools/test.py", line 118, in
main()
File "./tools/test.py", line 114, in main
runner.test()
File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1752, in test
metrics = self.test_loop.run() # type: ignore
File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 434, in run
for idx, data_batch in enumerate(self.dataloader):
File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 634, in next
data = self._next_data()
File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
return self._process_data(data)
File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
data.reraise()
File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
data = fetcher.fetch(index)
File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 406, in getitem
data = self.prepare_data(idx)
File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 797, in prepare_data
return self.pipeline(data_info)
File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 59, in call
data = t(data)
File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in call
return self.transform(results)
File "/data/LK/Video_Processing/mmaction2-main/mmaction/datasets/transforms/processing.py", line 1167, in transform
assert crop_h == img_h or crop_w == img_w
AssertionError`

**Comment by KunLiam** [comment]
According to your tips, the training code did run through, but I made an error in the process of testing. I wonder if you have encountered the same problem before?

The instructions I run are:
> CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 PORT=29501 ./tools/dist_test.sh configs/recognition/uniformerv2/uniformerv2-base-p16-res224_clip-kinetics710-pre_u8_kinetics400-rgb.py work_dirs/uniformerv2-base-p16-res224_clip-kinetics710-pre_u8_kinetics400-rgb/best_acc_top1_epoch_363.pth 1


But there is a mistake, could you help to solve it, I would be grateful!
> Traceback (most recent call last):
> File "./tools/test.py", line 118, in
> main()
> File "./tools/test.py", line 114, in main
> runner.test()
> File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1752, in test
> metrics = self.test_loop.run() # type: ignore
> File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 434, in run
> for idx, data_batch in enumerate(self.dataloader):
> File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 634, in next
> data = self._next_data()
> File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
> return self._process_data(data)
> File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
> data.reraise()
> File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
> raise exception
> AssertionError: Caught AssertionError in DataLoader worker process 0.
> Original Traceback (most recent call last):
> File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
> data = fetcher.fetch(index)
> File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 406, in getitem
> data = self.prepare_data(idx)
> File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 797, in prepare_data
> return self.pipeline(data_info)
> File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 59, in call
> data = t(data)
> File "/home/LK/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in call
> return self.transform(results)
> File "/data/LK/Video_Processing/mmaction2-main/mmaction/datasets/transforms/processing.py", line 1167, in transform
> assert crop_h == img_h or crop_w == img_w
> AssertionError
