### ISSUE TITLE
[Bug] BaseMiniBatchBlending doesn't support multi label classification

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmaction2#2462]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

```
Python: 3.9.0 (default, Jul 27 2022, 17:09:22) [GCC 8.4.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 2070 Super with Max-Q Design
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 10.1, V10.1.24
GCC: gcc (Ubuntu 8.4.0-3ubuntu2) 8.4.0
PyTorch: 1.10.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1+cu113
OpenCV: 4.7.0
MMEngine: 0.7.2
MMAction2: 1.0.0+dc6b9c9
```

### Describe the bug

`label = torch.tensor(label, dtype=torch.long).to(imgs.device)` [here](https://github.com/open-mmlab/mmaction2/blob/6c7180592694bd9800cf5de4196a710eb62704be/mmaction/models/utils/blending_utils.py#L70) will fail with`TypeError: only integer tensors of a single element can be converted to an index` if the it's a multi-label classification problem.

### Reproduces the problem - code sample

E.g. if we add some augments like so to a multi-label classification config file:

```
    data_preprocessor=dict(
        type='ActionDataPreprocessor',
        mean=[114.75, 114.75, 114.75],
        std=[57.375, 57.375, 57.375],
        blending=dict(
            type='RandomBatchAugment',
            augments=[
                dict(type='MixupBlending', alpha=0.8, num_classes=174),
                dict(type='CutmixBlending', alpha=1, num_classes=174)
            ]),
        format_shape='NCTHW'),
```

When training the model the above-mentioned error is thrown. Full stack-trace:

```
Traceback (most recent call last):
  File "mmaction2/tools/train.py", line 135, in <module>
    main()
  File "mmaction2/tools/train.py", line 131, in main
    runner.train()
  File ".pyenv/versions/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1706, in train
    model = self.train_loop.run()  # type: ignore
  File ".pyenv/versions/lib/python3.9/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File ".pyenv/versions/lib/python3.9/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File ".pyenv/versions/lib/python3.9/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File ".pyenv/versions/lib/python3.9/site-packages/mmengine/model/wrappers/distributed.py", line 120, in train_step
    data = self.module.data_preprocessor(data, training=True)
  File ".pyenv/versions/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "mmaction2/mmaction/models/data_preprocessors/data_preprocessor.py", line 82, in forward
    return self.forward_onesample(data, training=training)
  File "mmaction2/mmaction/models/data_preprocessors/data_preprocessor.py", line 105, in forward_onesample
    inputs, data_samples = self.preprocess(inputs, data_samples, training)
  File "mmaction2/mmaction/models/data_preprocessors/data_preprocessor.py", line 147, in preprocess
    batch_inputs, data_samples = self.blending(batch_inputs,
  File "mmaction2/mmaction/models/utils/blending_utils.py", line 64, in __call__
    label = torch.tensor(label, dtype=torch.long).to(imgs.device)
TypeError: only integer tensors of a single element can be converted to an index
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 198139) of binary: .pyenv/versions/bin/python
Traceback (most recent call last):
  File ".pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".pyenv/versions/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File ".pyenv/versions/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File ".pyenv/versions/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File ".pyenv/versions/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File ".pyenv/versions/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File ".pyenv/versions/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-08_18:55:04
  host      : thinkpak-ark
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 198139)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by cir7** [comment]
Thanks for your feedback. Sorry for the bug, and we will fix it asap.
