### ISSUE TITLE
[Bug] ntu_pose_extraction.py give ValueError('all input arrays must have the same shape')

### ISSUE THREAD

**Issue by MABatin** [open-mmlab/mmaction2#2494]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

```
sys.platform: linux
Python: 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce GTX 1080
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.3, V11.3.109
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.1+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2.1
    - Built with CuDNN 8.3.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.1+cu113
OpenCV: 4.5.4
MMEngine: 0.7.3
MMAction2: 1.0.0+

```

### Describe the bug

I am trying to run ntu_pose_extraction.py script to extract pose information from an action clip and store them in a pickle file. However after extracting the pose information I get the following error:
`ValueError('all input arrays must have the same shape')`
for the line:
`anno['keypoint'] = np.stack(
        [pose['keypoints'].astype(np.float32) for pose in pose_results],
        axis=1)`
 pose['keypoints'] have different shapes of (1, 17, 2) and (2, 17, 2) at some different frames.

### Reproduces the problem - code sample

```
python {ROOT_DIR}/ntu_pose_extraction.py ' \
         f'{video_folder}/{filename} ' \
         f'{pickle_folder}/{os.path.splitext(filename)[0]}.pkl --skip-postproc'
```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "/home/portia/portia-train/ntu_pose_extraction.py", line 282, in <module>
    anno = ntu_pose_extraction(args.video, args.skip_postproc)
  File "/home/portia/portia-train/ntu_pose_extraction.py", line 250, in ntu_pose_extraction
    anno['keypoint'] = np.stack(
  File "<__array_function__ internals>", line 200, in stack
  File "/home/portia/portia-train/envtrain/lib/python3.8/site-packages/numpy/core/shape_base.py", line 464, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
```

### Additional information

I tried using np.concatenate instead of np.stack but as expected it didn't work either.

**Comment by cir7** [comment]
Hi, @MABatin 
this [pr](https://github.com/open-mmlab/mmaction2/pull/2402) has fixed the issue, please have a try.

**Comment by MABatin** [comment]
> Hi, @MABatin this [pr](https://github.com/open-mmlab/mmaction2/pull/2402) has fixed the issue, please have a try.

Thanks for commenting. I will give it a try.
