### ISSUE TITLE
Issue with RawFrameDataset setup

### ISSUE THREAD

**Issue by itruonghai** [open-mmlab/mmaction2#252]
Dear author, 

I try to use csn model for my action classification, I set up like in the tutorial documents, but it returns an error
```FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/mmaction2/mmaction/datasets/base.py", line 132, in __getitem__
    return self.prepare_train_frames(idx)
  File "/content/mmaction2/mmaction/datasets/rawframe_dataset.py", line 141, in prepare_train_frames
    return self.pipeline(results)
  File "/content/mmaction2/mmaction/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/content/mmaction2/mmaction/datasets/pipelines/loading.py", line 888, in __call__
    img_bytes = self.file_client.get(filepath)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/fileio/file_client.py", line 294, in get
    return self.client.get(filepath)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/fileio/file_client.py", line 185, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/content/mmaction2/mydata/train/863881946_02576_02736.mp4/img_00045.jpg'
``` 
Note that I save frame as 00000000000.jpg for example, with no prefix of img. The prefix img is so strange and I don't know what is going wrong. Thank you

**Comment by irvingzhang0512** [comment]
maybe you could pay more attention to the params of [rawframe_dataset.py](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/rawframe_dataset.py#L79). and in your case, `filename_tmpl={:01}.jpg` & `start_index=0`, then modify your own config files.

**Comment by dreamerlin** [comment]
That's right, you may need to try `filename_tmpl={:011}.jpg` & `start_index=0` to modify your own config files to suit the filename template as @irvingzhang0512 said.

**Comment by itruonghai** [comment]
> That's right, you may need to try `filename_tmpl={:011}.jpg` & `start_index=0` to modify your own config files to suit the filename template as @irvingzhang0512 said.

Thank you very much, it is working now. But I want to ask is there any way to see loss of val when evaluating. I just see top1 acc, top 5 acc and mean acc (don't understand about mean acc).
