### ISSUE TITLE
when i use "slowfast_r50_video_4x16x1_256e_kinetics400_rgb.py" config file ,i got this error?

### ISSUE THREAD

**Issue by zhaoleo1111** [open-mmlab/mmaction2#253]
```bash
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
2020-10-15 16:54:58,361 - mmaction - INFO - Start running, host: leo@leo-desktop, work_dir: /home/leo/mmaction2/work_dirs/slowfast_r50_video_3d_4x16x1_256e_kinetics400_rgb
2020-10-15 16:54:58,361 - mmaction - INFO - workflow: [('train', 1)], max: 256 epochs
[16:55:00] /io/decord/src/video/video_reader.cc:280: Failed to seek file to position: 0
[16:55:00] /io/decord/src/video/video_reader.cc:280: Failed to seek file to position: 0
[16:55:00] /io/decord/src/video/video_reader.cc:280: Failed to seek file to position: 0
[16:55:00] /io/decord/src/video/video_reader.cc:280: Failed to seek file to position: 0
[16:55:00] /io/decord/src/video/video_reader.cc:280: Failed to seek file to position: 0
Traceback (most recent call last):
  File "tools/train.py", line 155, in <module>
    main()
  File "tools/train.py", line 151, in main
    meta=meta)
  File "/home/leo/mmaction2/mmaction/apis/train.py", line 112, in train_model
[16:55:00] /io/decord/src/video/video_reader.cc:280: Failed to seek file to position: 0
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/leo/anaconda3/envs/mmaction2/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/leo/anaconda3/envs/mmaction2/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/leo/anaconda3/envs/mmaction2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/leo/anaconda3/envs/mmaction2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/leo/anaconda3/envs/mmaction2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
[16:55:00] /io/decord/src/video/video_reader.cc:280: Failed to seek file to position: 0
    data.reraise()
  File "/home/leo/anaconda3/envs/mmaction2/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/leo/anaconda3/envs/mmaction2/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/leo/anaconda3/envs/mmaction2/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/leo/anaconda3/envs/mmaction2/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/leo/mmaction2/mmaction/datasets/base.py", line 132, in __getitem__
    return self.prepare_train_frames(idx)
  File "/home/leo/mmaction2/mmaction/datasets/base.py", line 114, in prepare_train_frames
    return self.pipeline(results)
  File "/home/leo/mmaction2/mmaction/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/leo/mmaction2/mmaction/datasets/pipelines/loading.py", line 733, in __call__
    for idx in np.unique(frame_inds)
  File "/home/leo/mmaction2/mmaction/datasets/pipelines/loading.py", line 733, in <dictcomp>
    for idx in np.unique(frame_inds)
  File "/home/leo/anaconda3/envs/mmaction2/lib/python3.6/site-packages/decord/video_reader.py", line 91, in __getitem__
    self.seek_accurate(idx)
  File "/home/leo/anaconda3/envs/mmaction2/lib/python3.6/site-packages/decord/video_reader.py", line 222, in seek_accurate
    raise RuntimeError("Failed to seek_accurate to frame {}".format(pos))
RuntimeError: Failed to seek_accurate to frame 53

[16:55:00] /io/decord/src/video/video_reader.cc:280: Failed to seek file to position: 0
```

**Comment by innerlee** [comment]
looks like one of your video has bad format.
you may try to identify that file and replace it with a good one

**Comment by zhaoleo1111** [comment]
Thanks

**Comment by innerlee** [comment]
You can also try decord version 4.0.0, which does not implement accurate random seeking, but is more robust.

**Comment by dreamerlin** [comment]
@zhaoleo1111  How about the result ? Is that something wrong with a certain video, or the decord version ? or the config file ?

**Comment by hmmlencat** [comment]
hello ,i meet the same problem as you .  do you have solved this problem ,   please  give me some advice.
thank you very much
