### ISSUE TITLE
[Bug] KeyError: 'CTRGCN is not in the model registry. Please check whether the value of `CTRGCN` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

### ISSUE THREAD

**Issue by ya-92626** [open-mmlab/mmaction2#2541]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

Package                            Version              Location
---------------------------------- -------------------- -----------------------------------
absl-py                            1.0.0
adaPool                            0.1
addict                             2.4.0
alabaster                          0.7.12
anaconda-client                    1.9.0
anaconda-navigator                 2.1.1
anaconda-project                   0.10.1
anyio                              2.2.0
appdirs                            1.4.4
argh                               0.26.2
argon2-cffi                        20.1.0
arrow                              0.13.1
asgiref                            3.5.1
asn1crypto                         1.4.0
astroid                            2.6.6
astropy                            4.3.1
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              21.2.0
autopep8                           1.5.7
Babel                              2.9.1
backcall                           0.2.0
backports.functools-lru-cache      1.6.4
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.2.0
beautifulsoup4                     4.10.0
binaryornot                        0.4.4
bitarray                           2.3.0
bkcharts                           0.2
black                              19.10b0
bleach                             4.0.0
bokeh                              2.4.1
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
cached-property                    1.5.2
cachetools                         5.0.0
certifi                            2021.10.8
cffi                               1.14.6
chardet                            4.0.0
charset-normalizer                 2.0.4
chumpy                             0.70
click                              8.0.3
cloudpickle                        2.0.0
clyent                             1.2.2
codecov                            2.1.11
colorama                           0.4.4
coloredlogs                        15.0.1
commonmark                         0.9.1
comtypes                           1.1.10
conda                              22.9.0
conda-build                        3.24.0
conda-content-trust                0+unknown
conda-pack                         0.6.0
conda-package-handling             1.7.3
conda-repo-cli                     1.0.4
conda-token                        0.3.0
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
cookiecutter                       1.7.2
coverage                           7.2.2
cryptography                       3.4.8
cycler                             0.10.0
Cython                             0.29.24
cytoolz                            0.11.0
daal4py                            2021.3.0
dask                               2021.10.0
dataset2database                   1.2
debugpy                            1.4.1
decorator                          4.4.2
decord                             0.6.0
defusedxml                         0.7.1
diff-match-patch                   20200713
distributed                        2021.10.0
Django                             4.0.4
docutils                           0.17.1
einops                             0.6.1
entrypoints                        0.3
et-xmlfile                         1.1.0
fastcache                          1.1.0
ffmpeg-python                      0.2.0
filelock                           3.3.1
flake8                             3.9.2
Flask                              1.1.2
fonttools                          4.25.0
fsspec                             2021.10.1
future                             0.18.2
gevent                             21.8.0
glob2                              0.7
google-auth                        2.6.6
google-auth-oauthlib               0.4.6
greenlet                           1.1.1
grpcio                             1.46.0
h5py                               3.2.1
HeapDict                           1.0.1
html5lib                           1.1
humanfriendly                      10.0
idna                               3.2
image                              1.5.33
imagecodecs                        2021.8.26
imageio                            2.9.0
imageio-ffmpeg                     0.4.8
imagesize                          1.2.0
imgaug                             0.4.0
importlib-metadata                 4.8.1
inflection                         0.5.1
iniconfig                          1.1.1
intervaltree                       3.1.0
ipykernel                          6.4.1
ipython                            7.29.0
ipython-genutils                   0.2.0
ipywidgets                         7.6.5
isort                              5.9.3
itsdangerous                       2.0.1
jdcal                              1.4.1
jedi                               0.18.0
Jinja2                             2.11.3
jinja2-time                        0.2.0
joblib                             1.1.0
json-tricks                        3.17.0
json5                              0.9.6
jsonpatch                          1.32
jsonpointer                        2.3
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.12
jupyter-console                    6.4.0
jupyter-core                       4.8.1
jupyter-server                     1.4.1
jupyterlab                         3.2.1
jupyterlab-pygments                0.1.2
jupyterlab-server                  2.8.2
jupyterlab-widgets                 1.0.0
keyring                            23.1.0
kiwisolver                         1.3.1
lazy-object-proxy                  1.6.0
libarchive-c                       2.9
llvmlite                           0.37.0
locket                             0.2.1
lxml                               4.6.3
Markdown                           3.3.7
MarkupSafe                         1.1.1
matplotlib                         3.4.3
matplotlib-inline                  0.1.2
mccabe                             0.6.1
menuinst                           1.4.18
mistune                            0.8.4
mkl-fft                            1.3.1
mkl-random                         1.2.2
mkl-service                        2.4.0
mmaction2                          1.0.0                e:\360downloads\dzsb\mmaction2-main
mmcls                              0.23.1
mmcv                               2.0.0rc4
mmcv-full                          1.6.0
mmdet                              3.0.0
mmengine                           0.7.2
mmpose                             1.0.0
mmsegmentation                     0.26.0
mock                               4.0.3
model-index                        0.1.11
more-itertools                     8.10.0
moviepy                            1.0.3
mpmath                             1.2.1
msgpack                            1.0.2
multipledispatch                   0.6.0
munkres                            1.1.4
mypy-extensions                    0.4.3
navigator-updater                  0.2.1
nbclassic                          0.2.6
nbclient                           0.5.3
nbconvert                          6.1.0
nbformat                           5.1.3
nest-asyncio                       1.5.1
networkx                           2.6.3
nltk                               3.6.5
nose                               1.3.7
notebook                           6.4.5
numba                              0.54.1
numexpr                            2.7.3
numpy                              1.22.0
numpydoc                           1.1.0
oauthlib                           3.2.0
olefile                            0.46
opencv-contrib-python              4.7.0.72
opencv-python                      4.5.5.64
openmim                            0.3.7
openpyxl                           3.0.9
ordered-set                        4.1.0
packaging                          21.0
pandas                             1.3.4
pandocfilters                      1.4.3
paramiko                           2.7.2
parso                              0.8.2
partd                              1.2.0
path                               16.0.0
pathlib2                           2.3.6
pathspec                           0.7.0
patsy                              0.5.2
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             8.4.0
pip                                21.2.4
pkginfo                            1.7.1
pluggy                             0.13.1
ply                                3.11
poyo                               0.5.0
prettytable                        3.3.0
proglog                            0.1.10
prometheus-client                  0.11.0
prompt-toolkit                     3.0.20
protobuf                           3.20.1
psutil                             5.8.0
ptflops                            0.7
ptyprocess                         0.7.0
py                                 1.10.0
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycocotools                        2.0.4
pycodestyle                        2.7.0
pycosat                            0.6.3
pycparser                          2.20
pycurl                             7.44.1
pydocstyle                         6.1.1
pyerfa                             2.0.0
pyflakes                           2.3.1
Pygments                           2.10.0
PyJWT                              2.1.0
pylint                             2.9.6
pyls-spyder                        0.4.0
PyNaCl                             1.4.0
pyodbc                             4.0.0-unsupported
pyOpenSSL                          21.0.0
pyparsing                          3.0.4
pyreadline                         2.1
pyreadline3                        3.4.1
pyrsistent                         0.18.0
PySocks                            1.7.1
pytest                             6.2.4
python-dateutil                    2.8.2
python-lsp-black                   1.0.0
python-lsp-jsonrpc                 1.0.0
python-lsp-server                  1.2.4
python-slugify                     5.0.2
pytz                               2021.3
PyWavelets                         1.1.1
pywin32                            228
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             6.0
pyzmq                              22.2.1
QDarkStyle                         3.0.2
qstylizer                          0.1.10
QtAwesome                          1.0.2
qtconsole                          5.1.1
QtPy                               1.10.0
regex                              2021.8.3
requests                           2.26.0
requests-oauthlib                  1.3.1
rich                               12.5.1
rope                               0.19.0
rsa                                4.8
Rtree                              0.9.7
ruamel-yaml-conda                  0.15.100
scikit-image                       0.18.3
scikit-learn                       0.24.2
scikit-learn-intelex               2021.20210714.120553
scipy                              1.7.1
seaborn                            0.11.2
Send2Trash                         1.8.0
setuptools                         58.0.4
shapely                            2.0.1
simplegeneric                      0.8.1
singledispatch                     3.7.0
sip                                4.19.13
six                                1.16.0
sniffio                            1.2.0
snowballstemmer                    2.1.0
sortedcollections                  2.1.0
sortedcontainers                   2.4.0
soupsieve                          2.2.1
Sphinx                             4.2.0
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             2.0.0
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.5
sphinxcontrib-websupport           1.2.4
spyder                             5.1.5
spyder-kernels                     2.1.3
SQLAlchemy                         1.4.22
sqlparse                           0.4.2
statsmodels                        0.12.2
sympy                              1.9
tables                             3.6.1
tabulate                           0.8.10
TBB                                0.2
tblib                              1.7.0
tensorboard                        2.9.0
tensorboard-data-server            0.6.1
tensorboard-plugin-wit             1.8.1
tensorboardX                       2.2
termcolor                          2.0.1
terminado                          0.9.4
terminaltables                     3.1.10
testpath                           0.5.0
text-unidecode                     1.3
textdistance                       4.2.1
thop                               0.1.0.post2207010342
threadpoolctl                      2.2.0
three-merge                        0.1.1
tifffile                           2021.7.2
timm                               0.6.7
tinycss                            0.4
toml                               0.10.2
tomli                              2.0.1
toolz                              0.11.1
torch                              1.11.0
torchaudio                         0.11.0
torchfile                          0.1.0
torchvision                        0.12.0
tornado                            6.1
tqdm                               4.62.3
traitlets                          5.1.0
typed-ast                          1.4.3
typing-extensions                  3.10.0.2
tzdata                             2022.1
ujson                              4.0.2
unicodecsv                         0.14.1
Unidecode                          1.2.0
urllib3                            1.26.7
visdom                             0.1.8.9
watchdog                           2.1.3
wcwidth                            0.2.5
webencodings                       0.5.1
websocket-client                   1.3.3
Werkzeug                           2.0.2
wheel                              0.37.0
whichcraft                         0.6.1
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.12.1
xlrd                               2.0.1
XlsxWriter                         3.0.1
xlwings                            0.24.9
xlwt                               1.3.0
xmltodict                          0.12.0
xtcocotools                        1.13
yacs                               0.1.8
yapf                               0.31.0
youtube-dl                         2021.12.17
zict                               2.0.0
zipp                               3.6.0
zope.event                         4.5.0
zope.interface                     5.4.0
windows 10

### Describe the bug

The error that occurs when I use this command,
I need to train you with the downloaded ntu60-2d bone point dataset or ucf101 bone point dataset using ctr-gcn.
mim train mmaction configs/ctrgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py

### Reproduces the problem - code sample

i don't why.........
so sorry

### Reproduces the problem - command or script

mim train mmaction configs/ctrgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py

### Reproduces the problem - error message

E:\360Downloads\dzsb\mmaction2-main\projects\ctrgcn>mim train mmaction configs/ctrgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py
Training command is F:\anaconda\python.exe e:\360downloads\dzsb\mmaction2-main\mmaction\tools\train.py configs/ctrgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py --launcher none.
06/15 16:36:15 - mmengine - INFO -
------------------------------------------------------------
System environment:
    sys.platform: win32
    Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
    CUDA available: True
    numpy_random_seed: 75495881
    GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
    CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4
    NVCC: Cuda compilation tools, release 11.4, V11.4.152
    MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.16.27049 版
    GCC: n/a
    PyTorch: 1.11.0
    PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

    TorchVision: 0.12.0
    OpenCV: 4.7.0
    MMEngine: 0.7.2

Runtime environment:
    cudnn_benchmark: False
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: None
    diff_rank_seed: False
    deterministic: False
    Distributed launcher: none
    Distributed training: False
    GPU number: 1
------------------------------------------------------------

06/15 16:36:15 - mmengine - INFO - Config:
default_scope = 'mmaction'
default_hooks = dict(
    runtime_info=dict(type='RuntimeInfoHook', _scope_='mmaction'),
    timer=dict(type='IterTimerHook', _scope_='mmaction'),
    logger=dict(
        type='LoggerHook', interval=100, ignore_last=False,
        _scope_='mmaction'),
    param_scheduler=dict(type='ParamSchedulerHook', _scope_='mmaction'),
    checkpoint=dict(
        type='CheckpointHook',
        interval=1,
        save_best='auto',
        _scope_='mmaction'),
    sampler_seed=dict(type='DistSamplerSeedHook', _scope_='mmaction'),
    sync_buffers=dict(type='SyncBuffersHook', _scope_='mmaction'))
env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
log_processor = dict(
    type='LogProcessor', window_size=20, by_epoch=True, _scope_='mmaction')
vis_backends = [dict(type='LocalVisBackend', _scope_='mmaction')]
visualizer = dict(
    type='ActionVisualizer',
    vis_backends=[dict(type='LocalVisBackend')],
    _scope_='mmaction')
log_level = 'INFO'
load_from = None
resume = False
model = dict(
    type='RecognizerGCN',
    backbone=dict(
        type='CTRGCN', graph_cfg=dict(layout='coco', mode='spatial')),
    cls_head=dict(type='GCNHead', num_classes=60, in_channels=256))
dataset_type = 'PoseDataset'
ann_file = 'data/skeleton/ntu60_2d.pkl'
train_pipeline = [
    dict(type='PreNormalize2D'),
    dict(type='GenSkeFeat', dataset='coco', feats=['j']),
    dict(type='UniformSampleFrames', clip_len=100),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=2),
    dict(type='PackActionInputs')
]
val_pipeline = [
    dict(type='PreNormalize2D'),
    dict(type='GenSkeFeat', dataset='coco', feats=['j']),
    dict(
        type='UniformSampleFrames', clip_len=100, num_clips=1, test_mode=True),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=2),
    dict(type='PackActionInputs')
]
test_pipeline = [
    dict(type='PreNormalize2D'),
    dict(type='GenSkeFeat', dataset='coco', feats=['j']),
    dict(
        type='UniformSampleFrames', clip_len=100, num_clips=10,
        test_mode=True),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=2),
    dict(type='PackActionInputs')
]
train_dataloader = dict(
    batch_size=16,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='RepeatDataset',
        times=5,
        dataset=dict(
            type='PoseDataset',
            ann_file='data/skeleton/ntu60_2d.pkl',
            pipeline=[
                dict(type='PreNormalize2D'),
                dict(type='GenSkeFeat', dataset='coco', feats=['j']),
                dict(type='UniformSampleFrames', clip_len=100),
                dict(type='PoseDecode'),
                dict(type='FormatGCNInput', num_person=2),
                dict(type='PackActionInputs')
            ],
            split='xsub_train')))
val_dataloader = dict(
    batch_size=16,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='PoseDataset',
        ann_file='data/skeleton/ntu60_2d.pkl',
        pipeline=[
            dict(type='PreNormalize2D'),
            dict(type='GenSkeFeat', dataset='coco', feats=['j']),
            dict(
                type='UniformSampleFrames',
                clip_len=100,
                num_clips=1,
                test_mode=True),
            dict(type='PoseDecode'),
            dict(type='FormatGCNInput', num_person=2),
            dict(type='PackActionInputs')
        ],
        split='xsub_val',
        test_mode=True))
test_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='PoseDataset',
        ann_file='data/skeleton/ntu60_2d.pkl',
        pipeline=[
            dict(type='PreNormalize2D'),
            dict(type='GenSkeFeat', dataset='coco', feats=['j']),
            dict(
                type='UniformSampleFrames',
                clip_len=100,
                num_clips=10,
                test_mode=True),
            dict(type='PoseDecode'),
            dict(type='FormatGCNInput', num_person=2),
            dict(type='PackActionInputs')
        ],
        split='xsub_val',
        test_mode=True))
val_evaluator = [dict(type='AccMetric')]
test_evaluator = [dict(type='AccMetric')]
train_cfg = dict(
    type='EpochBasedTrainLoop', max_epochs=16, val_begin=1, val_interval=1)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')
param_scheduler = [
    dict(
        type='CosineAnnealingLR',
        eta_min=0,
        T_max=16,
        by_epoch=True,
        convert_to_iter_based=True)
]
optim_wrapper = dict(
    optimizer=dict(
        type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0005, nesterov=True))
auto_scale_lr = dict(enable=False, base_batch_size=128)
launcher = 'none'
work_dir = './work_dirs\\ctrgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d'
randomness = dict(seed=None, diff_rank_seed=False, deterministic=False)

Traceback (most recent call last):
  File "F:\anaconda\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "e:\360downloads\dzsb\mmaction2-main\mmaction\models\recognizers\base.py", line 83, in __init__
    self.backbone = MODELS.build(backbone)
  File "F:\anaconda\lib\site-packages\mmengine\registry\registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "F:\anaconda\lib\site-packages\mmengine\registry\build_functions.py", line 241, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "F:\anaconda\lib\site-packages\mmengine\registry\build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'CTRGCN is not in the model registry. Please check whether the value of `CTRGCN` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\360downloads\dzsb\mmaction2-main\mmaction\tools\train.py", line 135, in <module>
    main()
  File "e:\360downloads\dzsb\mmaction2-main\mmaction\tools\train.py", line 128, in main
    runner = Runner.from_cfg(cfg)
  File "F:\anaconda\lib\site-packages\mmengine\runner\runner.py", line 439, in from_cfg
    runner = cls(
  File "F:\anaconda\lib\site-packages\mmengine\runner\runner.py", line 406, in __init__
    self.model = self.build_model(model)
  File "F:\anaconda\lib\site-packages\mmengine\runner\runner.py", line 813, in build_model
    model = MODELS.build(model)
  File "F:\anaconda\lib\site-packages\mmengine\registry\registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "F:\anaconda\lib\site-packages\mmengine\registry\build_functions.py", line 241, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "F:\anaconda\lib\site-packages\mmengine\registry\build_functions.py", line 135, in build_from_cfg
    raise type(e)(
KeyError: "class `RecognizerGCN` in mmaction/models/recognizers/recognizer_gcn.py: 'CTRGCN is not in the model registry. Please check whether the value of `CTRGCN` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'"
Traceback (most recent call last):
  File "F:\anaconda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\anaconda\Scripts\mim.exe\__main__.py", line 7, in <module>
  File "F:\anaconda\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "F:\anaconda\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "F:\anaconda\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "F:\anaconda\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\anaconda\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "F:\anaconda\lib\site-packages\mim\commands\train.py", line 100, in cli
    is_success, msg = train(
  File "F:\anaconda\lib\site-packages\mim\commands\train.py", line 261, in train
    ret = subprocess.check_call(
  File "F:\anaconda\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['F:\\anaconda\\python.exe', 'e:\\360downloads\\dzsb\\mmaction2-main\\mmaction\\tools\\train.py', 'configs/ctrgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py', '--launcher', 'none']' returned non-zero exit status 1.

### Additional information

I need to train you with the downloaded ntu60-2d bone point dataset or ucf101 bone point dataset using ctr-gcn.

**Comment by Dai-Wenxun** [comment]
Did you follow this [instruction](https://github.com/open-mmlab/mmaction2/blob/main/projects/ctrgcn/README.md#setup-environment) to set the `pwd` as the current directory?

```shell
export PYTHONPATH=`pwd`:$PYTHONPATH
```

**Comment by ya-92626** [comment]
> 

I used the following command, and when I used export, there was an error. I searched for the reason, because Windows did not support export, and then changed it to set.
                  set PYTHONPATH=E:\360Downloads\dzsb\mmaction2-main\projects\ctrgcn
Is it used like this? Or am I setting it wrong?

**Comment by Dai-Wenxun** [comment]
Did you use Windows?

**Comment by ya-92626** [comment]
> 

yes ，i use windows

**Comment by Dai-Wenxun** [comment]
For windows, you could try `set PYTHONPATH=%cd%;%PYTHONPATH%` for cmd and `$env:PYTHONPATH = "$pwd;$env:PYTHONPATH"` for PowerShell.
