### ISSUE TITLE
[Bug] can not use train.py to train the ctrgcn and msg3d? 

### ISSUE THREAD

**Issue by Aidenxu0305** [open-mmlab/mmaction2#2610]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

cuda11.3
python 3.9.12
torch2.0

### Describe the bug

hi, i tryin to train the ctrgcn and msg3d but something goes wrong like that.Whether the config in ’projects‘ document  can not train by the tools/train.py? thanks

### Reproduces the problem - code sample

(workxzy) PS D:\xzy\mmaction2> python tools/train.py projects/ctrgcn/configs/ctrgcntraintest.py
Traceback (most recent call last):
  File "D:\xzy\mmaction2\tools\train.py", line 135, in <module>
    main()
  File "D:\xzy\mmaction2\tools\train.py", line 122, in main
    cfg = Config.fromfile(args.config)
  File "D:\Anaconda\envs\workxzy\lib\site-packages\mmengine\config\config.py", line 449, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "D:\Anaconda\envs\workxzy\lib\site-packages\mmengine\config\config.py", line 933, in _file2dict
    raise e
  File "D:\Anaconda\envs\workxzy\lib\site-packages\mmengine\config\config.py", line 873, in _file2dict
    base_cfg_path, scope = Config._get_cfg_path(
  File "D:\Anaconda\envs\workxzy\lib\site-packages\mmengine\config\config.py", line 1258, in _get_cfg_path
    cfg_path = _get_external_cfg_path(package_path, cfg_path)
  File "D:\Anaconda\envs\workxzy\lib\site-packages\mmengine\config\utils.py", line 93, in _get_external_cfg_path
    model_cfg = _get_cfg_metainfo(package_path, cfg_file)
  File "D:\Anaconda\envs\workxzy\lib\site-packages\mmengine\config\utils.py", line 70, in _get_cfg_metainfo
    cfg_name = model_cfg['Config'].partition('/')[-1]
AttributeError: 'list' object has no attribute 'partition'

**Comment by cir7** [comment]
similar issue to #2585, the issue had been fixed in the latest main branch, you could update your local repo.

**Comment by Aidenxu0305** [comment]
> similar issue to #2585, the issue had been fixed in the latest main branch, you could update your local repo.

thanks a lot，i will try it
