### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jskim1102** [open-mmlab/mmaction2#2644]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

conda create -n  openmmlab python=3.8 -y
conda install -c anaconda cudatoolkit==11.3.1 -y
conda install -c anaconda cudnn -y
pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
pip install -U openmim
mim install mmengine
mim install mmcv
mim install mmdet
mim install mmpose
git clone https://github.com/open-mmlab/mmaction2.git
cd mmaction2
pip install -v -e .
pip install moviepy

### Describe the bug

Hello, first of all, Thanks for providing this model.

I am trying to traing custom model by custom dataset with the same format as ava_dataset.

Before creating custom dataset, I trained with ava_dataset provided by AVA (https://github.com/open-mmlab/mmaction2/blob/main/tools/data/ava/README.md) to confirm the code works well in my conda environment, and I create custom_dataset with the same format as ava_dataset.

---------------------------------------------------------------

Ava_dataset and custom_dataset have different timestamp and number of data,..., so I will write the difference.

[ava]
num of video : 299
rawframes : 900sec -1800sec (len of video)
num of rawframes : 27,030
timestamp : 902sec ~ 1798sec

[custom]
num of video : 264
rawframes : 1sec -20sec (len of video)
num of rawframes : 600
timestamp : 1sec ~ 20sec

---------------------------------------------------------------

Here is the simple example of my custom_dataset annotations.

#1 train.csv
![img01](https://github.com/open-mmlab/mmaction2/assets/96895094/b3a45009-0275-42c8-a5d1-233020572306)

#2 action list.pbtxt
![img02](https://github.com/open-mmlab/mmaction2/assets/96895094/4e48eca3-2b85-4ebe-899b-9b7d28abc546)

#3 dense_proposal.pkl (created using yolov8)
![img03](https://github.com/open-mmlab/mmaction2/assets/96895094/a62e687f-685f-4f12-8b07-a7bd7e71fa97)

---------------------------------------------------------------

And then, I modified the annotations path to custom_dataset in the config file(cfg) and run training code.

The number of data is not enough, so I set the same train and valid file in the cfg file.

For example,

ann_file_train = f'{anno_root}/train.csv'
ann_file_valid = f'{anno_root}/train.csv'

proposal_file_train = f'{anno_root}/dense_proposal.pkl'
proposal_file_valid = f'{anno_root}/dense_proposal.pkl'

When the first epoch is done, ~_result.csv file is created in the path training started. I think it is created for validation. The format of the file is same as AVA annotation(csv). 

However the bounding box is [0 0 1 1] in the file generated after the first epoch. Because of the csv, there is an error due to the bounding box coordinate during the validation process. 

![Screenshot from 2023-08-15 16-21-14](https://github.com/open-mmlab/mmaction2/assets/96895094/4ffae8b9-2e98-401d-a87d-cd54703efbcb)

Why do these errors occur? Is it because the amount of data is low?

### Reproduces the problem - command or script

python tools/train.py configs/detection/slowfast/slowfast_kinetics400-pretrained-r50_8xb6-8x8x1-cosine-10e_custom.py --work-dir ./first --seed

### Reproduces the problem - error message

...
08/10 01:00:19 - mmengine - INFO - Epoch(val)  [1][2440/2720]    eta: 0:00:13  time: 0.0482  data_time: 0.0045  memory: 653  
08/10 01:00:20 - mmengine - INFO - Epoch(val)  [1][2460/2720]    eta: 0:00:12  time: 0.0469  data_time: 0.0035  memory: 653  
08/10 01:00:21 - mmengine - INFO - Epoch(val)  [1][2480/2720]    eta: 0:00:11  time: 0.0474  data_time: 0.0041  memory: 653  
08/10 01:00:22 - mmengine - INFO - Epoch(val)  [1][2500/2720]    eta: 0:00:10  time: 0.0467  data_time: 0.0033  memory: 653  
08/10 01:00:23 - mmengine - INFO - Epoch(val)  [1][2520/2720]    eta: 0:00:09  time: 0.0490  data_time: 0.0052  memory: 653  
08/10 01:00:24 - mmengine - INFO - Epoch(val)  [1][2540/2720]    eta: 0:00:08  time: 0.0471  data_time: 0.0037  memory: 653  
08/10 01:00:25 - mmengine - INFO - Epoch(val)  [1][2560/2720]    eta: 0:00:07  time: 0.0470  data_time: 0.0036  memory: 653  
08/10 01:00:26 - mmengine - INFO - Epoch(val)  [1][2580/2720]    eta: 0:00:06  time: 0.0482  data_time: 0.0044  memory: 653  
08/10 01:00:27 - mmengine - INFO - Epoch(val)  [1][2600/2720]    eta: 0:00:05  time: 0.0482  data_time: 0.0044  memory: 653  
08/10 01:00:28 - mmengine - INFO - Epoch(val)  [1][2620/2720]    eta: 0:00:04  time: 0.0485  data_time: 0.0047  memory: 653  
08/10 01:00:29 - mmengine - INFO - Epoch(val)  [1][2640/2720]    eta: 0:00:03  time: 0.0473  data_time: 0.0040  memory: 653  
08/10 01:00:30 - mmengine - INFO - Epoch(val)  [1][2660/2720]    eta: 0:00:02  time: 0.0469  data_time: 0.0036  memory: 653  
08/10 01:00:31 - mmengine - INFO - Epoch(val)  [1][2680/2720]    eta: 0:00:01  time: 0.0467  data_time: 0.0034  memory: 653  
08/10 01:00:32 - mmengine - INFO - Epoch(val)  [1][2700/2720]    eta: 0:00:00  time: 0.0464  data_time: 0.0036  memory: 653  
08/10 01:00:32 - mmengine - INFO - Epoch(val)  [1][2720/2720]    eta: 0:00:00  time: 0.0462  data_time: 0.0034  memory: 653  
==> 0.0566912 seconds to Reading GT results
==> 0.0700274 seconds to Reading Detection results
ignore empty frmes OOOO
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/anaconda3/envs/openmmlab/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/anaconda3/envs/openmmlab/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/Desktop/kjs/mmaction2/mmaction/evaluation/functional/ava_utils.py", line 182, in tpfp_single
    iou, score, num_boxes = get_overlaps_and_scores_box_mode(
  File "/home/Desktop/kjs/mmaction2/mmaction/evaluation/functional/ava_utils.py", line 160, in get_overlaps_and_scores_box_mode
    detected_boxlist = np_box_list.BoxList(detected_boxes)
  File "/home/Desktop/kjs/mmaction2/mmaction/evaluation/functional/ava_evaluation/np_box_list.py", line 51, in __init__
    raise ValueError('Invalid box data. data must be a numpy array of '
ValueError: Invalid box data. data must be a numpy array of N*[y_min, x_min, y_max, x_max]
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 131, in main
    runner.train()
  File "/home/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1721, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 102, in run
    self.runner.val_loop.run()
  File "/home/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 366, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/home/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/home/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/evaluator/metric.py", line 133, in evaluate
    _metrics = self.compute_metrics(results)  # type: ignore
  File "/home/Desktop/kjs/mmaction2/mmaction/evaluation/metrics/ava_metric.py", line 78, in compute_metrics
    eval_results = ava_eval(
  File "/home/Desktop/kjs/mmaction2/mmaction/evaluation/functional/ava_utils.py", line 258, in ava_eval
    rets = pool.map(tpfp_single, tups)
  File "/home/anaconda3/envs/openmmlab/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/anaconda3/envs/openmmlab/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: Invalid box data. data must be a numpy array of N*[y_min, x_min, y_max, x_max]

**Comment by Harry-KIT** [comment]
Hi @jskim1102 
Could you tell me how you prepared custom dataset like AVA?
Did you use any annotation tools?

**Comment by gauthamprakashan** [comment]
Hey did you find a solution for this?

**Comment by jskim1102** [comment]
Hi, I was working on this issue but had to stop midway. I don’t fully
remember all the details, but I had created training data with annotations
in the same format as provided in the labeled CSV file. However, an error
occurred during the process. I looked into possible solutions, and if I
recall correctly, the key was to use a specific labeling tool that could
directly generate the ground truth (GT) file in the exact annotation format
used in the CSV file.

2025년 1월 8일 (수) 오후 3:58, Gautham Prakashan ***@***.***>님이 작성:

**Comment by gauthamprakashan** [comment]
Thanks for your response.  Do you recall what the tool was? I am stuck exactly in the same position as you?
