### ISSUE TITLE
Question about training custom dataset with PoseC3D (error)

### ISSUE THREAD

**Issue by zksunday** [open-mmlab/mmaction2#2648]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

sys.platform: linux
Python: 3.8.10 (default, Jun  4 2021, 15:09:15) [GCC 7.5.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.3, V11.3.109
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.11.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0+cu113
OpenCV: 4.7.0
MMEngine: 0.7.1
MMAction2: 1.1.0+3368868
MMCV: 2.0.0
MMDetection: 3.0.0
MMPose: 1.0.0

### Describe the bug

i followed https://github.com/open-mmlab/mmaction2/blob/main/configs/skeleton/posec3d/custom_dataset_training.md
made custom dataset.
Integrate PKL files(use _ntu_pose_extraction.py_) extracted from multiple videos to get  _ZhengHe.pkl._
Then I changed the _ann_file_ of _slowonly_r50_8xb16-u48-240e_gym-keypoint.py_ to the path of _ZhengHe.pkl._
I got an error when I started training with this config file.

### Reproduces the problem - code sample

**I used the following code to integrate the pkl files extracted by ntu_pose_extraction.py**
import mmengine

result = []
pkl_file_list=['tools/data/skeleton/GEMEP-pkl/S001amuA002_Gemep.pkl',
               'tools/data/skeleton/GEMEP-pkl/S001angA104_Gemep.pkl',
               'tools/data/skeleton/GEMEP-pkl/S001anxA108_Gemep.pkl',
               #_Over a hundred file names are omitted here_
               'tools/data/skeleton/GEMEP-pkl/S110relA015_GEMEP.pkl',
               'tools/data/skeleton/GEMEP-pkl/S110sadA117_GEMEP.pkl',
               
               ]
output_path='tools/data/skeleton/ZhengHe.pkl'
for pkl_path in pkl_file_list:
    data = mmengine.load(pkl_path)
    result.append(data)
    
mmengine.dump(result, output_path)

### Reproduces the problem - command or script

python tools/train.py configs/skeleton/posec3d/slowonly_r50_8xb16-u48-240e_gym-keypoint.py

### Reproduces the problem - error message

 -------------------- 
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/autodl-tmp/mmaction2/mmaction/datasets/pose_dataset.py", line 40, in __init__
    super().__init__(
  File "/root/autodl-tmp/mmaction2/mmaction/datasets/base.py", line 48, in __init__
    super().__init__(
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 250, in __init__
    self.full_init()
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 301, in full_init
    self.data_list = self.load_data_list()
  File "/root/autodl-tmp/mmaction2/mmaction/datasets/pose_dataset.py", line 50, in load_data_list
    split, annos = data_list['split'], data_list['annotations']
KeyError: 'split'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/dataset/dataset_wrapper.py", line 211, in __init__
    self.dataset = DATASETS.build(dataset)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
KeyError: "class `PoseDataset` in mmaction/datasets/pose_dataset.py: 'split'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1346, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
KeyError: 'class `RepeatDataset` in mmengine/dataset/dataset_wrapper.py: "class `PoseDataset` in mmaction/datasets/pose_dataset.py: \'split\'"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 131, in main
    runner.train()
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1672, in train
    self._train_loop = self.build_train_loop(
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1464, in build_train_loop
    loop = LOOPS.build(
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
KeyError: 'class `EpochBasedTrainLoop` in mmengine/runner/loops.py: \'class `RepeatDataset` in mmengine/dataset/dataset_wrapper.py: "class `PoseDataset` in mmaction/datasets/pose_dataset.py: \\\'split\\\'"\''

### Additional information

Maybe I had a formatting problem when integrating the pkl files.

**Comment by cir7** [comment]
The original pkl file in `slowonly_r50_8xb16-u48-240e_gym-keypoint.py` contains multiple splits, you could refer to the [docstring](https://github.com/open-mmlab/mmaction2/blob/951dfc0ff8f4e30fe35e4e093690bf272fbae1e1/mmaction/datasets/pose_dataset.py#L25) for details. But your pkl file is a list, you could delete `split` field in your config file, and assign separate files for train/val/test dataloader. another way is to wrap your pkl file into a dict, you could refer to the format of gym_2d.pkl.
