### ISSUE TITLE
 demo\demo_skeleton.py， 'PoseLocalVisualizer is not in the mmaction::visualizer registry.

### ISSUE THREAD

**Issue by hsp2454** [open-mmlab/mmaction2#2674]
### The doc issue

When I use lameness_pig_stgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py to train custom data, run 
"`python demo\demo_skeleton.py data/videos/S001C001P001R001A001.avi data/result.avi`"，it reported the following mistake

```
Traceback (most recent call last):
  File "D:\Code\lameness_pig_mmaction2\demo\demo.py", line 158, in <module>
    main()
  File "D:\Code\lameness_pig_mmaction2\demo\demo.py", line 120, in main
    pred_result = inference_recognizer(model, args.video)
  File "D:\Code\lameness_pig_mmaction2\demo\demo_skeleton.py", line 151, in main
    visualize(args, frames, pose_data_samples, action_label)
  File "D:\Code\lameness_pig_mmaction2\demo\demo_skeleton.py", line 92, in visualize
    visualizer = VISUALIZERS.build(pose_config.visualizer)
  File "E:\software\Anaconda\envs\lameness_mmaction\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "E:\software\Anaconda\envs\lameness_mmaction\lib\site-packages\mmengine\registry\build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'PoseLocalVisualizer is not in the mmaction::visualizer registry. Please check whether the value of `PoseLocalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.
readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
```

**Comment by DreamSUUNY** [comment]
I am also encountering this issue, trying to change the environment, change the mmcv, mmdet versions, all report this error.

**Comment by ao-zz** [comment]
@DreamSUUNY @cir7 
I get a solution and explain it at #2316
