### ISSUE TITLE
mim faias to download kinetics700

### ISSUE THREAD

**Issue by beppe2hd** [open-mmlab/mmaction2#2743]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

sys.platform: linux
Python: 3.8.18 (default, Sep 11 2023, 13:40:15) [GCC 11.2.0]
CUDA available: False
numpy_random_seed: 2147483648
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.1.0
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.0, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.16.0
OpenCV: 4.8.1
MMEngine: 0.9.1
MMAction2: 1.2.0+4d6c934
MMCV: 2.1.0
MMDetection: 3.2.0
MMPose: 1.2.0

### Describe the bug

If I try to download the kinetics700 dataset with mim it fails

### Reproduces the problem - command or script

```bash
(openmmlab) daitan3@daitan3-workstation:~/decondDrive/pythonProjects/mmaction2$ mim download mmaction2 --dataset kinetics700
```

### Reproduces the problem - error message

```
Start downloading kinetics700 to data...
WARNING:This CLI tool is deprecated and will be removed in a future release.
The opendatalab(odl) pkg has been deprecated and will no longer be supported in few weeks.
We recommend that you switch to the openxlab pkg, which accept same username/password,
provides the same functionality and other enhanced AI friendly features.
More details please refer to https://openxlab.org.cn/datasets

No dataset: OpenMMLab
Traceback (most recent call last):
  File "/home/daitan3/miniconda3/envs/openmmlab/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/daitan3/miniconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/daitan3/miniconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/daitan3/miniconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/daitan3/miniconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/daitan3/miniconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/daitan3/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/download.py", line 70, in cli
    download(package, configs, dest_root, check_certificate, dataset)
  File "/home/daitan3/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/download.py", line 110, in download
    return _download_dataset(package, dataset, dest_root)  # type: ignore
  File "/home/daitan3/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/download.py", line 242, in _download_dataset
    subprocess.check_call(['odl', 'get', src_name, '-d', download_root],
  File "/home/daitan3/miniconda3/envs/openmmlab/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
```

### Additional information

If I try to download the dataset with the command:
```
openxlab dataset get --dataset-repo OpenMMLab/Kinetics_700
```
The dataste is correctly downloaded

**Comment by Altair-yang** [comment]
Thanks for your solution, I have correctly downloaded kinetics400 using the command : "openxlab dataset get --dataset-repo OpenMMLab/Kinetics-400"

**Comment by hustzyj** [comment]
> Thanks for your solution, I have correctly downloaded kinetics400 using the command : "openxlab dataset get --dataset-repo OpenMMLab/Kinetics-400"

Hi, I want to know how to process the .tar.gz.0000 file？I got the mistakes as follows:
gzip:sudin:unexpected end of file. Additional, the .tar.gz.0001 seems not a archive file, how to process it? Thank you very much!

**Comment by Altair-yang** [comment]
> > Thanks for your solution, I have correctly downloaded kinetics400 using the command : "openxlab dataset get --dataset-repo OpenMMLab/Kinetics-400"
> 
> Hi, I want to know how to process the .tar.gz.0000 file？I got the mistakes as follows: gzip:sudin:unexpected end of file. Additional, the .tar.gz.0001 seems not a archive file, how to process it? Thank you very much!

我下载好数据集后，直接运行 preprocess_k400.sh 这个脚本后，就解压好了，你可以试一试
<img width="603" alt="k400" src="https://github.com/open-mmlab/mmaction2/assets/90332613/6708a29f-ec26-44c0-a52a-5a11e7f9e55b">

**Comment by Code-kunkun** [comment]
> > Thanks for your solution, I have correctly downloaded kinetics400 using the command : "openxlab dataset get --dataset-repo OpenMMLab/Kinetics-400"
> 
> Hi, I want to know how to process the .tar.gz.0000 file？I got the mistakes as follows: gzip:sudin:unexpected end of file. Additional, the .tar.gz.0001 seems not a archive file, how to process it? Thank you very much!

Have you solved this problem? I also encountered a similar error

**Comment by MoH-assan** [comment]
Hi, 
Facing login issue in https://github.com/omniobject3d/OmniObject3D/issues/42

`$ openxlab dataset get --dataset-repo OpenMMLab/Kinetics_700
Fetching the list of datasets...
401: {"msg":"login required"}`

Although I verified that I am correctly logged in 

Appreciate your help. 
Thanks,
