### ISSUE TITLE
'PackDetInputs is not in the mmaction::transform registry. Please check whether the value of `PackDetInputs` is correct or it was registered as expected.

### ISSUE THREAD

**Issue by 15598003953** [open-mmlab/mmaction2#2747]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

pytorch=1.12.1
python=3.8
cuda=11.6
mmcv=2.0.1
mmengine=0.90
mmdet=3.2.0

### Describe the bug

running code：webcam_demo_spatiotemporal_det.py 
cfg：configs\detection\slowfast\slowfast_kinetics400-pretrained-r50_8xb6-8x8x1-cosine-10e_ava22-rgb.py
det_cfg:configs\faster_rcnn\faster-rcnn_r50_fpn_2x_coco.py

### Reproduces the problem - code sample

Traceback (most recent call last):
  File "D:/CODE/mmaction2-main/demo/webcam_demo_spatiotemporal_det.py", line 856, in <module>
    main(parse_args())
  File "D:/CODE/mmaction2-main/demo/webcam_demo_spatiotemporal_det.py", line 831, in main
    human_detector.predict(task)
  File "D:/CODE/mmaction2-main/demo/webcam_demo_spatiotemporal_det.py", line 224, in predict
    bboxes = self._do_detect(keyframe)
  File "D:/CODE/mmaction2-main/demo/webcam_demo_spatiotemporal_det.py", line 258, in _do_detect
    det_data_sample = inference_detector(self.model, image)
  File "D:\CODE\mmaction2-main\mmdetection-main\mmdet\apis\inference.py", line 159, in inference_detector
    test_pipeline = Compose(test_pipeline)
  File "D:\Anaconda3\envs\mmact2\lib\site-packages\mmcv\transforms\wrappers.py", line 66, in __init__
    transform = TRANSFORMS.build(transform)
  File "D:\Anaconda3\envs\mmact2\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\Anaconda3\envs\mmact2\lib\site-packages\mmengine\registry\build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'PackDetInputs is not in the mmaction::transform registry. Please check whether the value of `PackDetInputs` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

### Reproduces the problem - command or script

webcam_demo_spatiotemporal_det.py

**Comment by ao-zz** [comment]
There are tow possible ways to solve it.
1. Change model's load order, see [here](https://github.com/open-mmlab/mmdetection/issues/10900#issuecomment-1795925925)
2. Update cfg to make mmdet fit in mmpose's scope, see [here](https://github.com/open-mmlab/mmdetection/issues/10900#issuecomment-1858620214). // This works for me

**Comment by luosiqi666** [comment]
KeyError: 'PackDetInputs is not in the mmaction::transform registry. Please check whether the value of `PackDetInputs` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

I have the same problem, please how to solve it
