### ISSUE TITLE
[Bug] Fail to use confusion_matrix to RGBPoseC3D

### ISSUE THREAD

**Issue by Hobeom** [open-mmlab/mmaction2#2815]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

sys.platform: linux
Python: 3.9.17 (main, Jul  5 2023, 20:41:20) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3: NVIDIA GeForce RTX 4090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.0.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.8.1  (built against CUDA 11.8)
    - Built with CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.2
OpenCV: 4.8.0
MMEngine: 0.8.2
MMAction2: 1.2.0+4d6c934
MMCV: 2.0.1
MMDetection: 3.1.0

### Describe the bug

While attempting to configure evaluators for validation and testing phases for the RGBPoseC3D, I encountered an issue where specifying ConfusionMatrix as part of the evaluators does not work as expected. 

### Reproduces the problem - code sample

The configuration is defined in configs/skeleton/posec3d/rgbpose_conv3d/rgbpose_conv3d.py. The relevant section of the configuration is as follows:
```
val_evaluator = [dict(type='AccMetric'), dict(type='ConfusionMatrix')]
test_evaluator = val_evaluator
```

### Reproduces the problem - command or script

```bash
 ./tools/dist_train.sh configs/skeleton/posec3d/rgbpose_conv3d/rgbpose_conv3d.py 4
```

### Reproduces the problem - error message

```
mmaction/evaluation/metrics/acc_metric.py", line 252, in process
    pred_label = pred_scores.argmax(dim=0, keepdim=True)
AttributeError: 'dict' object has no attribute 'argmax'
```

### Additional information

The [modified version in my branch](https://github.com/HoBeom/mmaction2/commit/789c12d53ab830c8a7bfc01e34ae9ef777d8f775), which was adjusted to operate identically to the AccMetric module, functions only for specific purposes. There is a need to redesign the abstraction of the evaluation code.

**Comment by lmc2000** [comment]
解决了吗?

**Comment by Hobeom** [comment]
@lmc2000 Use modified version in my branch

https://github.com/HoBeom/mmaction2/blob/789c12d53ab830c8a7bfc01e34ae9ef777d8f775/mmaction/evaluation/metrics/acc_metric.py#L272-L300

**Comment by lmc2000** [comment]
谢谢,我也对我自己的代码做了相应的修改

**Comment by 1zhumble** [comment]
> [@lmc2000](https://github.com/lmc2000) Use modified version in my branch
> 
> https://github.com/HoBeom/mmaction2/blob/789c12d53ab830c8a7bfc01e34ae9ef777d8f775/mmaction/evaluation/metrics/acc_metric.py#L272-L300
Hello, after your modification, the following problems have occurred. May I ask how to modify them
Traceback (most recent call last):
  File "tools/test.py", line 126, in <module>
    main()
  File "tools/test.py", line 122, in main
    runner.test()
  File "D:\miniconda3\envs\openmmlab\lib\site-packages\mmengine\runner\runner.py", line 1823, in test
    metrics = self.test_loop.run()  # type: ignore
  File "D:\miniconda3\envs\openmmlab\lib\site-packages\mmengine\runner\loops.py", line 466, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "D:\miniconda3\envs\openmmlab\lib\site-packages\mmengine\evaluator\evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "D:\miniconda3\envs\openmmlab\lib\site-packages\mmengine\evaluator\metric.py", line 133, in evaluate
    _metrics = self.compute_metrics(results)  # type: ignore
  File "d:\zzb_code\mmaction2\mmaction\evaluation\metrics\acc_metric.py", line 291, in compute_metrics
    '1:1': get_weighted_score([rgb, pose], [1, 1]),
  File "d:\zzb_code\mmaction2\mmaction\evaluation\functional\accuracy.py", line 454, in get_weighted_score
    scores = np.array(score_list)  # (num_coeff, num_samples, num_classes)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 1305) + inhomogeneous part.
