### ISSUE TITLE
Pytorch RuntimeError when saving C3D model in training checkpoint

### ISSUE THREAD

**Issue by fluque1995** [open-mmlab/mmaction2#295]
**Bug description**
I have encountered an error when trying to train C3D model, specifically when trying to save a checkpoint of the model.

**Reproduction**
1. The script I have run is `tools/train.py`, using the configuration file provided for C3D model (`configs/recognition/c3d/c3d_sports1m_16x1x1_45e_ucf101_rgb.py`), with no modifications (for error reproducibility I have set the interval of checkpoint to 1 in order to save time, but no other changes have been introduced). The first time I got the error the file was not modified. The training dataset is UCF101, which I have configured using the instructions provided. The dataset has been also used to train a TSN model, so I believe everything is working smoothly.

The command run is:
```
python tools/train.py configs/c3d_sports1m_16x1x1_45e_ucf101_rgb.py --gpu-ids 1 --validate

```

**Environment**
`collect_env.py` output:

```
sys.platform: linux
Python: 3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
CUDA available: True
GPU 0,1: Tesla V100-SXM2-32GB
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 9.1, V9.1.85
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.6.0a0+35d732a
OpenCV: 4.4.0
MMCV: 1.1.5
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMAction2: 0.7.0+d6f76cd
```

**Error traceback**
The error traceback is the following:

```
  File "train.py", line 163, in <module>                                                       
    main()                                                                                              
  File "train.py", line 153, in main                                                           
    train_model(                                                                                        
  File "/home/pacoluque/mmaction2/mmaction/apis/train.py", line 112, in train_model                     
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)                                            
  File "/home/pacoluque/conda-envs/pyviad/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py$
, line 125, in run                                                                                      
    epoch_runner(data_loaders[i], **kwargs)                                                             
  File "/home/pacoluque/conda-envs/pyviad/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py$
, line 54, in train                                                                                     
    self.call_hook('after_train_epoch')                                                                 
  File "/home/pacoluque/conda-envs/pyviad/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 
307, in call_hook                                                                                       
    getattr(hook, fn_name)(self)                                                                        
  File "/home/pacoluque/mmaction2/mmaction/core/evaluation/eval_hooks.py", line 151, in after_train_epo$
h                                                                                                       
    results = single_gpu_test(runner.model, self.dataloader)                                            
  File "/home/pacoluque/mmaction2/mmaction/apis/test.py", line 28, in single_gpu_test                   
    for data in data_loader:                                                                            
  File "/home/pacoluque/conda-envs/pyviad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", $
ine 345, in __next__                                                                                    
    data = self._next_data()                                                                            
  File "/home/pacoluque/conda-envs/pyviad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", $
ine 856, in _next_data                                                                                  
    return self._process_data(data)                                                                     
  File "/home/pacoluque/conda-envs/pyviad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", $
ine 881, in _process_data                                                                               
    data.reraise()                                                                                      
  File "/home/pacoluque/conda-envs/pyviad/lib/python3.8/site-packages/torch/_utils.py", line 395, in re$
aise                                                                                                    
    raise self.exc_type(msg)                                                                            
RuntimeError: Caught RuntimeError in DataLoader worker process 0.                                       
Original Traceback (most recent call last):                                                             
  File "/home/pacoluque/conda-envs/pyviad/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py"
, line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/pacoluque/conda-envs/pyviad/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py",
 line 47, in fetch
    return self.collate_fn(data)
  File "/home/pacoluque/conda-envs/pyviad/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 79
, in collate
    return {
  File "/home/pacoluque/conda-envs/pyviad/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 80
, in <dictcomp>
    key: collate([d[key] for d in batch], samples_per_gpu)
  File "/home/pacoluque/conda-envs/pyviad/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 84
, in collate
    return default_collate(batch)
  File "/home/pacoluque/conda-envs/pyviad/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py
", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [1, 3, 16, 112, 112] at entry 0 and [1
, 3, 16, 8, 112] at entry 15
```

**Bug fix**
Seems like the dimension of a tensor is incorrect, I'm currently investigating the issue, but I don't understand why the batch must be saved with the model.

Thank you

**Comment by congee524** [comment]
modify the train_pipeline，add **Resize** after **RandomCrop**
```
train_pipeline = [
    dict(type='SampleFrames', clip_len=16, frame_interval=1, num_clips=1),
    dict(type='RawFrameDecode'),
    dict(type='Resize', scale=(128, 171)),
    dict(type='RandomCrop', size=112),
    dict(type='Resize', scale=(112, 112), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]
```
Does that solve the problem？

**Comment by fluque1995** [comment]
No, seems like the problem persists. I have only modified train_pipeline, I'll also add it in the validation and test config and try again.

I'll update you when done in a few mins! Thanks!

**Comment by fluque1995** [comment]
Must not be the case since that information is not usually included in checkpoints, but let's see

**Comment by fluque1995** [comment]
Adding the `Reshape` after `RandomCrop` in all the pipelines solved the problem! It is a bit strange that the validation pipeline affects the checkpointer, however.

Thanks for the help! :smile:

**Comment by congee524** [comment]
I'm also very confused. `RandomCrop` and `CenterCrop` should not change the size of images

**Comment by SuX97** [comment]
Seems to be the problem of a failure Resize or Crop(maybe a corrupted image), but nothing to do with the checkpoint or model. Is this a recurrent bug?

**Comment by fluque1995** [comment]
I'll try to find if there is any corrupted image in the dataset. It was converted from video to frames using your tools (the OpenCV extractor), and works like a charm with other models, so I don't think it's going to be the case.

Thanks for the suggestion though, and congrats for the great work!
