### ISSUE TITLE
Error in long video demo : too many indices for array: array is 0-dimensional, but 3 were indexed

### ISSUE THREAD

**Issue by wwdok** [open-mmlab/mmaction2#377]
When i am run [long-video-demo](https://github.com/open-mmlab/mmaction2/tree/master/demo#long-video-demo) example 1, it reports an error : 
```
(base) weidawang@weidawang-TUF-Gaming-FX506LU-FX506LU:~/Repo/mmaction2$ python demo/long_video_demo.py configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth demo/inputs/1.mp4 demo/label_map.txt demo/outputs/LongVideoDemo1_1.mp4 --input-step 3 --device cpu --threshold 0.2
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 650/650, 0.2 task/s, elapsed: 2761s, ETA:     0sTraceback (most recent call last):
  File "demo/long_video_demo.py", line 178, in <module>
    main()
  File "demo/long_video_demo.py", line 174, in main
    show_results()
  File "demo/long_video_demo.py", line 73, in show_results
    backup_frames.append(np.array(frame)[:, :, ::-1])
IndexError: too many indices for array: array is 0-dimensional, but 3 were indexed
```

**Comment by dreamerlin** [comment]
The demo runs correctly for me. It seems the last frame (that it, the `frame` variable) in your video got abnormal value. Could u please help to debug it using `try... except` and tell me the value of the `frame`. my wild guess is that it is `None` or `[]`

**Comment by wwdok** [comment]
Your guess is right, the frame turns out None,below is the output:
```
(base) user@user-TUF-Gaming-FX506LU-FX506LU:~/Repo/mmaction2$ python demo/long_video_demo.py configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth demo/inputs/1.mp4 demo/label_map.txt demo/outputs/LongVideoDemo1.mp4 --input-step 3 --threshold 0.2
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 650/650, 3.8 task/s, elapsed: 173s, ETA:     0s
too many indices for array: array is 0-dimensional, but 3 were indexed
None
Traceback (most recent call last):
  File "demo/long_video_demo.py", line 182, in <module>
    main()
  File "demo/long_video_demo.py", line 178, in main
    show_results()
  File "demo/long_video_demo.py", line 86, in show_results
    chosen_frame = random.choice(backup_frames)
  File "/home/user/miniconda3/lib/python3.7/random.py", line 261, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```
Added code are:
```
        try:
            backup_frames.append(np.array(frame)[:, :, ::-1])
        except Exception as e:
            print(e)
            print(np.array(frame))
```
But the weird thing is that the input video can normally play, and after running this command, it can output the result video, and the output video still can normally play, it seems this error have no influrence to the result ~
My used input video is : 
https://drive.google.com/file/d/1Unw_bgmeexooT4jsrQHDo3zj3-xcUlNK/view?usp=sharing

I also tested another video, it is noraml, so above video is really wierd.
