### ISSUE TITLE
Question about data

### ISSUE THREAD

**Issue by ylyenjoy** [open-mmlab/mmaction2#378]
**I try to achieve the mmaciton2/tsn with my dataset,but get some wrong
I made dataset following steps: My dataset format is like this:**
/home/shtf/ysir/20201124_ceshi/TC_train/nw/0.avi 0
/home/shtf/ysir/20201124_ceshi/TC_train/nw/1.avi 0
/home/shtf/ysir/20201124_ceshi/TC_train/nw/2.avi 0
**and in my configuration(tsn_r50_1x1x3_100e_kinetics400_rgb.py) what I changed like following:**
dataset_type = 'VideoDataset'
data_root = '/home/shtf/ysir/20201124_ceshi/TC_train'
data_root_val = '/home/shtf/ysir/20201124_ceshi/TC_val'
ann_file_train = '/home/shtf/ysir/20201124_ceshi/TC_train/annotation.txt'
ann_file_val = '/home/shtf/ysir/20201124_ceshi/TC_val/annotation.txt'
ann_file_test = '/home/shtf/ysir/20201124_ceshi/TC_val/annotation.txt' 
**Then I execute the statement 'python tools/train.py configs/recognition/tsn/tsn_r50_1x1x3_100e_kinetics400_rgb.py  --work-dir work_dirs/tsn_r50_1x1x3_100e_kinetics400_rgb --validate --seed 0 --deterministic',but got wrong like this**:

Traceback (most recent call last):
  File "/home/shtf/ysir/mmaction2/tools/train.py", line 178, in <module>
    main()
  File "/home/shtf/ysir/mmaction2/tools/train.py", line 174, in main
    meta=meta)
  File "/home/shtf/ysir/mmaction2/mmaction/apis/train.py", line 141, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/shtf/anaconda3/envs/mmaction2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/shtf/anaconda3/envs/mmaction2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/shtf/anaconda3/envs/mmaction2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/shtf/anaconda3/envs/mmaction2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/shtf/anaconda3/envs/mmaction2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/shtf/anaconda3/envs/mmaction2/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/shtf/anaconda3/envs/mmaction2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/shtf/anaconda3/envs/mmaction2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/shtf/anaconda3/envs/mmaction2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/shtf/ysir/mmaction2/mmaction/datasets/base.py", line 280, in __getitem__
    return self.prepare_train_frames(idx)
  File "/home/shtf/ysir/mmaction2/mmaction/datasets/base.py", line 249, in prepare_train_frames
    return self.pipeline(results)
  File "/home/shtf/ysir/mmaction2/mmaction/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/shtf/ysir/mmaction2/mmaction/datasets/pipelines/loading.py", line 208, in __call__
    total_frames = results['total_frames']
KeyError: 'total_frames'
Process finished with exit code 1
**When it  preprocessed the image，It prompted me the results got from video_dataset didn't have keyword "total_frames" ,I checked all files about tsn I used,but it didn't find any about 'total_frames' ,I don't know the reason of the question,whether it is I forget something before preparing dataset,Thanks**

**Comment by dreamerlin** [comment]
Since you use video as input rather than frames, you should use configs for videos like [this](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_video_320p_1x1x3_100e_kinetics400_rgb.py).

**Comment by ylyenjoy** [comment]
OK,I tried it ,it works,Thank you,I compared two files,I found in your simple there is two statements more than my files,And this is yours
 "train_pipeline = [
train_pipeline = [
    dict(type='DecordInit'),
    dict(type='SampleFrames', clip_len=1, frame_interval=1, num_clips=3),
    dict(type='DecordDecode'),
    dict(type='RandomResizedCrop'),
    .....]"
and this is mine 
"train_pipeline = [
    dict(type='SampleFrames', clip_len=1, frame_interval=1, num_clips=3),
    dict(type='RawFrameDecode'),
    dict(type='Resize', scale=(-1, 256)),
    ....]"
I wonder whether  if it is necessary to add "dict(type='DecordInit')" and "dict(type='DecordDecode')"
Thanks

**Comment by dreamerlin** [comment]
> OK,I tried it ,it works,Thank you,I compared two files,I found in your simple there is two statements more than my files,And this is yours
> "train_pipeline = [
> train_pipeline = [
> dict(type='DecordInit'),
> dict(type='SampleFrames', clip_len=1, frame_interval=1, num_clips=3),
> dict(type='DecordDecode'),
> dict(type='RandomResizedCrop'),
> .....]"
> and this is mine
> "train_pipeline = [
> dict(type='SampleFrames', clip_len=1, frame_interval=1, num_clips=3),
> dict(type='RawFrameDecode'),
> dict(type='Resize', scale=(-1, 256)),
> ....]"
> I wonder whether if it is necessary to add "dict(type='DecordInit')" and "dict(type='DecordDecode')"
> Thanks

Our repo support to process extracted rawframes and videos on the fly, and there are some differences in the loading between them. Since you are using a video rather than its extracted frames, you should use video pipeline rather than frame pipeline : )

**Comment by innerlee** [comment]
Please use ` ``` ... ``` ` to fence your snippets

**Comment by ylyenjoy** [comment]
OK,I got it,thanks
