### ISSUE TITLE
OSError: convert: not authorized `@/tmp/tmptu3e5vax.txt' @ error/property.c/InterpretImageProperties/3405. convert: no images defined `PNG32:/tmp/tmpp4uzhuew.png' @ error/convert.c/ConvertImageCommand/3210.

### ISSUE THREAD

**Issue by Sean-hku** [open-mmlab/mmaction2#385]
**Hi, I run this demo script:**
`python demo/demo.py configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py \
    checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth \
    demo/demo.mp4 demo/label_map.txt --out-filename demo/demo_out.mp4`

**there is a OSError:**
The top-5 labels with corresponding scores are:
arm wrestling:  29.616438
rock scissors paper:  10.754841
shaking hands:  9.908401
clapping:  9.189913
massaging feet:  8.305306
Traceback (most recent call last):
  File "/home/hkuit164/anaconda3/envs/mmaction/lib/python3.7/site-packages/moviepy/video/VideoClip.py", line 1137, in __init__
    subprocess_call(cmd, logger=None)
  File "/home/hkuit164/anaconda3/envs/mmaction/lib/python3.7/site-packages/moviepy/tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: convert: not authorized `@/tmp/tmptu3e5vax.txt' @ error/property.c/InterpretImageProperties/3405.
convert: no images defined `PNG32:/tmp/tmpp4uzhuew.png' @ error/convert.c/ConvertImageCommand/3210.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/hkuit164/TOSHIBA/mmaction2/demo/demo.py", line 169, in <module>
    main()
  File "/media/hkuit164/TOSHIBA/mmaction2/demo/demo.py", line 165, in main
    use_frames=args.use_frames)
  File "/media/hkuit164/TOSHIBA/mmaction2/demo/demo.py", line 112, in get_output
    text_clips = TextClip(label, fontsize=font_size, color=font_color)
  File "/home/hkuit164/anaconda3/envs/mmaction/lib/python3.7/site-packages/moviepy/video/VideoClip.py", line 1146, in __init__
    raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

convert: not authorized `@/tmp/tmptu3e5vax.txt' @ error/property.c/InterpretImageProperties/3405.
convert: no images defined `PNG32:/tmp/tmpp4uzhuew.png' @ error/convert.c/ConvertImageCommand/3210.
.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect

**Is this due to the moviepy?**

**Comment by dreamerlin** [comment]
https://github.com/open-mmlab/mmaction2/blob/master/docs/install.md#requirements

**Comment by Sean-hku** [comment]
> https://github.com/open-mmlab/mmaction2/blob/master/docs/install.md#requirements

**Thx. 
But I get another error,**
t:   0%|          | 0/280 [00:00<?, ?it/s, now=None]Traceback (most recent call last):
  File "/home/hkuit164/anaconda3/envs/mmaction/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_writer.py", line 136, in write_frame
    self.proc.stdin.write(img_array.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/hkuit164/TOSHIBA/mmaction2/demo/demo.py", line 169, in <module>
    main()
  File "/media/hkuit164/TOSHIBA/mmaction2/demo/demo.py", line 165, in main
    use_frames=args.use_frames)
  File "/media/hkuit164/TOSHIBA/mmaction2/demo/demo.py", line 124, in get_output
    video_clips.write_videofile(out_filename, remove_temp=True)
  File "<decorator-gen-55>", line 2, in write_videofile
  File "/home/hkuit164/anaconda3/envs/mmaction/lib/python3.7/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-54>", line 2, in write_videofile
  File "/home/hkuit164/anaconda3/envs/mmaction/lib/python3.7/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-53>", line 2, in write_videofile
  File "/home/hkuit164/anaconda3/envs/mmaction/lib/python3.7/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/home/hkuit164/anaconda3/envs/mmaction/lib/python3.7/site-packages/moviepy/video/VideoClip.py", line 307, in write_videofile
    logger=logger)
  File "/home/hkuit164/anaconda3/envs/mmaction/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_writer.py", line 228, in ffmpeg_write_video
    writer.write_frame(frame)
  File "/home/hkuit164/anaconda3/envs/mmaction/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_writer.py", line 180, in write_frame
    raise IOError(error)
OSError: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file demo/demo_out.mp4:

 b'demo/demo_out.mp4: No such file or directory\n'

Process finished with exit code 1

**Comment by innerlee** [comment]
mkdir demo

**Comment by Sean-hku** [comment]
Thx
solved it
