### ISSUE TITLE
 [Errno 2] No such file or directory: 'data/hmdb51/annotations/trainlist01.txt'

### ISSUE THREAD

**Issue by wwdok** [open-mmlab/mmaction2#386]
I am running `bash generate_rawframes_filelist.sh` as the preparing_hmdb51.md instructs, but met an error :
```
(base) root@LAB_VM:/home/mmaction2/tools/data/hmdb51# bash generate_rawframes_filelist.sh
parse frames under directory data/hmdb51/rawframes/
0 videos parsed
200 videos parsed
400 videos parsed
600 videos parsed
800 videos parsed
1000 videos parsed
1200 videos parsed
1400 videos parsed
1600 videos parsed
1800 videos parsed
2000 videos parsed
2200 videos parsed
2400 videos parsed
2600 videos parsed
2800 videos parsed
3000 videos parsed
3200 videos parsed
3400 videos parsed
3600 videos parsed
3800 videos parsed
4000 videos parsed
4200 videos parsed
4400 videos parsed
4600 videos parsed
4800 videos parsed
5000 videos parsed
5200 videos parsed
5400 videos parsed
5600 videos parsed
5800 videos parsed
6000 videos parsed
6200 videos parsed
6400 videos parsed
6600 videos parsed
frame directory analysis done
Traceback (most recent call last):
  File "tools/data/build_file_list.py", line 263, in <module>
    main()
  File "tools/data/build_file_list.py", line 205, in main
    splits = parse_hmdb51_split(args.level)
  File "/home/mmaction2/tools/data/parse_file_list.py", line 492, in parse_hmdb51_split
    with open(train_file_template.format(i), 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'data/hmdb51/annotations/trainlist01.txt'
Filelist for rawframes generated.

```

Above is the second try, the first try report similar error:

```
(base) root@LAB_VM:/home/mmaction2/tools/data/hmdb51# bash generate_rawframes_filelist.sh
parse frames under directory data/hmdb51/rawframes/
0 videos parsed
200 videos parsed
400 videos parsed
600 videos parsed
800 videos parsed
1000 videos parsed
1200 videos parsed
1400 videos parsed
1600 videos parsed
1800 videos parsed
2000 videos parsed
2200 videos parsed
2400 videos parsed
2600 videos parsed
2800 videos parsed
3000 videos parsed
3200 videos parsed
3400 videos parsed
3600 videos parsed
3800 videos parsed
4000 videos parsed
4200 videos parsed
4400 videos parsed
4600 videos parsed
4800 videos parsed
5000 videos parsed
5200 videos parsed
5400 videos parsed
5600 videos parsed
5800 videos parsed
6000 videos parsed
6200 videos parsed
6400 videos parsed
6600 videos parsed
frame directory analysis done
Traceback (most recent call last):
  File "tools/data/build_file_list.py", line 263, in <module>
    main()
  File "tools/data/build_file_list.py", line 205, in main
    splits = parse_hmdb51_split(args.level)
  File "/home/mmaction2/tools/data/parse_file_list.py", line 473, in parse_hmdb51_split
    generate_class_index_file()
  File "/home/mmaction2/tools/data/parse_file_list.py", line 449, in generate_class_index_file
    with open(filename_path, 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'data/hmdb51/annotations/hmdb51_org.rar_test_split1.txt'
Filelist for rawframes generated.
```

This is part of my annotation folder : 
![image](https://user-images.githubusercontent.com/43233772/100403571-36f42980-309a-11eb-99e6-5e16009c2611.png)

**Comment by innerlee** [comment]
You may have run the script at the wrong path

**Comment by innerlee** [comment]
Okay please move 'data/hmdb51/rawframes/hmdb51_org.rar' elsewhere

**Comment by wwdok** [comment]
Yes, it is my fault to put hmdb51_org.rar in the folder, but how to explain `No such file or directory: 'data/hmdb51/annotations/trainlist01.txt'`, i have removed hmdb51_org.rar away, and rerun `bash generate_rawframes_filelist.sh`, the error is still like the one of second try.

**Comment by innerlee** [comment]
rename `data/hmdb51/annotations/classInd.txt` to `data/hmdb51/annotations/classInd.txt.bk`

**Comment by wwdok** [comment]
Great, it works like a charm !

**Comment by 59394** [comment]
Excuse me, I have one question ，can you help me？
I only have hmdb51_val_split_1_videos.txt.
there is no hmdb51_{train,val}_split_{1,2,3} _rawframes.txt.
where did you get it?
