### ISSUE TITLE
Train with multiple GPUs

### ISSUE THREAD

**Issue by skyqwe123** [open-mmlab/mmaction2#432]
Hi, @SuX97  It works, for a single GPU, if set workers_per_gpu=0.  But for multiple GPUs, it report the error like this：
```bash
Traceback (most recent call last):
  File "./tools/train.py", line 182, in <module>
    main()
  File "./tools/train.py", line 102, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/earhian/anaconda3/envs/ac/lib/python3.6/site-packages/mmcv/runner/dist_utils.py", line 20, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/earhian/anaconda3/envs/ac/lib/python3.6/site-packages/mmcv/runner/dist_utils.py", line 34, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "/home/earhian/anaconda3/envs/ac/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 400, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/home/earhian/anaconda3/envs/ac/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 143, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon)
RuntimeError: Connection timed out
Traceback (most recent call last):
  File "./tools/train.py", line 182, in <module>
    main()
  File "./tools/train.py", line 102, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/earhian/anaconda3/envs/ac/lib/python3.6/site-packages/mmcv/runner/dist_utils.py", line 20, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/earhian/anaconda3/envs/ac/lib/python3.6/site-packages/mmcv/runner/dist_utils.py", line 34, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "/home/earhian/anaconda3/envs/ac/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 400, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/home/earhian/anaconda3/envs/ac/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 143, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon)
RuntimeError: Connection timed out
Traceback (most recent call last):
  File "/home/earhian/anaconda3/envs/ac/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/earhian/anaconda3/envs/ac/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/earhian/anaconda3/envs/ac/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/earhian/anaconda3/envs/ac/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/earhian/anaconda3/envs/ac/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/recognition/tsn/tsn_r50_1x1x3_75e_ucf101_rgb.py', '--launcher', 'pytorch', '--local_rank', '6']' returned non-zero exit status 1.
```

**Comment by SuX97** [comment]
Hi @skyqwe123:

Two questions to sort out before we start reproduction:
1. Did you set `workers_per_gpu=0`?
2. Did you monitor the memory status of your workstation (e.g. , top;cat /proc/sys/kernel/shmall ) and observe that memory overloaded?
3. Did you try the suggestion in the traceback log: OMP_NUM_THREADS=1

**Comment by skyqwe123** [comment]
Hi, @SuX97 
I have made the following settings，
workers_per_gpu=0, # 8
use  nmon ;
![nmon](https://user-images.githubusercontent.com/49860891/101900931-3e174d80-3beb-11eb-957b-b39c64002027.png)

export OMP_NUM_THREADS=1

But report the error like this:
RuntimeError: Connection timed out
    store = TCPStore(master_addr, master_port, world_size, start_daemon)
    store = TCPStore(master_addr, master_port, world_size, start_daemon)
RuntimeError: Connection timed out
RuntimeError: Connection timed out

**Comment by Ultraman82** [comment]
here same issue. works with sing rtx 3090. not with multiple(4)

020-12-15 09:27:16,569 - mmaction - INFO - These parameters in pretrained checkpoint are not loaded: {'fc.bias', 'fc.weight'}
2020-12-15 09:27:16,772 - mmaction - INFO - load checkpoint from ./work_dirs/test_r34/latest.pth
2020-12-15 09:27:17,006 - mmaction - INFO - resumed epoch 25, iter 850
2020-12-15 09:27:17,007 - mmaction - INFO - Start running, host: oem@codeproB, work_dir: /home/oem/mmaction2/work_dirs/test_r34
2020-12-15 09:27:17,007 - mmaction - INFO - workflow: [('train', 1)], max: 50 epochs
/home/oem/mmaction2/mmaction/models/backbones/resnet_tin.py:12: UserWarning: Please install mmcv-full to support "tin_shift"
  warnings.warn('Please install mmcv-full to support "tin_shift"')
/home/oem/mmaction2/mmaction/models/backbones/resnet_tin.py:12: UserWarning: Please install mmcv-full to support "tin_shift"
  warnings.warn('Please install mmcv-full to support "tin_shift"')
/home/oem/mmaction2/mmaction/models/backbones/resnet_tin.py:12: UserWarning: Please install mmcv-full to support "tin_shift"
  warnings.warn('Please install mmcv-full to support "tin_shift"')
/home/oem/mmaction2/mmaction/models/backbones/resnet_tin.py:12: UserWarning: Please install mmcv-full to support "tin_shift"
  warnings.warn('Please install mmcv-full to support "tin_shift"')
/home/oem/mmaction2/mmaction/models/backbones/resnet_tin.py:12: UserWarning: Please install mmcv-full to support "tin_shift"
  warnings.warn('Please install mmcv-full to support "tin_shift"')
/home/oem/mmaction2/mmaction/models/backbones/resnet_tin.py:12: UserWarning: Please install mmcv-full to support "tin_shift"
  warnings.warn('Please install mmcv-full to support "tin_shift"')
/home/oem/mmaction2/mmaction/models/backbones/resnet_tin.py:12: UserWarning: Please install mmcv-full to support "tin_shift"
  warnings.warn('Please install mmcv-full to support "tin_shift"')
/home/oem/mmaction2/mmaction/models/backbones/resnet_tin.py:12: UserWarning: Please install mmcv-full to support "tin_shift"
  warnings.warn('Please install mmcv-full to support "tin_shift"')
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    exitcode = _main(fd, parent_sentinel)
    exitcode = _main(fd, parent_sentinel)
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    prepare(preparation_data)
    prepare(preparation_data)
    prepare(preparation_data)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    main()
    main()  File "tools/train.py", line 167, in main

  File "tools/train.py", line 167, in main
    main()
  File "tools/train.py", line 167, in main
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
        train_model(train_model(

  File "/home/oem/mmaction2/mmaction/apis/train.py", line 141, in train_model
  File "/home/oem/mmaction2/mmaction/apis/train.py", line 141, in train_model
    train_model(
  File "/home/oem/mmaction2/mmaction/apis/train.py", line 141, in train_model
    main_content = runpy.run_path(main_path,
    main_content = runpy.run_path(main_path,
Traceback (most recent call last):
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    main_content = runpy.run_path(main_path,
  File "tools/train.py", line 178, in <module>
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
    return _run_module_code(code, init_globals, run_name,
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    return _run_module_code(code, init_globals, run_name,
    _run_code(code, mod_globals, init_globals,
    _run_code(code, mod_globals, init_globals,
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/oem/mmaction2/tools/train.py", line 8, in <module>
    exec(code, run_globals)
    exec(code, run_globals)
  File "/home/oem/mmaction2/tools/train.py", line 8, in <module>
  File "/home/oem/mmaction2/tools/train.py", line 8, in <module>
    _run_code(code, mod_globals, init_globals,
    import mmcv
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    import mmcv
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    import mmcv
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 4, in <module>
    from .io import dump, load, register_handler
    exec(code, run_globals)
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/fileio/io.py", line 4, in <module>
    from .io import dump, load, register_handler
  File "/home/oem/mmaction2/tools/train.py", line 8, in <module>
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/fileio/io.py", line 4, in <module>
    from .io import dump, load, register_handler
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/fileio/io.py", line 4, in <module>
    from ..utils import is_list_of, is_str
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 29, in <module>
    from ..utils import is_list_of, is_str
    import mmcv
    from ..utils import is_list_of, is_str
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 29, in <module>
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 29, in <module>
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .env import collect_env
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/utils/env.py", line 12, in <module>
    from .env import collect_env
    from .env import collect_env
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/utils/env.py", line 12, in <module>
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/utils/env.py", line 12, in <module>
    from .fileio import *
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 4, in <module>
    from .io import dump, load, register_handler
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/fileio/io.py", line 4, in <module>
    from ..utils import is_list_of, is_str
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 29, in <module>
    from .env import collect_env
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/utils/env.py", line 12, in <module>
    main()
  File "tools/train.py", line 167, in main
    train_model(
  File "/home/oem/mmaction2/mmaction/apis/train.py", line 141, in train_model
    from .parrots_wrapper import get_build_config
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/utils/parrots_wrapper.py", line 75, in <module>
    from .parrots_wrapper import get_build_config
    from .parrots_wrapper import get_build_config
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/utils/parrots_wrapper.py", line 75, in <module>
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/utils/parrots_wrapper.py", line 75, in <module>
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    from .parrots_wrapper import get_build_config
        runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)

  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/utils/parrots_wrapper.py", line 75, in <module>
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
        CUDA_HOME = _get_cuda_home()
runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/utils/parrots_wrapper.py", line 12, in _get_cuda_home

  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    from torch.utils.cpp_extension import CUDA_HOME
  File "/usr/lib/python3/dist-packages/torch/utils/cpp_extension.py", line 17, in <module>
    CUDA_HOME = _get_cuda_home()
    CUDA_HOME = _get_cuda_home()
      File "/home/oem/.local/lib/python3.8/site-packages/mmcv/utils/parrots_wrapper.py", line 12, in _get_cuda_home
    epoch_runner(data_loaders[i], **kwargs)      File "/home/oem/.local/lib/python3.8/site-packages/mmcv/utils/parrots_wrapper.py", line 12, in _get_cuda_home
    from .hipify import hipify_python
epoch_runner(data_loaders[i], **kwargs)  File "/usr/lib/python3/dist-packages/torch/utils/hipify/hipify_python.py", line 648, in <module>

epoch_runner(data_loaders[i], **kwargs)

  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    CUDA_HOME = _get_cuda_home()
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/utils/parrots_wrapper.py", line 12, in _get_cuda_home
        for i, data_batch in enumerate(self.data_loader):for i, data_batch in enumerate(self.data_loader):
    
for i, data_batch in enumerate(self.data_loader):  File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 352, in __iter__
  File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 352, in __iter__

    from torch.utils.cpp_extension import CUDA_HOME
    from torch.utils.cpp_extension import CUDA_HOME
  File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 352, in __iter__
  File "/usr/lib/python3/dist-packages/torch/utils/cpp_extension.py", line 7, in <module>
  File "/usr/lib/python3/dist-packages/torch/utils/cpp_extension.py", line 7, in <module>
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/oem/.local/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    import setuptools
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 17, in <module>
    import setuptools
    from torch.utils.cpp_extension import CUDA_HOME
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 19, in <module>
  File "/usr/lib/python3/dist-packages/torch/utils/cpp_extension.py", line 7, in <module>
    for i, data_batch in enumerate(self.data_loader):
    RE_CAFFE2_PREPROCESSOR = re.compile(CAFFE2_TRIE.pattern())
  File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 352, in __iter__
  File "/usr/lib/python3/dist-packages/torch/utils/hipify/hipify_python.py", line 630, in pattern
    import setuptools
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 17, in <module>
        return self._get_iterator()return self._get_iterator()
    
return self._get_iterator()  File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator

  File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
  File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    import setuptools.version
    return self._pattern(self.dump())
  File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>
  File "/usr/lib/python3/dist-packages/torch/utils/hipify/hipify_python.py", line 603, in _pattern
    from setuptools.dist import Distribution, Feature
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 29, in <module>
    return _MultiProcessingDataLoaderIter(self)    
return _MultiProcessingDataLoaderIter(self)  File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 801, in __init__

  File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 801, in __init__
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 801, in __init__
    import setuptools.version
  File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>
    recurse = self._pattern(data[char])
  File "/usr/lib/python3/dist-packages/torch/utils/hipify/hipify_python.py", line 603, in _pattern
        import pkg_resources
return self._get_iterator()    import pkg_resources

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
      File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    w.start()w.start()

  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    w.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
        self._popen = self._Popen(self)self._popen = self._Popen(self)

  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    from setuptools.extern import packaging
    recurse = self._pattern(data[char])
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "/usr/lib/python3/dist-packages/torch/utils/hipify/hipify_python.py", line 603, in _pattern
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    recurse = self._pattern(data[char])
  [Previous line repeated 4 more times]
  File "/usr/lib/python3/dist-packages/torch/utils/hipify/hipify_python.py", line 592, in _pattern
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 801, in __init__
    return _default_context.get_context().Process._Popen(process_obj)    
return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
      File "/usr/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    def _pattern(self, pData):
KeyboardInterrupt
    return Popen(process_obj)    
return Popen(process_obj)  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__

  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    super().__init__(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    super().__init__(process_obj)    
super().__init__(process_obj)  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__

  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    self._launch(process_obj)
      File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 62, in _launch
self._launch(process_obj)    
self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 62, in _launch
  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 62, in _launch
    f.write(fp.getbuffer())
    f.write(fp.getbuffer())
KeyboardInterrupt  File "/usr/lib/python3/dist-packages/setuptools/extern/__init__.py", line 43, in load_module
    
f.write(fp.getbuffer())KeyboardInterrupt

KeyboardInterrupt
    w.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    __import__(extant)
  File "/usr/lib/python3/dist-packages/setuptools/_vendor/packaging/__init__.py", line 6, in <module>
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    from .__about__ import (
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
  File "<frozen importlib._bootstrap>", line 960, in _find_and_load_unlocked
    KeyboardInterrupt
return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 62, in _launch
    f.write(fp.getbuffer())
KeyboardInterrupt
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 575, in _build_master
    ws = cls()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 568, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 624, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in find_on_path
    for dist in factory(fullpath):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2135, in distributions_from_metadata
    tuple(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3280, in <genexpr>
    yield Distribution.from_location(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2592, in from_location
    return cls(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2996, in _reload_version
    dist.activate(replace=False)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2784, in activate
    md_version = self._get_version()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2774, in _get_version
    version = _version_from_file(lines)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2558, in _version_from_file
    line = next(iter(version_lines), '')
    fixup_namespace_packages(self.location)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2768, in _get_metadata
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2296, in fixup_namespace_packages
    if self.has_metadata(name):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1414, in has_metadata
    path = self._get_metadata_path(name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1408, in _get_metadata_path
    return self._fn(self.egg_info, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1488, in _fn
    subpath = _handle_ns(package, path_item)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2202, in _handle_ns
    self._validate_resource_path(resource_name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1549, in _validate_resource_path
    ntpath.isabs(path)
  File "/usr/lib/python3.8/ntpath.py", line 70, in isabs
    if s.replace('/', '\\').startswith('\\\\?\\'):
KeyboardInterrupt
    loader = importer.find_module(packageName)
  File "<frozen importlib._bootstrap_external>", line 486, in _find_module_shim
  File "<frozen importlib._bootstrap_external>", line 1421, in find_loader
  File "<frozen importlib._bootstrap_external>", line 1457, in find_spec
  File "<frozen importlib._bootstrap_external>", line 64, in _path_join
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/usr/lib/python3/dist-packages/torch/distributed/launch.py", line 253, in main
    process.wait()
  File "/usr/lib/python3.8/subprocess.py", line 1079, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1804, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.8/subprocess.py", line 1762, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)

**Comment by innerlee** [comment]
> UserWarning: Please install mmcv-full to support "tin_shift"

@Ultraman82 Is the error caused by mmcv?

**Comment by Ultraman82** [comment]
yeah, with mmcv-full==1.2.1 installed.
