### ISSUE TITLE
when i try to run the tsn model on the dataset of finegym, there is a queston,ImportError: /home/lgh/lgh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_14DispatchKeySetE

### ISSUE THREAD

**Issue by lenka844** [open-mmlab/mmaction2#435]
Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    main()
  File "tools/train.py", line 119, in main
    env_info_dict = collect_env()
  File "/media/scw4750/lgh/project/mmaction2/mmaction/utils/collect_env.py", line 8, in collect_env
    env_info = collect_basic_env()
  File "/home/lgh/lgh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/env.py", line 85, in collect_env
    from mmcv.ops import get_compiler_version, get_compiling_cuda_version
  File "/home/lgh/lgh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/lgh/lgh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/lgh/lgh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/lgh/lgh/anaconda3/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/lgh/lgh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_14DispatchKeySetE

we already have tried to change the version of pytorch and mmcv, but it still cannot wwork!

**Comment by skyqwe123** [comment]
Hi,@lenka844 ,Try to check the pytorch-cuda version and cuda version， make sure the versions are consistent between them.

**Comment by lenka844** [comment]
> Hi,@lenka844 ,Try to check the pytorch-cuda version and cuda version， make sure the versions are consistent between them.

hello,@skyqwe123, firstly thanks for your help, after i report this issue i try to change the version of mmcv by using the source code of the offical repository, luclily, it works. i inever meet the same error again.
Thanyou again!
