### ISSUE TITLE
How to run demo/long_video_demo.py inference on multiple GPUs?

### ISSUE THREAD

**Issue by barnettx** [open-mmlab/mmaction2#450]
Hi

## I would to ask how to use multiple GPUs to speed up inference
I've been using mmaction's `long_video_demo.py` to perform realtime action recognition on a 15 second video
```
python demo/long_video_demo.py \
configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py \
checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth \
./pocket_card_trick_15s.mp4 demo/label_map.txt \
./demo/pocket_card_trick_15s_long_demo_dist_3.mp4
````
However, it takes about 10 mins to process a 15 second video.

```
~/mmaction2$ python3 demo/long_video_demo.py configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth ./pocket_card_trick_15s.mp4 demo/label_map.txt
./demo/pocket_card_DataParallel.mp4
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 467/467, 0.6 task/s, elapsed: 833s, ETA:     0s
```
`nvidia-smi` shows that I'm only utilising one GPU.
```
Thu Dec 17 04:11:23 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:04.0 Off |                    0 |
| N/A   73C    P0   146W / 149W |   3770MiB / 11441MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 00000000:00:05.0 Off |                    0 |
| N/A   64C    P8    34W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 00000000:00:06.0 Off |                    0 |
| N/A   33C    P8    26W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 00000000:00:07.0 Off |                    0 |
| N/A   45C    P8    29W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     24791      C   python3                          3767MiB |
+-----------------------------------------------------------------------------+
```

## dist_train.sh / torch.distributed.launch

Reading https://mmaction2.readthedocs.io/en/latest/getting_started.html#train-with-multiple-gpus, I applied https://github.com/open-mmlab/mmaction2/blob/master/tools/dist_train.sh to `demo/long_video_demo.py`

This is the `torch.distributed.launch` script I came up with
```
python -m torch.distributed.launch --nproc_per_node=4 --master_port=29500 \
demo/long_video_demo.py \
configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py \
checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth \
./pocket_card_trick_15s.mp4 \
demo/label_map.txt \
./demo/pocket_card_trick_15s_long_demo_dist_2.mp4
```
where `--nproc_per_node=4` is for 4 gpus as stated in https://pytorch.org/docs/stable/distributed.html#launch-utility
![image](https://user-images.githubusercontent.com/18087283/102443803-91adef00-4062-11eb-8703-e82a10c2319a.png)

### Result
Loads multiple processes onto 1 GPU instead of splitting over 4, running out of memory. Have to kill the run away processes. 

```
~/mmaction2$ python -m torch.distributed.launch --nproc_per_node=4 --master_port=29500 demo/long_video_de
mo.py configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_202
00614-e508be42.pth ./pocket_card_trick_15s.mp4 demo/label_map.txt ./demo/pocket_card_trick_15s_long_demo_dist_2.mp4                   
*****************************************                                                                                             
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please furthe
r tune the variable for optimal performance in your application as needed.                                                            
*****************************************                                                                                             
[                                                  ] 2/467, 66.4 task/s, elapsed: 0s, ETA:     7s[                                    
[                                                  ] 2/467, 65.2 task/s, elapsed: 0s, ETA:     7s[                                    
[                                                  ] 2/467, 65.4 task/s, elapsed: 0s, ETA:     7s[                                    
[>>                                                ] 25/467, 84.9 task/s, elapsed: 0s, ETA:     5sTraceback (most recent call last):  
  File "demo/long_video_demo.py", line 200, in <module>                                                                               
    main()                                                                                                                            
  File "demo/long_video_demo.py", line 196, in main                                                                                   
    show_results()                                                                                                                    
  File "demo/long_video_demo.py", line 97, in show_results                                                                            
    ret, scores = inference()                                                                                                         
  File "demo/long_video_demo.py", line 157, in inference                                                                              
    scores = model(return_loss=False, **cur_data)[0]                                                                                  
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl              
    result = self.forward(*input, **kwargs)                                                                                           
  File "/home/barnett_lee/mmaction2/mmaction/models/recognizers/base.py", line 171, in forward                                        
    return self.forward_test(imgs, **kwargs)                                                                                          
  File "/home/barnett_lee/mmaction2/mmaction/models/recognizers/recognizer2d.py", line 76, in forward_test                            
    return self._do_test(imgs).cpu().numpy()                                                                                          
  File "/home/barnett_lee/mmaction2/mmaction/models/recognizers/recognizer2d.py", line 45, in _do_test                                
    x = self.extract_feat(imgs)                                                                                                       
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func                  
    return old_func(*args, **kwargs)                                                                                                  
  File "/home/barnett_lee/mmaction2/mmaction/models/recognizers/base.py", line 72, in extract_feat                                    
    x = self.backbone(imgs)                                                                                                           
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl              
    result = self.forward(*input, **kwargs)                                                                                           
  File "/home/barnett_lee/mmaction2/mmaction/models/backbones/resnet.py", line 541, in forward                                        
    x = res_layer(x)                                                                                                                  
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl              
    result = self.forward(*input, **kwargs)                                                                                           
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward              
    input = module(input)
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/barnett_lee/mmaction2/mmaction/models/backbones/resnet.py", line 214, in forward
    out = _inner_forward(x)
  File "/home/barnett_lee/mmaction2/mmaction/models/backbones/resnet.py", line 205, in _inner_forward
    identity = self.downsample(x)
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/mmcv/cnn/bricks/conv_module.py", line 194, in forward
    x = self.norm(x)
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/nn/functional.py", line 2058, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 766.00 MiB (GPU 0; 11.17 GiB total capacity; 1.91 GiB already allocated; 238.19 Mi
B free; 2.50 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "demo/long_video_demo.py", line 200, in <module>
    main()
  File "demo/long_video_demo.py", line 196, in main
    show_results()
  File "demo/long_video_demo.py", line 97, in show_results
    ret, scores = inference()
  File "demo/long_video_demo.py", line 157, in inference
    scores = model(return_loss=False, **cur_data)[0]
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/barnett_lee/mmaction2/mmaction/models/recognizers/base.py", line 171, in forward
    return self.forward_test(imgs, **kwargs)
  File "/home/barnett_lee/mmaction2/mmaction/models/recognizers/recognizer2d.py", line 76, in forward_test
    return self._do_test(imgs).cpu().numpy()
  File "/home/barnett_lee/mmaction2/mmaction/models/recognizers/recognizer2d.py", line 45, in _do_test
    x = self.extract_feat(imgs)
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/barnett_lee/mmaction2/mmaction/models/recognizers/base.py", line 72, in extract_feat
    x = self.backbone(imgs)
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/barnett_lee/mmaction2/mmaction/models/backbones/resnet.py", line 536, in forward
    x = self.conv1(x)
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/mmcv/cnn/bricks/conv_module.py", line 192, in forward
    x = self.conv(x)
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/mmcv/cnn/bricks/wrappers.py", line 58, in forward
    return super().forward(x)
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 766.00 MiB (GPU 0; 11.17 GiB total capacity; 237.04 MiB already allocated; 238.19
MiB free; 262.00 MiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/barnett_lee/mmaction2/env/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/barnett_lee/mmaction2/env/bin/python', '-u', 'demo/long_video_demo.py', '--local_rank=
3', 'configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py', 'checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_2
0200614-e508be42.pth', './pocket_card_trick_15s.mp4', 'demo/label_map.txt', './demo/pocket_card_trick_15s_long_demo_dist_2.mp4']' retu
rned non-zero exit status 1.
[>>                                                ] 28/467, 2.5 task/s, elapsed: 11s, ETA:   175s
```

```
Thu Dec 17 04:26:26 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P0   152W / 149W |   7540MiB / 11441MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 00000000:00:05.0 Off |                    0 |
| N/A   63C    P8    34W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 00000000:00:06.0 Off |                    0 |
| N/A   33C    P8    26W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 00000000:00:07.0 Off |                    0 |
| N/A   44C    P8    29W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     25053      C   .../mmaction2/env/bin/python     3767MiB |
|    0   N/A  N/A     25055      C   .../mmaction2/env/bin/python     3767MiB |
+-----------------------------------------------------------------------------+
```
<details>
<summary>Set --nproc_per_node=2</summary>

Runs two processes on 1 GPU. Only 2nd process seems to run. No faster than 1 process on 1 GPU
```
python -m torch.distributed.launch --nproc_per_node=2 --master_port=29500 demo/long_video_de
mo.py configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_202
00614-e508be42.pth ./pocket_card_trick_15s.mp4 demo/label_map.txt ./demo/pocket_card_trick_15s_long_demo_dist_2.mp4
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
[                                                  ] 1/467, 119837.3 task/s, elapsed: 0s, ETA:     0s[
[>>>>>                                             ] 54/467, 0.5 task/s, elapsed: 102s, ETA:   782s
```

```
Thu Dec 17 04:47:50 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:04.0 Off |                    0 |
| N/A   73C    P0   125W / 149W |   7540MiB / 11441MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 00000000:00:05.0 Off |                    0 |
| N/A   72C    P8    35W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 00000000:00:06.0 Off |                    0 |
| N/A   33C    P8    26W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 00000000:00:07.0 Off |                    0 |
| N/A   45C    P8    30W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     25608      C   .../mmaction2/env/bin/python     3767MiB |
|    0   N/A  N/A     25609      C   .../mmaction2/env/bin/python     3767MiB |
+-----------------------------------------------------------------------------+
```
</details>

## `torch.nn.DataParallel`

Currently looking into using `torch.nn.DataParallel`. https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html

**Comment by innerlee** [comment]
The demo code currently runs on single gpu

**Comment by dreamerlin** [comment]
@barnettx Hi, according to https://github.com/open-mmlab/mmaction2/tree/master/demo#long-video-demo and your result

```
~/mmaction2$ python3 demo/long_video_demo.py configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth ./pocket_card_trick_15s.mp4 demo/label_map.txt
./demo/pocket_card_DataParallel.mp4
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 467/467, 0.6 task/s, elapsed: 833s, ETA:     0s
```

The number 467 shows that you should assign `STRIDE` or `INPUT_STEP` to reduce redundant frame operations.
