### ISSUE TITLE
RuntimeError: shape '[-1, 8, 64, 5440]' is invalid for input of size 348160

### ISSUE THREAD

**Issue by wwdok** [open-mmlab/mmaction2#451]
Hi, mmaction2 team, this time i got an error in converting TSM model to onnx format, 
The pytorch i used is 
![image](https://user-images.githubusercontent.com/43233772/102459593-c5980d00-4080-11eb-9878-09353234bf1d.png)

The commands i used in colab are :

```
!wget -c https://download.openmmlab.com/mmaction/recognition/tsm/tsm_r50_1x1x8_50e_kinetics400_rgb/tsm_r50_1x1x8_50e_kinetics400_rgb_20200607-af7fb746.pth \
      -O checkpoints/tsm_r50_1x1x8_50e_kinetics400_rgb_20200607-af7fb746.pth
```
and
```
!python tools/pytorch2onnx.py ./configs/recognition/tsm/tsm_r50_video_inference_1x1x8_100e_kinetics400_rgb.py ./checkpoints/tsm_r50_1x1x8_50e_kinetics400_rgb_20200607-af7fb746.pth --shape 1 1 3 256 340 --verify --show
```

The logging output are : 

```
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 163, in <module>
    verify=args.verify)
  File "tools/pytorch2onnx.py", line 74, in pytorch2onnx
    opset_version=opset_version)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 168, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 69, in export
    use_external_data_format=use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 334, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 291, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, _force_outplace=False, _return_inputs_states=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 278, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 361, in forward
    self._force_outplace,
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 348, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/content/mmaction2/mmaction/models/recognizers/recognizer2d.py", line 93, in forward_dummy
    x = self.extract_feat(imgs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/content/mmaction2/mmaction/models/recognizers/base.py", line 72, in extract_feat
    x = self.backbone(imgs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/content/mmaction2/mmaction/models/backbones/resnet.py", line 541, in forward
    x = res_layer(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/content/mmaction2/mmaction/models/backbones/resnet.py", line 214, in forward
    out = _inner_forward(x)
  File "/content/mmaction2/mmaction/models/backbones/resnet.py", line 200, in _inner_forward
    out = self.conv1(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/cnn/bricks/conv_module.py", line 192, in forward
    x = self.conv(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/content/mmaction2/mmaction/models/backbones/resnet_tsm.py", line 68, in forward
    x = self.shift(x, self.num_segments, shift_div=self.shift_div)
  File "/content/mmaction2/mmaction/models/backbones/resnet_tsm.py", line 88, in shift
    x = x.view(-1, num_segments, c, h * w)
RuntimeError: shape '[-1, 8, 64, 5440]' is invalid for input of size 348160
```

**Comment by irvingzhang0512** [comment]
I guess `--shape 1 1 3 256 340` is not correct.
try `--shape 1 8 3 256 340`

**Comment by wwdok** [comment]
Yes, you are totally correct ! So in [Exporting a model to ONNX](Exporting a model to ONNX) `$clip` correpond to `{num_clips}`  in [Config File Naming Convention](https://mmaction2.readthedocs.io/en/latest/config.html#config-file-naming-convention) , `$time` correspond to  `{clip_len}` ?

**Comment by irvingzhang0512** [comment]
Technically, when using 2d models & uniform sampling(eg. 1x1x8), `$clip` corresponds to `{num_clips}`; for 3D models,  `$time` corresponds to `{clip_len}`.
