### ISSUE TITLE
re:error 

### ISSUE THREAD

**Issue by HHHcwb** [open-mmlab/mmaction2#49]
tsn_r50_1x1x3_80e_ucf101_rgb.py
Traceback (most recent call last):
  File "D:\Anaconda\envs\mmaction2-master\lib\sre_parse.py", line 1015, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\U'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/11987/Desktop/小论文素材/model/mmaction2-master/tools/train.py", line 167, in <module>
    main()
  File "C:/Users/11987/Desktop/小论文素材/model/mmaction2-master/tools/train.py", line 83, in main
    cfg = Config.fromfile(args.config)
  File "D:\Anaconda\envs\mmaction2-master\lib\site-packages\mmcv-1.0.2-py3.7-win-amd64.egg\mmcv\utils\config.py", line 204, in fromfile
    use_predefined_variables)
  File "D:\Anaconda\envs\mmaction2-master\lib\site-packages\mmcv-1.0.2-py3.7-win-amd64.egg\mmcv\utils\config.py", line 127, in _file2dict
    temp_config_file.name)
  File "D:\Anaconda\envs\mmaction2-master\lib\site-packages\mmcv-1.0.2-py3.7-win-amd64.egg\mmcv\utils\config.py", line 108, in _substitute_predefined_vars
    config_file = re.sub(regexp, value, config_file)
  File "D:\Anaconda\envs\mmaction2-master\lib\re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "D:\Anaconda\envs\mmaction2-master\lib\re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "D:\Anaconda\envs\mmaction2-master\lib\re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "D:\Anaconda\envs\mmaction2-master\lib\sre_parse.py", line 1018, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \U at position 2

When I run train.py, I encountered this problem, I tried to change re to regex and I also got this:

regex._regex_core.error: incomplete escape \U at position 5

Can anyone help me,Thanks!!!

**Comment by innerlee** [comment]
which config file is used?

**Comment by HHHcwb** [comment]
I use ucf101 dataset with tsn_r50_1x1x3_80e_ucf101_rgb.py

**Comment by HHHcwb** [comment]
I used ucf-101 dataset with tsn_r50_1x1x3_80e_ucf101_rgb.py

**Comment by HHHcwb** [comment]
And I also switch the config file it still does not work

**Comment by innerlee** [comment]
It is a string format error. It might related to windows system. Maybe the file path is not properly escaped? Or maybe the config file contains bad unicode.

Could you share your config file if possible? We need a reproduce

**Comment by dreamerlin** [comment]
We replace `re` with `regex` in [mmcv](https://github.com/open-mmlab/mmcv/commit/9de04d228455e490d9bcbb4fd0186a2b058d938a) on Windows platform to solve this problem.
