### ISSUE TITLE
something error in a new dataset

### ISSUE THREAD

**Issue by JoanYu** [open-mmlab/mmaction2#525]
I tried to train a new dataset named autsl with slowfast model but I got a built-in errors.
this dataset has such a label type:
```
signer0_sample1,41
signer0_sample2,104
signer0_sample3,205
signer0_sample4,26
signer0_sample5,191
signer0_sample6,140
signer0_sample7,139
signer0_sample8,225
signer0_sample9,102
signer0_sample10,19
```
and the dataset has both color video and depth video so it has a file skeleton as below:
```
.
├── signer0_sample1000_color.mp4
├── signer0_sample1000_depth.mp4
├── signer0_sample1001_color.mp4
├── signer0_sample1001_depth.mp4
├── signer0_sample1002_color.mp4
├── signer0_sample1002_depth.mp4
├── signer0_sample1003_color.mp4
├── signer0_sample1003_depth.mp4
├── signer0_sample1004_color.mp4
├── signer0_sample1004_depth.mp4
├── signer0_sample1005_color.mp4
├── signer0_sample1005_depth.mp4
├── signer0_sample1006_color.mp4
├── signer0_sample1006_depth.mp4
├── signer0_sample1007_color.mp4
├── signer0_sample1007_depth.mp4
...
```
so I modified `datasets/video_dataset.py`,
```
with open(self.ann_file, 'r') as fin:
            for line in fin:
                line_split = line.strip().split(',')
                if self.multi_class:
                    assert self.num_classes is not None
                    filename, label = line_split[0], line_split[1:]
                    label = list(map(int, label))
                    onehot = torch.zeros(self.num_classes)
                    onehot[label] = 1.0
                else:
                    # filename, label = line_split
                    # label = int(label)
                    filename = line_split[0]+'_color.mp4'
                    label = int(line_split[1])
```
the config is as below:
```
model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='ResNet3dSlowFast',
        pretrained=None,
        resample_rate=8,  # tau
        speed_ratio=8,  # alpha
        channel_ratio=8,  # beta_inv
        slow_pathway=dict(
            type='resnet3d',
            depth=50,
            pretrained=None,
            lateral=True,
            conv1_kernel=(1, 7, 7),
            dilations=(1, 1, 1, 1),
            conv1_stride_t=1,
            pool1_stride_t=1,
            inflate=(0, 0, 1, 1),
            norm_eval=False),
        fast_pathway=dict(
            type='resnet3d',
            depth=50,
            pretrained=None,
            lateral=False,
            base_channels=8,
            conv1_kernel=(5, 7, 7),
            conv1_stride_t=1,
            pool1_stride_t=1,
            norm_eval=False)),
    cls_head=dict(
        type='SlowFastHead',
        in_channels=2304,  # 2048+256
        num_classes=226,
        spatial_type='avg',
        dropout_ratio=0.5))

# model training and testing settings
train_cfg = None
test_cfg = dict(average_clips='prob')
# dataset settings
dataset_type = 'VideoDataset'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)
data_root = 'Dataset/AUTSL/train'
ann_file_train = 'Dataset/AUTSL/train_labels.csv'
train_pipeline = [
    dict(type='SampleFrames', clip_len=32, frame_interval=2, num_clips=1),
    dict(type='RawFrameDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='RandomResizedCrop'),
    dict(type='Resize', scale=(224, 224), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]

data = dict(
    videos_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix=data_root,
        pipeline=train_pipeline))
# optimizer
optimizer = dict(
    type='SGD', lr=0.1, momentum=0.9,
    weight_decay=0.0001)  # this lr is used for 8 gpus
optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))
# learning policy
lr_config = dict(
    policy='CosineAnnealing',
    min_lr=0,
    warmup='linear',
    warmup_by_epoch=True,
    warmup_iters=34)
total_epochs = 256
checkpoint_config = dict(interval=4)
workflow = [('train', 1)]
evaluation = dict(
    interval=5, metrics=['top_k_accuracy', 'mean_class_accuracy'])
log_config = dict(
    interval=20,
    hooks=[
        dict(type='TextLoggerHook'),
        #    dict(type='TensorboardLoggerHook'),
    ])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
find_unused_parameters = False
```
error printed in term like this:
```
Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    main()
  File "tools/train.py", line 174, in main
    meta=meta)
  File "/home/ipiu/Documents/xduyzy/mmaction2/mmaction/apis/train.py", line 156, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/ipiu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ipiu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/ipiu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/ipiu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/ipiu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/ipiu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ipiu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ipiu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ipiu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ipiu/Documents/xduyzy/mmaction2/mmaction/datasets/base.py", line 280, in __getitem__
    return self.prepare_train_frames(idx)
  File "/home/ipiu/Documents/xduyzy/mmaction2/mmaction/datasets/base.py", line 249, in prepare_train_frames
    return self.pipeline(results)
  File "/home/ipiu/Documents/xduyzy/mmaction2/mmaction/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/ipiu/Documents/xduyzy/mmaction2/mmaction/datasets/pipelines/loading.py", line 209, in __call__
    total_frames = results['total_frames']
KeyError: 'total_frames'
```
and now I have no way to fix them out...
Thanks!

**Comment by irvingzhang0512** [comment]
Your train pipeline seems to support `RawVideoDataset`, not `VideoDataset`.

Maybe you can modify train pipeline base on [this](https://github.com/open-mmlab/mmaction2/blob/023777cfd26bb175f85d78c455f6869673e0aa09/configs/recognition/slowfast/slowfast_r50_video_4x16x1_256e_kinetics400_rgb.py#L46)

**Comment by JoanYu** [comment]
> Your train pipeline seems to support `RawVideoDataset`, not `VideoDataset`.
> 
> Maybe you can modify train pipeline base on [this](https://github.com/open-mmlab/mmaction2/blob/023777cfd26bb175f85d78c455f6869673e0aa09/configs/recognition/slowfast/slowfast_r50_video_4x16x1_256e_kinetics400_rgb.py#L46), remove `RawFrameDecode`, add `DecordInit` and `DecordDecode`

It works! Thank you!
