### ISSUE TITLE
Maybe find a bug

### ISSUE THREAD

**Issue by SKBL5694** [open-mmlab/mmaction2#551]
During my training, an error is like this

```bash
2021-01-20 12:40:05,482 - mmaction - INFO - Saving checkpoint at 4 epochs
Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    main()
  File "tools/train.py", line 174, in main
    meta=meta)
  File "f:\zhst\mmaction\mmaction2-master\mmaction\apis\train.py", line 142, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "F:\anaconda\envs\torch16\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "F:\anaconda\envs\torch16\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "F:\anaconda\envs\torch16\lib\site-packages\mmcv\runner\base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "F:\anaconda\envs\torch16\lib\site-packages\mmcv\runner\dist_utils.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "F:\anaconda\envs\torch16\lib\site-packages\mmcv\runner\hooks\checkpoint.py", line 52, in after_train_epoch
    self.out_dir, save_optimizer=self.save_optimizer, **self.args)
  File "F:\anaconda\envs\torch16\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 172, in save_checkpoint
    shutil.copy(filename, dst_file)
  File "F:\anaconda\envs\torch16\lib\shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "F:\anaconda\envs\torch16\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'epoch_4.pth'`
```
I check the file File "F:\anaconda\envs\torch16\lib\site-packages\mmcv\runner\epoch_based_runner.py"
the code in lin172 is `shutil.copy(filename, dst_file)`
I  change it to `shutil.copy(filenpath, dst_file)` and it can work now.
BTW, I run the codes on Windows, so I'm not sure if the code in line 169 and 170 should be changed too.
'if platform.system() != 'Windows':
                mmcv.symlink(filename, dst_file)'

**Comment by innerlee** [comment]
Thanks for the report! A fix is here https://github.com/open-mmlab/mmcv/pull/796
