### ISSUE TITLE
error when i use docker to install 

### ISSUE THREAD

**Issue by 523997931** [open-mmlab/mmaction2#626]
When i install use the provided dockerfile,the final step report the error like this
Obtaining file:///mmaction2
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mmaction2/setup.py'"'"'; __file__='"'"'/mmaction2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-v9k_1lt2
         cwd: /mmaction2/
    Complete output (146 lines):
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/future/
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa5631befd0>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa5631501d0>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa563150590>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
    ERROR: Exception:
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
        crit = self.state.criteria[name]
    KeyError: 'future'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/connection.py", line 170, in _new_conn
        (self._dns_host, self.port), self.timeout, **extra_kw
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/util/connection.py", line 96, in create_connection
        raise err
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/util/connection.py", line 86, in create_connection
        sock.connect(sa)
    socket.timeout: timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 706, in urlopen
        chunked=chunked,
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 382, in _make_request
        self._validate_conn(conn)
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 1010, in _validate_conn
        conn.connect()
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/connection.py", line 353, in connect
        conn = self._new_conn()
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/connection.py", line 177, in _new_conn
        % (self.host, self.timeout),
    pip._vendor.urllib3.exceptions.ConnectTimeoutError: (<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa56315a090>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/adapters.py", line 449, in send
        timeout=timeout
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 796, in urlopen
        **response_kw
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 796, in urlopen
        **response_kw
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 796, in urlopen
        **response_kw
      [Previous line repeated 2 more times]
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 756, in urlopen
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/util/retry.py", line 573, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    pip._vendor.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (Caused by ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa56315a090>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
        status = self.run(options, args)
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
        return func(self, options, args)
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/commands/wheel.py", line 159, in run
        reqs, check_supported_wheels=True
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
        requirements, max_rounds=try_to_avoid_resolution_too_deep,
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
        state = resolution.resolve(requirements, max_rounds=max_rounds)
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 318, in resolve
        name, crit = self._merge_into_criterion(r, parent=None)
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
        crit = Criterion.from_requirement(self._p, requirement, parent)
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 82, in from_requirement
        if not cands:
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 124, in __bool__
        return bool(self._sequence)
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in __bool__
        return any(self)
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 38, in _iter_built
        candidate = func()
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 169, in _make_candidate_from_link
        name=name, version=version,
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 306, in __init__
        version=version,
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 144, in __init__
        self.dist = self._prepare()
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
        dist = self._prepare_distribution()
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 312, in _prepare_distribution
        self._ireq, parallel_builds=True,
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 457, in prepare_linked_requirement
        return self._prepare_linked_requirement(req, parallel_builds)
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 482, in _prepare_linked_requirement
        self.download_dir, hashes,
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 234, in unpack_url
        hashes=hashes,
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 108, in get_http_url
        from_path, content_type = download(link, temp_dir.path)
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/network/download.py", line 150, in __call__
        resp = _http_get_download(self._session, link)
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/network/download.py", line 131, in _http_get_download
        resp = session.get(target_url, headers=HEADERS, stream=True)
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 555, in get
        return self.request('GET', url, **kwargs)
      File "/opt/conda/lib/python3.7/site-packages/pip/_internal/network/session.py", line 424, in request
        return super().request(method, url, *args, **kwargs)
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 542, in request
        resp = self.send(prep, **send_kwargs)
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 655, in send
        r = adapter.send(request, **kwargs)
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 53, in send
        resp = super(CacheControlAdapter, self).send(request, **kw)
      File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/adapters.py", line 504, in send
        raise ConnectTimeout(e, request=request)
    pip._vendor.requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (Caused by ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa56315a090>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)'))
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/opt/conda/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmphuuchnid', '--quiet', 'future']' returned non-zero exit status 2.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mmaction2/setup.py", line 128, in <module>
        zip_safe=False)
      File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 689, in fetch_build_eggs
        replace_conflicting=True,
      File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 768, in resolve
        replace_conflicting=replace_conflicting
      File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 745, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/opt/conda/lib/python3.7/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/opt/conda/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmphuuchnid', '--quiet', 'future']' returned non-zero exit status 2.
    ----------------------------------------
WARNING: Discarding file:///mmaction2. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I just use the same way as the instruction,but it can't install.

**Comment by congee524** [comment]
It seems that the network is unreachable. 443 error

**Comment by 523997931** [comment]
> It seems that the network is unreachable. 443 error

Thank you for reply, I have solved it
