### ISSUE TITLE
ValueError: could not convert string to float: 'test'

### ISSUE THREAD

**Issue by pengxuding** [open-mmlab/mmaction2#785]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I download kinetics400 dataset. However, when i cd /tools/data/kinetics400 and bash generate_video_filelist.sh, code running error. 

**Reproduction**

1. What command or script did you run?
```sh
cd /tools/data/kinetics400
bash generate_video_filelist.sh
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

I don't make any modifications.

3. What dataset did you use?

I used kinetics400 dataset from [download](https://pan.baidu.com/s/1LZFCtMsPqd0QVnj-ddhL4Q?from=init&_at_=1617677545387#list/path=%2Fkinetics-400).
I run the following command is normal.
```sh
bash extract_rgb_frames_opencv.sh kinetics400
```

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: linux
Python: 3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce RTX 3080
CUDA_HOME: None
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.1
OpenCV: 4.5.1
MMCV: 1.2.6
MMCV Compiler: n/a
MMCV CUDA Compiler: n/a
MMAction2: 0.12.0+4261ef6
```

**Error traceback**

If applicable, paste the error traceback here.

```
We are processing kinetics400
Traceback (most recent call last):
  File "tools/data/build_file_list.py", line 263, in <module>
    main()
  File "tools/data/build_file_list.py", line 203, in main
    splits = parse_kinetics_splits(args.level, args.dataset)
  File "/home/ding/disk_b/git/mmaction2/tools/data/parse_file_list.py", line 384, in parse_kinetics_splits
    test_list = [line_to_map(x, test=True) for x in csv_reader]
  File "/home/ding/disk_b/git/mmaction2/tools/data/parse_file_list.py", line 384, in <listcomp>
    test_list = [line_to_map(x, test=True) for x in csv_reader]
  File "/home/ding/disk_b/git/mmaction2/tools/data/parse_file_list.py", line 351, in line_to_map
    video = f'{x[1]}_{int(float(x[2])):06d}_{int(float(x[3])):06d}'
ValueError: could not convert string to float: 'test'
Train filelist for video generated.
Traceback (most recent call last):
  File "tools/data/build_file_list.py", line 263, in <module>
    main()
  File "tools/data/build_file_list.py", line 203, in main
    splits = parse_kinetics_splits(args.level, args.dataset)
  File "/home/ding/disk_b/git/mmaction2/tools/data/parse_file_list.py", line 384, in parse_kinetics_splits
    test_list = [line_to_map(x, test=True) for x in csv_reader]
  File "/home/ding/disk_b/git/mmaction2/tools/data/parse_file_list.py", line 384, in <listcomp>
    test_list = [line_to_map(x, test=True) for x in csv_reader]
  File "/home/ding/disk_b/git/mmaction2/tools/data/parse_file_list.py", line 351, in line_to_map
    video = f'{x[1]}_{int(float(x[2])):06d}_{int(float(x[3])):06d}'
ValueError: could not convert string to float: 'test'
Val filelist for video generated.
```

**Comment by mbilalshaikh** [comment]
any answer on this, I am facing the same issue.

**Comment by mbilalshaikh** [comment]
I have fixed this issue.

**Comment by todzh** [comment]
> I have fixed this issue.

how do you fixed the issue?

**Comment by hajarbaharom** [comment]
> I have fixed this issue.

why

**Comment by hajarbaharom** [comment]
> I have fixed this issue.

how?
