### ISSUE TITLE
Issue loading custom pretrained model

### ISSUE THREAD

**Issue by Rajawat23** [open-mmlab/mmaction2#827]
Hi Team,
Please allow me to thank you guys for amazing work, 
I am running into an issue that may be because of my ignorance. I trained a  backbone model in `mmdetection` with custom data. The model is Resnet50. 
I am trying to load the custom pre-trained resnet backbone model saved by mmdetection to mmaction2 and I am running into the following error 
`/data/object_recognition/models/fast_rcnn_r50_fpn_0_01_LR/epoch_25.pth is not a checkpoint file`

my config looks something like this:-
```
_base_ = [
    '../../_base_/models/i3d_r50.py', '../../_base_/schedules/sgd_100e.py',
    '../../_base_/default_runtime.py'
]

# model settings
model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='ResNet3d',
        non_local=((0, 0, 0), (0, 1, 0, 1), (0, 0, 0, 1, 1, 0), (0, 0, 0)),
        non_local_cfg=dict(
            sub_sample=True,
            use_scale=False,
            norm_cfg=dict(type='BN3d', requires_grad=True),
            mode='dot_product'),
        pretrained2d=True,
        pretrained='/data/object_recognition/models/fast_rcnn_r50_fpn_0_01_LR/epoch_25.pth',
        depth=50,
        conv_cfg=dict(type='Conv3d'),
        frozen_stages=50
        ),
    cls_head=dict(
        type='I3DHead',
        num_classes=14,
        in_channels=2048,
        spatial_type='avg',
        dropout_ratio=0.5,
        init_std=0.01,
        multi_class=True),
    # model training and testing settings
    train_cfg=None,
    test_cfg=dict(average_clips='prob'))
```

**Comment by dreamerlin** [comment]
Could you please provide us more traceback info?

**Comment by Rajawat23** [comment]
yeah sure. Here is whole traceback
```
# runtime settings
2021-04-22T08:33:43.423820204Z checkpoint_config = dict(interval=5)
2021-04-22T08:33:43.423822621Z work_dir = './data/i3d_nl_dot_product_r50_video_32x2x8_1e_3d_fastcnn_pretrained/'
2021-04-22T08:33:43.423825184Z find_unused_parameters = True
2021-04-22T08:33:44.073156507Z Use load_from_local loader
2021-04-22T08:33:44.073211997Z 2021-04-22 08:33:44,072 - mmaction - INFO - load model from: /data/object_recognition/models/fast_rcnn_r50_fpn_0_01_LR/epoch_25.pth
2021-04-22T08:33:44.073382343Z Traceback (most recent call last):
2021-04-22T08:33:44.073397552Z   File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
2021-04-22T08:33:44.073540182Z     return obj_cls(**args)
2021-04-22T08:33:44.073554647Z   File "/mmaction2/mmaction/models/recognizers/base.py", line 90, in __init__
2021-04-22T08:33:44.073558479Z     self.init_weights()
2021-04-22T08:33:44.073561351Z   File "/mmaction2/mmaction/models/recognizers/base.py", line 97, in init_weights
2021-04-22T08:33:44.073568328Z     self.backbone.init_weights()
2021-04-22T08:33:44.073571422Z   File "/mmaction2/mmaction/models/backbones/resnet3d.py", line 806, in init_weights
2021-04-22T08:33:44.073595973Z Use load_from_local loader
2021-04-22T08:33:44.073699376Z Traceback (most recent call last):
2021-04-22T08:33:44.073704419Z   File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
2021-04-22T08:33:44.073750735Z     self._init_weights(self, pretrained)
2021-04-22T08:33:44.073764636Z   File "/mmaction2/mmaction/models/backbones/resnet3d.py", line 782, in _init_weights
2021-04-22T08:33:44.073847051Z     return obj_cls(**args)
2021-04-22T08:33:44.073853146Z   File "/mmaction2/mmaction/models/recognizers/base.py", line 90, in __init__
2021-04-22T08:33:44.073911133Z     self.init_weights()
2021-04-22T08:33:44.073915703Z       File "/mmaction2/mmaction/models/recognizers/base.py", line 97, in init_weights
2021-04-22T08:33:44.073918769Z self.inflate_weights(logger)
2021-04-22T08:33:44.073922870Z   File "/mmaction2/mmaction/models/backbones/resnet3d.py", line 727, in inflate_weights
2021-04-22T08:33:44.073961525Z     self.backbone.init_weights()
2021-04-22T08:33:44.073973000Z   File "/mmaction2/mmaction/models/backbones/resnet3d.py", line 806, in init_weights
2021-04-22T08:33:44.074079013Z     self._inflate_weights(self, logger)
2021-04-22T08:33:44.074084584Z   File "/mmaction2/mmaction/models/backbones/resnet3d.py", line 675, in _inflate_weights
2021-04-22T08:33:44.074145246Z     self._init_weights(self, pretrained)
2021-04-22T08:33:44.074150572Z   File "/mmaction2/mmaction/models/backbones/resnet3d.py", line 782, in _init_weights
2021-04-22T08:33:44.074231272Z     state_dict_r2d = _load_checkpoint(self.pretrained)
2021-04-22T08:33:44.074236570Z   File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 467, in _load_checkpoint
2021-04-22T08:33:44.074318384Z     self.inflate_weights(logger)
2021-04-22T08:33:44.074322978Z   File "/mmaction2/mmaction/models/backbones/resnet3d.py", line 727, in inflate_weights
2021-04-22T08:33:44.074359514Z     return CheckpointLoader.load_checkpoint(filename, map_location, logger)
2021-04-22T08:33:44.074373155Z   File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
2021-04-22T08:33:44.074438513Z     return checkpoint_loader(filename, map_location)
2021-04-22T08:33:44.074452720Z   File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 260, in load_from_local
2021-04-22T08:33:44.074486764Z     self._inflate_weights(self, logger)
2021-04-22T08:33:44.074492790Z   File "/mmaction2/mmaction/models/backbones/resnet3d.py", line 675, in _inflate_weights
2021-04-22T08:33:44.074535660Z     raise IOError(f'{filename} is not a checkpoint file')
2021-04-22T08:33:44.074541471Z OSError: /data/object_recognition/models/fast_rcnn_r50_fpn_0_01_LR/epoch_25.pth is not a checkpoint file
2021-04-22T08:33:44.074544881Z 
2021-04-22T08:33:44.074547600Z During handling of the above exception, another exception occurred:
2021-04-22T08:33:44.074550439Z 
2021-04-22T08:33:44.074553189Z Traceback (most recent call last):
2021-04-22T08:33:44.074555807Z   File "tools/train.py", line 197, in <module>
2021-04-22T08:33:44.074610310Z     main()
2021-04-22T08:33:44.074615307Z   File "tools/train.py", line 155, in main
2021-04-22T08:33:44.074685364Z     state_dict_r2d = _load_checkpoint(self.pretrained)
2021-04-22T08:33:44.074691117Z   File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 467, in _load_checkpoint
2021-04-22T08:33:44.074694353Z     test_cfg=cfg.get('test_cfg'))
2021-04-22T08:33:44.074697043Z   File "/mmaction2/mmaction/models/builder.py", line 86, in build_model
2021-04-22T08:33:44.074714535Z     return build_recognizer(cfg, train_cfg, test_cfg)
2021-04-22T08:33:44.074720420Z   File "/mmaction2/mmaction/models/builder.py", line 66, in build_recognizer
2021-04-22T08:33:44.074814220Z     return CheckpointLoader.load_checkpoint(filename, map_location, logger)    
2021-04-22T08:33:44.074819813Z dict(train_cfg=train_cfg, test_cfg=test_cfg))
2021-04-22T08:33:44.074822488Z   File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
2021-04-22T08:33:44.074825630Z   File "/mmaction2/mmaction/models/builder.py", line 40, in build
2021-04-22T08:33:44.074828494Z     return build_from_cfg(cfg, registry, default_args)
2021-04-22T08:33:44.074831126Z   File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
2021-04-22T08:33:44.074834662Z     return checkpoint_loader(filename, map_location)
2021-04-22T08:33:44.074837268Z   File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 260, in load_from_local
2021-04-22T08:33:44.074847324Z     raise type(e)(f'{obj_cls.__name__}: {e}')
2021-04-22T08:33:44.074851984Z OSError: Recognizer3D: /data/object_recognition/models/fast_rcnn_r50_fpn_0_01_LR/epoch_25.pth is not a checkpoint file
2021-04-22T08:33:44.074915585Z     raise IOError(f'{filename} is not a checkpoint file')
2021-04-22T08:33:44.074926506Z OSError: /data/object_recognition/models/fast_rcnn_r50_fpn_0_01_LR/epoch_25.pth is not a checkpoint file
2021-04-22T08:33:44.074930473Z 
2021-04-22T08:33:44.074933184Z During handling of the above exception, another exception occurred:
2021-04-22T08:33:44.074936038Z 
2021-04-22T08:33:44.074938598Z Traceback (most recent call last):
2021-04-22T08:33:44.074941139Z   File "tools/train.py", line 197, in <module>
2021-04-22T08:33:44.074997884Z     main()
2021-04-22T08:33:44.075004327Z   File "tools/train.py", line 155, in main
2021-04-22T08:33:44.075052954Z     test_cfg=cfg.get('test_cfg'))
2021-04-22T08:33:44.075058001Z   File "/mmaction2/mmaction/models/builder.py", line 86, in build_model
2021-04-22T08:33:44.075103573Z     return build_recognizer(cfg, train_cfg, test_cfg)
2021-04-22T08:33:44.075115111Z   File "/mmaction2/mmaction/models/builder.py", line 66, in build_recognizer
2021-04-22T08:33:44.075145594Z     dict(train_cfg=train_cfg, test_cfg=test_cfg))
2021-04-22T08:33:44.075151454Z   File "/mmaction2/mmaction/models/builder.py", line 40, in build
2021-04-22T08:33:44.075187375Z     return build_from_cfg(cfg, registry, default_args)
2021-04-22T08:33:44.075191490Z   File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
2021-04-22T08:33:44.075234212Z     raise type(e)(f'{obj_cls.__name__}: {e}')
2021-04-22T08:33:44.075240320Z OSError: Recognizer3D: /data/object_recognition/models/fast_rcnn_r50_fpn_0_01_LR/epoch_25.pth is not a checkpoint file
2021-04-22T08:33:44.511877898Z Traceback (most recent call last):
2021-04-22T08:33:44.511932423Z   File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2021-04-22T08:33:44.511937541Z     "__main__", mod_spec)
2021-04-22T08:33:44.511940531Z   File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
2021-04-22T08:33:44.511943593Z     exec(code, run_globals)
2021-04-22T08:33:44.511946399Z   File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
2021-04-22T08:33:44.511949776Z     main()
2021-04-22T08:33:44.511952364Z   File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
2021-04-22T08:33:44.511955256Z     cmd=cmd)
2021-04-22T08:33:44.511958918Z subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'configs/recognition/i3d/i3d_nl_dot_product_r50_video_32x8x1e_cater_3d_fastercnn_pretrained.py', '--launcher', 'pytorch', '--validate']' returned non-zero exit status 1.
2021-04-22T08:33:44.511896589Z *****************************************
```

**Comment by dreamerlin** [comment]
https://github.com/open-mmlab/mmcv/blob/0dd0c49a5be452e6e7e844a0fa1d5fe68a5ef1bb/mmcv/runner/checkpoint.py#L247-L262

It seems your file url is invalid

**Comment by LiUzHiAn** [comment]
@Rajawat23  Emm... Where did you save your ckpt file when training your custom model? It seems you miss the first dot in path `/data/object_recognition/models/fast_rcnn_r50_fpn_0_01_LR/epoch_25.pth`? Maybe you mean `./data` rather '/data' ?

**Comment by Rajawat23** [comment]
It's an issue of disk mounting since I am training using a docker container, `/data` is not getting mapped to the actual location of the saved model.
Thanks a ton for the help :)
I'll go ahead close the issue as well
