### ISSUE TITLE
ImportError: cannot import name 'MODELS' from 'mmcv.cnn'

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmaction2#855]
The error is coming @[builder](https://github.com/open-mmlab/mmaction2/commit/56515c493a12fe2cc8190498e5e3ad5b321f1975#diff-ccedd4279a68b7e8c02ea509747c55c0cf7f59d7485f347e0c4292a607632b32), `from mmcv.cnn import MODELS as MMCV_MODELS`

```
/mmaction2/mmaction/core/evaluation/eval_hooks.py:36: UserWarning: DeprecationWarning: EvalHook and DistEvalHook in mmaction2 will be deprecated, please install mmcv through master branch.
  warnings.warn('DeprecationWarning: EvalHook and DistEvalHook in mmaction2 '
Traceback (most recent call last):
  File "demo/demo_gradcam.py", line 10, in <module>
    from mmaction.apis import init_recognizer
  File "/mmaction2/mmaction/apis/__init__.py", line 1, in <module>
    from .inference import inference_recognizer, init_recognizer
  File "/mmaction2/mmaction/apis/inference.py", line 12, in <module>
    from mmaction.models import build_recognizer
  File "/mmaction2/mmaction/models/__init__.py", line 1, in <module>
    from .backbones import (C3D, X3D, MobileNetV2, MobileNetV2TSM, ResNet,
  File "/mmaction2/mmaction/models/backbones/__init__.py", line 1, in <module>
    from .c3d import C3D
  File "/mmaction2/mmaction/models/backbones/c3d.py", line 7, in <module>
    from ..builder import BACKBONES
  File "/mmaction2/mmaction/models/builder.py", line 3, in <module>
    from mmcv.cnn import MODELS as MMCV_MODELS
ImportError: cannot import name 'MODELS' from 'mmcv.cnn' (/opt/conda/lib/python3.8/site-packages/mmcv/cnn/__init__.py)
```

**Comment by dreamerlin** [comment]
Need to update the MMCV version

**Comment by freepoet** [comment]
hi, @rlleshi i met a same question?whats your mmcv version? Have you solved this problem?

**Comment by rlleshi** [comment]
Hi @freepoet. The error was actually fixed when the MMCV version was updated.

What error are you getting exactly?

**Comment by freepoet** [comment]
> Hi @freepoet. The error was actually fixed when the MMCV version was updated.
> 
> What error are you getting exactly?

I solved this problem, and it's really a version Incompatibility. Latest version of **mmcv** is required.

You can refer this [issue](https://github.com/open-mmlab/mmclassification/issues/263).
