### ISSUE TITLE
[BytesIO] Failed to measure duration/frame-count due to broken metadata.

### ISSUE THREAD

**Issue by soltkreig** [open-mmlab/mmaction2#887]
I try to train model on an image dataset, use this config:
```
from mmcv import Config
cfg = Config.fromfile('./configs/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics/tsn_r50_1x1x8_100e_minikinetics_rgb.py')

from mmcv.runner import set_random_seed

# Modify dataset type and path
cfg.dataset_type = 'ImageDataset'
cfg.data_root = '/home/kfour/mmaction2/dataset/train'
cfg.data_root_val = '/home/kfour/mmaction2/dataset/val'
cfg.ann_file_train = '/home/kfour/mmaction2/dataset/train.txt'
cfg.ann_file_val = '/home/kfour/mmaction2/dataset/val.txt'
cfg.ann_file_test = '/home/kfour/mmaction2/dataset/test.txt'

cfg.data.test.type = 'ImageDataset'
cfg.data.test.ann_file = '/home/kfour/mmaction2/dataset/test.txt'
cfg.data.test.data_prefix = '/home/kfour/mmaction2/dataset/test'

cfg.data.train.type = 'ImageDataset'
cfg.data.train.ann_file = '/home/kfour/mmaction2/dataset/train.txt'
cfg.data.train.data_prefix = '/home/kfour/mmaction2/dataset/train'

cfg.data.val.type = 'ImageDataset'
cfg.data.val.ann_file = '/home/kfour/mmaction2/dataset/val.txt'
cfg.data.val.data_prefix = '/home/kfour/mmaction2/dataset/val'

# The flag is used to determine whether it is omnisource training
cfg.setdefault('omnisource', False)
# Modify num classes of the model in cls_head
cfg.model.cls_head.num_classes = 3
# We can use the pre-trained TSN model
cfg.load_from = './checkpoints/tsn_r50_1x1x8_100e_minikinetics_rgb_20201030-b4eaf92b.pth'

# Set up working dir to save files and logs.
cfg.work_dir = './tutorial_exps'

# The original learning rate (LR) is set for 8-GPU training.
# We divide it by 8 since we only use one GPU.
cfg.data.videos_per_gpu = 8
cfg.optimizer.lr = cfg.optimizer.lr / 8
cfg.total_epochs = 30

# We can set the checkpoint saving interval to reduce the storage cost
cfg.checkpoint_config.interval = 10
# We can set the log print interval to reduce the the times of printing log
cfg.log_config.interval = 5

# Set seed thus the results are more reproducible
cfg.seed = 0
set_random_seed(0, deterministic=False)
cfg.gpu_ids = range(1)


# We can initialize the logger for training and have a look
# at the final config used for training
print(f'Config:\n{cfg.pretty_text}')
```
Use standard train as tutorial
```
import os.path as osp

from mmaction.datasets import build_dataset
from mmaction.models import build_model
from mmaction.apis import train_model

import mmcv
Build the dataset

datasets = [build_dataset(cfg.data.train)]

# Build the recognizer
model = build_model(cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))

# Create work_dir
mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
train_model(model, datasets, cfg, distributed=False, validate=True)
```

But finally got the error:
```
Use load_from_torchvision loader
2021-05-26 14:58:35,470 - mmaction - INFO - These parameters in pretrained checkpoint are not loaded: {'fc.bias', 'fc.weight'}
2021-05-26 14:59:11,479 - mmaction - INFO - load checkpoint from ./checkpoints/tsn_r50_1x1x8_100e_minikinetics_rgb_20201030-b4eaf92b.pth
2021-05-26 14:59:11,542 - mmaction - INFO - Use load_from_local loader
2021-05-26 14:59:12,683 - mmaction - WARNING - The model and loaded state dict do not match exactly

size mismatch for cls_head.fc_cls.weight: copying a param with shape torch.Size([200, 2048]) from checkpoint, the shape in current model is torch.Size([3, 2048]).
size mismatch for cls_head.fc_cls.bias: copying a param with shape torch.Size([200]) from checkpoint, the shape in current model is torch.Size([3]).
2021-05-26 14:59:12,685 - mmaction - INFO - Start running, host: kfour@kfour, work_dir: /home/kfour/mmaction2/tutorial_exps
2021-05-26 14:59:12,686 - mmaction - INFO - workflow: [('train', 1)], max: 30 epochs
/home/kfour/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py:144: UserWarning: runner.meta is None. Creating an empty one.
  warnings.warn('runner.meta is None. Creating an empty one.')
---------------------------------------------------------------------------
DECORDError                               Traceback (most recent call last)
<ipython-input-5-75094123c5f1> in <module>
     15 # Create work_dir
     16 mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
---> 17 train_model(model, datasets, cfg, distributed=False, validate=True)

~/mmaction2/mmaction/apis/train.py in train_model(model, dataset, cfg, distributed, validate, test, timestamp, meta)
    161     if cfg.omnisource:
    162         runner_kwargs = dict(train_ratio=train_ratio)
--> 163     runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
    164 
    165     if test['test_last'] or test['test_best']:

~/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py in run(self, data_loaders, workflow, max_epochs, **kwargs)
    123                     if mode == 'train' and self.epoch >= self._max_epochs:
    124                         break
--> 125                     epoch_runner(data_loaders[i], **kwargs)
    126 
    127         time.sleep(1)  # wait for some hooks like loggers to finish

~/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py in train(self, data_loader, **kwargs)
     45         self.call_hook('before_train_epoch')
     46         time.sleep(2)  # Prevent possible deadlock during epoch transition
---> 47         for i, data_batch in enumerate(self.data_loader):
     48             self._inner_iter = i
     49             self.call_hook('before_train_iter')

~/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    515             if self._sampler_iter is None:
    516                 self._reset()
--> 517             data = self._next_data()
    518             self._num_yielded += 1
    519             if self._dataset_kind == _DatasetKind.Iterable and \

~/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
   1197             else:
   1198                 del self._task_info[idx]
-> 1199                 return self._process_data(data)
   1200 
   1201     def _try_put_index(self):

~/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1223         self._try_put_index()
   1224         if isinstance(data, ExceptionWrapper):
-> 1225             data.reraise()
   1226         return data
   1227 

~/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py in reraise(self)
    427             # have message field
    428             raise self.exc_type(message=msg)
--> 429         raise self.exc_type(msg)
    430 
    431 

DECORDError: Caught DECORDError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/kfour/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/kfour/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/kfour/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/kfour/mmaction2/mmaction/datasets/base.py", line 285, in __getitem__
    return self.prepare_train_frames(idx)
  File "/home/kfour/mmaction2/mmaction/datasets/base.py", line 259, in prepare_train_frames
    return self.pipeline(results)
  File "/home/kfour/mmaction2/mmaction/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/kfour/mmaction2/mmaction/datasets/pipelines/loading.py", line 937, in __call__
    container = decord.VideoReader(file_obj, num_threads=self.num_threads)
  File "/home/kfour/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/decord/video_reader.py", line 52, in __init__
    ba, ctx.device_type, ctx.device_id, width, height, num_threads, 2, fault_tol)
  File "/home/kfour/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/decord/_ffi/_ctypes/function.py", line 175, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/kfour/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/decord/_ffi/base.py", line 78, in check_call
    raise DECORDError(err_str)
decord._ffi.base.DECORDError: [14:59:17] /github/workspace/src/video/video_reader.cc:270: [BytesIO] Failed to measure duration/frame-count due to broken metadata.
```

**Comment by rlleshi** [comment]
Hi, 
this might be due to corrupt data and it seems that the latest version of `decord` doesn't work so well with some kind of corrupt data. Try to downgrade `decord` from 0.5.0 to 0.4.0.

**Comment by soltkreig** [comment]
It broke my numpy

**Comment by rlleshi** [comment]
Maybe try to create a new `virtualenv` where you already install `decord 0.4.0`, instead of downgrading in your current environment
