### ISSUE TITLE
NameError: name 'args' is not defined

### ISSUE THREAD

**Issue by KouateMuhamed** [open-mmlab/mmaction2#944]
```
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/stir_cereals
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/spoon_flour
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/spoon_sugar
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/take_cup
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/pour_dough2pan
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/butter_pan
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/pour_milk
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/.DS_Store
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/take_butter
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/pour_oil
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/put_bunTogether
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/stirfry_egg
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/spoon_powder
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/cut_bun
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/stir_tea
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/put_toppingOnTop
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/take_plate
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/cut_fruit
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/pour_juice
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/pour_egg2pan
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/put_pancake2plate
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/squeeze_orange
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/take_eggs
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/fry_pancake
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/cut_orange
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/take_squeezer
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/add_saltnpepper
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/put_egg2plate
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/crack_egg
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/smear_butter
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/stir_coffee
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/take_bowl
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/stir_milk
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/pour_coffee
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/peel_fruit
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/put_fruit2bowl
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/pour_cereals
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/take_glass
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/stir_fruit
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/fry_egg
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/stir_egg
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/take_knife
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/SIL
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/take_topping
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/pour_sugar
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/add_teabag
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/pour_flour
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/pour_water
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/stir_dough
Creating folder: /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes/rawframes
Reading videos from folder:  /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01
Extension of videos:  avi
Total number of videos found:  2277
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/ubermenschub/miniconda3/envs/torch-env/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/ubermenschub/miniconda3/envs/torch-env/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/ubermenschub/Desktop/Project/BreakfastV2/build_rawframes.py", line 24, in extract_frame
    out_full_path = osp.join(args.out_dir, act_name)
NameError: name 'args' is not defined
```
Hi! 

I am trying to use the build_rawframes.py script to generate the frames of my videos (Breakfast Dataset).
For each folder representing an action, I have one or more videos in .avi format.
However, when I try to run the script like this:
`python build_rawframes.py /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01 /Users/ubermenschub/Desktop/Project/BreakfastV2/data/cam_01/rawframes --task rgb --level 2 --out-format jpg --ext avi`

I get the above error. How can I fix it?
Thanks in advance.

**Comment by dreamerlin** [comment]
It seems your `args` variable can not be got by `extract_frames`. you can either write it in `__main__` or pass it in `pool`

**Comment by dreamerlin** [comment]
It seems the problem has been solved. If you feel we have helped you, you can give us a STAR! : )

**Comment by KouateMuhamed** [comment]
> It seems your `args` variable can not be got by `extract_frames`. you can either write it in `__main__` or pass it in `pool`

Please, Could you show me an example?
