### ISSUE TITLE
load checkpoint error: RuntimeError: storage has wrong size: expected -4917841579173726103 got 256

### ISSUE THREAD

**Issue by ly59782** [open-mmlab/mmaction2#963]
I download the checkpoint from readme, I didn't change the config file, an error occurred while executing the following command，
python tools/test.py configs/recognition/slowfast/slowfast_r101_8x8x1_256e_kinetics400_rgb.py checkpoints/slowfast_r101_8x8x1_256e_kinetics400_rgb_20210218-0dd54025.pth --eval top_k_accuracy mean_class_accuracy --out result.json

Use load_from_local loader
Traceback (most recent call last):
  File "tools/test.py", line 364, in <module>
    main()
  File "tools/test.py", line 349, in main
    outputs = inference_pytorch(args, cfg, distributed, data_loader)
  File "tools/test.py", line 153, in inference_pytorch
    load_checkpoint(model, args.checkpoint, map_location='cpu')
  File "/root/WangYan/mmaction2-master/mmcv-1.3.5/mmcv/runner/checkpoint.py", line 513, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/root/WangYan/mmaction2-master/mmcv-1.3.5/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/root/WangYan/mmaction2-master/mmcv-1.3.5/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/root/WangYan/mmaction2-master/mmcv-1.3.5/mmcv/runner/checkpoint.py", line 261, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/root/.local/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/.local/lib/python3.7/site-packages/torch/serialization.py", line 780, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected -4917841579173726103 got 256

The same error occurs with the following checkpoints：
slowfast_r101_8x8x1_256e_kinetics400_rgb_20210218-0dd54025.pth
slowfast_r152_4x16x1_256e_kinetics400_rgb_20210122-bdeb6b87.pth
slowfast_r50_256p_4x16x1_256e_kinetics400_rgb_20200728-145f1097.pth
slowfast_r50_256p_8x8x1_256e_kinetics400_rgb_20200810-863812c2.pth

But when I running the checkpoint "slowfast_r50_video_4x16x1_256e_kinetics400_rgb_20200826-f85b90c5.pth" everything's OK

Is there something wrong with these checkpoints?

**Comment by dreamerlin** [comment]
It got no problems when I test it. your ckpts may be broken and you can re-download them to have a try.
