### ISSUE TITLE
KeyError: 'CopyOfSGD is already registered in optimizer'

### ISSUE THREAD

**Issue by Note-Liu** [open-mmlab/mmaction2#978]
when i train Video-Swin-Transformer,
I want to call mmaction in the code of Video-Swin-Transformer, but it always uses my locally installed mmaction

Traceback (most recent call last):
  File "tools/train.py", line 15, in <module>
    from mmaction.apis import train_model
  File "/home/Video-Swin-Transformer/mmaction/apis/__init__.py", line 3, in <module>
    from .train import train_model
  File "/home/Video-Swin-Transformer/mmaction/apis/train.py", line 10, in <module>
    from mmaction.core import (DistEvalHook, EvalHook, OmniSourceDistSamplerSeedHook,
  File "/home/Video-Swin-Transformer/mmaction/core/__init__.py", line 4, in <module>
    from .optimizer import *  # noqa: F401, F403
  File "/home/Video-Swin-Transformer/mmaction/core/optimizer/__init__.py", line 1, in <module>
    from .copy_of_sgd import CopyOfSGD
  File "/home/Video-Swin-Transformer/mmaction/core/optimizer/copy_of_sgd.py", line 6, in <module>
    class CopyOfSGD(SGD):
  File "/home/anaconda3/envs/pytorch/lib/python3/site-packages/mmcv/utils/registry.py", line 311, in _register
    self._register_module(
  File "/home/anaconda3/envs/pytorch/lib/python3/site-packages/mmcv/utils/registry.py", line 246, in _register_module
    raise KeyError(f'{name} is already registered '
KeyError: 'CopyOfSGD is already registered in optimizer'

how to solve it?

**Comment by dreamerlin** [comment]
FYI: https://github.com/open-mmlab/mmaction2/issues/728
